amarokarts.cc File Reference
#include `amarokarts.h`
Functions
void _dispatch_Amarok_Synth_STEREO_XFADE_00 (void *object, Arts::Buffer *, Arts::Buffer *result)
void _dispatch_Amarok_Synth_STEREO_XFADE_01 (void *object, Arts::Buffer *request, Arts::Buffer *)
void _dispatch_Amarok_RawScope_00 (void *object, Arts::Buffer *, Arts::Buffer *result)
void _dispatch_Amarok_RawScope_01 (void *object, Arts::Buffer *, Arts::Buffer *result)
void _dispatch_Amarok_RawScope_02 (void *object, Arts::Buffer *request, Arts::Buffer *)
Arts::IDLFileReg IDLFileReg_amarokarts (`amarokarts`,`IDLFile:00000001000000000000000000000000020000001b416d61726f6b3a3a5379``6e74685f53544552454f5f5846414445000000000100000012417274733a3a53796e74``684d6f64756c650000000000000000070000000b70657263656e746167650000000006``666c6f61740000000013000000000000000b696e76616c7565315f6c0000000006666c``6f61740000000009000000000000000b696e76616c7565315f720000000006666c6f61``740000000009000000000000000b696e76616c7565325f6c0000000006666c6f617400``00000009000000000000000b696e76616c7565325f720000000006666c6f6174000000``0009000000000000000b6f757476616c75655f6c0000000006666c6f6174000000000a``000000000000000b6f757476616c75655f720000000006666c6f6174000000000a0000``0000000000000000000000000011416d61726f6b3a3a52617753636f70650000000001``00000013417274733a3a53746572656f45666665637400000000010000000673636f70``6500000000072a666c6f61740000000002000000000000000000000001000000076275``6666657200000000056c6f6e67000000001300000000000000000000000000000000`)
Function Documentation
void _dispatch_Amarok_RawScope_00 (void * object, Arts::Buffer *, Arts::Buffer * result) [static]
Definition at line 336 of file amarokarts.cc.
Referenced by Amarok::RawScope_skel::_buildMethodTable().
337 {
338         std::vector<float> *_returnCode = ((Amarok::RawScope_skel *)object)->scope();
339         result->writeFloatSeq(*_returnCode);
340         delete _returnCode;
341 }
void _dispatch_Amarok_RawScope_01 (void * object, Arts::Buffer *, Arts::Buffer * result) [static]
Definition at line 344 of file amarokarts.cc.
Referenced by Amarok::RawScope_skel::_buildMethodTable().
345 {
346         result->writeLong(((Amarok::RawScope_skel *)object)->buffer());
347 }
void _dispatch_Amarok_RawScope_02 (void * object, Arts::Buffer * request, Arts::Buffer *) [static]
Definition at line 350 of file amarokarts.cc.
Referenced by Amarok::RawScope_skel::_buildMethodTable().
351 {
352         long newValue = request->readLong();
353         ((Amarok::RawScope_skel *)object)->buffer(newValue);
354 }
void _dispatch_Amarok_Synth_STEREO_XFADE_00 (void * object, Arts::Buffer *, Arts::Buffer * result) [static]
Definition at line 139 of file amarokarts.cc.
Referenced by Amarok::Synth_STEREO_XFADE_skel::_buildMethodTable().
140 {
141         result->writeFloat(((Amarok::Synth_STEREO_XFADE_skel *)object)->percentage());
142 }
void _dispatch_Amarok_Synth_STEREO_XFADE_01 (void * object, Arts::Buffer * request, Arts::Buffer *) [static]
Definition at line 145 of file amarokarts.cc.
Referenced by Amarok::Synth_STEREO_XFADE_skel::_buildMethodTable().
146 {
147         float newValue = request->readFloat();
148         ((Amarok::Synth_STEREO_XFADE_skel *)object)->percentage(newValue);
149 }
Arts::IDLFileReg IDLFileReg_amarokarts (`amarokarts`, `IDLFile:00000001000000000000000000000000020000001b416d61726f6b3a3a5379``6e74685f53544552454f5f5846414445000000000100000012417274733a3a53796e74``684d6f64756c650000000000000000070000000b70657263656e746167650000000006``666c6f61740000000013000000000000000b696e76616c7565315f6c0000000006666c``6f61740000000009000000000000000b696e76616c7565315f720000000006666c6f61``740000000009000000000000000b696e76616c7565325f6c0000000006666c6f617400``00000009000000000000000b696e76616c7565325f720000000006666c6f6174000000``0009000000000000000b6f757476616c75655f6c0000000006666c6f6174000000000a``000000000000000b6f757476616c75655f720000000006666c6f6174000000000a0000``0000000000000000000000000011416d61726f6b3a3a52617753636f70650000000001``00000013417274733a3a53746572656f45666665637400000000010000000673636f70``6500000000072a666c6f61740000000002000000000000000000000001000000076275``6666657200000000056c6f6e67000000001300000000000000000000000000000000`) [static]