PluginManager Class Reference
#include <pluginmanager.h>
Static Public Member Functions
KTrader::OfferList query (const QString &constraint=QString::null)
Plugin * createFromQuery (const QString &constraint=QString::null)
Plugin * createFromService (const KService::Ptr service)
void unload (Plugin *plugin)
KService::Ptr getService (const Plugin *plugin)
void dump (const KService::Ptr service)
Static Public Attributes
const int FrameworkVersion = 2
Static Private Member Functions
vector< StoreItem >::iterator lookupPlugin (const Plugin *plugin)
Static Private Attributes
vector< StoreItem > m_store
Member Function Documentation
Plugin * PluginManager::createFromQuery (const QString & constraint = QString::null) [static]
Load and instantiate plugin from query
Parameters:
constraint A constraint to limit the choices returned, QString::null to get all services of the given servicetype
Returns: Pointer to Plugin(p.), or NULL if error
See also: http://developer.kde.org/documentation/library/kdeqt/tradersyntax.html
Definition at line 51 of file pluginmanager.cpp.
References createFromService(), and query().
52 {
53     KTrader::OfferList offers = query( constraint );
54 
55     if ( offers.isEmpty() ) {
56         kdWarning() << k_funcinfo << "No matching plugin found.\n";                                          
57         return 0;
58     }
59                 
60     return createFromService( *offers.begin() );    
61 }
Plugin * PluginManager::createFromService (const KService::Ptr service) [static]
Load and instantiate plugin from service
Parameters:
service Pointer to KService
Returns: Pointer to Plugin(p.), or NULL if error
Definition at line 65 of file pluginmanager.cpp.
References dump(), PluginManager::StoreItem::library, m_store, PluginManager::StoreItem::plugin, and PluginManager::StoreItem::service.
Referenced by createFromQuery().
66 {
67     kdDebug() << k_funcinfo << "Trying to load: " << service->library() << endl;
68     
69     //get the library loader instance
70     KLibLoader *loader = KLibLoader::self();
71     //try to load the specified library
72     KLibrary *lib = loader->globalLibrary( QFile::encodeName( service->library() ) );
73 
74     if ( !lib ) {
75         kdWarning() << k_funcinfo << "lib == NULL\n";
76         return 0;
77     }
78     //look up address of init function and cast it to pointer-to-function
79     Plugin* (*create_plugin)() = ( Plugin* (*)() ) lib->symbol( "create_plugin" );
80     
81     if ( !create_plugin ) {
82         kdWarning() << k_funcinfo << "create_plugin == NULL\n";
83         return 0;
84     }
85     //create plugin on the heap
86     Plugin* plugin = create_plugin();
87     
88     //put plugin into store
89     StoreItem item;
90     item.plugin = plugin;
91     item.library = lib;
92     item.service = service;
93     m_store.push_back( item );
94     
95     dump( service );
96     return plugin;
97 }
void PluginManager::dump (const KService::Ptr service) [static]
Dump properties from a service to stdout for debugging
Parameters:
service Pointer to KService
Definition at line 140 of file pluginmanager.cpp.
Referenced by createFromService().
141 {
142     assert( service.data() );
143     
144     kdDebug() << endl;
145     
146     kdDebug() << "PluginManager Service DUMP:\n";
147     kdDebug() << "---------------------------\n";
148     kdDebug() << "name                          : "
149                 << service->name()                                                  << endl;
150     kdDebug() << "library                       : "
151                 << service->library()                                               << endl;
152     kdDebug() << "desktopEntryPath              : "
153                 << service->desktopEntryPath()                                      << endl;
154     kdDebug() << "X-KDE-plugintype              : "
155                 << service->property( "X-KDE-amaroK-plugintype" ).toString()        << endl;
156     kdDebug() << "X-KDE-amaroK-authors          : "
157                 << service->property( "X-KDE-amaroK-authors" ).toStringList()       << endl;
158     kdDebug() << "X-KDE-amaroK-version          : "
159                 << service->property( "X-KDE-amaroK-version" ).toString()           << endl;
160     kdDebug() << "X-KDE-amaroK-framework-version: "
161                 << service->property( "X-KDE-amaroK-framework-version" ).toString() << endl;
162     
163     kdDebug() << endl;
164 }
KService::Ptr PluginManager::getService (const Plugin * plugin) [static]
Look up service for loaded plugin from store
Parameters:
pointer Pointer to plugin
Returns: KService, or 0 if not found
Definition at line 120 of file pluginmanager.cpp.
References lookupPlugin(), and m_store.
121 {
122     kdDebug() << k_funcinfo << endl;
123     
124     if ( !plugin ) {
125         kdWarning() << k_funcinfo << "pointer == NULL\n";   
126         return 0;
127     }
128        
129     //search plugin in store
130     vector<StoreItem>::const_iterator iter = lookupPlugin( plugin ); 
131     
132     if ( iter == m_store.end() ) 
133         kdWarning() << k_funcinfo << "Plugin not found in store.\n";
134     
135     return (*iter).service;
136 }
vector< PluginManager::StoreItem >::iterator PluginManager::lookupPlugin (const Plugin * plugin) [static, private]
Definition at line 172 of file pluginmanager.cpp.
References m_store.
Referenced by getService(), and unload().
173 {
174     vector<StoreItem>::iterator iter; 
175     
176     //search plugin pointer in store
177     for ( iter = m_store.begin(); iter != m_store.end(); iter++ ) {
178         if ( (*iter).plugin == plugin )
179             break;
180     }
181 
182     return iter;
183 }
KTrader::OfferList PluginManager::query (const QString & constraint = QString::null) [static]
It will return a list of services that match your specifications. The only required parameter is the service type. This is something like 'text/plain' or 'text/html'. The constraint parameter is used to limit the possible choices returned based on the constraints you give it.
The constraint language is rather full. The most common keywords are AND, OR, NOT, IN, and EXIST, all used in an almost spoken-word form. An example is:
 (Type == 'Service') and (('KParts/ReadOnlyPart' in ServiceTypes) or (exist Exec))
The keys used in the query (Type, ServiceType, Exec) are all fields found in the .desktop files.
Parameters:
constraint A constraint to limit the choices returned, QString::null to get all services of the given servicetype
Returns: A list of services that satisfy the query
See also: http://developer.kde.org/documentation/library/kdeqt/tradersyntax.html
Definition at line 37 of file pluginmanager.cpp.
References FrameworkVersion.
Referenced by createFromQuery().
38 {    
39     // Add versioning constraint
40     QString str = QString( "[X-KDE-amaroK-framework-version] >= %1 and " )
41                      .arg( FrameworkVersion );
42     
43     kdDebug() << k_funcinfo << endl
44               << "Plugin trader constraint: " << str + constraint << endl;
45     
46     return KTrader::self()->query( "amaroK/Plugin", str + constraint );
47 }    
void PluginManager::unload (Plugin * plugin) [static]
Remove library and delete plugin
Parameters:
plugin Pointer to plugin
Definition at line 101 of file pluginmanager.cpp.
References lookupPlugin(), and m_store.
102 {
103     kdDebug() << k_funcinfo << endl;
104     
105     vector<StoreItem>::iterator iter = lookupPlugin( plugin ); 
106             
107     if ( iter != m_store.end() ) {
108         delete (*iter).plugin;
109         kdDebug() << "Unloading library: "<< (*iter).service->library() << endl;
110         (*iter).library->unload();
111         
112         m_store.erase( iter );
113     }
114     else
115         kdWarning() << k_funcinfo << "Could not unload plugin (not found in store).\n";
116 }
Member Data Documentation
const int PluginManager::FrameworkVersion = 2 [static]
Bump this number whenever the plugin framework gets incompatible with older versions
Definition at line 32 of file pluginmanager.h.
Referenced by query().
vector< PluginManager::StoreItem > PluginManager::m_store [static, private]
Definition at line 29 of file pluginmanager.cpp.
Referenced by createFromService(), getService(), lookupPlugin(), and unload().
The documentation for this class was generated from the following files:
pluginmanager.h
pluginmanager.cpp