ArtsEngine Class Reference
#include <artsengine.h>
Public Types
enum EngineState { Empty,
Idle,
Playing,
Paused
 }
enum StreamingMode { Socket,
Signal,
NoStreaming
 }
Public Slots
void play (const KURL &)
void play ()
void stop ()
void pause ()
void seek (long ms)
void setVolume (int percent)
void configureDecoder ()
virtual void newStreamData (char *, int)
Signals
void endOfTrack ()
void stopped ()
Public Member Functions
ArtsEngine ()
~ArtsEngine ()
void init (bool &restart, int scopeSize, bool restoreEffects)
bool initMixer (bool hardware)
bool canDecode (const KURL &url, mode_t mode, mode_t permissions)
StreamingMode streamingMode ()
long position () const
EngineBase::EngineState state () const
bool isStream () const
std::vector< float > * scope ()
QStringList availableEffects () const
std::vector< long > activeEffects () const
QString effectNameForId (long id) const
bool effectConfigurable (long id) const
long createEffect (const QString &name)
void removeEffect (long id)
void configureEffect (long id)
bool decoderConfigurable ()
bool supportsXFade () const
virtual QStringList getOutputsList ()
bool loaded ()
int volume () const
bool isMixerHardware () const
void setRestoreEffects (bool yes)
virtual bool decoderConfigurable () const
virtual void setXfadeLength (int ms)
virtual void setSoundOutput (const QString &output)
virtual void setSoundDevice (const QString &device)
virtual void setDefaultSoundDevice (bool isDefault)
Protected Member Functions
void closeMixerHW ()
bool initMixerHW ()
void setVolumeHW (int percent)
Protected Attributes
int m_mixerHW
int m_volume
int m_xfadeLength
bool m_restoreEffects
QString m_soundOutput
QString m_soundDevice
bool m_defaultSoundDevice
Private Slots
void connectPlayObject ()
void connectTimeout ()
Private Member Functions
void startXfade ()
void timerEvent (QTimerEvent *)
void loadEffects ()
void saveEffects ()
Private Attributes
KArtsDispatcher * m_pArtsDispatcher
KDE::PlayObject * m_pPlayObject
KDE::PlayObject * m_pPlayObjectXfade
Arts::SoundServerV2 m_server
Arts::StereoEffectStack m_globalEffectStack
Arts::StereoEffectStack m_effectStack
Arts::StereoVolumeControl m_volumeControl
Arts::Synth_AMAN_PLAY m_amanPlay
Amarok::RawScope m_scope
Amarok::Synth_STEREO_XFADE m_xfade
long m_scopeId
int m_scopeSize
long m_volumeId
QMap< long, EffectContainer > m_effectMap
bool m_xfadeFadeout
float m_xfadeValue
QString m_xfadeCurrent
QGuardedPtr< ArtsConfigWidget > m_pDecoderConfigWidget
QTimer * m_pConnectTimer
Static Private Attributes
const int ARTS_TIMER = 100
const int TIMEOUT = 4000
Member Enumeration Documentation
enum EngineBase::EngineState [inherited]
Enumeration values:
Empty
Idle
Playing
Paused
Definition at line 43 of file enginebase.h.
43 { Empty, Idle, Playing, Paused };
enum EngineBase::StreamingMode [inherited]
Enumeration values:
Socket
Signal
NoStreaming
Definition at line 44 of file enginebase.h.
Referenced by EngineBase::streamingMode().
44 { Socket, Signal, NoStreaming };
Constructor & Destructor Documentation
ArtsEngine::ArtsEngine ()
Definition at line 66 of file artsengine.cpp.
67         : EngineBase()
68         , m_pArtsDispatcher( new KArtsDispatcher( this ) )
69         , m_pPlayObject( 0 )
70         , m_pPlayObjectXfade( 0 )
71         , m_scopeId( 0 )
72         , m_volumeId( 0 )
73         , m_xfadeFadeout( false )
74         , m_xfadeValue( 0.0 )
75         , m_xfadeCurrent( "invalue2" )
76         , m_pConnectTimer( new QTimer( this ) )
77 {
78     kdDebug() << "Engine is ready" << k_funcinfo << endl;
79 }
ArtsEngine::~ArtsEngine ()
Definition at line 82 of file artsengine.cpp.
References m_amanPlay, m_effectStack, m_globalEffectStack, m_pConnectTimer, m_pPlayObject, m_pPlayObjectXfade, m_scope, m_server, m_volumeControl, m_xfade, Amarok::Synth_STEREO_XFADE::null(), Amarok::RawScope::null(), and saveEffects().
83 {
84     kdDebug() << "BEGIN " << k_funcinfo << endl;
85 
86     m_pConnectTimer->stop();
87     killTimers();
88     delete m_pPlayObject;
89     delete m_pPlayObjectXfade;
90     saveEffects();
91 
92     m_server            = Arts::SoundServerV2::null();
93     m_scope             = Amarok::RawScope::null();
94     m_xfade             = Amarok::Synth_STEREO_XFADE::null();
95     m_volumeControl     = Arts::StereoVolumeControl::null();
96     m_effectStack       = Arts::StereoEffectStack::null();
97     m_globalEffectStack = Arts::StereoEffectStack::null();
98     m_amanPlay          = Arts::Synth_AMAN_PLAY::null();
99 
100     kdDebug() << "END " << k_funcinfo << endl;
101 }
Member Function Documentation
std::vector< long > ArtsEngine::activeEffects () const [virtual]
Reimplemented from EngineBase (p.).
Definition at line 498 of file artsengine.cpp.
References m_effectMap.
499 {
500     std::vector<long> vec;
501     QMap<long, EffectContainer>::ConstIterator it;
502 
503     for ( it = m_effectMap.begin(); it != m_effectMap.end(); ++it )
504     {
505         vec.push_back( it.key() );
506     }
507 
508     return vec;
509 }
QStringList ArtsEngine::availableEffects () const [virtual]
Reimplemented from EngineBase (p.).
Definition at line 478 of file artsengine.cpp.
479 {
480     QStringList val;
481     Arts::TraderQuery query;
482     query.supports( "Interface", "Arts::StereoEffect" );
483     query.supports( "Interface", "Arts::SynthModule" );
484     std::vector<Arts::TraderOffer> *offers = query.query();
485 
486     for ( std::vector<Arts::TraderOffer>::iterator i = offers->begin(); i != offers->end(); i++ )
487     {
488         Arts::TraderOffer &offer = *i;
489         QCString name = offer.interfaceName().c_str();
490         val.append( name );
491     }
492     delete offers;
493 
494     return val;
495 }
bool ArtsEngine::canDecode (const KURL & url, mode_t mode, mode_t permissions) [virtual]
Implements EngineBase (p.).
Definition at line 284 of file artsengine.cpp.
285 {
286     KFileItem fileItem( mode, permissions, url, false ); //false = determineMimeType straight away
287     KMimeType::Ptr mimetype = fileItem.determineMimeType();
288 
289     Arts::TraderQuery query;
290     query.supports( "Interface", "Arts::PlayObject" );
291     query.supports( "MimeType", mimetype->name().latin1() );
292     std::vector<Arts::TraderOffer> *offers = query.query();
293 
294     bool result = !offers->empty();
295     delete offers;
296 
297     return result;
298 }
void EngineBase::closeMixerHW () [protected, inherited]
Definition at line 61 of file enginebase.cpp.
References EngineBase::m_mixerHW.
Referenced by initMixer(), and EngineBase::~EngineBase().
62 {
63     if ( m_mixerHW != -1 )
64     {
65         ::close( m_mixerHW );   //close /dev/mixer device
66         m_mixerHW = -1;
67     }
68 }
void ArtsEngine::configureDecoder () [virtual, slot]
Reimplemented from EngineBase (p.).
Definition at line 614 of file artsengine.cpp.
References m_pDecoderConfigWidget, and m_pPlayObject.
615 {
616     //this method shows a GUI for an aRts CODEC. currently only working with markey's modplug_artsplugin
617 
618     if ( m_pPlayObject && !m_pDecoderConfigWidget )
619     {
620         m_pDecoderConfigWidget = new ArtsConfigWidget( m_pPlayObject->object() );
621         connect( m_pPlayObject, SIGNAL( destroyed() ), m_pDecoderConfigWidget, SLOT( deleteLater() ) );
622 
623         m_pDecoderConfigWidget->show();
624     }
625 }
void ArtsEngine::configureEffect (long id) [virtual]
Reimplemented from EngineBase (p.).
Definition at line 586 of file artsengine.cpp.
References m_effectMap.
587 {
588     if ( !m_effectMap[id].widget )
589     {
590         m_effectMap[id].widget = new ArtsConfigWidget( *m_effectMap[id].effect );
591         m_effectMap[id].widget->show();
592     }
593 }
void ArtsEngine::connectPlayObject () [private, slot]
Definition at line 385 of file artsengine.cpp.
References m_pConnectTimer, m_pPlayObject, m_xfade, m_xfadeCurrent, and m_xfadeValue.
Referenced by play().
386 {
387     m_pConnectTimer->stop();
388 
389     if ( m_pPlayObject && !m_pPlayObject->isNull() && !m_pPlayObject->object().isNull() )
390     {
391         m_pPlayObject->object()._node()->start();
392 
393         //switch xfade channels
394         m_xfadeCurrent = ( m_xfadeCurrent == "invalue1" ) ? "invalue2" : "invalue1";
395 
396         if ( m_xfadeValue == 0.0 )
397             m_xfadeValue = 1.0;
398 
399         Arts::connect( m_pPlayObject->object(), "left", m_xfade, ( m_xfadeCurrent + "_l" ).latin1() );
400         Arts::connect( m_pPlayObject->object(), "right", m_xfade, ( m_xfadeCurrent + "_r" ).latin1() );
401     }
402 }
void ArtsEngine::connectTimeout () [private, slot]
Definition at line 405 of file artsengine.cpp.
References m_pConnectTimer, and m_pPlayObject.
Referenced by init(), and play().
406 {
407     kdWarning() << "[ArtsEngine::connectTimeout()] Cannot initialize PlayObject! Skipping this track." << endl;
408     m_pConnectTimer->stop();
409 
410     delete m_pPlayObject;
411     m_pPlayObject = NULL;
412 }
long ArtsEngine::createEffect (const QString & name) [virtual]
Reimplemented from EngineBase (p.).
Definition at line 538 of file artsengine.cpp.
References ArtsEngine::EffectContainer::effect, m_effectMap, m_effectStack, m_server, and ArtsEngine::EffectContainer::widget.
Referenced by loadEffects().
539 {
540     const long error = 0;
541 
542     if ( name.isEmpty() )
543         return error;
544 
545     Arts::StereoEffect* pFX = new Arts::StereoEffect;
546     *pFX = Arts::DynamicCast( m_server.createObject( std::string( name.ascii() ) ) );
547 
548     if ( (*pFX).isNull() ) {
549         kdWarning() << "[ArtsEngine::createEffect] error: could not create effect." << endl;
550         delete pFX;
551         return error;
552     }
553 
554     pFX->start();
555     long id = m_effectStack.insertBottom( *pFX, std::string( name.ascii() ) );
556 
557     if ( !id ) {
558         kdWarning() << "[ArtsEngine::createEffect] error: insertBottom failed." << endl;
559         pFX->stop();
560         delete pFX;
561         return error;
562     }
563 
564     EffectContainer container;
565     container.effect = pFX;
566     container.widget = 0;
567 
568     m_effectMap.insert( id, container );
569 
570     return id;
571 }
virtual bool EngineBase::decoderConfigurable () const [inline, virtual, inherited]
Definition at line 109 of file enginebase.h.
109 { return false; }
bool ArtsEngine::decoderConfigurable ()
Definition at line 596 of file artsengine.cpp.
References m_pDecoderConfigWidget, and m_pPlayObject.
597 {
598     if ( m_pPlayObject && !m_pPlayObject->object().isNull() && !m_pDecoderConfigWidget )
599     {
600         Arts::TraderQuery query;
601         query.supports( "Interface", "Arts::GuiFactory" );
602         query.supports( "CanCreate", m_pPlayObject->object()._interfaceName() );
603 
604         std::vector<Arts::TraderOffer> *queryResults = query.query();
605         bool yes = queryResults->size();
606         delete queryResults;
607 
608         return yes;
609     }
610     return false;
611 }
bool ArtsEngine::effectConfigurable (long id) const [virtual]
Reimplemented from EngineBase (p.).
Definition at line 521 of file artsengine.cpp.
References m_effectMap.
522 {
523     if ( m_effectMap.find(id) == m_effectMap.end() )
524         return false;
525 
526     Arts::TraderQuery query;
527     query.supports( "Interface", "Arts::GuiFactory" );
528     query.supports( "CanCreate", (*m_effectMap[id].effect)._interfaceName() );
529 
530     std::vector<Arts::TraderOffer> *queryResults = query.query();
531     bool yes = queryResults->size();
532     delete queryResults;
533 
534     return yes;
535 }
QString ArtsEngine::effectNameForId (long id) const [virtual]
Reimplemented from EngineBase (p.).
Definition at line 512 of file artsengine.cpp.
References m_effectMap.
513 {
514     const std::string str = (*m_effectMap[id].effect)._interfaceName();
515     QString qstr( str.c_str() );
516 
517     return qstr;
518 }
void EngineBase::endOfTrack () [signal, inherited]
Definition at line 113 of file enginebase.moc.
114 {
115     activate_signal( staticMetaObject()->signalOffset() + 0 );
116 }
virtual QStringList EngineBase::getOutputsList () [inline, virtual, inherited]
Get list of available output plugins
Definition at line 61 of file enginebase.h.
61 { return QStringList(); }
void ArtsEngine::init (bool & restart, int scopeSize, bool restoreEffects) [virtual]
Implements EngineBase (p.).
Definition at line 104 of file artsengine.cpp.
References ARTS_TIMER, Amarok::RawScope::buffer(), connectTimeout(), loadEffects(), m_amanPlay, m_effectStack, m_globalEffectStack, m_pConnectTimer, m_scope, m_scopeId, m_scopeSize, m_server, m_xfade, m_xfadeValue, Amarok::Synth_STEREO_XFADE::percentage(), Amarok::RawScope::start(), and Amarok::Synth_STEREO_XFADE::start().
105 {
106     kdDebug() << "BEGIN " << k_funcinfo << endl;
107 
108     m_scopeSize = 1 << scopeSize;   
109     m_restoreEffects = restoreEffects;
110     m_mixerHW = -1;   //initialize
111 
112     // We must restart artsd whenever we installed new mcopclasses
113     if ( restart )
114     {
115         QCString kill_cmdline;
116         kill_cmdline = "killall artsd";
117 
118         int kill_status = ::system( kill_cmdline );
119         if ( kill_status != -1 && WIFEXITED( kill_status ) )
120         {
121             kdWarning() << "killall artsd succeeded." << endl;
122             restart = false;
123         }
124     }
125 
126     KConfig config( "kcmartsrc" );
127     config.setGroup( "Arts" );
128 
129     bool realtime = config.readBoolEntry( "StartRealtime", true );
130 
131     if ( !realtime )
132         KMessageBox::information( 0, i18n( "<p>artsd is not running with <b>realtime priority</b> which may cause audio playback to \"skip\" and stutter.<p>"
133                                      "<p>To use realtime priority, open the KDE Control Center and enable \"Run with highest possible priority\", under <i>Sound System</i> in the <i>Sound & Multimedia</i> branch. "
134                                      "Some people may also have to check that \"$KDEDIR/bin/artswrapper\" is <b>set suid</b> (chmod +s).</p>"
135                                      "<p>You may find, however, that playback is fine without increasing the priority of artsd.</p>" ),
136                                i18n( "aRts Problem" ), "artsRealtimeAdvice" );
137 
138     m_server = Arts::Reference( "global:Arts_SoundServerV2" );
139 
140     if ( m_server.isNull() || m_server.error() )
141     {
142         kdWarning() << "aRtsd not running.. trying to start" << endl;
143         // aRts seems not to be running, let's try to run it
144         // First, let's read the configuration as in kcmarts
145         QCString cmdline;
146 
147         bool x11Comm = config.readBoolEntry( "X11GlobalComm", false );
148 
149         // put the value of x11Comm into .mcoprc
150         {
151             KConfig X11CommConfig( QDir::homeDirPath() + "/.mcoprc" );
152 
153             if ( x11Comm )
154                 X11CommConfig.writeEntry( "GlobalComm", "Arts::X11GlobalComm" );
155             else
156                 X11CommConfig.writeEntry( "GlobalComm", "Arts::TmpGlobalComm" );
157 
158             X11CommConfig.sync();
159         }
160 
161         cmdline = QFile::encodeName( KStandardDirs::findExe( QString::fromLatin1( "kdeinit_wrapper" ) ) );
162         cmdline += " ";
163 
164         if ( realtime )
165             cmdline += QFile::encodeName( KStandardDirs::findExe(
166                                               QString::fromLatin1( "artswrapper" ) ) );
167         else
168             cmdline += QFile::encodeName( KStandardDirs::findExe(
169                                               QString::fromLatin1( "artsd" ) ) );
170 
171         cmdline += " ";
172         cmdline += config.readEntry( "Arguments", "-F 10 -S 4096 -s 60 -m artsmessage -l 3 -f -n" ).utf8();
173 
174         int status = ::system( cmdline );
175 
176         if ( status != -1 && WIFEXITED( status ) )
177         {
178             // We could have a race-condition here.
179             // The correct way to do it is to make artsd fork-and-exit
180             // after starting to listen to connections (and running artsd
181             // directly instead of using kdeinit), but this is better
182             // than nothing.
183             int time = 0;
184             do
185             {
186                 // every time it fails, we should wait a little longer
187                 // between tries
188                 ::sleep( 1 + time / 2 );
189                 m_server = Arts::Reference( "global:Arts_SoundServerV2" );
190             }
191             while ( ++time < 5 && ( m_server.isNull() ) );
192         }
193     }
194 
195     if ( m_server.isNull() )
196     {
197         KMessageBox::error( 0, i18n( "Cannot start aRts. Exiting." ), i18n( "Fatal Error" ) );
198         ::exit( 1 );
199     }
200 
201     { //amanPlay
202         m_amanPlay = Arts::DynamicCast( m_server.createObject( "Arts::Synth_AMAN_PLAY" ) );
203         m_amanPlay.title( "amarok" );
204         m_amanPlay.autoRestoreID( "amarok" );
205         m_amanPlay.start();
206     }
207 
208     { //Xfade
209         m_xfade = Arts::DynamicCast( m_server.createObject( "Amarok::Synth_STEREO_XFADE" ) );
210 
211         if ( m_xfade.isNull() ) {
212             KMessageBox::error( 0,
213                                 i18n( "<p>There was an error loading libamarokarts. First try:"
214                                       "<pre>killall -9 artsd && amarok</pre>"
215                                       "If that does not work then amaroK was probably installed with the wrong prefix; "
216                                       "please re-configure amaroK using:"
217                                       "<pre>./configure --prefix=`kde-config --prefix` && su -c \"make install\"</pre>" ),
218                                 i18n( "Fatal Error" ) );
219             ::exit( 1 );
220         }
221 
222         m_xfade.percentage( m_xfadeValue );
223         m_xfade.start();
224     }
225 
226     { //globalEffectStack
227         m_globalEffectStack = Arts::DynamicCast( m_server.createObject( "Arts::StereoEffectStack" ) );
228         m_globalEffectStack.start();
229     }
230 
231     { //effectStack
232         m_effectStack = Arts::DynamicCast( m_server.createObject( "Arts::StereoEffectStack" ) );
233         m_effectStack.start();
234         m_globalEffectStack.insertBottom( m_effectStack, "Effect Stack" );
235     }
236 
237     { //scope
238         m_scope = Arts::DynamicCast( m_server.createObject( "Amarok::RawScope" ) );
239         m_scope.start();
240         m_scope.buffer( m_scopeSize );
241         m_scopeId = m_globalEffectStack.insertTop( m_scope, "Analyzer" );
242     }
243 
244     Arts::connect( m_globalEffectStack  , m_amanPlay );
245     Arts::connect( m_xfade, "outvalue_l", m_globalEffectStack, "inleft" );
246     Arts::connect( m_xfade, "outvalue_r", m_globalEffectStack, "inright" );
247 
248     if ( m_restoreEffects ) loadEffects();
249     startTimer( ARTS_TIMER );
250     connect( m_pConnectTimer, SIGNAL( timeout() ), this, SLOT( connectTimeout() ) );
251 
252     kdDebug() << "END " << k_funcinfo << endl;
253     
254 }
bool ArtsEngine::initMixer (bool hardware) [virtual]
Initialize mixer.
Parameters:
hardware True for soundcard hardware mixing
Returns: True if using hardware mixing
Implements EngineBase (p.).
Definition at line 257 of file artsengine.cpp.
References EngineBase::closeMixerHW(), EngineBase::initMixerHW(), m_globalEffectStack, m_server, m_volumeControl, and m_volumeId.
258 {
259     { //make sure any previously started volume control gets killed
260         if ( m_volumeId )
261         {
262             m_globalEffectStack.remove( m_volumeId );
263             m_volumeId = 0;
264             m_volumeControl = Arts::StereoVolumeControl::null();
265         }
266         closeMixerHW();
267     }
268 
269     if ( hardware )
270         hardware = initMixerHW();
271     else
272     {
273         m_volumeControl = Arts::DynamicCast( m_server.createObject( "Arts::StereoVolumeControl" ) );
274         m_volumeControl.start();
275         m_volumeId = m_globalEffectStack.insertBottom( m_volumeControl, "Volume Control" );
276     }
277     return hardware;
278 }
bool EngineBase::initMixerHW () [protected, inherited]
Definition at line 43 of file enginebase.cpp.
References EngineBase::m_mixerHW.
Referenced by initMixer().
44 {
45     if ( ( m_mixerHW = ::open( "/dev/mixer", O_RDWR ) ) < 0 )
46         return false;  //failed
47     else
48     {
49         int devmask, recmask, i_recsrc, stereodevs;
50         if ( ioctl( m_mixerHW, SOUND_MIXER_READ_DEVMASK, &devmask )       == -1 ) return false;
51         if ( ioctl( m_mixerHW, SOUND_MIXER_READ_RECMASK, &recmask )       == -1 ) return false;
52         if ( ioctl( m_mixerHW, SOUND_MIXER_READ_RECSRC, &i_recsrc )       == -1 ) return false;
53         if ( ioctl( m_mixerHW, SOUND_MIXER_READ_STEREODEVS, &stereodevs ) == -1 ) return false;
54         if ( !devmask )                                                           return false;
55     }
56 
57     return true;
58 }
bool EngineBase::isMixerHardware () const [inline, inherited]
Sets the master volume.
Returns: True if using hardware mixer.
Definition at line 85 of file enginebase.h.
References EngineBase::m_mixerHW.
85 { return m_mixerHW != -1; }
bool ArtsEngine::isStream () const [virtual]
Implements EngineBase (p.).
Definition at line 333 of file artsengine.cpp.
References m_pPlayObject.
334 {
335     if ( m_pPlayObject )
336         return m_pPlayObject->stream();
337     else
338         return false;
339 }
bool EngineBase::loaded () [inline, inherited]
Returns: True if media is loaded, system is ready to play.
Definition at line 73 of file enginebase.h.
References EngineBase::Empty, and EngineBase::state().
Referenced by EngineController::pause().
73 { return state() != Empty; }
void ArtsEngine::loadEffects () [private]
Definition at line 672 of file artsengine.cpp.
References createEffect(), and m_effectMap.
Referenced by init().
673 {
674     kdDebug() << k_funcinfo << endl;
675 
676     QDomDocument doc;
677     assert( kapp );
678     QFile file( kapp->dirs()->saveLocation( "data", kapp->instanceName() + "/" ) + "arts-effects.xml" );
679 
680     if ( !file.open( IO_ReadOnly ) )
681     {
682         kdWarning() << "[ArtsEngine::loadEffects()] error: !file.open()" << endl;
683         return;
684     }
685 
686     QString errorMsg;
687     int     errorLine;
688     int     errorColumn;
689     if ( !doc.setContent( &file, &errorMsg, &errorLine, &errorColumn ) )
690     {
691         kdWarning() << "[ArtsEngine::loadEffects()] error: !doc.setContent()" << endl;
692         kdWarning() << "[ArtsEngine::loadEffects()] errorMsg   : " << errorMsg    << endl;
693         kdWarning() << "[ArtsEngine::loadEffects()] errorLine  : " << errorLine   << endl;
694         kdWarning() << "[ArtsEngine::loadEffects()] errorColumn: " << errorColumn << endl;
695         file.close();
696         return;
697     }
698 
699     QDomElement docElem = doc.documentElement();
700 
701     for ( QDomNode n = docElem.firstChild(); !n.isNull(); n = n.nextSibling() )
702     {
703         QString effect = n.namedItem( "effectname" ).firstChild().toText().nodeValue();
704         kdDebug() << "effectname: " << effect << endl;
705 
706         long id = createEffect( effect );
707         for ( QDomNode nAttr = n.firstChild(); id && !nAttr.isNull(); nAttr = nAttr.nextSibling() )
708         {
709             if ( nAttr.nodeName() == "attribute" )
710             {
711                 QString name  = nAttr.namedItem( "name"  ).firstChild().toText().nodeValue();
712                 QString type  = nAttr.namedItem( "type"  ).firstChild().toText().nodeValue();
713                 QString value = nAttr.namedItem( "value" ).firstChild().toText().nodeValue();
714 
715                 kdDebug() << "name : " << name  << endl;
716                 kdDebug() << "type : " << type  << endl;
717                 kdDebug() << "value: " << value << endl;
718 
719                 Arts::DynamicRequest req( *m_effectMap[id].effect );
720                 std::string set( "_set_" );
721                 set.append( std::string( name.latin1() ) );
722                 req.method( set );
723 
724                 Arts::Buffer buf;
725                 buf.fromString( std::string( value.latin1() ), "" );
726 
727                 Arts::Any param;
728                 param.type = std::string( type.latin1() );
729                 param.readType( buf );
730                 req.param( param );
731 
732                 if ( !req.invoke() )
733                     kdWarning() << "DynamicRequest failed." << endl;
734             }
735         }
736     }
737 }
virtual void EngineBase::newStreamData (char *, int) [inline, virtual, slot, inherited]
Definition at line 130 of file enginebase.h.
130 {};
void ArtsEngine::pause () [virtual, slot]
Implements EngineBase (p.).
Definition at line 440 of file artsengine.cpp.
References m_pPlayObject.
441 {
442     if ( m_pPlayObject )
443     {
444         m_pPlayObject->pause();
445     }
446 }
void ArtsEngine::play () [virtual, slot]
Implements EngineBase (p.).
Definition at line 415 of file artsengine.cpp.
References m_pPlayObject.
Referenced by play().
416 {
417     if ( m_pPlayObject )
418     {   
419         qWarning("Arts Play files");  
420         m_pPlayObject->play();
421     }
422 }
void ArtsEngine::play (const KURL &) [virtual, slot]
Implements EngineBase (p.).
Definition at line 349 of file artsengine.cpp.
References connectPlayObject(), connectTimeout(), m_pConnectTimer, m_pPlayObject, m_server, m_xfadeFadeout, play(), startXfade(), EngineBase::stopped(), and TIMEOUT.
350 {
351     kdDebug() << k_funcinfo << endl;
352     m_xfadeFadeout = false;
353     startXfade();
354     KDE::PlayObjectFactory factory( m_server );
355     m_pPlayObject = factory.createPlayObject( url, false ); //second parameter: create BUS(true/false)
356 
357     if ( !m_pPlayObject || m_pPlayObject->isNull() ) 
358     {
359         qWarning("Arts Error 1----------------");
360         connectTimeout();
361         emit stopped();
362     }
363     else
364     {      
365         connect( m_pPlayObject, SIGNAL( destroyed() ), this, SIGNAL( stopped() ) );
366 
367         if ( m_pPlayObject->object().isNull() ) 
368         {
369             kdDebug() << k_funcinfo << " m_pPlayObject->object().isNull()" << endl;
370             qWarning("Arts Error 2----------------");
371             connect( m_pPlayObject, SIGNAL( playObjectCreated() ), this, SLOT( connectPlayObject() ) );
372             m_pConnectTimer->start( TIMEOUT, true );
373         }
374         else 
375         {
376             connectPlayObject();
377              qWarning("Arts Connect");
378         }
379 
380         play();
381     }
382 }
long ArtsEngine::position () const [virtual]
Returns: Time position in ms
Implements EngineBase (p.).
Definition at line 301 of file artsengine.cpp.
References m_pPlayObject.
302 {
303     if ( m_pPlayObject )
304         return m_pPlayObject->currentTime().seconds * 1000 +
305                m_pPlayObject->currentTime().ms;
306     else
307         return 0;
308 }
void ArtsEngine::removeEffect (long id) [virtual]
Reimplemented from EngineBase (p.).
Definition at line 574 of file artsengine.cpp.
References m_effectMap, and m_effectStack.
Referenced by saveEffects().
575 {
576     m_effectStack.remove( id );
577 
578     m_effectMap[id].effect->stop();
579     delete m_effectMap[id].widget;
580     delete m_effectMap[id].effect;
581 
582     m_effectMap.remove( id );
583 }
void ArtsEngine::saveEffects () [private]
Definition at line 740 of file artsengine.cpp.
References m_effectMap, and removeEffect().
Referenced by ~ArtsEngine().
741 {
742     QDomDocument doc;
743     QDomElement root = doc.createElement( "aRts-Effects" );
744     doc.appendChild( root );
745 
746     for ( QMap<long, EffectContainer>::Iterator it = m_effectMap.begin(); it != m_effectMap.end(); ++it )
747     {
748         QDomElement tagEffect = doc.createElement( "effect" );
749         root.appendChild( tagEffect );
750 
751             { //effectname
752                 QDomElement tag = doc.createElement( "effectname" );
753                 tagEffect.appendChild( tag );
754                 QDomText txt = doc.createTextNode( (*it.data().effect)._interfaceName().c_str() );
755                 tag.appendChild( txt );
756             }
757 
758         Arts::InterfaceDef def = (*it.data().effect)._queryInterface( (*it.data().effect)._interfaceName() );
759 
760         for ( uint i = 0; i < def.attributes.size(); i++ )
761         {
762             QDomElement tagAttribute = doc.createElement( "attribute" );
763             tagEffect.appendChild( tagAttribute );
764 
765             { //name
766                 QDomElement tag = doc.createElement( "name" );
767                 tagAttribute.appendChild( tag );
768                 QDomText txt = doc.createTextNode( def.attributes[i].name.c_str() );
769                 tag.appendChild( txt );
770             }
771 
772             Arts::DynamicRequest req( *it.data().effect );
773             req.method( "_get_" + def.attributes[i].name );
774             Arts::Any result;
775             result.type = def.attributes[i].type;
776 
777             { //type
778                 QDomElement tag = doc.createElement( "type" );
779                 tagAttribute.appendChild( tag );
780                 QDomText txt = doc.createTextNode( def.attributes[i].type.c_str() );
781                 tag.appendChild( txt );
782             }
783 
784             if ( !req.invoke( result ) )
785                 kdWarning() << "request failed." << endl;
786 
787             Arts::Buffer buf;
788             result.writeType( buf );
789 
790             { //value
791                 QDomElement tag = doc.createElement( "value" );
792                 tagAttribute.appendChild( tag );
793                 QDomText txt = doc.createTextNode( buf.toString( "" ).c_str() );
794                 tag.appendChild( txt );
795             }
796         }
797         removeEffect( it.key() );
798     }
799 
800     assert( kapp );
801     QString path = kapp->dirs()->saveLocation( "data", kapp->instanceName() + "/" ) + "arts-effects.xml";
802     QFile::remove( path );
803     QFile file( path );
804     file.open( IO_ReadWrite );
805     QTextStream stream( &file );
806     stream << doc;
807 }
std::vector< float > * ArtsEngine::scope () [virtual]
Fetches the current audio sample buffer.
Returns: Pointer to result of FFT calculation. Must be deleted after use.
Reimplemented from EngineBase (p.).
Definition at line 342 of file artsengine.cpp.
References m_scope, and Amarok::RawScope::scope().
343 {
344     return m_scope.scope();
345 }
void ArtsEngine::seek (long ms) [virtual, slot]
Implements EngineBase (p.).
Definition at line 449 of file artsengine.cpp.
References m_pPlayObject.
450 {
451 kdDebug() << "seek" << ms << endl;
452     if ( m_pPlayObject )
453     {
454     kdDebug() << "if ~~~seek" << ms << endl;
455         Arts::poTime time;
456         time.ms      = ms % 1000;
457         time.seconds = ( ms - time.ms ) / 1000;
458         time.custom  = 0.0;
459         m_pPlayObject->seek( time );
460     }
461 }
virtual void EngineBase::setDefaultSoundDevice (bool isDefault) [inline, virtual, inherited]
Definition at line 114 of file enginebase.h.
References EngineBase::m_defaultSoundDevice.
Referenced by Myplayer::Myplayer().
114 { m_defaultSoundDevice = isDefault; }
void EngineBase::setRestoreEffects (bool yes) [inline, inherited]
Definition at line 101 of file enginebase.h.
References EngineBase::m_restoreEffects.
Referenced by Myplayer::Myplayer().
101 { m_restoreEffects = yes; }
virtual void EngineBase::setSoundDevice (const QString & device) [inline, virtual, inherited]
Definition at line 113 of file enginebase.h.
References EngineBase::m_soundDevice.
Referenced by Myplayer::Myplayer().
113 { m_soundDevice = device; }
void EngineBase::setSoundOutput (const QString & output) [virtual, inherited]
Definition at line 87 of file enginebase.cpp.
References EngineBase::m_soundOutput.
Referenced by Myplayer::Myplayer().
88 {
89     kdDebug() << "Setting sound output to: " << output << endl;
90     
91     m_soundOutput = output;
92 }
void ArtsEngine::setVolume (int percent) [virtual, slot]
Parameters:
percent Set volume in range 0 to 100.
Implements EngineBase (p.).
Definition at line 464 of file artsengine.cpp.
References m_volumeControl, m_volumeId, and EngineBase::setVolumeHW().
465 {
466     m_volume = percent;
467 
468     if ( m_volumeId ) {
469         //using a logarithmic function to make the volume slider more natural
470         m_volumeControl.scaleFactor( 1.0 - log10( ( 100 - percent) * 0.09 + 1.0 ) );
471     }
472     else {
473         EngineBase::setVolumeHW( percent );
474     }
475 }
void EngineBase::setVolumeHW (int percent) [protected, inherited]
Definition at line 71 of file enginebase.cpp.
References EngineBase::m_mixerHW.
Referenced by setVolume().
72 {
73     if ( m_mixerHW != -1 )
74     {
75         percent = percent + ( percent << 8 );
76         ioctl( m_mixerHW, MIXER_WRITE( 4 ), &percent );
77     }
78 }
void EngineBase::setXfadeLength (int ms) [virtual, inherited]
Definition at line 81 of file enginebase.cpp.
References EngineBase::m_xfadeLength.
Referenced by Myplayer::Myplayer().
82 {
83     m_xfadeLength = ms;
84 }
void ArtsEngine::startXfade () [private]
Definition at line 632 of file artsengine.cpp.
References m_pPlayObject, and m_pPlayObjectXfade.
Referenced by play(), and stop().
633 {
634      if ( m_pPlayObjectXfade )
635     {
636         m_pPlayObjectXfade->halt();
637         delete m_pPlayObjectXfade;
638     }
639 
640     m_pPlayObjectXfade = m_pPlayObject;
641     m_pPlayObject = 0;
642 }
EngineBase::EngineState ArtsEngine::state () const [virtual]
Implements EngineBase (p.).
Definition at line 311 of file artsengine.cpp.
References m_pPlayObject.
312 {
313     if ( m_pPlayObject && !m_pPlayObject->isNull() )
314     {
315         if ( m_pPlayObject->object().isNull() )
316             return Playing;
317 
318         switch ( m_pPlayObject->state() )
319         {
320             case Arts::posPaused:
321                 return Paused;
322             case Arts::posPlaying:
323                 return Playing;
324             case Arts::posIdle:
325                 return Idle;
326         }
327     }
328 
329     return EngineBase::Empty;
330 }
void ArtsEngine::stop () [virtual, slot]
Implements EngineBase (p.).
Definition at line 425 of file artsengine.cpp.
References m_xfadeCurrent, m_xfadeFadeout, m_xfadeValue, and startXfade().
426 {
427     kdDebug() << k_funcinfo << endl;
428 
429     //switch xfade channels
430     m_xfadeCurrent = ( m_xfadeCurrent == "invalue1" ) ? "invalue2" : "invalue1";
431 
432     if ( m_xfadeValue == 0.0 )
433         m_xfadeValue = 1.0;
434 
435     m_xfadeFadeout = true;
436     startXfade();
437 }
void EngineBase::stopped () [signal, inherited]
Definition at line 119 of file enginebase.moc.
Referenced by play().
120 {
121     activate_signal( staticMetaObject()->signalOffset() + 1 );
122 }
StreamingMode ArtsEngine::streamingMode () [inline, virtual]
Reimplemented from EngineBase (p.).
Definition at line 61 of file artsengine.h.
61 { return Socket; }
bool ArtsEngine::supportsXFade () const [inline, virtual]
Determines whether the engine supports crossfading.
Returns: True if crossfading is supported.
Reimplemented from EngineBase (p.).
Definition at line 77 of file artsengine.h.
77 { return true; }
void ArtsEngine::timerEvent (QTimerEvent *) [private]
Definition at line 645 of file artsengine.cpp.
References ARTS_TIMER, m_pPlayObjectXfade, m_xfade, m_xfadeCurrent, m_xfadeFadeout, m_xfadeValue, and Amarok::Synth_STEREO_XFADE::percentage().
646 {
647     if ( m_xfadeValue > 0.0 )
648     {
649         m_xfadeValue -= ( m_xfadeLength ) ?  1.0 / m_xfadeLength * ARTS_TIMER : 1.0;
650 
651         if ( m_xfadeValue <= 0.0 )
652         {
653             m_xfadeValue = 0.0;
654             if ( m_pPlayObjectXfade )
655             {
656                 m_pPlayObjectXfade->halt();
657                 delete m_pPlayObjectXfade;
658                 m_pPlayObjectXfade = 0;
659             }
660         }
661         float value;
662         if ( m_xfadeFadeout )
663             value = 1.0 - log10( ( 1.0 - m_xfadeValue ) * 9.0 + 1.0 );
664         else
665             value = log10( m_xfadeValue * 9.0 + 1.0 );
666 
667         m_xfade.percentage( ( m_xfadeCurrent == "invalue2" ) ? value : 1.0 - value );
668     }
669 }
int EngineBase::volume () const [inline, inherited]
Sets the master volume.
Returns: Volume in range 0 to 100.
Definition at line 79 of file enginebase.h.
References EngineBase::m_volume.
Referenced by EngineController::decreaseVolume(), EngineController::increaseVolume(), and EngineController::setVolume().
79 { return m_volume; }
Member Data Documentation
const int ArtsEngine::ARTS_TIMER = 100 [static, private]
Definition at line 119 of file artsengine.h.
Referenced by init(), and timerEvent().
Arts::Synth_AMAN_PLAY ArtsEngine::m_amanPlay [private]
Definition at line 129 of file artsengine.h.
Referenced by init(), and ~ArtsEngine().
bool EngineBase::m_defaultSoundDevice [protected, inherited]
Definition at line 145 of file enginebase.h.
Referenced by EngineBase::setDefaultSoundDevice().
QMap<long, EffectContainer> ArtsEngine::m_effectMap [private]
Definition at line 138 of file artsengine.h.
Referenced by activeEffects(), configureEffect(), createEffect(), effectConfigurable(), effectNameForId(), loadEffects(), removeEffect(), and saveEffects().
Arts::StereoEffectStack ArtsEngine::m_effectStack [private]
Definition at line 127 of file artsengine.h.
Referenced by createEffect(), init(), removeEffect(), and ~ArtsEngine().
Arts::StereoEffectStack ArtsEngine::m_globalEffectStack [private]
Definition at line 126 of file artsengine.h.
Referenced by init(), initMixer(), and ~ArtsEngine().
int EngineBase::m_mixerHW [protected, inherited]
Definition at line 139 of file enginebase.h.
Referenced by EngineBase::closeMixerHW(), EngineBase::initMixerHW(), EngineBase::isMixerHardware(), and EngineBase::setVolumeHW().
KArtsDispatcher* ArtsEngine::m_pArtsDispatcher [private]
Definition at line 122 of file artsengine.h.
QTimer* ArtsEngine::m_pConnectTimer [private]
Definition at line 144 of file artsengine.h.
Referenced by connectPlayObject(), connectTimeout(), init(), play(), and ~ArtsEngine().
QGuardedPtr<ArtsConfigWidget> ArtsEngine::m_pDecoderConfigWidget [private]
Definition at line 143 of file artsengine.h.
Referenced by configureDecoder(), and decoderConfigurable().
KDE::PlayObject* ArtsEngine::m_pPlayObject [private]
Definition at line 123 of file artsengine.h.
Referenced by configureDecoder(), connectPlayObject(), connectTimeout(), decoderConfigurable(), isStream(), pause(), play(), position(), seek(), startXfade(), state(), and ~ArtsEngine().
KDE::PlayObject* ArtsEngine::m_pPlayObjectXfade [private]
Definition at line 124 of file artsengine.h.
Referenced by startXfade(), timerEvent(), and ~ArtsEngine().
bool EngineBase::m_restoreEffects [protected, inherited]
Definition at line 142 of file enginebase.h.
Referenced by EngineBase::setRestoreEffects().
Amarok::RawScope ArtsEngine::m_scope [private]
Definition at line 130 of file artsengine.h.
Referenced by init(), scope(), and ~ArtsEngine().
long ArtsEngine::m_scopeId [private]
Definition at line 135 of file artsengine.h.
Referenced by init().
int ArtsEngine::m_scopeSize [private]
Definition at line 136 of file artsengine.h.
Referenced by init().
Arts::SoundServerV2 ArtsEngine::m_server [private]
Definition at line 125 of file artsengine.h.
Referenced by createEffect(), init(), initMixer(), play(), and ~ArtsEngine().
QString EngineBase::m_soundDevice [protected, inherited]
Definition at line 144 of file enginebase.h.
Referenced by EngineBase::setSoundDevice().
QString EngineBase::m_soundOutput [protected, inherited]
Definition at line 143 of file enginebase.h.
Referenced by EngineBase::setSoundOutput().
int EngineBase::m_volume [protected, inherited]
Definition at line 140 of file enginebase.h.
Referenced by EngineBase::volume().
Arts::StereoVolumeControl ArtsEngine::m_volumeControl [private]
Definition at line 128 of file artsengine.h.
Referenced by initMixer(), setVolume(), and ~ArtsEngine().
long ArtsEngine::m_volumeId [private]
Definition at line 137 of file artsengine.h.
Referenced by initMixer(), and setVolume().
Amarok::Synth_STEREO_XFADE ArtsEngine::m_xfade [private]
Definition at line 132 of file artsengine.h.
Referenced by connectPlayObject(), init(), timerEvent(), and ~ArtsEngine().
QString ArtsEngine::m_xfadeCurrent [private]
Definition at line 142 of file artsengine.h.
Referenced by connectPlayObject(), stop(), and timerEvent().
bool ArtsEngine::m_xfadeFadeout [private]
Definition at line 140 of file artsengine.h.
Referenced by play(), stop(), and timerEvent().
int EngineBase::m_xfadeLength [protected, inherited]
Definition at line 141 of file enginebase.h.
Referenced by EngineBase::setXfadeLength().
float ArtsEngine::m_xfadeValue [private]
Definition at line 141 of file artsengine.h.
Referenced by connectPlayObject(), init(), stop(), and timerEvent().
const int ArtsEngine::TIMEOUT = 4000 [static, private]
Definition at line 120 of file artsengine.h.
Referenced by play().
The documentation for this class was generated from the following files:
artsengine.h
artsengine.cpp