QtFileIconViewItem Class Reference
#include <qfileiconview.h>
Public Types
enum ItemType { File = 0,
Dir,
Link,
Image
 }
Public Member Functions
QtFileIconViewItem (QtFileIconView *parent, QFileInfo *fi, int pixindex)
virtual ~QtFileIconViewItem ()
ItemType type () const
QString filename () const
virtual bool acceptDrop (const QMimeSource *e) const
virtual void setText (const QString &text)
virtual QPixmap * pixmap () const
virtual void dragEntered ()
virtual void dragLeft ()
void viewModeChanged (QtFileIconView::ViewMode m)
void paintItem (QPainter *p, const QColorGroup &cg)
Public Attributes
QPixmap img
QPixmap * p_img
Protected Member Functions
virtual void dropped (QDropEvent *e, const QValueList< QIconDragItem > &)
Protected Attributes
QString itemFileName
QFileInfo * itemFileInfo
ItemType itemType
bool checkSetText
QTimer timer
QtFileIconView::ViewMode vm
int PixIndex
Friends
class QtFileIconView
Member Enumeration Documentation
enum QtFileIconViewItem::ItemType
Enumeration values:
File
Dir
Link
Image
Definition at line 141 of file qfileiconview.h.
Referenced by type().
141                   {
142         File = 0,// define MP3 file
143         Dir,
144         Link,
145         Image
146     };
Constructor & Destructor Documentation
QtFileIconViewItem::QtFileIconViewItem (QtFileIconView * parent, QFileInfo * fi, int pixindex)
Definition at line 98 of file qfileiconview.cpp.
References addBorder(), ArrayImage, checkSetText, File, Image, img, itemFileInfo, itemFileName, itemType, and PixIndex.
99     : QIconViewItem( parent, fi->fileName() ), itemFileName( fi->filePath() ),PixIndex(pixindex),
100       itemFileInfo( fi ), checkSetText( FALSE )
101 {
102     vm = QtFileIconView::Large;//view mode
103 
104    if ( itemFileInfo->isFile() )
105     {
106         if(fi->extension()=="jpg"||fi->extension()=="png"||fi->extension()=="bmp"||fi->extension()=="jpeg")
107         itemType=Image;
108         else if(fi->extension()=="mp3")
109         {
110         itemType = File;//MP3 File
111         }
112     }
113 
114     checkSetText = TRUE;
115 
116     QObject::connect( &timer, SIGNAL( timeout() ), iconView(), SLOT( openFolder() ) );
117         if(itemType==Image)
118         {
119                  if(ArrayImage[PixIndex])
120                  {
121                         delete ArrayImage[PixIndex];
122                  }
123                  img=QPixmap(itemFileName);
124                 ArrayImage[PixIndex]=addBorder(&img,1);
125                 setPixmap(*ArrayImage[PixIndex]);
126         }
127 }
QtFileIconViewItem::~QtFileIconViewItem () [virtual]
Definition at line 161 of file qfileiconview.cpp.
References itemFileInfo.
162 {
163     delete itemFileInfo;
164 }
Member Function Documentation
bool QtFileIconViewItem::acceptDrop (const QMimeSource * e) const [virtual]
Definition at line 209 of file qfileiconview.cpp.
References Dir, and type().
210 {
211     if ( type() == Dir && e->provides( "text/uri-list" ) &&
212          dropEnabled() )
213         return TRUE;
214 
215     return FALSE;
216 }
void QtFileIconViewItem::dragEntered () [virtual]
Definition at line 247 of file qfileiconview.cpp.
References Dir, itemFileName, and type().
248 {
249     if ( type() != Dir ||
250          type() == Dir && !QDir( itemFileName ).isReadable() )
251         return;
252 
253     ( (QtFileIconView*)iconView() )->setOpenItem( this );
254     timer.start( 1500 );
255 }
void QtFileIconViewItem::dragLeft () [virtual]
Definition at line 257 of file qfileiconview.cpp.
References Dir, itemFileName, and type().
258 {
259     if ( type() != Dir ||
260          type() == Dir && !QDir( itemFileName ).isReadable() )
261         return;
262 
263     timer.stop();
264 }
void QtFileIconViewItem::dropped (QDropEvent * e, const QValueList< QIconDragItem > &) [protected, virtual]
Definition at line 218 of file qfileiconview.cpp.
References filename().
219 {
220     timer.stop();
221 
222     if ( !QUriDrag::canDecode( e ) ) {
223         e->ignore();
224         return;
225     }
226 
227     QStringList lst;
228     QUriDrag::decodeLocalFiles( e, lst );
229 
230     QString str;
231     if ( e->action() == QDropEvent::Copy )
232         str = "Copy\n\n";
233     else
234         str = "Move\n\n";
235     for ( uint i = 0; i < lst.count(); ++i )
236         str += QString( "   %1\n" ).arg( lst[i] );
237     str += QString( "\n"
238         "To\n\n"
239         "       %1" ).arg( filename() );
240 
241     QMessageBox::information( iconView(), e->action() == QDropEvent::Copy ? "Copy" : "Move" , str, "Not Implemented" );
242     if ( e->action() == QDropEvent::Move )
243         QMessageBox::information( iconView(), "Remove" , str, "Not Implemented" );
244     e->acceptAction();
245 }
QString QtFileIconViewItem::filename () const [inline]
Definition at line 154 of file qfileiconview.h.
References itemFileName.
Referenced by QtFileIconView::dragObject(), dropped(), QtFileIconView::itemDoubleClicked(), and QtFileIconView::slotDeletCurrItem().
154 { return itemFileName; }
void QtFileIconViewItem::paintItem (QPainter * p, const QColorGroup & cg)
Definition at line 128 of file qfileiconview.cpp.
References itemFileInfo.
129 {
130     if ( itemFileInfo->isSymLink() ) {
131         QFont f( p->font() );
132         f.setItalic( TRUE );
133         p->setFont( f );
134     }
135     QIconViewItem::paintItem( p, cg );
136 }
QPixmap * QtFileIconViewItem::pixmap () const [virtual]
Definition at line 145 of file qfileiconview.cpp.
References ArrayImage, iconFileLarge, Image, itemType, and PixIndex.
146 {
147     switch ( itemType ) 
148     {
149    
150         case Image:
151         {
152                 return ArrayImage[PixIndex];
153         }
154         default:
155         {
156                 return iconFileLarge;
157         }
158     }
159 }
void QtFileIconViewItem::setText (const QString & text) [virtual]
Definition at line 166 of file qfileiconview.cpp.
References checkSetText, itemFileInfo, and itemFileName.
167 {
168     if ( checkSetText ) {
169         if ( text == "." || text == "." || text.isEmpty() )
170             return;
171         QDir dir( itemFileInfo->dir() );
172         if ( dir.rename( itemFileInfo->fileName(), text ) ) {
173             itemFileName = itemFileInfo->dirPath( TRUE ) + "/" + text;
174             delete itemFileInfo;
175             itemFileInfo = new QFileInfo( itemFileName );
176             QIconViewItem::setText( text );
177         }
178     } else {
179         QIconViewItem::setText( text );
180     }
181 }
ItemType QtFileIconViewItem::type () const [inline]
Definition at line 152 of file qfileiconview.h.
References itemType, and ItemType.
Referenced by acceptDrop(), dragEntered(), dragLeft(), QtFileIconView::itemDoubleClicked(), and QtFileIconView::openFolder().
153     { return itemType; }
void QtFileIconViewItem::viewModeChanged (QtFileIconView::ViewMode m)
Definition at line 138 of file qfileiconview.cpp.
References Dir, itemFileName, and itemType.
Referenced by QtFileIconView::setViewMode().
139 {
140     vm = m;
141     setDropEnabled( itemType == Dir && QDir( itemFileName ).isReadable() );
142     calcRect();
143 }
Friends And Related Function Documentation
friend class QtFileIconView [friend]
Definition at line 138 of file qfileiconview.h.
Member Data Documentation
bool QtFileIconViewItem::checkSetText [protected]
Definition at line 175 of file qfileiconview.h.
Referenced by QtFileIconViewItem(), and setText().
QPixmap QtFileIconViewItem::img
Definition at line 167 of file qfileiconview.h.
Referenced by QtFileIconViewItem().
QFileInfo* QtFileIconViewItem::itemFileInfo [protected]
Definition at line 173 of file qfileiconview.h.
Referenced by paintItem(), QtFileIconViewItem(), setText(), and ~QtFileIconViewItem().
QString QtFileIconViewItem::itemFileName [protected]
Definition at line 172 of file qfileiconview.h.
Referenced by dragEntered(), dragLeft(), filename(), QtFileIconView::openFolder(), QtFileIconViewItem(), setText(), and viewModeChanged().
ItemType QtFileIconViewItem::itemType [protected]
Definition at line 174 of file qfileiconview.h.
Referenced by pixmap(), QtFileIconViewItem(), type(), and viewModeChanged().
QPixmap * QtFileIconViewItem::p_img
Definition at line 167 of file qfileiconview.h.
int QtFileIconViewItem::PixIndex [protected]
Definition at line 178 of file qfileiconview.h.
Referenced by pixmap(), and QtFileIconViewItem().
QTimer QtFileIconViewItem::timer [protected]
Definition at line 176 of file qfileiconview.h.
Referenced by QtFileIconView::openFolder(), and QtFileIconView::slotDropped().
QtFileIconView::ViewMode QtFileIconViewItem::vm [protected]
Definition at line 177 of file qfileiconview.h.
The documentation for this class was generated from the following files:
qfileiconview.h
qfileiconview.cpp