Amarok::RawScope_base Class Reference
#include <amarokarts.h>
Public Member Functions
RawScope_base * _copy ()
virtual std::vector< std::string > _defaultPortsIn () const
virtual std::vector< std::string > _defaultPortsOut () const
void * _cast (unsigned long iid)
virtual long buffer ()=0
virtual void buffer (long newValue)=0
virtual std::vector< float > * scope ()=0
Static Public Member Functions
RawScope_base * _create (const std::string &subClass=`Amarok::RawScope`)
RawScope_base * _fromString (const std::string &objectref)
RawScope_base * _fromReference (Arts::ObjectReference ref, bool needcopy)
RawScope_base * _fromDynamicCast (const Arts::Object &object)
Static Public Attributes
unsigned long _IID = Arts::MCOPUtils::makeIID(`Amarok::RawScope`)
Member Function Documentation
void * Amarok::RawScope_base::_cast (unsigned long iid)
Definition at line 249 of file amarokarts.cc.
References _IID.
Referenced by _fromDynamicCast(), and Amarok::RawScope::_method_call().
250 {
251         if(iid == Amarok::RawScope_base::_IID) return (Amarok::RawScope_base *)this;
252         if(iid == Arts::StereoEffect_base::_IID) return (Arts::StereoEffect_base *)this;
253         if(iid == Arts::SynthModule_base::_IID) return (Arts::SynthModule_base *)this;
254         if(iid == Arts::Object_base::_IID) return (Arts::Object_base *)this;
255         return 0;
256 }
RawScope_base* Amarok::RawScope_base::_copy () [inline]
Definition at line 139 of file amarokarts.h.
Referenced by _fromDynamicCast().
139                                       {
140                 assert(_refCnt > 0);
141                 _refCnt++;
142                 return this;
143         }
Amarok::RawScope_base * Amarok::RawScope_base::_create (const std::string & subClass = `Amarok::RawScope`) [static]
Definition at line 182 of file amarokarts.cc.
References _IID.
Referenced by Amarok::RawScope::_Creator().
183 {
184         Arts::Object_skel *skel = Arts::ObjectManager::the()->create(subClass);
185         assert(skel);
186         Amarok::RawScope_base *castedObject = (Amarok::RawScope_base *)skel->_cast(Amarok::RawScope_base::_IID);
187         assert(castedObject);
188         return castedObject;
189 }
std::vector< std::string > Amarok::RawScope_base::_defaultPortsIn () const [virtual]
Definition at line 236 of file amarokarts.cc.
236                                                                 {
237         std::vector<std::string> ret;
238         ret.push_back("inleft");
239         ret.push_back("inright");
240         return ret;
241 }
std::vector< std::string > Amarok::RawScope_base::_defaultPortsOut () const [virtual]
Definition at line 242 of file amarokarts.cc.
242                                                                  {
243         std::vector<std::string> ret;
244         ret.push_back("outleft");
245         ret.push_back("outright");
246         return ret;
247 }
Amarok::RawScope_base * Amarok::RawScope_base::_fromDynamicCast (const Arts::Object & object) [static]
Definition at line 200 of file amarokarts.cc.
References _cast(), _copy(), _fromString(), and _IID.
201 {
202         if(object.isNull()) return 0;
203 
204         Amarok::RawScope_base *castedObject = (Amarok::RawScope_base *)object._base()->_cast(Amarok::RawScope_base::_IID);
205         if(castedObject) return castedObject->_copy();
206 
207         return _fromString(object._toString());
208 }
Amarok::RawScope_base * Amarok::RawScope_base::_fromReference (Arts::ObjectReference ref, bool needcopy) [static]
Definition at line 210 of file amarokarts.cc.
Referenced by _fromString().
211 {
212         Amarok::RawScope_base *result;
213         result = (Amarok::RawScope_base *)Arts::Dispatcher::the()->connectObjectLocal(r,"Amarok::RawScope");
214         if(result)
215         {
216                 if(!needcopy)
217                         result->_cancelCopyRemote();
218         }
219         else
220         {
221                 Arts::Connection *conn = Arts::Dispatcher::the()->connectObjectRemote(r);
222                 if(conn)
223                 {
224                         result = new Amarok::RawScope_stub(conn,r.objectID);
225                         if(needcopy) result->_copyRemote();
226                         result->_useRemote();
227                         if (!result->_isCompatibleWith("Amarok::RawScope")) {
228                                 result->_release();
229                                 return 0;
230                         }
231                 }
232         }
233         return result;
234 }
Amarok::RawScope_base * Amarok::RawScope_base::_fromString (const std::string & objectref) [static]
Definition at line 191 of file amarokarts.cc.
References _fromReference().
Referenced by _fromDynamicCast().
192 {
193         Arts::ObjectReference r;
194 
195         if(Arts::Dispatcher::the()->stringToObjectReference(r,objectref))
196                 return Amarok::RawScope_base::_fromReference(r,true);
197         return 0;
198 }
virtual void Amarok::RawScope_base::buffer (long newValue) [pure virtual]
Implemented in Amarok::RawScope_stub (p.).
virtual long Amarok::RawScope_base::buffer () [pure virtual]
Implemented in Amarok::RawScope_stub (p.).
Referenced by Amarok::RawScope::buffer().
virtual std::vector<float>* Amarok::RawScope_base::scope () [pure virtual]
Implemented in Amarok::RawScope_stub (p.).
Referenced by Amarok::RawScope::scope().
Member Data Documentation
unsigned long Amarok::RawScope_base::_IID = Arts::MCOPUtils::makeIID(`Amarok::RawScope`) [static]
Definition at line 381 of file amarokarts.cc.
Referenced by _cast(), _create(), and _fromDynamicCast().
The documentation for this class was generated from the following files:
amarokarts.h
amarokarts.cc