DirectoryView Class Reference
#include <dirview.h>
Public Slots
void setDir (const QString &)
Signals
void folderSelected (const QString &)
Public Member Functions
DirectoryView (QWidget *parent=0, const char *name=0, bool sdo=FALSE)
bool showDirsOnly ()
Protected Slots
void slotFolderSelected (QListViewItem *)
void openFolder ()
Protected Member Functions
void contentsDragEnterEvent (QDragEnterEvent *e)
void contentsDragMoveEvent (QDragMoveEvent *e)
void contentsDragLeaveEvent (QDragLeaveEvent *e)
void contentsDropEvent (QDropEvent *e)
void contentsMouseMoveEvent (QMouseEvent *e)
void contentsMousePressEvent (QMouseEvent *e)
void contentsMouseReleaseEvent (QMouseEvent *e)
Private Member Functions
QString fullPath (QListViewItem *item)
Private Attributes
bool dirsOnly
QListViewItem * oldCurrent
QListViewItem * dropItem
QTimer * autoopen_timer
QPoint presspos
bool mousePressed
Constructor & Destructor Documentation
DirectoryView::DirectoryView (QWidget * parent = 0, const char * name = 0, bool sdo = FALSE)
Definition at line 236 of file dirview.cpp.
References autoopen_timer, fileNormal, folder_locked, folderClosed, folderLocked, folderOpen, openFolder(), pix_file, and slotFolderSelected().
237     : QListView( parent, name ), dirsOnly( sdo ), oldCurrent( 0 ),
238       dropItem( 0 ), mousePressed( FALSE )
239 {
240     autoopen_timer = new QTimer( this );
241     if ( !folderLocked ) {
242         folderLocked = new QPixmap( folder_locked );
243         folderClosed = new QPixmap( "/root/kde_application/hdass08/skin/folder_sound.png" );
244         folderOpen = new QPixmap( "/root/kde_application/hdass08/skin/folder_sound.png" );
245         fileNormal = new QPixmap( pix_file );
246     }
247 
248     connect( this, SIGNAL( doubleClicked( QListViewItem * ) ),
249              this, SLOT( slotFolderSelected( QListViewItem * ) ) );
250     connect( this, SIGNAL( returnPressed( QListViewItem * ) ),
251              this, SLOT( slotFolderSelected( QListViewItem * ) ) );
252 
253     setAcceptDrops( TRUE );
254     viewport()->setAcceptDrops( TRUE );
255 
256     connect( autoopen_timer, SIGNAL( timeout() ),
257              this, SLOT( openFolder() ) );
258 }
Member Function Documentation
void DirectoryView::contentsDragEnterEvent (QDragEnterEvent * e) [protected]
Definition at line 281 of file dirview.cpp.
References autoopen_timer, autoopenTime, dropItem, and oldCurrent.
282 {
283     if ( !QUriDrag::canDecode(e) ) {
284         e->ignore();
285         return;
286     }
287 
288     oldCurrent = currentItem();
289 
290     QListViewItem *i = itemAt( contentsToViewport(e->pos()) );
291     if ( i ) {
292         dropItem = i;
293         autoopen_timer->start( autoopenTime );
294     }
295     
296 }
void DirectoryView::contentsDragLeaveEvent (QDragLeaveEvent * e) [protected]
Definition at line 336 of file dirview.cpp.
References autoopen_timer, dropItem, and oldCurrent.
337 {
338     autoopen_timer->stop();
339     dropItem = 0;
340 
341     setCurrentItem( oldCurrent );
342     setSelected( oldCurrent, TRUE );
343 }
void DirectoryView::contentsDragMoveEvent (QDragMoveEvent * e) [protected]
Definition at line 299 of file dirview.cpp.
References autoopen_timer, autoopenTime, and dropItem.
300 {
301     if ( !QUriDrag::canDecode(e) ) {
302         e->ignore();
303         return;
304     }
305 
306     QPoint vp = contentsToViewport( ( (QDragMoveEvent*)e )->pos() );
307     QListViewItem *i = itemAt( vp );
308     
309     if ( i ) {
310         setSelected( i, TRUE );
311         e->accept();
312         if ( i != dropItem ) {
313             autoopen_timer->stop();
314             dropItem = i;
315             autoopen_timer->start( autoopenTime );
316         }
317         switch ( e->action() ) {
318         case QDropEvent::Copy:
319             break;
320         case QDropEvent::Move:
321             e->acceptAction();
322             break;
323         case QDropEvent::Link:
324             e->acceptAction();
325             break;
326         default:
327             ;
328         }
329     } else {
330         e->ignore();
331         autoopen_timer->stop();
332         dropItem = 0;
333     }
334 }
void DirectoryView::contentsDropEvent (QDropEvent * e) [protected]
Definition at line 345 of file dirview.cpp.
References autoopen_timer, and fullPath().
346 {
347     autoopen_timer->stop();
348 
349     if ( !QUriDrag::canDecode(e) ) {
350         e->ignore();
351         return;
352     }
353 
354     QListViewItem *item = itemAt( contentsToViewport(e->pos()) );
355     
356     if(item)
357     {
358         //DAVID make a list to receive the dropping objects
359         QStrList lst;
360         
361         //DAVID decode the objects data to list
362         QUriDrag::decode( e, lst );
363         
364         QString DirName=QDir::convertSeparators(fullPath(item));
365 
366         for ( uint i = 0; i < lst.count(); ++i ) 
367         
368         {
369                 
370                 //kdDebug()<<lst.at(i);
371                 //DAVID get the dropping object name
372                 QString fullpathfilename = QDir::convertSeparators(QUriDrag::uriToLocalFile(lst.at(i)));
373                 QUrl url(fullpathfilename);
374                 QString filename=url.fileName();
375                 QString distfilename=DirName+QString("/")+filename;
376                 //copy file
377                 KIO::copy(KURL(fullpathfilename),KURL(distfilename),false);
378         }
379         
380     }
381     else
382     {
383      e->ignore();
384     }
385 
386 }
void DirectoryView::contentsMouseMoveEvent (QMouseEvent * e) [protected]
Definition at line 424 of file dirview.cpp.
References fullPath(), mousePressed, and presspos.
425 {
426     if ( mousePressed && ( presspos - e->pos() ).manhattanLength() > QApplication::startDragDistance() ) {
427         mousePressed = FALSE;
428         QListViewItem *item = itemAt( contentsToViewport(presspos) );
429         if ( item ) {
430             QString source = fullPath(item);
431             if ( QFile::exists(source) ) {
432                 QUriDrag* ud = new QUriDrag(viewport());
433                 ud->setFileNames( source );
434                 if ( ud->drag() )
435                     QMessageBox::information( this, "Drag source",
436                     QString("Delete ") + QDir::convertSeparators(source), "Not implemented" );
437             }
438         }
439     }
440 }
void DirectoryView::contentsMousePressEvent (QMouseEvent * e) [protected]
Definition at line 408 of file dirview.cpp.
References mousePressed, and presspos.
409 {
410     QListView::contentsMousePressEvent(e);
411     QPoint p( contentsToViewport( e->pos() ) );
412     QListViewItem *i = itemAt( p );
413     if ( i ) {
414         // if the user clicked into the root decoration of the item, don't try to start a drag!
415         if ( p.x() > header()->cellPos( header()->mapToActual( 0 ) ) +
416              treeStepSize() * ( i->depth() + ( rootIsDecorated() ? 1 : 0) ) + itemMargin() ||
417              p.x() < header()->cellPos( header()->mapToActual( 0 ) ) ) {
418             presspos = e->pos();
419             mousePressed = TRUE;
420         }
421     }
422 }
void DirectoryView::contentsMouseReleaseEvent (QMouseEvent * e) [protected]
Definition at line 442 of file dirview.cpp.
References mousePressed.
443 {
444     mousePressed = FALSE;
445 }
void DirectoryView::folderSelected (const QString &) [signal]
Definition at line 97 of file dirview.moc.cc.
Referenced by slotFolderSelected().
98 {
99     activate_signal( staticMetaObject()->signalOffset() + 0, t0 );
100 }
QString DirectoryView::fullPath (QListViewItem * item) [private]
Definition at line 389 of file dirview.cpp.
Referenced by contentsDropEvent(), and contentsMouseMoveEvent().
390 {
391     QString fullpath = item->text(0);
392     while ( (item=item->parent()) ) {
393         if ( item->parent() )
394             fullpath = item->text(0) + "/" + fullpath;
395         else
396             fullpath = item->text(0) + fullpath;
397     }
398 #ifdef Q_WS_WIN
399         if (fullpath.length() > 2 && fullpath[1] != ':') {
400                 QDir dir(fullpath);
401                 fullpath = dir.currentDirPath().left(2) + fullpath;
402         }
403 #endif
404         
405     return fullpath;
406 }
void DirectoryView::openFolder () [protected, slot]
Definition at line 269 of file dirview.cpp.
References autoopen_timer, and dropItem.
Referenced by DirectoryView().
270 {
271     autoopen_timer->stop();
272     if ( dropItem && !dropItem->isOpen() ) {
273         dropItem->setOpen( TRUE );
274         dropItem->repaint();
275     }
276 }
void DirectoryView::setDir (const QString &) [slot]
Definition at line 447 of file dirview.cpp.
448 {
449     QListViewItemIterator it( this );
450     ++it;
451     for ( ; it.current(); ++it ) {
452         it.current()->setOpen( FALSE );
453     }
454 
455     QStringList lst( QStringList::split( "/", s ) );
456     QListViewItem *item = firstChild();
457     QStringList::Iterator it2 = lst.begin();
458     for ( ; it2 != lst.end(); ++it2 ) {
459         while ( item ) {
460             if ( item->text( 0 ) == *it2 ) {
461                 item->setOpen( TRUE );
462                 break;
463             }
464             item = item->itemBelow();
465         }
466     }
467 
468     if ( item )
469         setCurrentItem( item );
470 }
bool DirectoryView::showDirsOnly () [inline]
Definition at line 80 of file dirview.h.
References dirsOnly.
Referenced by slotFolderSelected().
80 { return dirsOnly; }
void DirectoryView::slotFolderSelected (QListViewItem *) [protected, slot]
Definition at line 260 of file dirview.cpp.
References folderSelected(), Directory::fullName(), and showDirsOnly().
Referenced by DirectoryView().
261 {
262     if ( !i || !showDirsOnly() )
263         return;
264 
265     Directory *dir = (Directory*)i;
266     emit folderSelected( dir->fullName() );
267 }
Member Data Documentation
QTimer* DirectoryView::autoopen_timer [private]
Definition at line 106 of file dirview.h.
Referenced by contentsDragEnterEvent(), contentsDragLeaveEvent(), contentsDragMoveEvent(), contentsDropEvent(), DirectoryView(), and openFolder().
bool DirectoryView::dirsOnly [private]
Definition at line 103 of file dirview.h.
Referenced by showDirsOnly().
QListViewItem* DirectoryView::dropItem [private]
Definition at line 105 of file dirview.h.
Referenced by contentsDragEnterEvent(), contentsDragLeaveEvent(), contentsDragMoveEvent(), and openFolder().
bool DirectoryView::mousePressed [private]
Definition at line 108 of file dirview.h.
Referenced by contentsMouseMoveEvent(), contentsMousePressEvent(), and contentsMouseReleaseEvent().
QListViewItem* DirectoryView::oldCurrent [private]
Definition at line 104 of file dirview.h.
Referenced by contentsDragEnterEvent(), and contentsDragLeaveEvent().
QPoint DirectoryView::presspos [private]
Definition at line 107 of file dirview.h.
Referenced by contentsMouseMoveEvent(), and contentsMousePressEvent().
The documentation for this class was generated from the following files:
dirview.h
dirview.moc.cc
dirview.cpp