SubBarAlbumClock Class Reference
#include <subbaralbumclock.h>
Detailed Description
Author: sonicat
Definition at line 30 of file src/subbaralbumclock.h.
Public Slots
void slotChangeMode ()
void slotChangePlayNPauseBtnGraphic ()
void slotChangeMode ()
void slotChangePlayNPauseBtnGraphic ()
Signals
void signalAlbumClockModeChangeToDispalyArea (int)
void signalAlbumClockModeChangeToDispalyArea (int)
Public Member Functions
SubBarAlbumClock (QWidget *parent=0, const char *name=0)
~SubBarAlbumClock ()
void xSetup ()
SubBarAlbumClock (QWidget *parent=0, const char *name=0)
~SubBarAlbumClock ()
void xSetup ()
Public Attributes
SkinButton * SubBarBtnAlbumClock
SkinButton * SubBarBtnPrevious
SkinButton * SubBarBtnPlayNPause
SkinButton * SubBarBtnNext
SkinButton * SubBarBtnAlbumClock
Private Types
enum SLIDESHOWSTATE { GO = 0,
STOP
 }
enum SLIDESHOWSTATE { GO = 0,
STOP
 }
Private Member Functions
void ChangeButtonGraphic (int)
void ChangeButtonGraphic (int)
Private Attributes
QPixmap * btnGraphic [12]
QPixmap pixBackground
SLIDESHOWSTATE slideshowstate
QPixmap * btnGraphic [12]
Member Enumeration Documentation
enum SubBarAlbumClock::SLIDESHOWSTATE [private]
Enumeration values:
GO
STOP
Definition at line 32 of file subbaralbumclock.h.
33 {
34         GO=0,
35         STOP
36 };
enum SubBarAlbumClock::SLIDESHOWSTATE [private]
Enumeration values:
GO
STOP
Definition at line 33 of file src/subbaralbumclock.h.
34 {
35         GO=0,
36         STOP
37 };
Constructor & Destructor Documentation
SubBarAlbumClock::SubBarAlbumClock (QWidget * parent = 0, const char * name = 0)
Definition at line 22 of file src/subbaralbumclock.cpp.
References xSetup().
23  : QWidget(parent, name)
24 {
25  xSetup();
26 }
SubBarAlbumClock::~SubBarAlbumClock ()
Definition at line 29 of file src/subbaralbumclock.cpp.
30 {
31 }
SubBarAlbumClock::SubBarAlbumClock (QWidget * parent = 0, const char * name = 0)
SubBarAlbumClock::~SubBarAlbumClock ()
Member Function Documentation
void SubBarAlbumClock::ChangeButtonGraphic (int) [private]
void SubBarAlbumClock::ChangeButtonGraphic (int) [private]
Definition at line 89 of file src/subbaralbumclock.cpp.
References GlobalSetting, HDASSGlobalSetting::intHDSS_DISPLAY_STATE, SkinButton::setPixmaps(), signalAlbumClockModeChangeToDispalyArea(), and SubBarBtnAlbumClock.
Referenced by slotChangeMode().
90 {
91     qWarning("~~~~~~~~%d",GlobalSetting.intHDSS_DISPLAY_STATE);
92     emit signalAlbumClockModeChangeToDispalyArea(GlobalSetting.intHDSS_DISPLAY_STATE);
93    if(!Mode)//Album
94    SubBarBtnAlbumClock->setPixmaps(btnGraphic[0],btnGraphic[1]);
95    else//Clock
96    SubBarBtnAlbumClock->setPixmaps(btnGraphic[2],btnGraphic[3]);
97  
98 }
void SubBarAlbumClock::signalAlbumClockModeChangeToDispalyArea (int) [signal]
void SubBarAlbumClock::signalAlbumClockModeChangeToDispalyArea (int) [signal]
Definition at line 89 of file subbaralbumclock.moc.
Referenced by ChangeButtonGraphic().
90 {
91     activate_signal( staticMetaObject()->signalOffset() + 0, t0 );
92 }
void SubBarAlbumClock::slotChangeMode () [slot]
void SubBarAlbumClock::slotChangeMode () [slot]
Definition at line 78 of file src/subbaralbumclock.cpp.
References ChangeButtonGraphic(), GlobalSetting, HDASSGlobalSetting::intHDASS_ALBUMCLOCK_STATE, and HDASSGlobalSetting::intHDSS_DISPLAY_STATE.
Referenced by xSetup().
79 {
80   
81   // +3 make the value init form em_dispaly_album (3)
82   //qWarning("~~~~~~~~%d",GlobalSetting.intHDASS_ALBUMCLOCK_STATE);
83   GlobalSetting.intHDASS_ALBUMCLOCK_STATE++;
84   GlobalSetting.intHDASS_ALBUMCLOCK_STATE%=2;
85   GlobalSetting.intHDSS_DISPLAY_STATE=GlobalSetting.intHDASS_ALBUMCLOCK_STATE+3;
86   ChangeButtonGraphic(GlobalSetting.intHDASS_ALBUMCLOCK_STATE);
87 }
void SubBarAlbumClock::slotChangePlayNPauseBtnGraphic () [slot]
void SubBarAlbumClock::slotChangePlayNPauseBtnGraphic () [slot]
Definition at line 100 of file src/subbaralbumclock.cpp.
References GO, SkinButton::setPixmaps(), slideshowstate, STOP, and SubBarBtnPlayNPause.
Referenced by xSetup().
101 {
102   if(slideshowstate==SubBarAlbumClock::STOP)
103  {
104   slideshowstate=SubBarAlbumClock::GO;
105   SubBarBtnPlayNPause->setPixmaps(btnGraphic[6],btnGraphic[7]);
106  }
107  else
108  {
109   slideshowstate=SubBarAlbumClock::STOP;
110   SubBarBtnPlayNPause->setPixmaps(btnGraphic[8],btnGraphic[9]);
111  }
112 }
void SubBarAlbumClock::xSetup ()
void SubBarAlbumClock::xSetup ()
Definition at line 32 of file src/subbaralbumclock.cpp.
References SkinButton::setPixmaps(), slotChangeMode(), slotChangePlayNPauseBtnGraphic(), SubBarBtnAlbumClock, SubBarBtnNext, SubBarBtnPlayNPause, and SubBarBtnPrevious.
Referenced by SubBarAlbumClock().
33 {
34    //DAVID Setup Background;
35    pixBackground.load("/root/kde_application/hdass08/skin/SubBarBackground.png");
36    setBackgroundPixmap(pixBackground);
37    
38    //InitBtn Graphic
39    btnGraphic[0]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Album-Btn-Album.png");
40    btnGraphic[1]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Album-Btn-Album-Active.png");
41    btnGraphic[2]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Album-Btn-Clock.png");
42    btnGraphic[3]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Album-Btn-Clock-Active.png");
43    btnGraphic[4]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Album-Btn-Previous.png");
44    btnGraphic[5]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Album-Btn-Previous-Active.png");
45    btnGraphic[6]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Album-Btn-Play.png");
46    btnGraphic[7]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Album-Btn-Play-Active.png");
47    btnGraphic[8]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Album-Btn-Pause.png");
48    btnGraphic[9]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Album-Btn-Pause-Active.png");
49    btnGraphic[10]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Album-Btn-Next.png");
50    btnGraphic[11]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Album-Btn-Next-Active.png");
51    //Init Btn
52    SubBarBtnAlbumClock=new SkinButton(this);
53    SubBarBtnAlbumClock->setPixmaps(btnGraphic[0],btnGraphic[1]);
54    SubBarBtnAlbumClock->setGeometry(457,0,80,80);
55    SubBarBtnAlbumClock->show();
56    
57    SubBarBtnPrevious=new SkinButton(this);
58    SubBarBtnPrevious->setPixmaps(btnGraphic[4],btnGraphic[5]);
59    SubBarBtnPrevious->setGeometry(175,0,60,80);
60    SubBarBtnPrevious->show();
61    
62    SubBarBtnPlayNPause=new SkinButton(this);
63    SubBarBtnPlayNPause->setPixmaps(btnGraphic[6],btnGraphic[7]);
64    SubBarBtnPlayNPause->setGeometry(240,0,80,80);
65    SubBarBtnPlayNPause->show();
66    
67    SubBarBtnNext=new SkinButton(this);
68    SubBarBtnNext->setPixmaps(btnGraphic[10],btnGraphic[11]);
69    SubBarBtnNext->setGeometry(323,0,60,80);
70    SubBarBtnNext->show();
71    
72    QObject::connect(SubBarBtnAlbumClock,SIGNAL(pressed()),this,SLOT(slotChangeMode()));
73    QObject::connect(SubBarBtnPlayNPause,SIGNAL(pressed()),this,SLOT(slotChangePlayNPauseBtnGraphic()));
74   // slideshowstate=AlbumControl::GO;
75 
76 }
Member Data Documentation
QPixmap* SubBarAlbumClock::btnGraphic[12] [private]
Definition at line 52 of file subbaralbumclock.h.
QPixmap* SubBarAlbumClock::btnGraphic[12] [private]
Definition at line 52 of file src/subbaralbumclock.h.
QPixmap SubBarAlbumClock::pixBackground [private]
Definition at line 53 of file subbaralbumclock.h.
SLIDESHOWSTATE SubBarAlbumClock::slideshowstate [private]
Definition at line 55 of file subbaralbumclock.h.
Referenced by slotChangePlayNPauseBtnGraphic().
SkinButton* SubBarAlbumClock::SubBarBtnAlbumClock
Definition at line 43 of file subbaralbumclock.h.
SkinButton* SubBarAlbumClock::SubBarBtnAlbumClock
Definition at line 43 of file src/subbaralbumclock.h.
Referenced by ChangeButtonGraphic(), and xSetup().
SkinButton * SubBarAlbumClock::SubBarBtnNext
Definition at line 43 of file subbaralbumclock.h.
Referenced by xSetup(), and HDASS08::xSetup().
SkinButton * SubBarAlbumClock::SubBarBtnPlayNPause
Definition at line 43 of file subbaralbumclock.h.
Referenced by slotChangePlayNPauseBtnGraphic(), xSetup(), and HDASS08::xSetup().
SkinButton * SubBarAlbumClock::SubBarBtnPrevious
Definition at line 43 of file subbaralbumclock.h.
Referenced by xSetup(), and HDASS08::xSetup().
The documentation for this class was generated from the following files:
src/subbaralbumclock.h
subbaralbumclock.h
subbaralbumclock.moc
src/subbaralbumclock.cpp
subbaralbumclock.cpp