Analyzer::Base< W > Class Template Reference
#include <analyzerbase.h>
template<class W> class Analyzer::Base< W >
Public Member Functions
uint timeout () const
uint height () const
Protected Member Functions
Base (QWidget *, uint, uint=7)
void drawFrame ()
virtual void transform (Scope &)
virtual void analyze (const Scope &)=0
virtual void paused ()
virtual void demo ()
void changeTimeout (uint newTimeout)
Protected Attributes
QTimer m_timer
uint m_timeout
uint m_height
FHT m_fht
Private Member Functions
bool event (QEvent *)
Constructor & Destructor Documentation
template<class W> Analyzer::Base< W >::Base (QWidget *, uint, uint = 7) [protected]
Definition at line 43 of file analyzerbase.cpp.
44   : W( parent )
45   , m_timeout( timeout )
46   , m_height( 0 )
47   , m_fht( scopeSize )
48 {}
Member Function Documentation
template<class W> virtual void Analyzer::Base< W >::analyze (const Scope &) [protected, pure virtual]
Implemented in Sonogram (p.).
Referenced by Analyzer::Base< W >::demo(), and Analyzer::Base< W >::drawFrame().
template<class W> void Analyzer::Base< W >::changeTimeout (uint newTimeout) [inline, protected]
Definition at line 54 of file analyzerbase.h.
55     {
56         m_timer.changeInterval( newTimeout );
57         m_timeout = newTimeout;
58     }
template<class W> void Analyzer::Base< W >::demo () [protected, virtual]
Reimplemented in Sonogram (p.).
Definition at line 128 of file analyzerbase.cpp.
References Analyzer::Base< W >::analyze(), and Analyzer::Scope.
Referenced by Analyzer::Base< W >::drawFrame().
129 {
130     static int t = 201; //FIXME make static to namespace perhaps
131 
132     if( t > 999 ) t = 1; //0 = wasted calculations
133     if( t < 201 )
134     {
135         Scope s( 32 );
136 
137         const double dt = double(t) / 200;
138         for( uint i = 0; i < s.size(); ++i )
139             s[i] = dt * (sin( M_PI + (i * M_PI) / s.size() ) + 1.0);
140 
141         analyze( s );
142     }
143     else analyze( Scope( 32, 0 ) );
144 
145     ++t;
146 }
template<class W> void Analyzer::Base< W >::drawFrame () [protected]
Definition at line 94 of file analyzerbase.cpp.
References Analyzer::Base< W >::analyze(), Analyzer::Base< W >::demo(), EngineController::engine(), Analyzer::Base< W >::paused(), EngineBase::scope(), Analyzer::Scope, EngineBase::state(), and Analyzer::Base< W >::transform().
95 {
96     EngineBase *engine = EngineController::engine();
97 
98     switch( engine->state() )
99     {
100     case EngineBase::Playing:
101     {
102         Scope *scope = engine->scope();
103 
104         if( !scope->empty() )
105         {
106             transform( *scope );
107             analyze( *scope );
108         }
109 
110         delete scope;
111 
112         break;
113     }
114     case EngineBase::Paused:
115         paused();
116         break;
117 
118     default:
119         demo();
120     }
121 }
template<class W> bool Analyzer::Base< W >::event (QEvent *) [private]
Definition at line 51 of file analyzerbase.cpp.
References Analyzer::Base< W >::m_timer, and Analyzer::Base< W >::timeout().
52 {
53     switch( e->type() ) {
54 /*    case QEvent::Paint:
55         if( !canvas()->isNull() )
56             bitBlt( this, 0, 0, canvas() );
57         return true; //no propagate event*/
58     case QEvent::Hide:
59         m_timer.stop();
60         break;
61 
62     case QEvent::Show:
63         m_timer.start( timeout() );
64         break;
65 
66     default:
67         break;
68     }
69 
70     return QWidget::event( e );
71 }
template<class W> uint Analyzer::Base< W >::height () const [inline]
Definition at line 43 of file analyzerbase.h.
43 { return m_height; }
template<class W> void Analyzer::Base< W >::paused () [protected, virtual]
Definition at line 124 of file analyzerbase.cpp.
Referenced by Analyzer::Base< W >::drawFrame().
125 {}
template<class W> uint Analyzer::Base< W >::timeout () const [inline]
Definition at line 42 of file analyzerbase.h.
Referenced by Analyzer::Base< W >::event().
42 { return m_timeout; }
template<class W> void Analyzer::Base< W >::transform (Scope &) [protected, virtual]
Reimplemented in Sonogram (p.).
Definition at line 74 of file analyzerbase.cpp.
References FHT::copy(), FHT::logSpectrum(), Analyzer::Base< W >::m_fht, FHT::scale(), Analyzer::Scope, and FHT::size().
Referenced by Analyzer::Base< W >::drawFrame().
75 {
76     //this is a standard transformation that should give
77     //an FFT scope that has bands for pretty analyzers
78 
79     //NOTE resizing here is redundant as FHT routines only calculate FHT::size() values
80     //scope.resize( m_fht.size() );
81 
82     float *front = static_cast<float*>( &scope.front() );
83 
84     float* f = new float[ m_fht.size() ];
85     m_fht.copy( &f[0], front );
86     m_fht.logSpectrum( front, &f[0] );
87     m_fht.scale( front, 1.0 / 20 );
88 
89     scope.resize( m_fht.size()/2 ); //second half of values are rubbish
90     delete [] f;
91 }
Member Data Documentation
template<class W> FHT Analyzer::Base< W >::m_fht [protected]
Definition at line 67 of file analyzerbase.h.
Referenced by Analyzer::Base< W >::transform().
template<class W> uint Analyzer::Base< W >::m_height [protected]
Definition at line 66 of file analyzerbase.h.
template<class W> uint Analyzer::Base< W >::m_timeout [protected]
Definition at line 65 of file analyzerbase.h.
template<class W> QTimer Analyzer::Base< W >::m_timer [protected]
Definition at line 64 of file analyzerbase.h.
Referenced by Analyzer::Base< W >::event().
The documentation for this class was generated from the following files:
analyzerbase.h
analyzerbase.cpp