Analyzer::Base2D Class Reference
#include <analyzerbase.h>
Public Member Functions
const QPixmap * background () const
const QPixmap * canvas () const
uint timeout () const
uint height () const
Protected Member Functions
Base2D (QWidget *, uint timeout, uint scopeSize=7)
virtual void init ()
QPixmap * canvas ()
void eraseCanvas ()
void paintEvent (QPaintEvent *)
void resizeEvent (QResizeEvent *)
void paletteChange (const class QPalette &)
void polish ()
void drawFrame ()
virtual void transform (Scope &)
virtual void analyze (const Scope &)=0
virtual void paused ()
virtual void demo ()
void changeTimeout (uint newTimeout)
Protected Attributes
QTimer m_timer
uint m_timeout
uint m_height
FHT m_fht
Private Slots
void draw ()
Private Attributes
QPixmap m_background
QPixmap m_canvas
Constructor & Destructor Documentation
Analyzer::Base2D::Base2D (QWidget *, uint timeout, uint scopeSize = 7) [protected]
Definition at line 150 of file analyzerbase.cpp.
References draw(), and Analyzer::Base< QWidget >::timeout().
151    : Base<QWidget>( parent, timeout, scopeSize )
152 {
153     setWFlags( Qt::WNoAutoErase ); //no flicker
154 
155     connect( &m_timer, SIGNAL( timeout() ), SLOT( draw() ) );
156 }
Member Function Documentation
virtual void Analyzer::Base< QWidget >::analyze (const Scope &) [protected, pure virtual, inherited]
Implemented in Sonogram (p.).
const QPixmap* Analyzer::Base2D::background () const [inline]
Definition at line 75 of file analyzerbase.h.
References m_background.
Referenced by eraseCanvas().
75 { return &m_background; }
QPixmap* Analyzer::Base2D::canvas () [inline, protected]
Definition at line 86 of file analyzerbase.h.
References m_canvas.
86 { return &m_canvas; }
const QPixmap* Analyzer::Base2D::canvas () const [inline]
Definition at line 76 of file analyzerbase.h.
References m_canvas.
Referenced by Sonogram::analyze(), draw(), eraseCanvas(), and paintEvent().
76 { return &m_canvas; }
void Analyzer::Base< QWidget >::changeTimeout (uint newTimeout) [inline, protected, inherited]
Definition at line 54 of file analyzerbase.h.
55     {
56         m_timer.changeInterval( newTimeout );
57         m_timeout = newTimeout;
58     }
virtual void Analyzer::Base< QWidget >::demo () [protected, virtual, inherited]
Reimplemented in Sonogram (p.).
void Analyzer::Base2D::draw () [inline, private, slot]
Definition at line 79 of file analyzerbase.h.
References canvas(), and Analyzer::Base< QWidget >::drawFrame().
Referenced by Base2D().
79 { drawFrame(); bitBlt( this, 0, 0, canvas() ); }
void Analyzer::Base< QWidget >::drawFrame () [protected, inherited]
Referenced by draw().
void Analyzer::Base2D::eraseCanvas () [inline, protected]
Definition at line 87 of file analyzerbase.h.
References background(), and canvas().
Referenced by Sonogram::init(), and resizeEvent().
87 { bitBlt( canvas(), 0, 0, background() ); }
uint Analyzer::Base< QWidget >::height () const [inline, inherited]
Definition at line 43 of file analyzerbase.h.
Referenced by Sonogram::analyze().
43 { return m_height; }
virtual void Analyzer::Base2D::init () [inline, protected, virtual]
Reimplemented in Sonogram (p.).
Definition at line 84 of file analyzerbase.h.
Referenced by polish().
84 {}
void Analyzer::Base2D::paintEvent (QPaintEvent *) [inline, protected]
Definition at line 89 of file analyzerbase.h.
References canvas(), and m_canvas.
89 { if( !m_canvas.isNull() ) bitBlt( this, 0, 0, canvas() ); }
void Analyzer::Base2D::paletteChange (const class QPalette &) [protected]
virtual void Analyzer::Base< QWidget >::paused () [protected, virtual, inherited]
void Analyzer::Base2D::polish () [protected]
Definition at line 159 of file analyzerbase.cpp.
References init().
160 {
161     //TODO is there much point in this anymore?
162 
163     //we use polish for initialzing (instead of ctor)
164     //because we need to know the widget's final size
165     QWidget::polish();
166 
167     init(); //virtual
168 }
void Analyzer::Base2D::resizeEvent (QResizeEvent *) [protected]
Definition at line 171 of file analyzerbase.cpp.
References eraseCanvas(), m_background, and m_canvas.
172 {
173     m_height = QWidget::height();
174     m_background.resize( size() );
175     m_canvas.resize( size() );
176 
177     #ifdef DRAW_GRID
178     QPainter p( &m_background );
179     p.setPen( QColor( 0x20, 0x20, 0x50 ) );
180 
181     for( uint x = 0, w = m_background.width(), h = m_background.height()-1;
182         x < w; x += 3 ) p.drawLine( x, 0, x, h );
183     for( uint y = 0, w = m_background.width()-1 , h = m_background.height();
184         y < h; y += 3 ) p.drawLine( 0, y, w, y );
185     #else
186     m_background.fill( backgroundColor() );
187     #endif
188 
189     eraseCanvas(); //this is necessary
190 
191     QWidget::resizeEvent( e );
192 }
uint Analyzer::Base< QWidget >::timeout () const [inline, inherited]
Definition at line 42 of file analyzerbase.h.
Referenced by Base2D().
42 { return m_timeout; }
virtual void Analyzer::Base< QWidget >::transform (Scope &) [protected, virtual, inherited]
Reimplemented in Sonogram (p.).
Member Data Documentation
QPixmap Analyzer::Base2D::m_background [private]
Definition at line 96 of file analyzerbase.h.
Referenced by background(), and resizeEvent().
QPixmap Analyzer::Base2D::m_canvas [private]
Definition at line 97 of file analyzerbase.h.
Referenced by canvas(), paintEvent(), and resizeEvent().
FHT Analyzer::Base< QWidget >::m_fht [protected, inherited]
Definition at line 67 of file analyzerbase.h.
uint Analyzer::Base< QWidget >::m_height [protected, inherited]
Definition at line 66 of file analyzerbase.h.
uint Analyzer::Base< QWidget >::m_timeout [protected, inherited]
Definition at line 65 of file analyzerbase.h.
QTimer Analyzer::Base< QWidget >::m_timer [protected, inherited]
Definition at line 64 of file analyzerbase.h.
The documentation for this class was generated from the following files:
analyzerbase.h
analyzerbase.cpp