Myplayer Class Reference
#include <Myplayer.h>
Public Slots
void play ()
void play (QString FileName)
void pause ()
void stop ()
void next ()
void previous ()
void increase_volume ()
void decrease_volume ()
void setVolume (int)
void handleNext ()
void handlePrevious ()
void handlePosition (int)
void handleRepeat (bool)
void handleRandom (bool)
void handleSlider (int)
void handlePlayItem (KURL &)
void initlist (KURL::List &)
void add (KURL::List &)
void clearMedia ()
void removeMedia (KURL::List &)
Signals
void trackMessage (int, int, QString, QString, QString)
void volumeMessage (int)
void positionMessage (int)
Public Member Functions
Myplayer ()
~Myplayer ()
void handleMessage (const MetaBundle &)
Private Types
enum PLAYSTATE { Idle,
Pause,
Go
 }
Private Member Functions
void savePlaylist ()
void restorePlaylist ()
Private Attributes
KURL::List m_list
KURL::List::Iterator it
int m_Vol
bool m_repeat
bool m_random
PLAYSTATE state
Member Enumeration Documentation
enum Myplayer::PLAYSTATE [private]
Enumeration values:
Idle
Pause
Go
Definition at line 30 of file Myplayer.h.
31 {
32  Idle,Pause,Go
33 };
Constructor & Destructor Documentation
Myplayer::Myplayer ()
Definition at line 31 of file Myplayer.cpp.
References handleNext(), handlePosition(), handlePrevious(), EngineBase::init(), EngineBase::initMixer(), EngineController::instance(), m_list, m_random, m_repeat, m_Vol, EngineBase::setDefaultSoundDevice(), EngineController::setEngine(), EngineBase::setRestoreEffects(), EngineBase::setSoundDevice(), EngineBase::setSoundOutput(), EngineBase::setVolume(), and EngineBase::setXfadeLength().
32 {
33      bool restartArts = false;
34      m_repeat = true;
35      m_random = false;
36      EngineBase* const engine = new ArtsEngine();
37      engine->init( restartArts, 9, true );//AmarokConfig::rememberEffects() );
38      engine->initMixer( false );//AmarokConfig::hardwareMixer() ); try to check the hardware mixer and use it 
39      engine->setVolume( 50 );
40      m_Vol = 50;
41      EngineController::setEngine( engine );
42      engine->setSoundOutput( "Alsa" );
43      engine->setSoundDevice( AmarokConfig::soundDevice() );
44      engine->setDefaultSoundDevice( !AmarokConfig::customSoundDevice() );
45      engine->setRestoreEffects( AmarokConfig::rememberEffects() );
46          //TODO deprecate/improve
47      engine->setXfadeLength( 2200 );
48      EngineController* const ec = EngineController::instance();
49      connect( ec, SIGNAL( orderNext() ), SLOT( handleNext() ) );
50      connect( ec, SIGNAL( orderPrevious() ), SLOT( handlePrevious() ) );      
51      connect(ec, SIGNAL(TrackPosition(int)), SLOT(handlePosition(int)) );
52      it = m_list.begin();
53 }
Myplayer::~Myplayer ()
Definition at line 55 of file Myplayer.cpp.
56 {
57    kdDebug() << k_funcinfo << endl;
58 }
Member Function Documentation
void Myplayer::add (KURL::List &) [slot]
Definition at line 267 of file Myplayer.cpp.
References m_list.
Referenced by SubBarPlayer::insertMedia().
268 {     
269      if(!m_list.isEmpty())//Not Empty
270      {
271         kdDebug() << "PlayList is not empty !!" << endl;
272         KURL::List add_list = list;
273         for( KURL::List::ConstIterator add_it = add_list.begin();add_it != add_list.end();add_it++)
274         {
275               m_list.append( (*add_it).url() );
276         }       
277      }
278      else
279      {
280         m_list = list;
281         it = m_list.begin();
282         kdDebug() << "[Myplayer::add]: " << (*it).url() << endl;
283      }
284 }
void Myplayer::clearMedia () [slot]
Definition at line 286 of file Myplayer.cpp.
References m_list.
287 {    
288     if(m_list.isEmpty())kdDebug() << "[Myplayer::clearMedia]: it's empty"<< endl;
289     else{
290        m_list.clear();     
291        kdDebug() << "[Myplayer::clearMedia]: it's clear " << endl;      
292     }
293 }
void Myplayer::decrease_volume () [slot]
Definition at line 118 of file Myplayer.cpp.
References m_Vol, and setVolume().
119 {
120      setVolume(m_Vol-5);
121      kdDebug() << "[Myplayer]decrease_Vol --: " << endl;
122 }
void Myplayer::handleMessage (const MetaBundle &)
Definition at line 326 of file Myplayer.cpp.
References MetaBundle::album(), MetaBundle::artist(), MetaBundle::bitrate(), MetaBundle::length(), MetaBundle::title(), and trackMessage().
Referenced by handleNext(), handlePrevious(), and play().
327 {
328     int m_length = bundle.length();
329     int m_bitrate = bundle.bitrate();
330     QString m_title = bundle.title();
331     QString m_artist = bundle.artist();
332     QString m_album = bundle.album();
333 
334     emit trackMessage(m_length,m_bitrate,m_title,m_artist,m_album);
335 }
void Myplayer::handleNext () [slot]
Definition at line 160 of file Myplayer.cpp.
References handleMessage(), EngineController::instance(), m_list, m_random, m_repeat, EngineController::play(), and EngineController::stop().
Referenced by Myplayer().
161 {
162      kdDebug() << "[engine] hanleNext: " << endl;
163      if(m_random)
164      {
165       qWarning("Myplayer::random play item");
166        it = m_list.begin();
167        int randomNum = KApplication::random() % m_list.count();
168        for(int i = 0;it != m_list.end(); it++)
169        {
170          if(i == randomNum)break;
171          else i++;
172        }
173      }
174      else ++it;
175    
176      if(it != m_list.end())
177      {
178           EngineController::instance()->stop();
179           //kdDebug() << "[engine] play: " << (*it).url();
180           MetaBundle bundle( (*it).url() );  
181           EngineController::instance()->play(true,bundle);     
182           handleMessage(bundle);
183      }
184      else
185      {
186         
187         if(m_repeat)
188         {
189            it = m_list.begin();
190            qWarning("Myplayer::repeat play item");
191            MetaBundle bundle( (*it).url());
192            EngineController::instance()->play(true,bundle);
193            handleMessage(bundle);
194         }
195         
196         else 
197         {      
198              //  qWarning("=======================");
199              //  EngineController::instance()->stop();  
200            
201         }
202      }
203 }
void Myplayer::handlePlayItem (KURL &) [slot]
Definition at line 253 of file Myplayer.cpp.
References m_list, and play().
254 {
255      KURL::List::Iterator check_it = m_list.find(url);      
256      if(check_it != m_list.end())
257        {
258           it = check_it;
259           play();
260           kdDebug() << "Find Item "<< endl;
261        }
262      else kdDebug() << "NO this item!! " << endl;
263 }
void Myplayer::handlePosition (int) [slot]
Definition at line 238 of file Myplayer.cpp.
References positionMessage().
Referenced by Myplayer(), and stop().
239 {    
240      emit positionMessage(position);     
241 }
void Myplayer::handlePrevious () [slot]
Definition at line 205 of file Myplayer.cpp.
References handleMessage(), EngineController::instance(), m_list, and EngineController::play().
Referenced by Myplayer().
206 {
207 //     EngineBase *engine = EngineController::engine();
208      kdDebug() << "[engine] hanlePrevious: " << endl;
209      if(it != m_list.begin())
210      {
211         --it;
212         MetaBundle bundle( (*it).url() );  
213 //      if(engine->state() == EngineBase::Playing)
214           EngineController::instance()->play(true,bundle); 
215         handleMessage(bundle);    
216      }
217      else
218      {
219         it = m_list.end();
220         --it;
221         MetaBundle bundle( (*it).url());
222 //      if(engine->state() == EngineBase::Playing)
223           EngineController::instance()->play(true,bundle);
224         handleMessage(bundle);
225      }
226 }
void Myplayer::handleRandom (bool) [slot]
Definition at line 233 of file Myplayer.cpp.
References m_random.
234 {
235      m_random = random;
236 }
void Myplayer::handleRepeat (bool) [slot]
Definition at line 228 of file Myplayer.cpp.
References m_repeat.
Referenced by SubBarPlayer::initMedia(), and SubBarPlayer::insertMedia().
229 {
230      m_repeat = repeat;      
231 }
void Myplayer::handleSlider (int) [slot]
Definition at line 243 of file Myplayer.cpp.
References EngineController::engine(), and EngineBase::seek().
Referenced by SubBarPlayer::handleNextReleased(), SubBarPlayer::handlePreviousReleased(), and SubBarPlayer::handleSliderReleased().
244 {
245      kdDebug() << "[Myplayer]sliderValue: "<< sliderValue << endl;
246      EngineBase *engine = EngineController::engine();
247      //if ( engine->state() == EngineBase::Playing )
248     // {
249         engine->seek( sliderValue*1000 );
250 //     }
251 }
void Myplayer::increase_volume () [slot]
Definition at line 112 of file Myplayer.cpp.
References m_Vol, and setVolume().
113 {
114      setVolume(m_Vol+5);        
115      kdDebug() << "[Myplayer]increase_Vol ++: " << endl;
116 }
void Myplayer::initlist (KURL::List &) [slot]
Definition at line 364 of file Myplayer.cpp.
References m_list.
Referenced by SubBarPlayer::initMedia().
365 {
366   m_list=list;
367   it = m_list.begin();
368   kdDebug() << "[Myplayer::add]: " << (*it).url() << endl;
369 }
void Myplayer::next () [slot]
Definition at line 134 of file Myplayer.cpp.
References EngineController::instance(), m_list, EngineController::next(), and EngineController::stop().
135 {
136      if(!m_list.isEmpty())//DAVID Check list empty
137      {
138        EngineController::instance()->next();
139        kdDebug() << "[engine] Next: " << endl;
140      }
141      else 
142      {
143      
144        EngineController::instance()->stop();
145      }
146 }
void Myplayer::pause () [slot]
Definition at line 106 of file Myplayer.cpp.
References EngineController::instance(), and EngineController::pause().
107 {
108      EngineController::instance()->pause();
109      kdDebug() << "[engine] Pause: " << endl;
110 }
void Myplayer::play (QString FileName) [slot]
Definition at line 76 of file Myplayer.cpp.
References handleMessage(), EngineController::instance(), m_list, and EngineController::play().
77 {
78    bool find=false;
79    //DAVID Find file with filename
80    for( KURL::List::ConstIterator find_it = m_list.begin();find_it != m_list.end();find_it++)
81    {
82       if((*find_it).fileName()==filename)
83       {
84         //DAVID Find it
85         find=true;
86         it=m_list.find(*find_it);
87       }
88    }
89    if(find)
90    {
91        MetaBundle bundle( (*it).url() );        
92        EngineController::instance()->play(true,bundle); 
93        handleMessage(bundle);
94        kdDebug() << "[engine] play: " << endl;            
95    }
96    else qWarning("File Not Find!!");//this situation should not be happend
97 
98 }
void Myplayer::play () [slot]
Definition at line 61 of file Myplayer.cpp.
References handleMessage(), EngineController::instance(), m_list, EngineController::play(), and EngineController::stop().
Referenced by handlePlayItem().
62 {          
63      if(!m_list.isEmpty())
64      {
65        MetaBundle bundle( (*it).url() );        
66        EngineController::instance()->play(bundle); 
67        handleMessage(bundle);
68        kdDebug() << "[engine] play: " << endl;            
69      }
70      else
71      {
72         EngineController::instance()->stop();
73         kdDebug() << "[engine] Stop: " << endl;            
74      }
75 }
void Myplayer::positionMessage (int) [signal]
Definition at line 195 of file Myplayer.moc.
Referenced by handlePosition().
196 {
197     activate_signal( staticMetaObject()->signalOffset() + 2, t0 );
198 }
void Myplayer::previous () [slot]
Definition at line 148 of file Myplayer.cpp.
References EngineController::instance(), m_list, EngineController::previous(), and EngineController::stop().
149 {
150      if(!m_list.isEmpty())
151      {
152        EngineController::instance()->previous();
153        kdDebug() << "[engine] Previous: "<< endl;
154      }
155      else EngineController::instance()->stop();
156      
157 }
void Myplayer::removeMedia (KURL::List &) [slot]
Definition at line 295 of file Myplayer.cpp.
References m_list.
Referenced by SubBarPlayer::removeMedia().
296 {       
297     KURL::List::ConstIterator check_it;
298         
299     if(m_list.isEmpty())kdDebug() << "[Myplayer::removeMedia]: it's empty"<< endl;
300     else{
301                 for( KURL::List::ConstIterator remove_it = remove_list.begin();remove_it != remove_list.end();remove_it++)
302                 {
303                         check_it = m_list.find((*remove_it).url());      
304                         if(check_it != m_list.end())
305                         {
306                                 m_list.remove((*check_it).url());
307                                 kdDebug() << "Remove Item "<< endl;
308                         }
309                         else kdDebug() << "NO this item!! " << endl;
310                 }
311         
312                 for( KURL::List::ConstIterator refresh_it = m_list.begin();refresh_it != m_list.end();refresh_it++)  
313                 {
314                         if((*refresh_it).isEmpty())
315                         {
316                                 for(check_it = refresh_it; check_it != m_list.end();)
317                                 (*check_it).url() = (*(check_it++)).url();                  
318                         }         
319                 }
320                 it = m_list.begin();   
321     } 
322 }
void Myplayer::restorePlaylist () [private]
Definition at line 351 of file Myplayer.cpp.
References m_list.
352 {
353     QFile file( "file.txt" );
354     if ( file.open( IO_ReadOnly ) ) {
355         QTextStream stream( &file );            
356         while ( !stream.atEnd() ) {
357              KURL url(stream.readLine()); // line of text excluding '\n'         
358              m_list << url;
359         }
360         kdDebug() << "Load Playlist "<< endl;
361         file.close();
362     }
363 }
void Myplayer::savePlaylist () [private]
Definition at line 339 of file Myplayer.cpp.
References m_list.
340 {
341     QFile file( "file.txt" );
342     if ( file.open( IO_WriteOnly ) ) {
343         QTextStream stream( &file );
344           for(KURL::List::Iterator save_it = m_list.begin(); save_it != m_list.end(); ++save_it)
345             stream << (*save_it).url() << "\n";
346         file.close();
347 kdDebug() << "save file finished!!"<< endl;     
348     }    
349 }
void Myplayer::setVolume (int) [slot]
Definition at line 124 of file Myplayer.cpp.
References EngineController::instance(), m_Vol, EngineController::setVolume(), and volumeMessage().
Referenced by decrease_volume(), and increase_volume().
125 {
126      if( percent < 0 ) m_Vol = 0;
127      else if( percent > 100) m_Vol = 100;
128      else m_Vol = percent;
129      EngineController::instance()->setVolume(m_Vol);
130      emit volumeMessage(m_Vol);
131      kdDebug() << "[Myplayer]setVolume: " << m_Vol << endl;
132 }
void Myplayer::stop () [slot]
Definition at line 99 of file Myplayer.cpp.
References handlePosition(), EngineController::instance(), and EngineController::stop().
100 {     
101      EngineController::instance()->stop();
102      handlePosition(0);
103      kdDebug() << "[engine] Stop: " << endl;
104 }
void Myplayer::trackMessage (int, int, QString, QString, QString) [signal]
Definition at line 172 of file Myplayer.moc.
Referenced by handleMessage().
173 {
174     if ( signalsBlocked() )
175         return;
176     QConnectionList *clist = receivers( staticMetaObject()->signalOffset() + 0 );
177     if ( !clist )
178         return;
179     QUObject o[6];
180     static_QUType_int.set(o+1,t0);
181     static_QUType_int.set(o+2,t1);
182     static_QUType_QString.set(o+3,t2);
183     static_QUType_QString.set(o+4,t3);
184     static_QUType_QString.set(o+5,t4);
185     activate_signal( clist, o );
186 }
void Myplayer::volumeMessage (int) [signal]
Definition at line 189 of file Myplayer.moc.
Referenced by setVolume().
190 {
191     activate_signal( staticMetaObject()->signalOffset() + 1, t0 );
192 }
Member Data Documentation
KURL::List::Iterator Myplayer::it [private]
Definition at line 74 of file Myplayer.h.
KURL::List Myplayer::m_list [private]
Definition at line 73 of file Myplayer.h.
Referenced by add(), clearMedia(), handleNext(), handlePlayItem(), handlePrevious(), initlist(), Myplayer(), next(), play(), previous(), removeMedia(), restorePlaylist(), and savePlaylist().
bool Myplayer::m_random [private]
Definition at line 77 of file Myplayer.h.
Referenced by handleNext(), handleRandom(), and Myplayer().
bool Myplayer::m_repeat [private]
Definition at line 76 of file Myplayer.h.
Referenced by handleNext(), handleRepeat(), and Myplayer().
int Myplayer::m_Vol [private]
Definition at line 75 of file Myplayer.h.
Referenced by decrease_volume(), increase_volume(), Myplayer(), and setVolume().
PLAYSTATE Myplayer::state [private]
Definition at line 78 of file Myplayer.h.
The documentation for this class was generated from the following files:
Myplayer.h
Myplayer.moc
Myplayer.cpp