EngineSubject Class Reference
#include <engineobserver.h>
Detailed Description
Inherited by EngineController(p.). Notify observer functionality is captured in this class.
Definition at line 45 of file engineobserver.h.
Public Member Functions
void attach (EngineObserver *observer)
void detach (EngineObserver *observer)
Protected Member Functions
EngineSubject ()
virtual ~EngineSubject ()
void stateChangedNotify (EngineBase::EngineState)
void newMetaDataNotify (const MetaBundle &, bool)
void volumeChangedNotify (int)
void trackPositionChangedNotify (long)
Private Attributes
QPtrList< EngineObserver > Observers
Constructor & Destructor Documentation
EngineSubject::EngineSubject () [protected]
Definition at line 34 of file engineobserver.cpp.
35 {
36 }
EngineSubject::~EngineSubject () [protected, virtual]
Definition at line 39 of file engineobserver.cpp.
40 {
41 }
Member Function Documentation
void EngineSubject::attach (EngineObserver * observer)
Definition at line 92 of file engineobserver.cpp.
References Observers.
93 {
94     if( !observer || Observers.find( observer ) != -1 )
95         return;
96     Observers.append( observer );
97 }
void EngineSubject::detach (EngineObserver * observer)
Definition at line 100 of file engineobserver.cpp.
References Observers.
101 {
102     if( Observers.find( observer ) != -1 ) Observers.remove();
103 }
void EngineSubject::newMetaDataNotify (const MetaBundle &, bool) [protected]
Definition at line 56 of file engineobserver.cpp.
References EngineObserver::engineNewMetaData(), and Observers.
Referenced by EngineController::play().
57 {
58     QPtrListIterator<EngineObserver> it( Observers );
59     EngineObserver *observer;
60     while( ( observer = it.current() ) != 0 )
61     {
62         ++it;
63         observer->engineNewMetaData( bundle, trackChanged );
64     }
65 }
void EngineSubject::stateChangedNotify (EngineBase::EngineState) [protected]
Definition at line 44 of file engineobserver.cpp.
References EngineObserver::engineStateChanged(), and Observers.
Referenced by EngineController::pause(), EngineController::play(), and EngineController::stop().
45 {
46     QPtrListIterator<EngineObserver> it( Observers );
47     EngineObserver *observer;
48     while( ( observer = it.current() ) != 0 )
49     {
50         ++it;
51         observer->engineStateChanged( state );
52     }
53 }
void EngineSubject::trackPositionChangedNotify (long) [protected]
Definition at line 80 of file engineobserver.cpp.
References EngineObserver::engineTrackPositionChanged(), and Observers.
Referenced by EngineController::slotMainTimer().
81 {
82     QPtrListIterator<EngineObserver> it( Observers );
83     EngineObserver *observer;
84     while( ( observer = it.current() ) != 0 )
85     {
86         ++it;
87         observer->engineTrackPositionChanged( position );
88     }
89 }
void EngineSubject::volumeChangedNotify (int) [protected]
Definition at line 68 of file engineobserver.cpp.
References EngineObserver::engineVolumeChanged(), and Observers.
Referenced by EngineController::setVolume().
69 {
70     QPtrListIterator<EngineObserver> it( Observers );
71     EngineObserver *observer;
72     while( ( observer = it.current() ) != 0 )
73     {
74         ++it;
75         observer->engineVolumeChanged( percent );
76     }
77 }
Member Data Documentation
QPtrList<EngineObserver> EngineSubject::Observers [private]
Definition at line 60 of file engineobserver.h.
Referenced by attach(), detach(), newMetaDataNotify(), stateChangedNotify(), trackPositionChangedNotify(), and volumeChangedNotify().
The documentation for this class was generated from the following files:
engineobserver.h
engineobserver.cpp