SkinButton Class Reference
#include <skinbutton.h>
Public Member Functions
SkinButton (QPixmap *pixmap, QPixmap *active, QWidget *parent=0, const char *name=0, WFlags f=0)
SkinButton (QWidget *parent=0, const char *name=0, WFlags f=0)
void setPixmaps (QPixmap *regular, QPixmap *active)
Public Attributes
bool Down
Protected Slots
void slotPressed ()
void slotReleased ()
Protected Member Functions
virtual void drawButton (QPainter *p)
Protected Attributes
QPixmap * pixRegular
QPixmap * pixActive
Constructor & Destructor Documentation
SkinButton::SkinButton (QPixmap * pixmap, QPixmap * active, QWidget * parent = 0, const char * name = 0, WFlags f = 0)
Definition at line 13 of file skinbutton.cpp.
References slotPressed(), and slotReleased().
15         : QButton(parent, name, f), pixRegular(pixmap), pixActive(active)
16 {
17         setPixmap(*pixmap);
18         QObject::connect(this, SIGNAL(pressed()), SLOT(slotPressed()));
19         QObject::connect(this, SIGNAL(released()), SLOT(slotReleased()));
20 }
SkinButton::SkinButton (QWidget * parent = 0, const char * name = 0, WFlags f = 0)
Definition at line 6 of file skinbutton.cpp.
References slotPressed(), and slotReleased().
7         : QButton(parent, name, f), pixRegular(NULL), pixActive(NULL),Down(false)
8 {
9         QObject::connect(this, SIGNAL(pressed()), SLOT(slotPressed()));
10         QObject::connect(this, SIGNAL(released()), SLOT(slotReleased()));
11 }
Member Function Documentation
void SkinButton::drawButton (QPainter * p) [protected, virtual]
Definition at line 22 of file skinbutton.cpp.
23 {
24         const QPixmap *pm = pixmap();
25         if(pm) p->drawPixmap(0, 0, *pm);
26 }
void SkinButton::setPixmaps (QPixmap * regular, QPixmap * active)
Definition at line 40 of file skinbutton.cpp.
References pixActive, and pixRegular.
Referenced by SubBarPlayer::ChangeBtnPlayPauseGraphic(), SubBarAlbumClock::ChangeButtonGraphic(), SubBarManagement::slotChangeBtnImage(), SubBarAlbumClock::slotChangePlayNPauseBtnGraphic(), SubBarPlayer::xSetup(), SubBarManagement::xSetup(), SubBarInternet::xSetup(), SubBarAlbumClock::xSetup(), InfoArea::xSetup(), and Function_Control_Area::xSetup().
41 {
42         pixRegular = regular; 
43         pixActive= active; 
44         setPixmap(*pixRegular); 
45 }
void SkinButton::slotPressed () [protected, slot]
Definition at line 28 of file skinbutton.cpp.
References Down, and pixActive.
Referenced by SkinButton().
29 {
30         setPixmap(*pixActive);
31         Down=true;
32 }
void SkinButton::slotReleased () [protected, slot]
Definition at line 34 of file skinbutton.cpp.
References Down, and pixRegular.
Referenced by SkinButton().
35 {
36         setPixmap(*pixRegular);
37         Down=false;
38 }
Member Data Documentation
bool SkinButton::Down
Definition at line 18 of file skinbutton.h.
Referenced by slotPressed(), and slotReleased().
QPixmap* SkinButton::pixActive [protected]
Definition at line 21 of file skinbutton.h.
Referenced by setPixmaps(), and slotPressed().
QPixmap* SkinButton::pixRegular [protected]
Definition at line 20 of file skinbutton.h.
Referenced by setPixmaps(), and slotReleased().
The documentation for this class was generated from the following files:
skinbutton.h
skinbutton.cpp