Amarok::Synth_STEREO_XFADE Class Reference
#include <amarokarts.h>
Public Types
typedef Synth_STEREO_XFADE_base _base_class
Public Member Functions
Synth_STEREO_XFADE ()
Synth_STEREO_XFADE (const Arts::SubClass &s)
Synth_STEREO_XFADE (const Arts::Reference &r)
Synth_STEREO_XFADE (const Arts::DynamicCast &c)
Synth_STEREO_XFADE (const Synth_STEREO_XFADE &target)
Synth_STEREO_XFADE (Arts::Object::Pool &p)
Synth_STEREO_XFADE & operator= (const Synth_STEREO_XFADE &target)
operator Arts::SynthModule () const
Synth_STEREO_XFADE_base * _base ()
Arts::AutoSuspendState autoSuspend ()
void start ()
void stop ()
void streamInit ()
void streamStart ()
void streamEnd ()
float percentage ()
void percentage (float _newValue)
Static Public Member Functions
Synth_STEREO_XFADE null ()
Synth_STEREO_XFADE _from_base (Synth_STEREO_XFADE_base *b)
Protected Member Functions
Synth_STEREO_XFADE (Synth_STEREO_XFADE_base *b)
Private Member Functions
Synth_STEREO_XFADE_base * _method_call ()
Static Private Member Functions
Arts::Object_base * _Creator ()
Private Attributes
Synth_STEREO_XFADE_base * _cache
Member Typedef Documentation
typedef Synth_STEREO_XFADE_base Amarok::Synth_STEREO_XFADE::_base_class
Definition at line 97 of file amarokarts.h.
Constructor & Destructor Documentation
Amarok::Synth_STEREO_XFADE::Synth_STEREO_XFADE (Synth_STEREO_XFADE_base * b) [inline, protected]
Definition at line 93 of file amarokarts.h.
References _cache.
93 : Arts::Object(b), _cache(0) {}
Amarok::Synth_STEREO_XFADE::Synth_STEREO_XFADE () [inline]
Definition at line 99 of file amarokarts.h.
References _cache.
Referenced by _from_base(), and null().
99 : Arts::Object(_Creator), _cache(0) {}
Amarok::Synth_STEREO_XFADE::Synth_STEREO_XFADE (const Arts::SubClass & s) [inline]
Definition at line 100 of file amarokarts.h.
References _cache.
100                                                          :
101                 Arts::Object(Synth_STEREO_XFADE_base::_create(s.string())), _cache(0) {}
        inline Synth_STEREO_XFADE(const Arts::Reference &r) :
Amarok::Synth_STEREO_XFADE::Synth_STEREO_XFADE (const Arts::Reference & r) [inline]
Definition at line 102 of file amarokarts.h.
References _cache.
102                                                           :
103                 Arts::Object(r.isString()?(Synth_STEREO_XFADE_base::_fromString(r.string())):(Synth_STEREO_XFADE_base::_fromReference(r.reference(),true))), _cache(0) {}
        inline Synth_STEREO_XFADE(const Arts::DynamicCast& c) : Arts::Object(Synth_STEREO_XFADE_base::_fromDynamicCast(c.object())), _cache(0) {}
Amarok::Synth_STEREO_XFADE::Synth_STEREO_XFADE (const Arts::DynamicCast & c) [inline]
Definition at line 104 of file amarokarts.h.
References _cache.
104 : Arts::Object(Synth_STEREO_XFADE_base::_fromDynamicCast(c.object())), _cache(0) {}
Amarok::Synth_STEREO_XFADE::Synth_STEREO_XFADE (const Synth_STEREO_XFADE & target) [inline]
Definition at line 105 of file amarokarts.h.
References _cache.
105 : Arts::Object(target._pool), _cache(target._cache) {}
Amarok::Synth_STEREO_XFADE::Synth_STEREO_XFADE (Arts::Object::Pool & p) [inline]
Definition at line 106 of file amarokarts.h.
References _cache.
106 : Arts::Object(p), _cache(0) {}
Member Function Documentation
Synth_STEREO_XFADE_base* Amarok::Synth_STEREO_XFADE::_base () [inline]
Definition at line 118 of file amarokarts.h.
118 {return _cache?_cache:_method_call();}
Arts::Object_base * Amarok::Synth_STEREO_XFADE::_Creator () [static, private]
Definition at line 176 of file amarokarts.cc.
References Amarok::Synth_STEREO_XFADE_base::_create().
176                                                     {
177         return Amarok::Synth_STEREO_XFADE_base::_create();
178 }
Synth_STEREO_XFADE Amarok::Synth_STEREO_XFADE::_from_base (Synth_STEREO_XFADE_base * b) [inline, static]
Definition at line 108 of file amarokarts.h.
References Synth_STEREO_XFADE().
108 {return Synth_STEREO_XFADE(b);}
Synth_STEREO_XFADE_base* Amarok::Synth_STEREO_XFADE::_method_call () [inline, private]
Definition at line 83 of file amarokarts.h.
References _cache, and Amarok::Synth_STEREO_XFADE_base::_cast().
Referenced by autoSuspend(), percentage(), start(), stop(), streamEnd(), streamInit(), and streamStart().
83                                                        {
84                 _pool->checkcreate();
85                 if(_pool->base) {
86                         _cache=(Synth_STEREO_XFADE_base *)_pool->base->_cast(Synth_STEREO_XFADE_base::_IID);
87                         assert(_cache);
88                 }
89                 return _cache;
90         }
Arts::AutoSuspendState Amarok::Synth_STEREO_XFADE::autoSuspend () [inline]
Definition at line 243 of file amarokarts.h.
References _cache, and _method_call().
244 {
245         return _cache?static_cast<Arts::SynthModule_base*>(_cache)->autoSuspend():static_cast<Arts::SynthModule_base*>(_method_call())->autoSuspend();
246 }
Synth_STEREO_XFADE Amarok::Synth_STEREO_XFADE::null () [inline, static]
Definition at line 107 of file amarokarts.h.
References Synth_STEREO_XFADE().
Referenced by ArtsEngine::~ArtsEngine().
107 {return Synth_STEREO_XFADE((Synth_STEREO_XFADE_base*)0);}
Amarok::Synth_STEREO_XFADE::operator Arts::SynthModule () const [inline]
Definition at line 117 of file amarokarts.h.
References operator Arts::SynthModule().
Referenced by operator Arts::SynthModule().
117 { return Arts::SynthModule(*_pool); }
Synth_STEREO_XFADE& Amarok::Synth_STEREO_XFADE::operator= (const Synth_STEREO_XFADE & target) [inline]
Definition at line 109 of file amarokarts.h.
References _cache.
109                                                                                {
110                 if (_pool == target._pool) return *this;
111                 _pool->Dec();
112                 _pool = target._pool;
113                 _cache = target._cache;
114                 _pool->Inc();
115                 return *this;
116         }
void Amarok::Synth_STEREO_XFADE::percentage (float _newValue) [inline]
Definition at line 278 of file amarokarts.h.
References _cache, _method_call(), and Amarok::Synth_STEREO_XFADE_base::percentage().
279 {
280          _cache?static_cast<Amarok::Synth_STEREO_XFADE_base*>(_cache)->percentage(_newValue):static_cast<Amarok::Synth_STEREO_XFADE_base*>(_method_call())->percentage(_newValue);
281 }
float Amarok::Synth_STEREO_XFADE::percentage () [inline]
Definition at line 273 of file amarokarts.h.
References _cache, _method_call(), and Amarok::Synth_STEREO_XFADE_base::percentage().
Referenced by ArtsEngine::init(), and ArtsEngine::timerEvent().
274 {
275         return _cache?static_cast<Amarok::Synth_STEREO_XFADE_base*>(_cache)->percentage():static_cast<Amarok::Synth_STEREO_XFADE_base*>(_method_call())->percentage();
276 }
void Amarok::Synth_STEREO_XFADE::start () [inline]
Definition at line 248 of file amarokarts.h.
References _cache, and _method_call().
Referenced by ArtsEngine::init().
249 {
250          _cache?static_cast<Arts::SynthModule_base*>(_cache)->start():static_cast<Arts::SynthModule_base*>(_method_call())->start();
251 }
void Amarok::Synth_STEREO_XFADE::stop () [inline]
Definition at line 253 of file amarokarts.h.
References _cache, and _method_call().
254 {
255          _cache?static_cast<Arts::SynthModule_base*>(_cache)->stop():static_cast<Arts::SynthModule_base*>(_method_call())->stop();
256 }
void Amarok::Synth_STEREO_XFADE::streamEnd () [inline]
Definition at line 268 of file amarokarts.h.
References _cache, and _method_call().
269 {
270          _cache?static_cast<Arts::SynthModule_base*>(_cache)->streamEnd():static_cast<Arts::SynthModule_base*>(_method_call())->streamEnd();
271 }
void Amarok::Synth_STEREO_XFADE::streamInit () [inline]
Definition at line 258 of file amarokarts.h.
References _cache, and _method_call().
259 {
260          _cache?static_cast<Arts::SynthModule_base*>(_cache)->streamInit():static_cast<Arts::SynthModule_base*>(_method_call())->streamInit();
261 }
void Amarok::Synth_STEREO_XFADE::streamStart () [inline]
Definition at line 263 of file amarokarts.h.
References _cache, and _method_call().
264 {
265          _cache?static_cast<Arts::SynthModule_base*>(_cache)->streamStart():static_cast<Arts::SynthModule_base*>(_method_call())->streamStart();
266 }
Member Data Documentation
Synth_STEREO_XFADE_base* Amarok::Synth_STEREO_XFADE::_cache [private]
Definition at line 82 of file amarokarts.h.
Referenced by _method_call(), autoSuspend(), operator=(), percentage(), start(), stop(), streamEnd(), streamInit(), streamStart(), and Synth_STEREO_XFADE().
The documentation for this class was generated from the following files:
amarokarts.h
amarokarts.cc