Amarok::Synth_STEREO_XFADE_skel Class Reference
#include <amarokarts.h>
Public Member Functions
Synth_STEREO_XFADE_skel ()
std::string _interfaceName ()
bool _isCompatibleWith (const std::string &interfacename)
void _buildMethodTable ()
void dispatch (Arts::Buffer *request, Arts::Buffer *result, long methodID)
Synth_STEREO_XFADE_base * _copy ()
virtual std::vector< std::string > _defaultPortsIn () const
virtual std::vector< std::string > _defaultPortsOut () const
void * _cast (unsigned long iid)
virtual float percentage ()=0
virtual void percentage (float newValue)=0
Static Public Member Functions
std::string _interfaceNameSkel ()
Synth_STEREO_XFADE_base * _create (const std::string &subClass=`Amarok::Synth_STEREO_XFADE`)
Synth_STEREO_XFADE_base * _fromString (const std::string &objectref)
Synth_STEREO_XFADE_base * _fromReference (Arts::ObjectReference ref, bool needcopy)
Synth_STEREO_XFADE_base * _fromDynamicCast (const Arts::Object &object)
Static Public Attributes
unsigned long _IID = Arts::MCOPUtils::makeIID(`Amarok::Synth_STEREO_XFADE`)
Protected Member Functions
void percentage_changed (float newValue)
Protected Attributes
float * invalue1_l
float * invalue1_r
float * invalue2_l
float * invalue2_r
float * outvalue_l
float * outvalue_r
Constructor & Destructor Documentation
Amarok::Synth_STEREO_XFADE_skel::Synth_STEREO_XFADE_skel ()
Definition at line 166 of file amarokarts.cc.
References invalue1_l, invalue1_r, invalue2_l, invalue2_r, outvalue_l, and outvalue_r.
167 {
168         _initStream("invalue1_l",&invalue1_l,9);
169         _initStream("invalue1_r",&invalue1_r,9);
170         _initStream("invalue2_l",&invalue2_l,9);
171         _initStream("invalue2_r",&invalue2_r,9);
172         _initStream("outvalue_l",&outvalue_l,10);
173         _initStream("outvalue_r",&outvalue_r,10);
174 }
Member Function Documentation
void Amarok::Synth_STEREO_XFADE_skel::_buildMethodTable ()
Definition at line 151 of file amarokarts.cc.
References _dispatch_Amarok_Synth_STEREO_XFADE_00(), and _dispatch_Amarok_Synth_STEREO_XFADE_01().
152 {
153         Arts::Buffer m;
154         m.fromString(
155         "MethodTable:000000105f6765745f70657263656e746167650000000006666c6f"
156         "617400000000020000000000000000000000105f7365745f70657263656e746167"
157         "650000000005766f696400000000020000000100000006666c6f61740000000009"
158         "6e657756616c7565000000000000000000",
159                 "MethodTable"
160         );
161         _addMethod(_dispatch_Amarok_Synth_STEREO_XFADE_00,this,Arts::MethodDef(m));
162         _addMethod(_dispatch_Amarok_Synth_STEREO_XFADE_01,this,Arts::MethodDef(m));
163         Arts::SynthModule_skel::_buildMethodTable();
164 }
void * Amarok::Synth_STEREO_XFADE_base::_cast (unsigned long iid) [inherited]
Definition at line 71 of file amarokarts.cc.
References Amarok::Synth_STEREO_XFADE_base::_IID.
Referenced by Amarok::Synth_STEREO_XFADE_base::_fromDynamicCast(), and Amarok::Synth_STEREO_XFADE::_method_call().
72 {
73         if(iid == Amarok::Synth_STEREO_XFADE_base::_IID) return (Amarok::Synth_STEREO_XFADE_base *)this;
74         if(iid == Arts::SynthModule_base::_IID) return (Arts::SynthModule_base *)this;
75         if(iid == Arts::Object_base::_IID) return (Arts::Object_base *)this;
76         return 0;
77 }
Synth_STEREO_XFADE_base* Amarok::Synth_STEREO_XFADE_base::_copy () [inline, inherited]
Definition at line 24 of file amarokarts.h.
Referenced by Amarok::Synth_STEREO_XFADE_base::_fromDynamicCast().
24                                                 {
25                 assert(_refCnt > 0);
26                 _refCnt++;
27                 return this;
28         }
Amarok::Synth_STEREO_XFADE_base * Amarok::Synth_STEREO_XFADE_base::_create (const std::string & subClass = `Amarok::Synth_STEREO_XFADE`) [static, inherited]
Definition at line 8 of file amarokarts.cc.
References Amarok::Synth_STEREO_XFADE_base::_IID.
Referenced by Amarok::Synth_STEREO_XFADE::_Creator().
9 {
10         Arts::Object_skel *skel = Arts::ObjectManager::the()->create(subClass);
11         assert(skel);
12         Amarok::Synth_STEREO_XFADE_base *castedObject = (Amarok::Synth_STEREO_XFADE_base *)skel->_cast(Amarok::Synth_STEREO_XFADE_base::_IID);
13         assert(castedObject);
14         return castedObject;
15 }
std::vector< std::string > Amarok::Synth_STEREO_XFADE_base::_defaultPortsIn () const [virtual, inherited]
Definition at line 62 of file amarokarts.cc.
62                                                                           {
63         std::vector<std::string> ret;
64         return ret;
65 }
std::vector< std::string > Amarok::Synth_STEREO_XFADE_base::_defaultPortsOut () const [virtual, inherited]
Definition at line 66 of file amarokarts.cc.
66                                                                            {
67         std::vector<std::string> ret;
68         return ret;
69 }
Amarok::Synth_STEREO_XFADE_base * Amarok::Synth_STEREO_XFADE_base::_fromDynamicCast (const Arts::Object & object) [static, inherited]
Definition at line 26 of file amarokarts.cc.
References Amarok::Synth_STEREO_XFADE_base::_cast(), Amarok::Synth_STEREO_XFADE_base::_copy(), Amarok::Synth_STEREO_XFADE_base::_fromString(), and Amarok::Synth_STEREO_XFADE_base::_IID.
27 {
28         if(object.isNull()) return 0;
29 
30         Amarok::Synth_STEREO_XFADE_base *castedObject = (Amarok::Synth_STEREO_XFADE_base *)object._base()->_cast(Amarok::Synth_STEREO_XFADE_base::_IID);
31         if(castedObject) return castedObject->_copy();
32 
33         return _fromString(object._toString());
34 }
Amarok::Synth_STEREO_XFADE_base * Amarok::Synth_STEREO_XFADE_base::_fromReference (Arts::ObjectReference ref, bool needcopy) [static, inherited]
Definition at line 36 of file amarokarts.cc.
Referenced by Amarok::Synth_STEREO_XFADE_base::_fromString().
37 {
38         Amarok::Synth_STEREO_XFADE_base *result;
39         result = (Amarok::Synth_STEREO_XFADE_base *)Arts::Dispatcher::the()->connectObjectLocal(r,"Amarok::Synth_STEREO_XFADE");
40         if(result)
41         {
42                 if(!needcopy)
43                         result->_cancelCopyRemote();
44         }
45         else
46         {
47                 Arts::Connection *conn = Arts::Dispatcher::the()->connectObjectRemote(r);
48                 if(conn)
49                 {
50                         result = new Amarok::Synth_STEREO_XFADE_stub(conn,r.objectID);
51                         if(needcopy) result->_copyRemote();
52                         result->_useRemote();
53                         if (!result->_isCompatibleWith("Amarok::Synth_STEREO_XFADE")) {
54                                 result->_release();
55                                 return 0;
56                         }
57                 }
58         }
59         return result;
60 }
Amarok::Synth_STEREO_XFADE_base * Amarok::Synth_STEREO_XFADE_base::_fromString (const std::string & objectref) [static, inherited]
Definition at line 17 of file amarokarts.cc.
References Amarok::Synth_STEREO_XFADE_base::_fromReference().
Referenced by Amarok::Synth_STEREO_XFADE_base::_fromDynamicCast().
18 {
19         Arts::ObjectReference r;
20 
21         if(Arts::Dispatcher::the()->stringToObjectReference(r,objectref))
22                 return Amarok::Synth_STEREO_XFADE_base::_fromReference(r,true);
23         return 0;
24 }
std::string Amarok::Synth_STEREO_XFADE_skel::_interfaceName ()
Definition at line 120 of file amarokarts.cc.
121 {
122         return "Amarok::Synth_STEREO_XFADE";
123 }
std::string Amarok::Synth_STEREO_XFADE_skel::_interfaceNameSkel () [static]
Definition at line 133 of file amarokarts.cc.
134 {
135         return "Amarok::Synth_STEREO_XFADE";
136 }
bool Amarok::Synth_STEREO_XFADE_skel::_isCompatibleWith (const std::string & interfacename)
Definition at line 125 of file amarokarts.cc.
126 {
127         if (interfacename == "Amarok::Synth_STEREO_XFADE") return true;
128         if (interfacename == "Arts::SynthModule") return true;
129         if (interfacename == "Arts::Object") return true;
130         return false;
131 }
void Amarok::Synth_STEREO_XFADE_skel::dispatch (Arts::Buffer * request, Arts::Buffer * result, long methodID)
virtual void Amarok::Synth_STEREO_XFADE_base::percentage (float newValue) [pure virtual, inherited]
Implemented in Amarok::Synth_STEREO_XFADE_stub (p.).
virtual float Amarok::Synth_STEREO_XFADE_base::percentage () [pure virtual, inherited]
Implemented in Amarok::Synth_STEREO_XFADE_stub (p.).
Referenced by Amarok::Synth_STEREO_XFADE::percentage().
void Amarok::Synth_STEREO_XFADE_skel::percentage_changed (float newValue) [inline, protected]
Definition at line 62 of file amarokarts.h.
62                                                        {
63                 _emit_changed("percentage_changed",newValue);
64         }
Member Data Documentation
unsigned long Amarok::Synth_STEREO_XFADE_base::_IID = Arts::MCOPUtils::makeIID(`Amarok::Synth_STEREO_XFADE`) [static, inherited]
Definition at line 180 of file amarokarts.cc.
Referenced by Amarok::Synth_STEREO_XFADE_base::_cast(), Amarok::Synth_STEREO_XFADE_base::_create(), and Amarok::Synth_STEREO_XFADE_base::_fromDynamicCast().
float* Amarok::Synth_STEREO_XFADE_skel::invalue1_l [protected]
Definition at line 53 of file amarokarts.h.
Referenced by Synth_STEREO_XFADE_skel().
float* Amarok::Synth_STEREO_XFADE_skel::invalue1_r [protected]
Definition at line 54 of file amarokarts.h.
Referenced by Synth_STEREO_XFADE_skel().
float* Amarok::Synth_STEREO_XFADE_skel::invalue2_l [protected]
Definition at line 55 of file amarokarts.h.
Referenced by Synth_STEREO_XFADE_skel().
float* Amarok::Synth_STEREO_XFADE_skel::invalue2_r [protected]
Definition at line 56 of file amarokarts.h.
Referenced by Synth_STEREO_XFADE_skel().
float* Amarok::Synth_STEREO_XFADE_skel::outvalue_l [protected]
Definition at line 57 of file amarokarts.h.
Referenced by Synth_STEREO_XFADE_skel().
float* Amarok::Synth_STEREO_XFADE_skel::outvalue_r [protected]
Definition at line 58 of file amarokarts.h.
Referenced by Synth_STEREO_XFADE_skel().
The documentation for this class was generated from the following files:
amarokarts.h
amarokarts.cc