DummyEngine Class Reference
Public Types
enum EngineState { Empty,
Idle,
Playing,
Paused
 }
enum StreamingMode { Socket,
Signal,
NoStreaming
 }
Public Slots
virtual void configureDecoder ()
virtual void newStreamData (char *, int)
Signals
void endOfTrack ()
void stopped ()
Public Member Functions
DummyEngine ()
virtual StreamingMode streamingMode ()
virtual QStringList getOutputsList ()
bool loaded ()
int volume () const
bool isMixerHardware () const
virtual bool supportsXFade () const
virtual std::vector< float > * scope ()
void setRestoreEffects (bool yes)
virtual QStringList availableEffects () const
virtual std::vector< long > activeEffects () const
virtual QString effectNameForId (long) const
virtual bool effectConfigurable (long) const
virtual long createEffect (const QString &)
virtual void removeEffect (long)
virtual void configureEffect (long)
virtual bool decoderConfigurable () const
virtual void setXfadeLength (int ms)
virtual void setSoundOutput (const QString &output)
virtual void setSoundDevice (const QString &device)
virtual void setDefaultSoundDevice (bool isDefault)
Protected Member Functions
void closeMixerHW ()
bool initMixerHW ()
void setVolumeHW (int percent)
Protected Attributes
int m_mixerHW
int m_volume
int m_xfadeLength
bool m_restoreEffects
QString m_soundOutput
QString m_soundDevice
bool m_defaultSoundDevice
Private Member Functions
virtual void init (bool &, int, bool)
virtual bool initMixer (bool)
virtual bool canDecode (const KURL &, mode_t, mode_t)
virtual long length () const
virtual long position () const
virtual EngineState state () const
virtual bool isStream () const
virtual void play (const KURL &)
virtual void play ()
virtual void stop ()
virtual void pause ()
virtual void seek (long)
virtual void setVolume (int v)
Member Enumeration Documentation
enum EngineBase::EngineState [inherited]
Enumeration values:
Empty
Idle
Playing
Paused
Definition at line 43 of file enginebase.h.
43 { Empty, Idle, Playing, Paused };
enum EngineBase::StreamingMode [inherited]
Enumeration values:
Socket
Signal
NoStreaming
Definition at line 44 of file enginebase.h.
Referenced by EngineBase::streamingMode().
44 { Socket, Signal, NoStreaming };
Constructor & Destructor Documentation
DummyEngine::DummyEngine () [inline]
Definition at line 48 of file enginecontroller.cpp.
48 : DummyEngine() : EngineBase() { setName( "Dummy" ); }
Member Function Documentation
virtual std::vector<long> EngineBase::activeEffects () const [inline, virtual, inherited]
Reimplemented in ArtsEngine (p.).
Definition at line 103 of file enginebase.h.
103 { return std::vector<long>(); }
virtual QStringList EngineBase::availableEffects () const [inline, virtual, inherited]
Reimplemented in ArtsEngine (p.).
Definition at line 102 of file enginebase.h.
102 { return QStringList(); }
virtual bool DummyEngine::canDecode (const KURL &, mode_t, mode_t) [inline, private, virtual]
Implements EngineBase (p.).
Definition at line 35 of file enginecontroller.cpp.
35 { return false; }
void EngineBase::closeMixerHW () [protected, inherited]
Definition at line 61 of file enginebase.cpp.
References EngineBase::m_mixerHW.
Referenced by ArtsEngine::initMixer(), and EngineBase::~EngineBase().
62 {
63     if ( m_mixerHW != -1 )
64     {
65         ::close( m_mixerHW );   //close /dev/mixer device
66         m_mixerHW = -1;
67     }
68 }
virtual void EngineBase::configureDecoder () [inline, virtual, slot, inherited]
Reimplemented in ArtsEngine (p.).
Definition at line 129 of file enginebase.h.
129 {}
virtual void EngineBase::configureEffect (long) [inline, virtual, inherited]
Reimplemented in ArtsEngine (p.).
Definition at line 108 of file enginebase.h.
108 { }
virtual long EngineBase::createEffect (const QString &) [inline, virtual, inherited]
Reimplemented in ArtsEngine (p.).
Definition at line 106 of file enginebase.h.
106 { return -1; }
virtual bool EngineBase::decoderConfigurable () const [inline, virtual, inherited]
Definition at line 109 of file enginebase.h.
109 { return false; }
virtual bool EngineBase::effectConfigurable (long) const [inline, virtual, inherited]
Reimplemented in ArtsEngine (p.).
Definition at line 105 of file enginebase.h.
105 { return false; }
virtual QString EngineBase::effectNameForId (long) const [inline, virtual, inherited]
Reimplemented in ArtsEngine (p.).
Definition at line 104 of file enginebase.h.
104 { return QString::null; }
void EngineBase::endOfTrack () [signal, inherited]
Definition at line 113 of file enginebase.moc.
114 {
115     activate_signal( staticMetaObject()->signalOffset() + 0 );
116 }
virtual QStringList EngineBase::getOutputsList () [inline, virtual, inherited]
Get list of available output plugins
Definition at line 61 of file enginebase.h.
61 { return QStringList(); }
virtual void DummyEngine::init (bool &, int, bool) [inline, private, virtual]
Implements EngineBase (p.).
Definition at line 33 of file enginecontroller.cpp.
33 {}
virtual bool DummyEngine::initMixer (bool) [inline, private, virtual]
Initialize mixer.
Parameters:
hardware True for soundcard hardware mixing
Returns: True if using hardware mixing
Implements EngineBase (p.).
Definition at line 34 of file enginecontroller.cpp.
34 { return false; }
bool EngineBase::initMixerHW () [protected, inherited]
Definition at line 43 of file enginebase.cpp.
References EngineBase::m_mixerHW.
Referenced by ArtsEngine::initMixer().
44 {
45     if ( ( m_mixerHW = ::open( "/dev/mixer", O_RDWR ) ) < 0 )
46         return false;  //failed
47     else
48     {
49         int devmask, recmask, i_recsrc, stereodevs;
50         if ( ioctl( m_mixerHW, SOUND_MIXER_READ_DEVMASK, &devmask )       == -1 ) return false;
51         if ( ioctl( m_mixerHW, SOUND_MIXER_READ_RECMASK, &recmask )       == -1 ) return false;
52         if ( ioctl( m_mixerHW, SOUND_MIXER_READ_RECSRC, &i_recsrc )       == -1 ) return false;
53         if ( ioctl( m_mixerHW, SOUND_MIXER_READ_STEREODEVS, &stereodevs ) == -1 ) return false;
54         if ( !devmask )                                                           return false;
55     }
56 
57     return true;
58 }
bool EngineBase::isMixerHardware () const [inline, inherited]
Sets the master volume.
Returns: True if using hardware mixer.
Definition at line 85 of file enginebase.h.
References EngineBase::m_mixerHW.
85 { return m_mixerHW != -1; }
virtual bool DummyEngine::isStream () const [inline, private, virtual]
Implements EngineBase (p.).
Definition at line 39 of file enginecontroller.cpp.
39 { return false; }
virtual long DummyEngine::length () const [inline, private, virtual]
Definition at line 36 of file enginecontroller.cpp.
36 { return 0; }
bool EngineBase::loaded () [inline, inherited]
Returns: True if media is loaded, system is ready to play.
Definition at line 73 of file enginebase.h.
References EngineBase::Empty, and EngineBase::state().
Referenced by EngineController::pause().
73 { return state() != Empty; }
virtual void EngineBase::newStreamData (char *, int) [inline, virtual, slot, inherited]
Definition at line 130 of file enginebase.h.
130 {};
virtual void DummyEngine::pause () [inline, private, virtual]
Implements EngineBase (p.).
Definition at line 43 of file enginecontroller.cpp.
43 {}
virtual void DummyEngine::play () [inline, private, virtual]
Implements EngineBase (p.).
Definition at line 41 of file enginecontroller.cpp.
41 {}
virtual void DummyEngine::play (const KURL &) [inline, private, virtual]
Implements EngineBase (p.).
Definition at line 40 of file enginecontroller.cpp.
40 {}
virtual long DummyEngine::position () const [inline, private, virtual]
Returns: Time position in ms
Implements EngineBase (p.).
Definition at line 37 of file enginecontroller.cpp.
37 { return 0; }
virtual void EngineBase::removeEffect (long) [inline, virtual, inherited]
Reimplemented in ArtsEngine (p.).
Definition at line 107 of file enginebase.h.
107 { }
virtual std::vector<float>* EngineBase::scope () [inline, virtual, inherited]
Fetches the current audio sample buffer.
Returns: Pointer to result of FFT calculation. Must be deleted after use.
Reimplemented in ArtsEngine (p.).
Definition at line 99 of file enginebase.h.
Referenced by Analyzer::Base< W >::drawFrame().
99 { return new std::vector<float>(); }
virtual void DummyEngine::seek (long) [inline, private, virtual]
Implements EngineBase (p.).
Definition at line 45 of file enginecontroller.cpp.
45 {}
virtual void EngineBase::setDefaultSoundDevice (bool isDefault) [inline, virtual, inherited]
Definition at line 114 of file enginebase.h.
References EngineBase::m_defaultSoundDevice.
Referenced by Myplayer::Myplayer().
114 { m_defaultSoundDevice = isDefault; }
void EngineBase::setRestoreEffects (bool yes) [inline, inherited]
Definition at line 101 of file enginebase.h.
References EngineBase::m_restoreEffects.
Referenced by Myplayer::Myplayer().
101 { m_restoreEffects = yes; }
virtual void EngineBase::setSoundDevice (const QString & device) [inline, virtual, inherited]
Definition at line 113 of file enginebase.h.
References EngineBase::m_soundDevice.
Referenced by Myplayer::Myplayer().
113 { m_soundDevice = device; }
void EngineBase::setSoundOutput (const QString & output) [virtual, inherited]
Definition at line 87 of file enginebase.cpp.
References EngineBase::m_soundOutput.
Referenced by Myplayer::Myplayer().
88 {
89     kdDebug() << "Setting sound output to: " << output << endl;
90     
91     m_soundOutput = output;
92 }
virtual void DummyEngine::setVolume (int v) [inline, private, virtual]
Parameters:
percent Set volume in range 0 to 100.
Implements EngineBase (p.).
Definition at line 46 of file enginecontroller.cpp.
46 { m_volume = v; }
void EngineBase::setVolumeHW (int percent) [protected, inherited]
Definition at line 71 of file enginebase.cpp.
References EngineBase::m_mixerHW.
Referenced by ArtsEngine::setVolume().
72 {
73     if ( m_mixerHW != -1 )
74     {
75         percent = percent + ( percent << 8 );
76         ioctl( m_mixerHW, MIXER_WRITE( 4 ), &percent );
77     }
78 }
void EngineBase::setXfadeLength (int ms) [virtual, inherited]
Definition at line 81 of file enginebase.cpp.
References EngineBase::m_xfadeLength.
Referenced by Myplayer::Myplayer().
82 {
83     m_xfadeLength = ms;
84 }
virtual EngineState DummyEngine::state () const [inline, private, virtual]
Implements EngineBase (p.).
Definition at line 38 of file enginecontroller.cpp.
38 { return EngineBase::Empty; }
virtual void DummyEngine::stop () [inline, private, virtual]
Implements EngineBase (p.).
Definition at line 42 of file enginecontroller.cpp.
42 {}
void EngineBase::stopped () [signal, inherited]
Definition at line 119 of file enginebase.moc.
Referenced by ArtsEngine::play().
120 {
121     activate_signal( staticMetaObject()->signalOffset() + 1 );
122 }
virtual StreamingMode EngineBase::streamingMode () [inline, virtual, inherited]
Reimplemented in ArtsEngine (p.).
Definition at line 59 of file enginebase.h.
References EngineBase::NoStreaming, and EngineBase::StreamingMode.
59 { return NoStreaming; }       
virtual bool EngineBase::supportsXFade () const [inline, virtual, inherited]
Determines whether the engine supports crossfading.
Returns: True if crossfading is supported.
Reimplemented in ArtsEngine (p.).
Definition at line 93 of file enginebase.h.
Referenced by EngineController::slotMainTimer().
93 { return false; }
int EngineBase::volume () const [inline, inherited]
Sets the master volume.
Returns: Volume in range 0 to 100.
Definition at line 79 of file enginebase.h.
References EngineBase::m_volume.
Referenced by EngineController::decreaseVolume(), EngineController::increaseVolume(), and EngineController::setVolume().
79 { return m_volume; }
Member Data Documentation
bool EngineBase::m_defaultSoundDevice [protected, inherited]
Definition at line 145 of file enginebase.h.
Referenced by EngineBase::setDefaultSoundDevice().
int EngineBase::m_mixerHW [protected, inherited]
Definition at line 139 of file enginebase.h.
Referenced by EngineBase::closeMixerHW(), EngineBase::initMixerHW(), EngineBase::isMixerHardware(), and EngineBase::setVolumeHW().
bool EngineBase::m_restoreEffects [protected, inherited]
Definition at line 142 of file enginebase.h.
Referenced by EngineBase::setRestoreEffects().
QString EngineBase::m_soundDevice [protected, inherited]
Definition at line 144 of file enginebase.h.
Referenced by EngineBase::setSoundDevice().
QString EngineBase::m_soundOutput [protected, inherited]
Definition at line 143 of file enginebase.h.
Referenced by EngineBase::setSoundOutput().
int EngineBase::m_volume [protected, inherited]
Definition at line 140 of file enginebase.h.
Referenced by EngineBase::volume().
int EngineBase::m_xfadeLength [protected, inherited]
Definition at line 141 of file enginebase.h.
Referenced by EngineBase::setXfadeLength().
The documentation for this class was generated from the following file:
enginecontroller.cpp