KStartupLogo Class Reference
#include <kstartuplogo.h>
Detailed Description
Author:
Definition at line 31 of file kstartuplogo.h.
Public Slots
void slotCloseLogo ()
Signals
void signalTriggerMainWidget ()
Public Member Functions
KStartupLogo (QWidget *parent=0, const char *name=0)
~KStartupLogo ()
void setHideEnabled (bool bEnabled)
Protected Member Functions
virtual void mousePressEvent (QMouseEvent *)
Protected Attributes
bool m_bReadyToHide
QTimer * LogoCloseTimer
int LogoCloseTime
Constructor & Destructor Documentation
KStartupLogo::KStartupLogo (QWidget * parent = 0, const char * name = 0)
Definition at line 23 of file kstartuplogo.cpp.
References LogoCloseTime, LogoCloseTimer, and slotCloseLogo().
23                                                              : QWidget(parent,name, WStyle_NoBorder | WStyle_Customize | WDestructiveClose ), m_bReadyToHide( false ),LogoCloseTimer(NULL),LogoCloseTime(1){
24         QPixmap pm;
25         pm.load("/root/kde_application/hdass08/skin/skin-logo.jpg");
26         setBackgroundPixmap(pm);
27         setGeometry(KApplication::desktop()->width()/2-pm.width()/2, KApplication::desktop()->height()/2-pm.height()/2, pm.width(),pm.height());
28         
29         //DAVID Timer Set up
30         LogoCloseTimer=new QTimer(this);
31         //DAVID Connect LogoCloseTimer to slot "slotCloseLogo"
32         connect(LogoCloseTimer,SIGNAL(timeout()),this,SLOT(slotCloseLogo()));
33         LogoCloseTimer->start( LogoCloseTime*1000, TRUE ); // 2 seconds single-shot timer
34 }
KStartupLogo::~KStartupLogo ()
Definition at line 36 of file kstartuplogo.cpp.
37 {
38 }
Member Function Documentation
void KStartupLogo::mousePressEvent (QMouseEvent *) [protected, virtual]
Definition at line 40 of file kstartuplogo.cpp.
References m_bReadyToHide.
41 {
42         if (m_bReadyToHide) hide();
43 }
void KStartupLogo::setHideEnabled (bool bEnabled) [inline]
Definition at line 38 of file kstartuplogo.h.
References m_bReadyToHide.
38 { m_bReadyToHide = bEnabled; };
void KStartupLogo::signalTriggerMainWidget () [signal]
Definition at line 84 of file kstartuplogo.moc.
Referenced by slotCloseLogo().
85 {
86     activate_signal( staticMetaObject()->signalOffset() + 0 );
87 }
void KStartupLogo::slotCloseLogo () [slot]
Definition at line 45 of file kstartuplogo.cpp.
References signalTriggerMainWidget().
Referenced by KStartupLogo().
46 {
47    //DAVID Hide Logo itself.
48    this->hide();
49    emit signalTriggerMainWidget();
50 }
Member Data Documentation
int KStartupLogo::LogoCloseTime [protected]
Definition at line 47 of file kstartuplogo.h.
Referenced by KStartupLogo().
QTimer* KStartupLogo::LogoCloseTimer [protected]
Definition at line 46 of file kstartuplogo.h.
Referenced by KStartupLogo().
bool KStartupLogo::m_bReadyToHide [protected]
Definition at line 45 of file kstartuplogo.h.
Referenced by mousePressEvent(), and setHideEnabled().
The documentation for this class was generated from the following files:
kstartuplogo.h
kstartuplogo.moc
kstartuplogo.cpp