EngineBase Class Reference
#include <enginebase.h>
Public Types
enum EngineState { Empty,
Idle,
Playing,
Paused
 }
enum StreamingMode { Socket,
Signal,
NoStreaming
 }
Public Slots
virtual void play (const KURL &)=0
virtual void play ()=0
virtual void stop ()=0
virtual void pause ()=0
virtual void setVolume (int percent)=0
virtual void seek (long ms)=0
virtual void configureDecoder ()
virtual void newStreamData (char *, int)
Signals
void endOfTrack ()
void stopped ()
Public Member Functions
EngineBase ()
virtual ~EngineBase ()
virtual void init (bool &restart, int scopeSize, bool restoreEffects)=0
virtual bool initMixer (bool hardware)=0
virtual bool canDecode (const KURL &url, mode_t mode, mode_t permissions)=0
virtual StreamingMode streamingMode ()
virtual QStringList getOutputsList ()
virtual long position () const=0
virtual EngineState state () const=0
bool loaded ()
int volume () const
bool isMixerHardware () const
virtual bool isStream () const=0
virtual bool supportsXFade () const
virtual std::vector< float > * scope ()
void setRestoreEffects (bool yes)
virtual QStringList availableEffects () const
virtual std::vector< long > activeEffects () const
virtual QString effectNameForId (long) const
virtual bool effectConfigurable (long) const
virtual long createEffect (const QString &)
virtual void removeEffect (long)
virtual void configureEffect (long)
virtual bool decoderConfigurable () const
virtual void setXfadeLength (int ms)
virtual void setSoundOutput (const QString &output)
virtual void setSoundDevice (const QString &device)
virtual void setDefaultSoundDevice (bool isDefault)
Protected Member Functions
void closeMixerHW ()
bool initMixerHW ()
void setVolumeHW (int percent)
EngineBase (const EngineBase &)
const EngineBase & operator= (const EngineBase &)
Protected Attributes
int m_mixerHW
int m_volume
int m_xfadeLength
bool m_restoreEffects
QString m_soundOutput
QString m_soundDevice
bool m_defaultSoundDevice
Member Enumeration Documentation
enum EngineBase::EngineState
Enumeration values:
Empty
Idle
Playing
Paused
Definition at line 43 of file enginebase.h.
43 { Empty, Idle, Playing, Paused };
enum EngineBase::StreamingMode
Enumeration values:
Socket
Signal
NoStreaming
Definition at line 44 of file enginebase.h.
Referenced by streamingMode().
44 { Socket, Signal, NoStreaming };
Constructor & Destructor Documentation
EngineBase::EngineBase ()
Definition at line 30 of file enginebase.cpp.
31 {}
EngineBase::~EngineBase () [virtual]
Definition at line 34 of file enginebase.cpp.
References closeMixerHW().
35 {
36     kdDebug() << k_funcinfo << endl;
37 
38     closeMixerHW();
39 }
EngineBase::EngineBase (const EngineBase &) [protected]
Member Function Documentation
virtual std::vector<long> EngineBase::activeEffects () const [inline, virtual]
Reimplemented in ArtsEngine (p.).
Definition at line 103 of file enginebase.h.
103 { return std::vector<long>(); }
virtual QStringList EngineBase::availableEffects () const [inline, virtual]
Reimplemented in ArtsEngine (p.).
Definition at line 102 of file enginebase.h.
102 { return QStringList(); }
virtual bool EngineBase::canDecode (const KURL & url, mode_t mode, mode_t permissions) [pure virtual]
Implemented in ArtsEngine (p.), and DummyEngine (p.).
void EngineBase::closeMixerHW () [protected]
Definition at line 61 of file enginebase.cpp.
References m_mixerHW.
Referenced by ArtsEngine::initMixer(), and ~EngineBase().
62 {
63     if ( m_mixerHW != -1 )
64     {
65         ::close( m_mixerHW );   //close /dev/mixer device
66         m_mixerHW = -1;
67     }
68 }
virtual void EngineBase::configureDecoder () [inline, virtual, slot]
Reimplemented in ArtsEngine (p.).
Definition at line 129 of file enginebase.h.
129 {}
virtual void EngineBase::configureEffect (long) [inline, virtual]
Reimplemented in ArtsEngine (p.).
Definition at line 108 of file enginebase.h.
108 { }
virtual long EngineBase::createEffect (const QString &) [inline, virtual]
Reimplemented in ArtsEngine (p.).
Definition at line 106 of file enginebase.h.
106 { return -1; }
virtual bool EngineBase::decoderConfigurable () const [inline, virtual]
Definition at line 109 of file enginebase.h.
109 { return false; }
virtual bool EngineBase::effectConfigurable (long) const [inline, virtual]
Reimplemented in ArtsEngine (p.).
Definition at line 105 of file enginebase.h.
105 { return false; }
virtual QString EngineBase::effectNameForId (long) const [inline, virtual]
Reimplemented in ArtsEngine (p.).
Definition at line 104 of file enginebase.h.
104 { return QString::null; }
void EngineBase::endOfTrack () [signal]
Definition at line 113 of file enginebase.moc.
114 {
115     activate_signal( staticMetaObject()->signalOffset() + 0 );
116 }
virtual QStringList EngineBase::getOutputsList () [inline, virtual]
Get list of available output plugins
Definition at line 61 of file enginebase.h.
61 { return QStringList(); }
virtual void EngineBase::init (bool & restart, int scopeSize, bool restoreEffects) [pure virtual]
Implemented in ArtsEngine (p.), and DummyEngine (p.).
Referenced by Myplayer::Myplayer().
virtual bool EngineBase::initMixer (bool hardware) [pure virtual]
Initialize mixer.
Parameters:
hardware True for soundcard hardware mixing
Returns: True if using hardware mixing
Implemented in ArtsEngine (p.), and DummyEngine (p.).
Referenced by Myplayer::Myplayer().
bool EngineBase::initMixerHW () [protected]
Definition at line 43 of file enginebase.cpp.
References m_mixerHW.
Referenced by ArtsEngine::initMixer().
44 {
45     if ( ( m_mixerHW = ::open( "/dev/mixer", O_RDWR ) ) < 0 )
46         return false;  //failed
47     else
48     {
49         int devmask, recmask, i_recsrc, stereodevs;
50         if ( ioctl( m_mixerHW, SOUND_MIXER_READ_DEVMASK, &devmask )       == -1 ) return false;
51         if ( ioctl( m_mixerHW, SOUND_MIXER_READ_RECMASK, &recmask )       == -1 ) return false;
52         if ( ioctl( m_mixerHW, SOUND_MIXER_READ_RECSRC, &i_recsrc )       == -1 ) return false;
53         if ( ioctl( m_mixerHW, SOUND_MIXER_READ_STEREODEVS, &stereodevs ) == -1 ) return false;
54         if ( !devmask )                                                           return false;
55     }
56 
57     return true;
58 }
bool EngineBase::isMixerHardware () const [inline]
Sets the master volume.
Returns: True if using hardware mixer.
Definition at line 85 of file enginebase.h.
References m_mixerHW.
85 { return m_mixerHW != -1; }
virtual bool EngineBase::isStream () const [pure virtual]
Implemented in ArtsEngine (p.), and DummyEngine (p.).
Referenced by EngineController::slotMainTimer().
bool EngineBase::loaded () [inline]
Returns: True if media is loaded, system is ready to play.
Definition at line 73 of file enginebase.h.
References Empty, and state().
Referenced by EngineController::pause().
73 { return state() != Empty; }
virtual void EngineBase::newStreamData (char *, int) [inline, virtual, slot]
Definition at line 130 of file enginebase.h.
130 {};
const EngineBase& EngineBase::operator= (const EngineBase &) [protected]
virtual void EngineBase::pause () [pure virtual, slot]
Implemented in ArtsEngine (p.), and DummyEngine (p.).
Referenced by EngineController::pause().
virtual void EngineBase::play () [pure virtual, slot]
Implemented in ArtsEngine (p.), and DummyEngine (p.).
virtual void EngineBase::play (const KURL &) [pure virtual, slot]
Implemented in ArtsEngine (p.), and DummyEngine (p.).
Referenced by EngineController::pause(), and EngineController::play().
virtual long EngineBase::position () const [pure virtual]
Returns: Time position in ms
Implemented in ArtsEngine (p.), and DummyEngine (p.).
Referenced by EngineController::slotMainTimer().
virtual void EngineBase::removeEffect (long) [inline, virtual]
Reimplemented in ArtsEngine (p.).
Definition at line 107 of file enginebase.h.
107 { }
virtual std::vector<float>* EngineBase::scope () [inline, virtual]
Fetches the current audio sample buffer.
Returns: Pointer to result of FFT calculation. Must be deleted after use.
Reimplemented in ArtsEngine (p.).
Definition at line 99 of file enginebase.h.
Referenced by Analyzer::Base< W >::drawFrame().
99 { return new std::vector<float>(); }
virtual void EngineBase::seek (long ms) [pure virtual, slot]
Implemented in ArtsEngine (p.), and DummyEngine (p.).
Referenced by Myplayer::handleSlider().
virtual void EngineBase::setDefaultSoundDevice (bool isDefault) [inline, virtual]
Definition at line 114 of file enginebase.h.
References m_defaultSoundDevice.
Referenced by Myplayer::Myplayer().
114 { m_defaultSoundDevice = isDefault; }
void EngineBase::setRestoreEffects (bool yes) [inline]
Definition at line 101 of file enginebase.h.
References m_restoreEffects.
Referenced by Myplayer::Myplayer().
101 { m_restoreEffects = yes; }
virtual void EngineBase::setSoundDevice (const QString & device) [inline, virtual]
Definition at line 113 of file enginebase.h.
References m_soundDevice.
Referenced by Myplayer::Myplayer().
113 { m_soundDevice = device; }
void EngineBase::setSoundOutput (const QString & output) [virtual]
Definition at line 87 of file enginebase.cpp.
References m_soundOutput.
Referenced by Myplayer::Myplayer().
88 {
89     kdDebug() << "Setting sound output to: " << output << endl;
90     
91     m_soundOutput = output;
92 }
virtual void EngineBase::setVolume (int percent) [pure virtual, slot]
Parameters:
percent Set volume in range 0 to 100.
Implemented in ArtsEngine (p.), and DummyEngine (p.).
Referenced by EngineController::EngineController(), Myplayer::Myplayer(), and EngineController::setVolume().
void EngineBase::setVolumeHW (int percent) [protected]
Definition at line 71 of file enginebase.cpp.
References m_mixerHW.
Referenced by ArtsEngine::setVolume().
72 {
73     if ( m_mixerHW != -1 )
74     {
75         percent = percent + ( percent << 8 );
76         ioctl( m_mixerHW, MIXER_WRITE( 4 ), &percent );
77     }
78 }
void EngineBase::setXfadeLength (int ms) [virtual]
Definition at line 81 of file enginebase.cpp.
References m_xfadeLength.
Referenced by Myplayer::Myplayer().
82 {
83     m_xfadeLength = ms;
84 }
virtual EngineState EngineBase::state () const [pure virtual]
Implemented in ArtsEngine (p.), and DummyEngine (p.).
Referenced by Analyzer::Base< W >::drawFrame(), loaded(), EngineController::pause(), EngineController::play(), EngineController::slotMainTimer(), and EngineController::stop().
virtual void EngineBase::stop () [pure virtual, slot]
Implemented in ArtsEngine (p.), and DummyEngine (p.).
Referenced by EngineController::stop().
void EngineBase::stopped () [signal]
Definition at line 119 of file enginebase.moc.
Referenced by ArtsEngine::play().
120 {
121     activate_signal( staticMetaObject()->signalOffset() + 1 );
122 }
virtual StreamingMode EngineBase::streamingMode () [inline, virtual]
Reimplemented in ArtsEngine (p.).
Definition at line 59 of file enginebase.h.
References NoStreaming, and StreamingMode.
59 { return NoStreaming; }       
virtual bool EngineBase::supportsXFade () const [inline, virtual]
Determines whether the engine supports crossfading.
Returns: True if crossfading is supported.
Reimplemented in ArtsEngine (p.).
Definition at line 93 of file enginebase.h.
Referenced by EngineController::slotMainTimer().
93 { return false; }
int EngineBase::volume () const [inline]
Sets the master volume.
Returns: Volume in range 0 to 100.
Definition at line 79 of file enginebase.h.
References m_volume.
Referenced by EngineController::decreaseVolume(), EngineController::increaseVolume(), and EngineController::setVolume().
79 { return m_volume; }
Member Data Documentation
bool EngineBase::m_defaultSoundDevice [protected]
Definition at line 145 of file enginebase.h.
Referenced by setDefaultSoundDevice().
int EngineBase::m_mixerHW [protected]
Definition at line 139 of file enginebase.h.
Referenced by closeMixerHW(), initMixerHW(), isMixerHardware(), and setVolumeHW().
bool EngineBase::m_restoreEffects [protected]
Definition at line 142 of file enginebase.h.
Referenced by setRestoreEffects().
QString EngineBase::m_soundDevice [protected]
Definition at line 144 of file enginebase.h.
Referenced by setSoundDevice().
QString EngineBase::m_soundOutput [protected]
Definition at line 143 of file enginebase.h.
Referenced by setSoundOutput().
int EngineBase::m_volume [protected]
Definition at line 140 of file enginebase.h.
Referenced by volume().
int EngineBase::m_xfadeLength [protected]
Definition at line 141 of file enginebase.h.
Referenced by setXfadeLength().
The documentation for this class was generated from the following files:
enginebase.h
enginebase.moc
enginebase.cpp