QtFileIconView Class Reference
#include <qfileiconview.h>
Public Types
enum ViewMode { Large,
Small
 }
Public Slots
void setDirectory (const QString &dir)
void setDirectory (const QDir &dir)
void newDirectory ()
QDir currentDir ()
void slotDeletCurrItem ()
Signals
void directoryChanged (const QString &)
void startReadDir (int dirs)
void readNextDir ()
void readDirDone ()
void enableUp ()
void disableUp ()
void enableMkdir ()
void disableMkdir ()
void signalAddFileToList (KURL::List list, HDASS_ACTION_TYPE act)
void signalShowTheDetialofImage (KURL url)
Public Member Functions
QtFileIconView (const QString &dir, QWidget *parent=0, const char *name=0,FloderType type=Music)
void setViewMode (ViewMode m)
ViewMode viewMode () const
void setOpenItem (QtFileIconViewItem *i)
Protected Slots
void itemDoubleClicked (QIconViewItem *i)
void itemClicked (QIconViewItem *i)
void slotDropped (QDropEvent *e, const QValueList< QIconDragItem > &)
void viewLarge ()
void viewSmall ()
void viewBottom ()
void viewRight ()
void flowEast ()
void flowSouth ()
void itemTextTruncate ()
void itemTextWordWrap ()
void sortAscending ()
void sortDescending ()
void arrangeItemsInGrid ()
void slotRightPressed (QIconViewItem *item)
void openFolder ()
Protected Member Functions
void readDir (const QDir &dir)
virtual QDragObject * dragObject ()
virtual void keyPressEvent (QKeyEvent *e)
Protected Attributes
QDir viewDir
int newFolderNum
QSize sz
QPixmap pix
ViewMode vm
QtFileIconViewItem * openItem
FloderType flodertype
Member Enumeration Documentation
enum QtFileIconView::ViewMode
Enumeration values:
Large
Small
Definition at line 68 of file qfileiconview.h.
Referenced by viewMode().
68 { Large, Small };
Constructor & Destructor Documentation
QtFileIconView::QtFileIconView (const QString & dir, QWidget * parent = 0, const char * name = 0, FloderType type = Music)
Definition at line 272 of file qfileiconview.cpp.
References cleanup(), iconFileLarge, itemClicked(), itemDoubleClicked(), Large, openItem, slotDropped(), slotRightPressed(), and vm.
273     : QIconView( parent, name ), viewDir( dir ), newFolderNum( 0 ),flodertype(type)
274 {
275    
276         qAddPostRoutine( cleanup );
277         //MP3 File Icon
278         iconFileLarge = new QPixmap( "/root/kde_application/hdass08/skin/mp3icon.png" );
279         vm = Large;
280 
281     setGridX( 75 );
282     setGridY( 75 );
283     setResizeMode( Adjust );
284     setWordWrapIconText( FALSE );
285 
286     connect( this, SIGNAL( doubleClicked( QIconViewItem * ) ),
287              this, SLOT( itemDoubleClicked( QIconViewItem * ) ) );
288     connect( this, SIGNAL( returnPressed( QIconViewItem * ) ),
289              this, SLOT( itemDoubleClicked( QIconViewItem * ) ) );
290     connect( this, SIGNAL( dropped( QDropEvent *, const QValueList<QIconDragItem> & ) ),
291              this, SLOT( slotDropped( QDropEvent *, const QValueList<QIconDragItem> & ) ) );
292     connect( this, SIGNAL( contextMenuRequested( QIconViewItem *, const QPoint & ) ),
293              this, SLOT( slotRightPressed( QIconViewItem * ) ) );
294     connect(this,SIGNAL(clicked( QIconViewItem *)),this,SLOT(itemClicked(QIconViewItem* ))); 
295     setHScrollBarMode( AlwaysOff );
296     setVScrollBarMode( Auto );
297 
298     setAutoArrange( TRUE );
299     setSorting( TRUE );
300     openItem = 0;
301 }
Member Function Documentation
void QtFileIconView::arrangeItemsInGrid () [inline, protected, slot]
Definition at line 108 of file qfileiconview.h.
Referenced by setViewMode(), and slotRightPressed().
108                               {
109         QIconView::arrangeItemsInGrid( TRUE );
110     }
QDir QtFileIconView::currentDir () [slot]
Definition at line 349 of file qfileiconview.cpp.
References viewDir.
350 {
351     return viewDir;
352 }
void QtFileIconView::directoryChanged (const QString &) [signal]
Definition at line 247 of file qfileiconview.moc.cc.
Referenced by readDir().
248 {
249     activate_signal( staticMetaObject()->signalOffset() + 0, t0 );
250 }
void QtFileIconView::disableMkdir () [signal]
Definition at line 289 of file qfileiconview.moc.cc.
Referenced by readDir().
290 {
291     activate_signal( staticMetaObject()->signalOffset() + 7 );
292 }
void QtFileIconView::disableUp () [signal]
Definition at line 277 of file qfileiconview.moc.cc.
Referenced by readDir().
278 {
279     activate_signal( staticMetaObject()->signalOffset() + 5 );
280 }
QDragObject * QtFileIconView::dragObject () [protected, virtual]
Definition at line 479 of file qfileiconview.cpp.
References QtFileIconDrag::append(), and QtFileIconViewItem::filename().
480 {
481 
482     if ( !currentItem() )
483         return 0;
484 
485     QPoint orig = viewportToContents( viewport()->mapFromGlobal( QCursor::pos() ) );
486     QtFileIconDrag *drag = new QtFileIconDrag( viewport() );
487     drag->setPixmap( *currentItem()->pixmap(),
488                      QPoint( currentItem()->pixmapRect().width() / 2, currentItem()->pixmapRect().height() / 2 ) );
489     for ( QtFileIconViewItem *item = (QtFileIconViewItem*)firstItem(); item;
490           item = (QtFileIconViewItem*)item->nextItem() ) {
491         if ( item->isSelected() ) {
492             QIconDragItem id;
493             id.setData( QCString( item->filename() ) );
494             drag->append( id,
495                           QRect( item->pixmapRect( FALSE ).x() - orig.x(),
496                                  item->pixmapRect( FALSE ).y() - orig.y(),
497                                  item->pixmapRect().width(), item->pixmapRect().height() ),
498                           QRect( item->textRect( FALSE ).x() - orig.x(),
499                                  item->textRect( FALSE ).y() - orig.y(),
500                                  item->textRect().width(), item->textRect().height() ),
501                           QString( item->filename() ) );
502         }
503     }
504     return drag;
505 }
void QtFileIconView::enableMkdir () [signal]
Definition at line 283 of file qfileiconview.moc.cc.
Referenced by readDir().
284 {
285     activate_signal( staticMetaObject()->signalOffset() + 6 );
286 }
void QtFileIconView::enableUp () [signal]
Definition at line 271 of file qfileiconview.moc.cc.
Referenced by readDir().
272 {
273     activate_signal( staticMetaObject()->signalOffset() + 4 );
274 }
void QtFileIconView::flowEast () [protected, slot]
Definition at line 566 of file qfileiconview.cpp.
Referenced by slotRightPressed().
567 {
568     setHScrollBarMode( AlwaysOff );
569     setVScrollBarMode( Auto );
570     setArrangement( LeftToRight );
571 }
void QtFileIconView::flowSouth () [protected, slot]
Definition at line 573 of file qfileiconview.cpp.
Referenced by slotRightPressed().
574 {
575     setVScrollBarMode( AlwaysOff );
576     setHScrollBarMode( Auto );
577     setArrangement( TopToBottom );
578 }
void QtFileIconView::itemClicked (QIconViewItem * i) [protected, slot]
Definition at line 679 of file qfileiconview.cpp.
Referenced by QtFileIconView().
680 {
681   QtFileIconViewItem *item = ( QtFileIconViewItem* )i;
682   setCurrentItem(i);
683   //qWarning(item->filename());
684 }
void QtFileIconView::itemDoubleClicked (QIconViewItem * i) [protected, slot]
Definition at line 441 of file qfileiconview.cpp.
References QtFileIconViewItem::filename(), mm_append, readDir(), signalAddFileToList(), signalShowTheDetialofImage(), QtFileIconViewItem::type(), and viewDir.
Referenced by QtFileIconView().
442 {
443     //qWarning("DAVID Test for itemDoubleClicked!!");
444     QtFileIconViewItem *item = ( QtFileIconViewItem* )i;
445     if ( item->type() == QtFileIconViewItem::Dir ) 
446     {
447         viewDir = QDir( item->filename() );
448         readDir( viewDir );
449     } 
450     else if ( item->type() == QtFileIconViewItem::Link && QFileInfo( QFileInfo( item->filename() ).readLink() ).isDir() ) 
451     {
452         viewDir = QDir( QFileInfo( item->filename() ).readLink() );
453         readDir( viewDir );
454     }
455     
456     //DAVID  If double clicked ,then send the file item to the playlist.
457     
458     //DAVID Check that if the file type,u just need to send mp3 file to the playlist.
459     else if(item->type()==QtFileIconViewItem::File)//MP3 file
460     {
461         //DAVID send the file path to the playlist.
462         kdDebug()<<item->filename();
463         KURL url(QString("file:")+item->filename());
464         qWarning(url.fileName());
465         KURL::List list;
466         list<<url;
467         emit signalAddFileToList(list,mm_append);
468     }
469     else if(item->type()==QtFileIconViewItem::Image)//Image file
470     {
471         //DAVID Show the detail of Image
472         kdDebug()<<item->filename();
473         KURL url(QString("file:")+item->filename());
474         emit signalShowTheDetialofImage(url);
475     }
476     
477 }
void QtFileIconView::itemTextTruncate () [protected, slot]
Definition at line 590 of file qfileiconview.cpp.
Referenced by slotRightPressed().
591 {
592     setWordWrapIconText( FALSE );
593 }
void QtFileIconView::itemTextWordWrap () [protected, slot]
Definition at line 595 of file qfileiconview.cpp.
Referenced by slotRightPressed().
596 {
597     setWordWrapIconText( TRUE );
598 }
void QtFileIconView::keyPressEvent (QKeyEvent * e) [protected, virtual]
Definition at line 507 of file qfileiconview.cpp.
References newDirectory().
508 {
509     if ( e->key() == Key_N &&
510          ( e->state() & ControlButton ) )
511         newDirectory();
512     else
513         QIconView::keyPressEvent( e );
514 }
void QtFileIconView::newDirectory () [slot]
Definition at line 328 of file qfileiconview.cpp.
References newFolderNum, and viewDir.
Referenced by keyPressEvent().
329 {
330     setAutoArrange( FALSE );
331     selectAll( FALSE );
332     if ( viewDir.mkdir( QString( "New Folder %1" ).arg( ++newFolderNum ) ) ) 
333     {                                                                        
334         QFileInfo *fi = new QFileInfo( viewDir, QString( "New Folder %1" ).arg( newFolderNum ) );
335         QtFileIconViewItem *item = new QtFileIconViewItem( this, new QFileInfo( *fi ) ,0);
336         item->setKey( QString( "000000%1" ).arg( fi->fileName() ) );
337         delete fi;
338         repaintContents( contentsX(), contentsY(), contentsWidth(), contentsHeight(), FALSE );
339         ensureItemVisible( item );
340         item->setSelected( TRUE, TRUE );
341         setCurrentItem( item );
342         repaintItem( item );
343         qApp->processEvents();
344         item->rename();
345     }
346     setAutoArrange( TRUE );
347 }
void QtFileIconView::openFolder () [protected, slot]
Definition at line 303 of file qfileiconview.cpp.
References QtFileIconViewItem::itemFileName, openItem, setDirectory(), QtFileIconViewItem::timer, and QtFileIconViewItem::type().
304 {
305     if ( !openItem )
306         return;
307     if ( openItem->type() != QtFileIconViewItem::Dir ||
308          openItem->type() == QtFileIconViewItem::Dir &&
309          !QDir( openItem->itemFileName ).isReadable() )
310         return;
311 
312     openItem->timer.stop();
313     setDirectory( openItem->itemFileName );
314 }
void QtFileIconView::readDir (const QDir & dir) [protected]
Definition at line 376 of file qfileiconview.cpp.
References directoryChanged(), disableMkdir(), disableUp(), enableMkdir(), enableUp(), flodertype, isRoot(), Music, readDirDone(), readNextDir(), and startReadDir().
Referenced by itemDoubleClicked(), and setDirectory().
377 {
378    QDir s=dir;
379    if(flodertype==Image)
380    {
381         s.setNameFilter("*.jpg");
382    }
383    else if(flodertype==Music)
384    {
385         s.setNameFilter("*.mp3");
386    }
387    if ( !dir.isReadable() )
388         return;
389 
390     if ( isRoot( dir.absPath() ) )
391         emit disableUp();
392     else
393         emit enableUp();
394 
395     clear();
396 
397     emit directoryChanged( s.absPath() );
398 
399     const QFileInfoList *filist = s.entryInfoList( QDir::Files );
400 
401     emit startReadDir( filist->count() );
402 
403     int pixindex=0;
404     QFileInfoListIterator it( *filist );
405     QFileInfo *fi;
406     bool allowRename = FALSE, allowRenameSet = FALSE;
407     while ( ( fi = it.current() ) != 0 ) {
408         
409         ++it;
410         if ( fi && fi->fileName() == ".." && ( fi->dirPath() == "/" || fi->dirPath().isEmpty() ) )
411             continue;
412         emit readNextDir();
413         QtFileIconViewItem *item = new QtFileIconViewItem( this, new QFileInfo( *fi ),pixindex );
414         if ( fi->isDir() )
415             item->setKey( QString( "000000%1" ).arg( fi->fileName() ) );
416         else
417             item->setKey( fi->fileName() );
418         if ( !allowRenameSet ) {
419             if ( !QFileInfo( fi->absFilePath() ).isWritable() ||
420                  item->text() == "." || item->text() == ".." )
421                 allowRename = FALSE;
422             else
423                 allowRename = TRUE;
424             if ( item->text() == "." || item->text() == ".." )
425                 allowRenameSet = FALSE;
426             else
427                 allowRenameSet = TRUE;
428         }
429         item->setRenameEnabled( allowRename );
430         ++pixindex;
431     }
432 
433     if ( !QFileInfo( s.absPath() ).isWritable() )
434         emit disableMkdir();
435     else
436         emit enableMkdir();
437 
438     emit readDirDone();
439 }
void QtFileIconView::readDirDone () [signal]
Definition at line 265 of file qfileiconview.moc.cc.
Referenced by readDir().
266 {
267     activate_signal( staticMetaObject()->signalOffset() + 3 );
268 }
void QtFileIconView::readNextDir () [signal]
Definition at line 259 of file qfileiconview.moc.cc.
Referenced by readDir().
260 {
261     activate_signal( staticMetaObject()->signalOffset() + 2 );
262 }
void QtFileIconView::setDirectory (const QDir & dir) [slot]
Definition at line 322 of file qfileiconview.cpp.
References readDir(), and viewDir.
323 {
324     viewDir = dir;
325     readDir( viewDir );
326 }
void QtFileIconView::setDirectory (const QString & dir) [slot]
Definition at line 316 of file qfileiconview.cpp.
References readDir(), and viewDir.
Referenced by openFolder().
317 {
318     viewDir = QDir( dir );
319     readDir( viewDir );
320 }
void QtFileIconView::setOpenItem (QtFileIconViewItem * i) [inline]
Definition at line 72 of file qfileiconview.h.
References openItem.
72                                               {
73         openItem = i;
74     }
void QtFileIconView::setViewMode (ViewMode m)
Definition at line 646 of file qfileiconview.cpp.
References arrangeItemsInGrid(), QtFileIconViewItem::viewModeChanged(), and vm.
Referenced by viewLarge(), and viewSmall().
647 {
648     if ( m == vm )
649         return;
650 
651     vm = m;
652     QtFileIconViewItem *item = (QtFileIconViewItem*)firstItem();
653     for ( ; item; item = (QtFileIconViewItem*)item->nextItem() )
654         item->viewModeChanged( vm );
655 
656     arrangeItemsInGrid();
657 }
void QtFileIconView::signalAddFileToList (KURL::List list, HDASS_ACTION_TYPE act) [signal]
Definition at line 298 of file qfileiconview.moc.cc.
Referenced by itemDoubleClicked().
299 {
300     if ( signalsBlocked() )
301         return;
302     QConnectionList *clist = receivers( staticMetaObject()->signalOffset() + 8 );
303     if ( !clist )
304         return;
305     QUObject o[3];
306     static_QUType_ptr.set(o+1,&t0);
307     static_QUType_ptr.set(o+2,&t1);
308     activate_signal( clist, o );
309 }
void QtFileIconView::signalShowTheDetialofImage (KURL url) [signal]
Definition at line 312 of file qfileiconview.moc.cc.
Referenced by itemDoubleClicked().
313 {
314     if ( signalsBlocked() )
315         return;
316     QConnectionList *clist = receivers( staticMetaObject()->signalOffset() + 9 );
317     if ( !clist )
318         return;
319     QUObject o[2];
320     static_QUType_ptr.set(o+1,&t0);
321     activate_signal( clist, o );
322 }
void QtFileIconView::slotDeletCurrItem () [slot]
Definition at line 658 of file qfileiconview.cpp.
References QtFileIconViewItem::filename().
Referenced by mediamanagement::slotDeleteItem().
659 {
660 
661  QtFileIconViewItem *item=( QtFileIconViewItem* )firstItem();
662  while(item)
663  {
664         if(item->isSelected())
665         {
666                 QFile deletefile(item->filename());
667                 deletefile.remove();
668                 QtFileIconViewItem *curitem=item;
669                 item=( QtFileIconViewItem* )item->nextItem();
670                 delete curitem;
671         }
672         else
673         {
674                 item=( QtFileIconViewItem* )item->nextItem();
675         }
676  }
677  sort();
678 }
void QtFileIconView::slotDropped (QDropEvent * e, const QValueList< QIconDragItem > &) [protected, slot]
Definition at line 516 of file qfileiconview.cpp.
References openItem, QtFileIconViewItem::timer, and viewDir.
Referenced by QtFileIconView().
517 {
518     if ( openItem )
519         openItem->timer.stop();
520     if ( !QUriDrag::canDecode( e ) ) {
521         e->ignore();
522         return;
523     }
524 
525     QStringList lst;
526     QUriDrag::decodeLocalFiles( e, lst );
527 
528     QString str;
529     if ( e->action() == QDropEvent::Copy )
530         str = "Copy\n\n";
531     else
532         str = "Move\n\n";
533     for ( uint i = 0; i < lst.count(); ++i )
534         str += QString( "   %1\n" ).arg( QDir::convertSeparators(lst[i]) );
535     str += QString( "\n"
536         "To\n\n"
537         "       %1" ).arg( viewDir.absPath() );
538 
539     QMessageBox::information( this, e->action() == QDropEvent::Copy ? "Copy" : "Move" , str, "Not Implemented" );
540     if ( e->action() == QDropEvent::Move )
541         QMessageBox::information( this, "Remove" , QDir::convertSeparators(lst.join("\n")), "Not Implemented" );
542     e->acceptAction();
543     openItem = 0;
544 }
void QtFileIconView::slotRightPressed (QIconViewItem * item) [protected, slot]
Definition at line 600 of file qfileiconview.cpp.
References arrangeItemsInGrid(), flowEast(), flowSouth(), itemTextTruncate(), itemTextWordWrap(), sortAscending(), sortDescending(), viewBottom(), viewLarge(), viewRight(), and viewSmall().
Referenced by QtFileIconView().
601 {
602     if ( !item ) { // right pressed on viewport
603         QPopupMenu menu( this );
604 
605         menu.insertItem( "&Large view", this, SLOT( viewLarge() ) );
606         menu.insertItem( "&Small view", this, SLOT( viewSmall() ) );
607         menu.insertSeparator();
608         menu.insertItem( "Text at the &bottom", this, SLOT( viewBottom() ) );
609         menu.insertItem( "Text at the &right", this, SLOT( viewRight() ) );
610         menu.insertSeparator();
611         menu.insertItem( "Arrange l&eft to right", this, SLOT( flowEast() ) );
612         menu.insertItem( "Arrange t&op to bottom", this, SLOT( flowSouth() ) );
613         menu.insertSeparator();
614         menu.insertItem( "&Truncate item text", this, SLOT( itemTextTruncate() ) );
615         menu.insertItem( "&Wordwrap item text", this, SLOT( itemTextWordWrap() ) );
616         menu.insertSeparator();
617         menu.insertItem( "Arrange items in &grid", this, SLOT( arrangeItemsInGrid() ) );
618         menu.insertSeparator();
619         menu.insertItem( "Sort &ascending", this, SLOT( sortAscending() ) );
620         menu.insertItem( "Sort &descending", this, SLOT( sortDescending() ) );
621 
622         menu.setMouseTracking( TRUE );
623         menu.exec( QCursor::pos() );
624     } else { // on item
625         QPopupMenu menu( this );
626 
627         int RENAME_ITEM = menu.insertItem( "Rename Item" );
628         int REMOVE_ITEM = menu.insertItem( "Remove Item" );
629 
630         menu.setMouseTracking( TRUE );
631         int id = menu.exec( QCursor::pos() );
632 
633         if ( id == -1 )
634             return;
635 
636         if ( id == RENAME_ITEM && item->renameEnabled() ) {
637             item->rename();
638         } else if ( id == REMOVE_ITEM ) {
639             delete item;
640             QMessageBox::information( this, "Not implemented!", "Deleting files not implemented yet,\n"
641                                       "The item has only been removed from the view! " );
642         }
643     }
644 }
void QtFileIconView::sortAscending () [protected, slot]
Definition at line 580 of file qfileiconview.cpp.
Referenced by slotRightPressed().
581 {
582     sort( TRUE );
583 }
void QtFileIconView::sortDescending () [protected, slot]
Definition at line 585 of file qfileiconview.cpp.
Referenced by slotRightPressed().
586 {
587     sort( FALSE );
588 }
void QtFileIconView::startReadDir (int dirs) [signal]
Definition at line 253 of file qfileiconview.moc.cc.
Referenced by readDir().
254 {
255     activate_signal( staticMetaObject()->signalOffset() + 1, t0 );
256 }
void QtFileIconView::viewBottom () [protected, slot]
Definition at line 556 of file qfileiconview.cpp.
Referenced by slotRightPressed().
557 {
558     setItemTextPos( Bottom );
559 }
void QtFileIconView::viewLarge () [protected, slot]
Definition at line 546 of file qfileiconview.cpp.
References Large, and setViewMode().
Referenced by slotRightPressed().
547 {
548     setViewMode( Large );
549 }
ViewMode QtFileIconView::viewMode () const [inline]
Definition at line 71 of file qfileiconview.h.
References ViewMode, and vm.
71 { return vm; }
void QtFileIconView::viewRight () [protected, slot]
Definition at line 561 of file qfileiconview.cpp.
Referenced by slotRightPressed().
562 {
563     setItemTextPos( Right );
564 }
void QtFileIconView::viewSmall () [protected, slot]
Definition at line 551 of file qfileiconview.cpp.
References setViewMode(), and Small.
Referenced by slotRightPressed().
552 {
553     setViewMode( Small );
554 }
Member Data Documentation
FloderType QtFileIconView::flodertype [protected]
Definition at line 127 of file qfileiconview.h.
Referenced by readDir().
int QtFileIconView::newFolderNum [protected]
Definition at line 122 of file qfileiconview.h.
Referenced by newDirectory().
QtFileIconViewItem* QtFileIconView::openItem [protected]
Definition at line 126 of file qfileiconview.h.
Referenced by openFolder(), QtFileIconView(), setOpenItem(), and slotDropped().
QPixmap QtFileIconView::pix [protected]
Definition at line 124 of file qfileiconview.h.
QSize QtFileIconView::sz [protected]
Definition at line 123 of file qfileiconview.h.
QDir QtFileIconView::viewDir [protected]
Definition at line 121 of file qfileiconview.h.
Referenced by currentDir(), itemDoubleClicked(), newDirectory(), setDirectory(), and slotDropped().
ViewMode QtFileIconView::vm [protected]
Definition at line 125 of file qfileiconview.h.
Referenced by QtFileIconView(), setViewMode(), and viewMode().
The documentation for this class was generated from the following files:
qfileiconview.h
qfileiconview.moc.cc
qfileiconview.cpp