ImageDetial Class Reference
#include <imagedetial.h>
Detailed Description
Author: sonicat
Definition at line 28 of file imagedetial.h.
Public Slots
void slotShowFloder (KURL floder_file)
void AddImageToAlbum (KURL addimage)
void RemoveImageFromAlbum (KURL removeimage)
void ChangeMode (AlbumMode mode)
void slotNextImage ()
void slotPreviousImage ()
void slotPlayNStop ()
void slotModeChange (int)
void slotSetSwitchingTime (int time)
Public Member Functions
ImageDetial (QWidget *parent=0, const char *name=0)
~ImageDetial ()
void xSetup ()
void SlideShow ()
void DrawImage (QPixmap pix)
Public Attributes
KURL::List::ConstIterator it
KURL::List AlbumList
KURL::List FloderList
QPtrList< QPixmap > PixList
Constructor & Destructor Documentation
ImageDetial::ImageDetial (QWidget * parent = 0, const char * name = 0)
Definition at line 22 of file imagedetial.cpp.
23  : hdassAlbum(parent, name)
24 {
25 }
ImageDetial::~ImageDetial ()
Definition at line 28 of file imagedetial.cpp.
29 {
30 }
Member Function Documentation
void hdassAlbum::AddImageToAlbum (KURL addimage) [slot, inherited]
Definition at line 60 of file hdassalbum.cpp.
References hdassAlbum::AlbumList.
61 {
62    AlbumList<<addimage;
63 }
void hdassAlbum::ChangeMode (AlbumMode mode) [slot, inherited]
Definition at line 69 of file hdassalbum.cpp.
70 {
71 
72 }
void hdassAlbum::DrawImage (QPixmap pix) [inherited]
Definition at line 154 of file hdassalbum.cpp.
Referenced by hdassAlbum::slotNextImage(), hdassAlbum::slotPreviousImage(), slotShowFloder(), and hdassAlbum::xSetup().
155 {
156    
157    
158    int width ,height;
159    width=pix.width();
160    height=pix.height();
161    
162    QPixmap draw(QSize(800,540));
163    QPainter p(&draw);
164 
165    p.fillRect(0,0,800,540,Qt::black);
166    if(width<800&&height<540)
167    {
168        //DAVID draw image at center
169        p.drawPixmap((400-width/2),(270-height/2),pix);
170    }
171 
172    else
173    {
174         if(11*width>20*height)
175         {
176                 int newheight=(800*height/width);
177                 QImage rescale=pix.convertToImage().scale(800,newheight);
178                 p.drawImage(0,270-newheight/2,rescale);
179                 
180         } 
181         else
182         {
183                 int newwidth=(540*width/height);
184                 QImage rescale=pix.convertToImage().scale(newwidth,540);
185                 p.drawImage((400-newwidth/2),0,rescale);
186         }
187    }    
188    p.end();
189    setBackgroundPixmap(draw);
190 }
void hdassAlbum::RemoveImageFromAlbum (KURL removeimage) [slot, inherited]
Definition at line 65 of file hdassalbum.cpp.
References hdassAlbum::AlbumList.
66 {
67   AlbumList.remove(removeimage);
68 }
void hdassAlbum::SlideShow () [inherited]
Definition at line 148 of file hdassalbum.cpp.
References hdassAlbum::switchtime, and hdassAlbum::timer.
149 {
150      qWarning("hdassAlbum::SlideShow()!!");
151      timer->start(switchtime*1000,FALSE);
152 }
void hdassAlbum::slotModeChange (int) [slot, inherited]
Definition at line 73 of file hdassalbum.cpp.
74 {
75 
76 }
void hdassAlbum::slotNextImage () [slot, inherited]
Definition at line 117 of file hdassalbum.cpp.
References hdassAlbum::AlbumList, hdassAlbum::DrawImage(), and hdassAlbum::it.
Referenced by hdassAlbum::xSetup().
118 {
119         //DAVID Read Image
120         it++;
121         if(it!=AlbumList.end())
122         {
123                 KURL url((*it).url());
124                 QPixmap pix;
125                 pix.load(url.path());
126                 DrawImage(pix);
127         }
128 }
void hdassAlbum::slotPlayNStop () [slot, inherited]
Definition at line 130 of file hdassalbum.cpp.
References hdassAlbum::switchtime, and hdassAlbum::timer.
131 {
132         if(timer->isActive ())
133         {
134                 timer->stop();
135         }
136         else
137         {
138                 timer->start(switchtime*1000,FALSE);
139         }
140 }
void hdassAlbum::slotPreviousImage () [slot, inherited]
Definition at line 104 of file hdassalbum.cpp.
References hdassAlbum::AlbumList, hdassAlbum::DrawImage(), and hdassAlbum::it.
105 {
106         //DAVID Read Image
107         it--;
108         if(it!=AlbumList.end())
109         {
110                 KURL url((*it).url());
111                 QPixmap pix;
112                 pix.load(url.path());
113                 DrawImage(pix);
114         }
115 }
void hdassAlbum::slotSetSwitchingTime (int time) [slot, inherited]
Definition at line 143 of file hdassalbum.cpp.
References hdassAlbum::switchtime.
144 {
145   switchtime=time;
146 }
void ImageDetial::slotShowFloder (KURL floder_file) [slot]
Definition at line 31 of file imagedetial.cpp.
References hdassAlbum::DrawImage().
32 {
33    //DAVID Read All Files in the floder of  floder_file
34    
35    //DAVID Get the Floder path
36    qWarning(floder_file.directory());
37    QDir dir;
38    dir.setPath(floder_file.directory());
39    const QFileInfoList * files=dir.entryInfoList();
40    QFileInfoListIterator its( *files );
41    QFileInfo * fi;
42    //DAVID Add all file to FloderList
43    while( (fi=its.current())!=0 )
44    {
45      if(fi->extension()=="jpg")
46      {
47        qWarning(fi->filePath());
48        FloderList<<KURL(fi->filePath());
49      }
50      ++its;
51    }
52    it=FloderList.find(floder_file);
53    
54    KURL url((*it).url());
55                 QPixmap pix;
56                 pix.load(url.path());
57                 DrawImage(pix);
58 }
void hdassAlbum::xSetup () [inherited]
Definition at line 38 of file hdassalbum.cpp.
References hdassAlbum::AlbumListFileName, hdassAlbum::DrawImage(), hdassAlbum::ReadAlbumList(), hdassAlbum::slotNextImage(), hdassAlbum::switchtime, and hdassAlbum::timer.
Referenced by hdassAlbum::hdassAlbum().
39 {
40   //DAVID Read album file list 
41   AlbumListFileName="AlbumList.txt";
42   ReadAlbumList(AlbumListFileName);
43   
44  
45 
46   //DAVID Set the switching time
47   switchtime=3;
48   //DAVID Set the timer
49   timer =new QTimer(this);
50   connect(timer,SIGNAL(timeout()),this,SLOT(slotNextImage()));
51   
52   //DAVID Draw a pix first
53   KURL url((*it).url());
54   QPixmap pix;
55   pix.load(url.path());
56   DrawImage(pix);
57   timer->stop();
58   
59 }
Member Data Documentation
KURL::List hdassAlbum::AlbumList [inherited]
Definition at line 50 of file hdassalbum.h.
Referenced by hdassAlbum::AddImageToAlbum(), hdassAlbum::ReadAlbumList(), hdassAlbum::RemoveImageFromAlbum(), hdassAlbum::slotNextImage(), and hdassAlbum::slotPreviousImage().
KURL::List hdassAlbum::FloderList [inherited]
Definition at line 50 of file hdassalbum.h.
KURL::List::ConstIterator hdassAlbum::it [inherited]
Definition at line 49 of file hdassalbum.h.
Referenced by hdassAlbum::ReadAlbumList(), hdassAlbum::slotNextImage(), and hdassAlbum::slotPreviousImage().
QPtrList<QPixmap> hdassAlbum::PixList [inherited]
Definition at line 51 of file hdassalbum.h.
The documentation for this class was generated from the following files:
imagedetial.h
imagedetial.cpp