HDASS08 Class Reference
#include <hdass08.h>
Detailed Description
Application Main Window.
Author: sonicat <is87098@cis.nctu.edu.tw>
Version: 0.1
Definition at line 43 of file hdass08.h.
Public Slots
void slotShow ()
void slotKeyboardShow ()
void slotKeyboardHide ()
void slotKeyboardString (QString)
Signals
void signalMkdir (QString)
Public Member Functions
HDASS08 ()
void xSetup ()
virtual ~HDASS08 ()
Public Attributes
Function_Control_Area * ControlArea
FunctionBar * Bar
DisplayArea * Display
hdassplaylist * HDASS_PLAY_LIST
keyboard * HDASS_KEYBOARD
QString strKeyboardString
Private Attributes
QPixmap pixBackground
Constructor & Destructor Documentation
HDASS08::HDASS08 ()
Default Constructor
Definition at line 29 of file hdass08.cpp.
References xSetup().
30     : KMainWindow( 0, "HDASS08",WStyle_NoBorder | WStyle_Customize  )
31 {
32  //DAVID Setting BackGround pixmap
33   pixBackground.load("/home/sonicat/hdass08/skin-background.jpg");
34   setBackgroundPixmap(pixBackground);
35   xSetup();
36 }
HDASS08::~HDASS08 () [virtual]
Definition at line 38 of file hdass08.cpp.
39 {
40 }
Member Function Documentation
void HDASS08::signalMkdir (QString) [signal]
Definition at line 96 of file hdass08.moc.
Referenced by slotKeyboardHide(), and xSetup().
97 {
98     activate_signal( staticMetaObject()->signalOffset() + 0, t0 );
99 }
void HDASS08::slotKeyboardHide () [slot]
Definition at line 133 of file hdass08.cpp.
References HDASS_KEYBOARD, signalMkdir(), and strKeyboardString.
Referenced by xSetup().
134 {
135   
136   HDASS_KEYBOARD->hide();
137   //Display->setEnabled(true);
138   //ControlArea->setEnabled(true);
139  // Bar->setEnabled(true);
140   emit signalMkdir(strKeyboardString);
141 }
void HDASS08::slotKeyboardShow () [slot]
Definition at line 124 of file hdass08.cpp.
References HDASS_KEYBOARD.
Referenced by xSetup().
125 {
126    //Set Disable
127   
128    HDASS_KEYBOARD->show();
129    //Display->setEnabled(false);
130    //ControlArea->setEnabled(false);
131   // Bar->setEnabled(false);
132 }
void HDASS08::slotKeyboardString (QString) [slot]
Definition at line 142 of file hdass08.cpp.
References strKeyboardString.
Referenced by xSetup().
143 {
144   strKeyboardString=s;
145   qWarning(strKeyboardString);
146 }
void HDASS08::slotShow () [slot]
Definition at line 120 of file hdass08.cpp.
121 {
122     this->show();
123 }
void HDASS08::xSetup ()
Default Destructor
Definition at line 42 of file hdass08.cpp.
References DisplayArea::Album, Bar, FunctionBar::BarAC, FunctionBar::BarID, FunctionBar::BarInternet, FunctionBar::BarManagement, FunctionBar::BarPlayer, DisplayArea::Browser, ControlArea, Display, HDASS_ACTION_TYPE, HDASS_KEYBOARD, HDASS_PLAY_LIST, DisplayArea::IA, InfoArea::IABtnVolumeDown, InfoArea::IABtnVolumeUp, mediamanagement::imgdetial, mediamanagement::imgFIV, SubBarPlayer::m_player, DisplayArea::Media, mediamanagement::musicFIV, InfoArea::ReadList(), signalMkdir(), slotKeyboardHide(), slotKeyboardShow(), slotKeyboardString(), strKeyboardString, SubBarInternet::SubBarBtnInternet_Home, SubBarInternet::SubBarBtnInternet_Next, SubBarInternet::SubBarBtnInternet_Previous, SubBarAlbumClock::SubBarBtnNext, SubBarAlbumClock::SubBarBtnPlayNPause, and SubBarAlbumClock::SubBarBtnPrevious.
Referenced by HDASS08().
43 {
44   //DAVID Init PlayList Here
45   HDASS_PLAY_LIST=new hdassplaylist(this,"PlayList");
46   
47   //DAVID Show the Function Control Widget 
48   
49   Display =new DisplayArea(this,"DisplayArea");
50   Display->setGeometry(0,0,800,600);
51   Display->show();
52   
53   ControlArea=new Function_Control_Area(this,"ControlArea");
54   ControlArea->setGeometry(665,465,135,135);
55   ControlArea->show();
56   
57   
58   Bar=new FunctionBar(this,"FunctionBar");
59   Bar->setGeometry(0,520,665,80);
60   Bar->show();
61   
62   HDASS_KEYBOARD =new keyboard(this,"HDASS_KEYBOARD");
63   HDASS_KEYBOARD->move(100,100);
64   HDASS_KEYBOARD->hide();
65   strKeyboardString=QString();
66   /*
67 
68   */
69   QObject::connect(ControlArea,SIGNAL(signalChangeFunc(int )),Bar,SLOT(slotChangeFunctionSubBar(int )));
70   QObject::connect(ControlArea,SIGNAL(signalBackToManagement()),Display->Media,SLOT(slotBackToManagement()));
71   QObject::connect(Bar->BarAC,SIGNAL(signalAlbumClockModeChangeToDispalyArea(int )),Display,SLOT(slotDisplayModeChange(int )));
72   QObject::connect(Bar,SIGNAL(siganlChangeDisplayAreaMode(int)),Display,SLOT(slotDisplayModeChange(int )));
73   
74   //DAVID Handle the connection between Bar and Display Buttons
75   QObject::connect(Bar->BarInternet->SubBarBtnInternet_Next, SIGNAL(clicked()), Display->Browser, SLOT(handleNext()));
76   QObject::connect(Bar->BarInternet->SubBarBtnInternet_Previous, SIGNAL(clicked()), Display->Browser, SLOT(handlePrevious()));
77   QObject::connect(Bar->BarInternet->SubBarBtnInternet_Home, SIGNAL(clicked()), Display->Browser, SLOT(handleHome()));
78   
79   //DAVID Handle the connection betwwen Album Control Buttons and all theirs corresponding function
80   QObject::connect(Bar->BarAC->SubBarBtnPrevious,SIGNAL(pressed()),Display->Album,SLOT(slotPreviousImage()));
81   QObject::connect(Bar->BarAC->SubBarBtnNext,SIGNAL(pressed()),Display->Album,SLOT(slotNextImage()));
82   QObject::connect(Bar->BarAC->SubBarBtnPlayNPause,SIGNAL(pressed()),Display->Album,SLOT(slotPlayNStop()));
83   
84   //DAVID Handle the connection between  ImageDetail Control Buttons and their  corresopnding functions 
85   QObject::connect(Bar->BarID->SubBarBtnPrevious,SIGNAL(pressed()),Display->Media->imgdetial,SLOT(slotPreviousImage()));
86   QObject::connect(Bar->BarID->SubBarBtnNext,SIGNAL(pressed()),Display->Media->imgdetial,SLOT(slotNextImage()));
87   QObject::connect(Bar->BarID->SubBarBtnPlayNPause,SIGNAL(pressed()),Display->Media->imgdetial,SLOT(slotPlayNStop()));
88   
89   //DAVID Handle the connection between Volume Buttons and the Myplayer
90   QObject::connect(Display->IA->IABtnVolumeUp, SIGNAL(pressed()), Bar->BarPlayer->m_player, SLOT(increase_volume()));
91   QObject::connect(Display->IA->IABtnVolumeDown, SIGNAL(pressed()), Bar->BarPlayer->m_player, SLOT(decrease_volume()));
92   
93   QObject::connect(Display->IA,SIGNAL(signalReadList()),HDASS_PLAY_LIST,SLOT(slotPLRequest()));
94   QObject::connect(HDASS_PLAY_LIST,SIGNAL(signalPLSend(KURL::List )),Display->IA,SLOT(slotReadListFromPlayList(KURL::List )));
95   QObject::connect(Bar->BarPlayer,SIGNAL(signalRequestPL()),HDASS_PLAY_LIST,SLOT(slotPLRequest()));
96   QObject::connect(HDASS_PLAY_LIST,SIGNAL(signalPLSend(KURL::List )),Bar->BarPlayer,SLOT(insertMedia(KURL::List )));
97   
98   QObject::connect(Display->IA,SIGNAL(signalRemoveList(KURL::List, HDASS_ACTION_TYPE )),HDASS_PLAY_LIST,SLOT(slotReciveList(KURL::List, HDASS_ACTION_TYPE )));
99   QObject::connect(Display->Media->musicFIV,SIGNAL(signalAddFileToList(KURL::List, HDASS_ACTION_TYPE )),HDASS_PLAY_LIST,SLOT(slotReciveList(KURL::List, HDASS_ACTION_TYPE )));
100   
101   QObject::connect(Bar->BarManagement,SIGNAL(signalManagementModeChange(int )),Display->Media,SLOT(slotChangeMode(int )));
102   QObject::connect(Bar->BarManagement,SIGNAL(signalMkdir()),this,SLOT(slotKeyboardShow()));
103   QObject::connect(Bar->BarManagement,SIGNAL(singalPasteFUNC_MEDIAM()),Display->Media,SLOT(slotPaste()));
104   QObject::connect(Bar->BarManagement,SIGNAL(signalCutFUNC_MEDIAM()),Display->Media,SLOT(slotCut()));
105   QObject::connect(Bar->BarManagement,SIGNAL(signalDeleteItem()),Display->Media,SLOT(slotDeleteItem()));
106   QObject::connect(Display->Media->imgFIV,SIGNAL(signalShowTheDetialofImage(KURL )),Display->Album,SLOT(slotShowFloder(KURL )));
107   
108   QObject::connect(Display->Media,SIGNAL(signalImageDetial()),ControlArea,SLOT(slotShowImageDetial()));
109   QObject::connect(Display->IA,SIGNAL(signalPlayItem(QString)),Bar->BarPlayer->m_player,SLOT(play(QString)));
110   QObject::connect(Display->IA,SIGNAL(singalPlayItem()),Bar->BarPlayer,SLOT(slotClickFromPlayList()));
111   QObject::connect(Bar->BarPlayer->m_player,SIGNAL(trackMessage(int, int, QString, QString, QString )),Display->IA,SLOT(slotHadleSongInfo(int, int, QString, QString, QString )));
112   
113   QObject::connect(HDASS_KEYBOARD,SIGNAL(signalEnter()),this,SLOT(slotKeyboardHide()));
114   QObject::connect(HDASS_KEYBOARD,SIGNAL(signalString(QString )),this,SLOT(slotKeyboardString(QString )));
115   
116   QObject::connect(Display->Media,SIGNAL(signalShowKeyboard()),this,SLOT(slotKeyboardShow()));
117   QObject::connect(this,SIGNAL(signalMkdir(QString )),Display->Media,SLOT(slotMkdir(QString )));
118   Display->IA->ReadList();
119 }
Member Data Documentation
FunctionBar* HDASS08::Bar
Definition at line 58 of file hdass08.h.
Referenced by xSetup().
Function_Control_Area* HDASS08::ControlArea
Definition at line 57 of file hdass08.h.
Referenced by xSetup().
DisplayArea* HDASS08::Display
Definition at line 60 of file hdass08.h.
Referenced by xSetup().
keyboard* HDASS08::HDASS_KEYBOARD
Definition at line 62 of file hdass08.h.
Referenced by slotKeyboardHide(), slotKeyboardShow(), and xSetup().
hdassplaylist* HDASS08::HDASS_PLAY_LIST
Definition at line 61 of file hdass08.h.
Referenced by xSetup().
QPixmap HDASS08::pixBackground [private]
Definition at line 73 of file hdass08.h.
QString HDASS08::strKeyboardString
Definition at line 63 of file hdass08.h.
Referenced by slotKeyboardHide(), slotKeyboardString(), and xSetup().
The documentation for this class was generated from the following files:
hdass08.h
hdass08.moc
hdass08.cpp