Sonogram Class Reference
#include <sonogram.h>
Detailed Description
Author: Melchior FRANZ
Definition at line 25 of file sonogram.h.
Public Member Functions
Sonogram (QWidget *)
~Sonogram ()
void init ()
void analyze (const Scope &)
void transform (Scope &)
void demo ()
const QPixmap * background () const
const QPixmap * canvas () const
uint timeout () const
uint height () const
Protected Member Functions
QPixmap * canvas ()
void eraseCanvas ()
void paintEvent (QPaintEvent *)
void resizeEvent (QResizeEvent *)
void paletteChange (const class QPalette &)
void polish ()
void drawFrame ()
virtual void paused ()
void changeTimeout (uint newTimeout)
Protected Attributes
QTimer m_timer
uint m_timeout
uint m_height
FHT m_fht
Constructor & Destructor Documentation
Sonogram::Sonogram (QWidget *)
Definition at line 18 of file sonogram.cpp.
18                                   :
19         Analyzer::Base2D(parent, 16)
20 {
21 setBackgroundColor(QColor(255,255,255));
22 }
Sonogram::~Sonogram ()
Definition at line 25 of file sonogram.cpp.
26 {
27 }
Member Function Documentation
void Sonogram::analyze (const Scope &) [virtual]
Implements Analyzer::Base< QWidget > (p.).
Definition at line 36 of file sonogram.cpp.
References Analyzer::Base2D::canvas(), and Analyzer::Base< QWidget >::height().
Referenced by demo().
37 {
38         int x = width() - 1;
39         QColor c;
40         
41         QPainter p(canvas());
42 
43         bitBlt(canvas(), 0, 0, canvas(), 1, 0, x, height());
44         //canvas()->fill();
45         Scope::const_iterator it = s.begin();
46         for (int y = height() - 1; y && it < s.end(); it++) {
47                 if (*it < .005)
48                         c = backgroundColor();
49                 else if (*it < .05)
50                         c.setHsv(95, 255, 255 - int(*it * 4000.0));
51                 else if (*it < 1.0)
52                         c.setHsv(95 - int(*it * 90.0), 255, 255);
53                 else
54                         c = Qt::red;
55 
56                 p.setPen(c);
57                 p.drawPoint(x, y--);
58         }
59 }
const QPixmap* Analyzer::Base2D::background () const [inline, inherited]
Definition at line 75 of file analyzerbase.h.
References Analyzer::Base2D::m_background.
Referenced by Analyzer::Base2D::eraseCanvas().
75 { return &m_background; }
QPixmap* Analyzer::Base2D::canvas () [inline, protected, inherited]
Definition at line 86 of file analyzerbase.h.
References Analyzer::Base2D::m_canvas.
86 { return &m_canvas; }
const QPixmap* Analyzer::Base2D::canvas () const [inline, inherited]
Definition at line 76 of file analyzerbase.h.
References Analyzer::Base2D::m_canvas.
Referenced by analyze(), Analyzer::Base2D::draw(), Analyzer::Base2D::eraseCanvas(), and Analyzer::Base2D::paintEvent().
76 { return &m_canvas; }
void Analyzer::Base< QWidget >::changeTimeout (uint newTimeout) [inline, protected, inherited]
Definition at line 54 of file analyzerbase.h.
55     {
56         m_timer.changeInterval( newTimeout );
57         m_timeout = newTimeout;
58     }
void Sonogram::demo () [virtual]
Reimplemented from Analyzer::Base< QWidget > (p.).
Definition at line 73 of file sonogram.cpp.
References analyze(), and FHT::size().
74 {
75         analyze(Scope(m_fht.size(), 0));
76 }
void Analyzer::Base< QWidget >::drawFrame () [protected, inherited]
Referenced by Analyzer::Base2D::draw().
void Analyzer::Base2D::eraseCanvas () [inline, protected, inherited]
Definition at line 87 of file analyzerbase.h.
References Analyzer::Base2D::background(), and Analyzer::Base2D::canvas().
Referenced by init(), and Analyzer::Base2D::resizeEvent().
87 { bitBlt( canvas(), 0, 0, background() ); }
uint Analyzer::Base< QWidget >::height () const [inline, inherited]
Definition at line 43 of file analyzerbase.h.
Referenced by analyze().
43 { return m_height; }
void Sonogram::init () [virtual]
Reimplemented from Analyzer::Base2D (p.).
Definition at line 30 of file sonogram.cpp.
References Analyzer::Base2D::eraseCanvas().
31 {
32         eraseCanvas();
33 }
void Analyzer::Base2D::paintEvent (QPaintEvent *) [inline, protected, inherited]
Definition at line 89 of file analyzerbase.h.
References Analyzer::Base2D::canvas(), and Analyzer::Base2D::m_canvas.
89 { if( !m_canvas.isNull() ) bitBlt( this, 0, 0, canvas() ); }
void Analyzer::Base2D::paletteChange (const class QPalette &) [protected, inherited]
virtual void Analyzer::Base< QWidget >::paused () [protected, virtual, inherited]
void Analyzer::Base2D::polish () [protected, inherited]
Definition at line 159 of file analyzerbase.cpp.
References Analyzer::Base2D::init().
160 {
161     //TODO is there much point in this anymore?
162 
163     //we use polish for initialzing (instead of ctor)
164     //because we need to know the widget's final size
165     QWidget::polish();
166 
167     init(); //virtual
168 }
void Analyzer::Base2D::resizeEvent (QResizeEvent *) [protected, inherited]
Definition at line 171 of file analyzerbase.cpp.
References Analyzer::Base2D::eraseCanvas(), Analyzer::Base2D::m_background, and Analyzer::Base2D::m_canvas.
172 {
173     m_height = QWidget::height();
174     m_background.resize( size() );
175     m_canvas.resize( size() );
176 
177     #ifdef DRAW_GRID
178     QPainter p( &m_background );
179     p.setPen( QColor( 0x20, 0x20, 0x50 ) );
180 
181     for( uint x = 0, w = m_background.width(), h = m_background.height()-1;
182         x < w; x += 3 ) p.drawLine( x, 0, x, h );
183     for( uint y = 0, w = m_background.width()-1 , h = m_background.height();
184         y < h; y += 3 ) p.drawLine( 0, y, w, y );
185     #else
186     m_background.fill( backgroundColor() );
187     #endif
188 
189     eraseCanvas(); //this is necessary
190 
191     QWidget::resizeEvent( e );
192 }
uint Analyzer::Base< QWidget >::timeout () const [inline, inherited]
Definition at line 42 of file analyzerbase.h.
Referenced by Analyzer::Base2D::Base2D().
42 { return m_timeout; }
void Sonogram::transform (Scope &) [virtual]
Reimplemented from Analyzer::Base< QWidget > (p.).
Definition at line 62 of file sonogram.cpp.
References FHT::power(), and FHT::scale().
63 {
64         scope.resize( scope.size() / 2 );
65 
66         float *front = static_cast<float*>(&scope.front());
67 
68         m_fht.power(front);
69         m_fht.scale(front, 1.0 / 64);
70 }
Member Data Documentation
FHT Analyzer::Base< QWidget >::m_fht [protected, inherited]
Definition at line 67 of file analyzerbase.h.
uint Analyzer::Base< QWidget >::m_height [protected, inherited]
Definition at line 66 of file analyzerbase.h.
uint Analyzer::Base< QWidget >::m_timeout [protected, inherited]
Definition at line 65 of file analyzerbase.h.
QTimer Analyzer::Base< QWidget >::m_timer [protected, inherited]
Definition at line 64 of file analyzerbase.h.
The documentation for this class was generated from the following files:
sonogram.h
sonogram.cpp