Amarok::RawScope_skel Class Reference
#include <amarokarts.h>
Public Member Functions
RawScope_skel ()
std::string _interfaceName ()
bool _isCompatibleWith (const std::string &interfacename)
void _buildMethodTable ()
void dispatch (Arts::Buffer *request, Arts::Buffer *result, long methodID)
RawScope_base * _copy ()
virtual std::vector< std::string > _defaultPortsIn () const
virtual std::vector< std::string > _defaultPortsOut () const
void * _cast (unsigned long iid)
virtual long buffer ()=0
virtual void buffer (long newValue)=0
virtual std::vector< float > * scope ()=0
Static Public Member Functions
std::string _interfaceNameSkel ()
RawScope_base * _create (const std::string &subClass=`Amarok::RawScope`)
RawScope_base * _fromString (const std::string &objectref)
RawScope_base * _fromReference (Arts::ObjectReference ref, bool needcopy)
RawScope_base * _fromDynamicCast (const Arts::Object &object)
Static Public Attributes
unsigned long _IID = Arts::MCOPUtils::makeIID(`Amarok::RawScope`)
Protected Member Functions
void buffer_changed (long newValue)
Constructor & Destructor Documentation
Amarok::RawScope_skel::RawScope_skel ()
Definition at line 373 of file amarokarts.cc.
374 {
375 }
Member Function Documentation
void Amarok::RawScope_skel::_buildMethodTable ()
Definition at line 356 of file amarokarts.cc.
References _dispatch_Amarok_RawScope_00(), _dispatch_Amarok_RawScope_01(), and _dispatch_Amarok_RawScope_02().
357 {
358         Arts::Buffer m;
359         m.fromString(
360         "MethodTable:0000000673636f706500000000072a666c6f617400000000020000"
361         "0000000000000000000c5f6765745f62756666657200000000056c6f6e67000000"
362         "000200000000000000000000000c5f7365745f6275666665720000000005766f69"
363         "64000000000200000001000000056c6f6e6700000000096e657756616c75650000"
364         "00000000000000",
365                 "MethodTable"
366         );
367         _addMethod(_dispatch_Amarok_RawScope_00,this,Arts::MethodDef(m));
368         _addMethod(_dispatch_Amarok_RawScope_01,this,Arts::MethodDef(m));
369         _addMethod(_dispatch_Amarok_RawScope_02,this,Arts::MethodDef(m));
370         Arts::StereoEffect_skel::_buildMethodTable();
371 }
void * Amarok::RawScope_base::_cast (unsigned long iid) [inherited]
Definition at line 249 of file amarokarts.cc.
References Amarok::RawScope_base::_IID.
Referenced by Amarok::RawScope_base::_fromDynamicCast(), and Amarok::RawScope::_method_call().
250 {
251         if(iid == Amarok::RawScope_base::_IID) return (Amarok::RawScope_base *)this;
252         if(iid == Arts::StereoEffect_base::_IID) return (Arts::StereoEffect_base *)this;
253         if(iid == Arts::SynthModule_base::_IID) return (Arts::SynthModule_base *)this;
254         if(iid == Arts::Object_base::_IID) return (Arts::Object_base *)this;
255         return 0;
256 }
RawScope_base* Amarok::RawScope_base::_copy () [inline, inherited]
Definition at line 139 of file amarokarts.h.
Referenced by Amarok::RawScope_base::_fromDynamicCast().
139                                       {
140                 assert(_refCnt > 0);
141                 _refCnt++;
142                 return this;
143         }
Amarok::RawScope_base * Amarok::RawScope_base::_create (const std::string & subClass = `Amarok::RawScope`) [static, inherited]
Definition at line 182 of file amarokarts.cc.
References Amarok::RawScope_base::_IID.
Referenced by Amarok::RawScope::_Creator().
183 {
184         Arts::Object_skel *skel = Arts::ObjectManager::the()->create(subClass);
185         assert(skel);
186         Amarok::RawScope_base *castedObject = (Amarok::RawScope_base *)skel->_cast(Amarok::RawScope_base::_IID);
187         assert(castedObject);
188         return castedObject;
189 }
std::vector< std::string > Amarok::RawScope_base::_defaultPortsIn () const [virtual, inherited]
Definition at line 236 of file amarokarts.cc.
236                                                                 {
237         std::vector<std::string> ret;
238         ret.push_back("inleft");
239         ret.push_back("inright");
240         return ret;
241 }
std::vector< std::string > Amarok::RawScope_base::_defaultPortsOut () const [virtual, inherited]
Definition at line 242 of file amarokarts.cc.
242                                                                  {
243         std::vector<std::string> ret;
244         ret.push_back("outleft");
245         ret.push_back("outright");
246         return ret;
247 }
Amarok::RawScope_base * Amarok::RawScope_base::_fromDynamicCast (const Arts::Object & object) [static, inherited]
Definition at line 200 of file amarokarts.cc.
References Amarok::RawScope_base::_cast(), Amarok::RawScope_base::_copy(), Amarok::RawScope_base::_fromString(), and Amarok::RawScope_base::_IID.
201 {
202         if(object.isNull()) return 0;
203 
204         Amarok::RawScope_base *castedObject = (Amarok::RawScope_base *)object._base()->_cast(Amarok::RawScope_base::_IID);
205         if(castedObject) return castedObject->_copy();
206 
207         return _fromString(object._toString());
208 }
Amarok::RawScope_base * Amarok::RawScope_base::_fromReference (Arts::ObjectReference ref, bool needcopy) [static, inherited]
Definition at line 210 of file amarokarts.cc.
Referenced by Amarok::RawScope_base::_fromString().
211 {
212         Amarok::RawScope_base *result;
213         result = (Amarok::RawScope_base *)Arts::Dispatcher::the()->connectObjectLocal(r,"Amarok::RawScope");
214         if(result)
215         {
216                 if(!needcopy)
217                         result->_cancelCopyRemote();
218         }
219         else
220         {
221                 Arts::Connection *conn = Arts::Dispatcher::the()->connectObjectRemote(r);
222                 if(conn)
223                 {
224                         result = new Amarok::RawScope_stub(conn,r.objectID);
225                         if(needcopy) result->_copyRemote();
226                         result->_useRemote();
227                         if (!result->_isCompatibleWith("Amarok::RawScope")) {
228                                 result->_release();
229                                 return 0;
230                         }
231                 }
232         }
233         return result;
234 }
Amarok::RawScope_base * Amarok::RawScope_base::_fromString (const std::string & objectref) [static, inherited]
Definition at line 191 of file amarokarts.cc.
References Amarok::RawScope_base::_fromReference().
Referenced by Amarok::RawScope_base::_fromDynamicCast().
192 {
193         Arts::ObjectReference r;
194 
195         if(Arts::Dispatcher::the()->stringToObjectReference(r,objectref))
196                 return Amarok::RawScope_base::_fromReference(r,true);
197         return 0;
198 }
std::string Amarok::RawScope_skel::_interfaceName ()
Definition at line 316 of file amarokarts.cc.
317 {
318         return "Amarok::RawScope";
319 }
std::string Amarok::RawScope_skel::_interfaceNameSkel () [static]
Definition at line 330 of file amarokarts.cc.
331 {
332         return "Amarok::RawScope";
333 }
bool Amarok::RawScope_skel::_isCompatibleWith (const std::string & interfacename)
Definition at line 321 of file amarokarts.cc.
322 {
323         if (interfacename == "Amarok::RawScope") return true;
324         if (interfacename == "Arts::StereoEffect") return true;
325         if (interfacename == "Arts::SynthModule") return true;
326         if (interfacename == "Arts::Object") return true;
327         return false;
328 }
virtual void Amarok::RawScope_base::buffer (long newValue) [pure virtual, inherited]
Implemented in Amarok::RawScope_stub (p.).
virtual long Amarok::RawScope_base::buffer () [pure virtual, inherited]
Implemented in Amarok::RawScope_stub (p.).
Referenced by Amarok::RawScope::buffer().
void Amarok::RawScope_skel::buffer_changed (long newValue) [inline, protected]
Definition at line 170 of file amarokarts.h.
170                                                   {
171                 _emit_changed("buffer_changed",newValue);
172         }
void Amarok::RawScope_skel::dispatch (Arts::Buffer * request, Arts::Buffer * result, long methodID)
virtual std::vector<float>* Amarok::RawScope_base::scope () [pure virtual, inherited]
Implemented in Amarok::RawScope_stub (p.).
Referenced by Amarok::RawScope::scope().
Member Data Documentation
unsigned long Amarok::RawScope_base::_IID = Arts::MCOPUtils::makeIID(`Amarok::RawScope`) [static, inherited]
Definition at line 381 of file amarokarts.cc.
Referenced by Amarok::RawScope_base::_cast(), Amarok::RawScope_base::_create(), and Amarok::RawScope_base::_fromDynamicCast().
The documentation for this class was generated from the following files:
amarokarts.h
amarokarts.cc