Directory Class Reference
#include <dirview.h>
Public Member Functions
Directory (QListView *parent, const QString &filename)
Directory (Directory *parent, const QString &filename, const QString &col2)
Directory (Directory *parent, const QString &filename)
QString text (int column) const
QString fullName ()
void setOpen (bool)
void setup ()
const QPixmap * pixmap (int i) const
void setPixmap (QPixmap *p)
void Mkdir (QString s)
Private Attributes
QFile f
Directory * p
bool readable
bool showDirsOnly
QPixmap * pix
Constructor & Destructor Documentation
Directory::Directory (QListView * parent, const QString & filename)
Definition at line 114 of file dirview.cpp.
References fullName(), p, and readable.
Referenced by Mkdir(), and setOpen().
115     : QListViewItem( parent ), f(filename),
116       showDirsOnly( ( (DirectoryView*)parent )->showDirsOnly() ),
117       pix( 0 )
118 {
119     p = 0;// no parent Directory 
120     readable = QDir( fullName() ).isReadable();
121 
122 }
Directory::Directory (Directory * parent, const QString & filename, const QString & col2) [inline]
Definition at line 48 of file dirview.h.
49         : QListViewItem( parent, filename, col2 ), pix( 0 ) {}
Directory::Directory (Directory * parent, const QString & filename)
Definition at line 98 of file dirview.cpp.
References folderClosed, folderLocked, fullName(), p, readable, and setPixmap().
99     : QListViewItem( parent ), f(filename),
100       showDirsOnly( parent->showDirsOnly ),
101       pix( 0 )
102 {
103     
104     p = parent;
105     readable = QDir( fullName() ).isReadable();
106 
107     if ( !readable )
108         setPixmap( folderLocked );
109     else
110         setPixmap( folderClosed );
111 }
Member Function Documentation
QString Directory::fullName ()
Definition at line 199 of file dirview.cpp.
References f, and p.
Referenced by Directory(), Mkdir(), setOpen(), mediamanagement::slotDeleteItem(), and DirectoryView::slotFolderSelected().
200 {
201     QString s;
202     if ( p ) {
203         s = p->fullName();
204         s.append( f.name() );
205         s.append( "/" );
206     } else {
207         s = f.name();
208     }
209     return s;
210 }
void Directory::Mkdir (QString s)
Definition at line 222 of file dirview.cpp.
References Directory(), and fullName().
Referenced by mediamanagement::slotMkdir().
223 {
224         QDir currDir=QDir( fullName() );
225         qWarning(fullName());
226         //DAVID need modified
227         currDir.mkdir(s);
228         new Directory(this,s);
229 }
const QPixmap * Directory::pixmap (int i) const
Definition at line 135 of file dirview.cpp.
136 {
137     if ( i )
138         return 0;
139     return pix;
140 }
void Directory::setOpen (bool)
Definition at line 142 of file dirview.cpp.
References Directory(), fileNormal, folderClosed, folderOpen, fullName(), readable, FileItem::setPixmap(), setPixmap(), and showDirsOnly.
Referenced by mediamanagement::xSetup().
143 {
144     if ( o )
145         setPixmap( folderOpen );
146     else
147         setPixmap( folderClosed );
148 
149     if ( o && !childCount() ) 
150     {
151         QString s( fullName() );
152         QDir thisDir( s );
153         if ( !thisDir.isReadable() ) 
154         {
155             readable = FALSE;
156             setExpandable( FALSE );
157             return;
158         }
159 
160         listView()->setUpdatesEnabled( FALSE );
161         const QFileInfoList * files = thisDir.entryInfoList();
162         if ( files ) {
163             QFileInfoListIterator it( *files );
164             QFileInfo * fi;
165             while( (fi=it.current()) != 0 ) {
166                 ++it;
167                 if ( fi->fileName() == "." || fi->fileName() == ".." )
168                     ; // nothing
169                 else if ( fi->isSymLink() && !showDirsOnly ) {
170                     FileItem *item = new FileItem( this, fi->fileName(),
171                                                      "Symbolic Link" );
172                     item->setPixmap( fileNormal );
173                 }
174                 else if ( fi->isDir() )
175                 {
176                     (void)new Directory( this, fi->fileName() );
177                 }
178                 else if ( !showDirsOnly ) {
179                     FileItem *item
180                         = new FileItem( this, fi->fileName(),
181                                              fi->isFile()?"File":"Special" );
182                     item->setPixmap( fileNormal );
183                 }
184             }
185         }
186         listView()->setUpdatesEnabled( TRUE );
187     }
188     QListViewItem::setOpen( o );
189 }
void Directory::setPixmap (QPixmap * p)
Definition at line 125 of file dirview.cpp.
References setup().
Referenced by Directory(), and setOpen().
126 {
127     pix = px;
128     setup();
129     widthChanged( 0 );
130     invalidateHeight();
131     repaint();
132 }
void Directory::setup ()
Definition at line 192 of file dirview.cpp.
Referenced by setPixmap().
193 {
194     setExpandable( TRUE );
195     QListViewItem::setup();
196 }
QString Directory::text (int column) const
Definition at line 213 of file dirview.cpp.
References f, and readable.
214 {
215     if ( column == 0 )
216         return f.name();
217     else if ( readable )
218         return "Directory";
219     else
220         return "Unreadable Directory";
221 }
Member Data Documentation
QFile Directory::f [private]
Definition at line 66 of file dirview.h.
Referenced by fullName(), and text().
Directory* Directory::p [private]
Definition at line 67 of file dirview.h.
Referenced by Directory(), and fullName().
QPixmap* Directory::pix [private]
Definition at line 70 of file dirview.h.
bool Directory::readable [private]
Definition at line 68 of file dirview.h.
Referenced by Directory(), setOpen(), and text().
bool Directory::showDirsOnly [private]
Definition at line 69 of file dirview.h.
Referenced by setOpen().
The documentation for this class was generated from the following files:
dirview.h
dirview.cpp