MyBrowser Class Reference
#include <MyBrowser.h>
Public Slots
void handleHome ()
void handleRefresh ()
void handleNext ()
void handlePrevious ()
void handleURL (const KURL &, const KParts::URLArgs &)
void handleCloseconnect (bool)
Public Member Functions
MyBrowser (QWidget *parentWidget=0)
~MyBrowser ()
void urlSelected (const QString &url, int button, int state, const QString &_target, KParts::URLArgs args=KParts::URLArgs())
void saveHistory (const KURL &)
void removeHistory ()
void getFile (KURL &)
Public Attributes
KURL::List history
KURL::List::Iterator it_history
DownFile * getfile
KURL home
Constructor & Destructor Documentation
MyBrowser::MyBrowser (QWidget * parentWidget = 0)
Definition at line 28 of file MyBrowser.cpp.
References handleHome(), history, home, and it_history.
29 : KHTMLPart(parentWidget)
30 {
31     it_history = history.begin();
32     home = KURL("http://tw.yahoo.com");
33     #if TRACE 
34     kdDebug() << "init() -> "<< home << endl;    
35     #endif
36     handleHome();      
37 }
MyBrowser::~MyBrowser ()
Definition at line 40 of file MyBrowser.cpp.
41 {
42 
43 }
Member Function Documentation
void MyBrowser::getFile (KURL &)
Definition at line 84 of file MyBrowser.cpp.
References getfile, and handleCloseconnect().
Referenced by handleURL(), and urlSelected().
85 {
86 #if TRACE 
87 kdDebug()<< "getFile -> download a mp3 file "<< endl;
88 #endif
89     getfile = new DownFile(url);
90     connect(getfile,SIGNAL(Finished(bool)),this,SLOT(handleCloseconnect(bool)));
91 }
void MyBrowser::handleCloseconnect (bool) [slot]
Definition at line 157 of file MyBrowser.cpp.
References getfile.
Referenced by getFile().
158 {
159     delete getfile;
160     #if TRACE     
161 kdDebug() << "MyBrowser::handleCloseconnect -> Delete connection !!!!"<< endl;
162 #endif    
163 }
void MyBrowser::handleHome () [slot]
Definition at line 95 of file MyBrowser.cpp.
References home, and saveHistory().
Referenced by MyBrowser().
96 {
97     if(home.protocol()=="http")
98     {
99         openURL(home);
100         saveHistory(home);
101     }   
102     else kdDebug() << "=====================Home -> " << home.protocol() << endl;
103 }
void MyBrowser::handleNext () [slot]
Definition at line 105 of file MyBrowser.cpp.
References history, and it_history.
106 {
107 #if TRACE 
108 kdDebug() << "handleNext"<< endl;
109 #endif
110     if(it_history != history.end())
111     {
112         ++it_history;
113         openURL((*it_history).url());
114 
115     }   
116 }
void MyBrowser::handlePrevious () [slot]
Definition at line 118 of file MyBrowser.cpp.
References history, and it_history.
119 {
120 #if TRACE 
121 kdDebug() << "handlePrevious"<< endl;
122 #endif
123     if(it_history != history.begin())
124     {
125         --it_history;
126         openURL((*it_history).url());
127 
128     }   
129 }
void MyBrowser::handleRefresh () [slot]
Definition at line 131 of file MyBrowser.cpp.
132 {
133 #if TRACE 
134 kdDebug() << "handleRefresh"<< endl;
135 #endif    
136     openURL((*it_history).url());
137 }
void MyBrowser::handleURL (const KURL &, const KParts::URLArgs &) [slot]
Definition at line 139 of file MyBrowser.cpp.
References getFile(), removeHistory(), and saveHistory().
140 {
141 #if TRACE 
142 kdDebug() << "handleURL -> submit control"<< endl;
143 #endif
144     if(uurl.protocol()=="http")
145     {
146         removeHistory();
147         openURL(uurl);
148         saveHistory(uurl);
149     }   
150     else if(uurl.protocol()=="hdas")
151     {           
152         KURL url = uurl;
153         getFile(url);
154     }
155 }
void MyBrowser::removeHistory ()
Definition at line 75 of file MyBrowser.cpp.
References history, and it_history.
Referenced by handleURL(), and urlSelected().
76 {
77     if(it_history != history.end())
78     {
79         KURL::List::Iterator it_remove = history.end();
80         for(it_remove;it_remove!=it_history;it_remove--)history.remove((*it_remove).url());
81     }
82 }
void MyBrowser::saveHistory (const KURL &)
Definition at line 66 of file MyBrowser.cpp.
References history, and it_history.
Referenced by handleHome(), handleURL(), and urlSelected().
67 {
68 #if TRACE 
69 kdDebug() << "Saving History !!"<< endl;
70 #endif
71         history << url;      
72         ++it_history;
73 }
void MyBrowser::urlSelected (const QString & url, int button, int state, const QString & _target, KParts::URLArgs args = KParts::URLArgs())
Definition at line 45 of file MyBrowser.cpp.
References getFile(), removeHistory(), and saveHistory().
46 {
47      KURL cURL = completeURL(url);
48      #if TRACE 
49 kdDebug() << "urlSelect -> " << cURL << endl;     
50 #endif
51      if(cURL.protocol()=="http")
52      {
53         removeHistory();
54         openURL(cURL);
55         saveHistory(cURL);
56      }
57      else if(cURL.protocol()=="hdas")
58      {
59 #if TRACE      
60 kdDebug()<< "MyBrowser::urlSelected -> HDAS -> " << cURL << endl;
61 #endif
62         getFile(cURL);
63      }
64 }
Member Data Documentation
DownFile* MyBrowser::getfile
Definition at line 45 of file MyBrowser.h.
Referenced by getFile(), and handleCloseconnect().
KURL::List MyBrowser::history
Definition at line 43 of file MyBrowser.h.
Referenced by handleNext(), handlePrevious(), MyBrowser(), removeHistory(), and saveHistory().
KURL MyBrowser::home
Definition at line 46 of file MyBrowser.h.
Referenced by handleHome(), and MyBrowser().
KURL::List::Iterator MyBrowser::it_history
Definition at line 44 of file MyBrowser.h.
Referenced by handleNext(), handlePrevious(), MyBrowser(), removeHistory(), and saveHistory().
The documentation for this class was generated from the following files:
MyBrowser.h
MyBrowser.cpp