Amarok::RawScope_stub Class Reference
#include <amarokarts.h>
Public Member Functions
RawScope_stub (Arts::Connection *connection, long objectID)
long buffer ()
void buffer (long newValue)
std::vector< float > * scope ()
RawScope_base * _copy ()
virtual std::vector< std::string > _defaultPortsIn () const
virtual std::vector< std::string > _defaultPortsOut () const
void * _cast (unsigned long iid)
Static Public Member Functions
RawScope_base * _create (const std::string &subClass=`Amarok::RawScope`)
RawScope_base * _fromString (const std::string &objectref)
RawScope_base * _fromReference (Arts::ObjectReference ref, bool needcopy)
RawScope_base * _fromDynamicCast (const Arts::Object &object)
Static Public Attributes
unsigned long _IID = Arts::MCOPUtils::makeIID(`Amarok::RawScope`)
Protected Member Functions
RawScope_stub ()
Constructor & Destructor Documentation
Amarok::RawScope_stub::RawScope_stub () [protected]
Definition at line 258 of file amarokarts.cc.
259 {
260         // constructor for subclasses (don't use directly)
261 }
Amarok::RawScope_stub::RawScope_stub (Arts::Connection * connection, long objectID)
Definition at line 263 of file amarokarts.cc.
264         : Arts::Object_stub(connection, objectID)
265 {
266         // constructor to create a stub for an object
267 }
Member Function Documentation
void * Amarok::RawScope_base::_cast (unsigned long iid) [inherited]
Definition at line 249 of file amarokarts.cc.
References Amarok::RawScope_base::_IID.
Referenced by Amarok::RawScope_base::_fromDynamicCast(), and Amarok::RawScope::_method_call().
250 {
251         if(iid == Amarok::RawScope_base::_IID) return (Amarok::RawScope_base *)this;
252         if(iid == Arts::StereoEffect_base::_IID) return (Arts::StereoEffect_base *)this;
253         if(iid == Arts::SynthModule_base::_IID) return (Arts::SynthModule_base *)this;
254         if(iid == Arts::Object_base::_IID) return (Arts::Object_base *)this;
255         return 0;
256 }
RawScope_base* Amarok::RawScope_base::_copy () [inline, inherited]
Definition at line 139 of file amarokarts.h.
Referenced by Amarok::RawScope_base::_fromDynamicCast().
139                                       {
140                 assert(_refCnt > 0);
141                 _refCnt++;
142                 return this;
143         }
Amarok::RawScope_base * Amarok::RawScope_base::_create (const std::string & subClass = `Amarok::RawScope`) [static, inherited]
Definition at line 182 of file amarokarts.cc.
References Amarok::RawScope_base::_IID.
Referenced by Amarok::RawScope::_Creator().
183 {
184         Arts::Object_skel *skel = Arts::ObjectManager::the()->create(subClass);
185         assert(skel);
186         Amarok::RawScope_base *castedObject = (Amarok::RawScope_base *)skel->_cast(Amarok::RawScope_base::_IID);
187         assert(castedObject);
188         return castedObject;
189 }
std::vector< std::string > Amarok::RawScope_base::_defaultPortsIn () const [virtual, inherited]
Definition at line 236 of file amarokarts.cc.
236                                                                 {
237         std::vector<std::string> ret;
238         ret.push_back("inleft");
239         ret.push_back("inright");
240         return ret;
241 }
std::vector< std::string > Amarok::RawScope_base::_defaultPortsOut () const [virtual, inherited]
Definition at line 242 of file amarokarts.cc.
242                                                                  {
243         std::vector<std::string> ret;
244         ret.push_back("outleft");
245         ret.push_back("outright");
246         return ret;
247 }
Amarok::RawScope_base * Amarok::RawScope_base::_fromDynamicCast (const Arts::Object & object) [static, inherited]
Definition at line 200 of file amarokarts.cc.
References Amarok::RawScope_base::_cast(), Amarok::RawScope_base::_copy(), Amarok::RawScope_base::_fromString(), and Amarok::RawScope_base::_IID.
201 {
202         if(object.isNull()) return 0;
203 
204         Amarok::RawScope_base *castedObject = (Amarok::RawScope_base *)object._base()->_cast(Amarok::RawScope_base::_IID);
205         if(castedObject) return castedObject->_copy();
206 
207         return _fromString(object._toString());
208 }
Amarok::RawScope_base * Amarok::RawScope_base::_fromReference (Arts::ObjectReference ref, bool needcopy) [static, inherited]
Definition at line 210 of file amarokarts.cc.
Referenced by Amarok::RawScope_base::_fromString().
211 {
212         Amarok::RawScope_base *result;
213         result = (Amarok::RawScope_base *)Arts::Dispatcher::the()->connectObjectLocal(r,"Amarok::RawScope");
214         if(result)
215         {
216                 if(!needcopy)
217                         result->_cancelCopyRemote();
218         }
219         else
220         {
221                 Arts::Connection *conn = Arts::Dispatcher::the()->connectObjectRemote(r);
222                 if(conn)
223                 {
224                         result = new Amarok::RawScope_stub(conn,r.objectID);
225                         if(needcopy) result->_copyRemote();
226                         result->_useRemote();
227                         if (!result->_isCompatibleWith("Amarok::RawScope")) {
228                                 result->_release();
229                                 return 0;
230                         }
231                 }
232         }
233         return result;
234 }
Amarok::RawScope_base * Amarok::RawScope_base::_fromString (const std::string & objectref) [static, inherited]
Definition at line 191 of file amarokarts.cc.
References Amarok::RawScope_base::_fromReference().
Referenced by Amarok::RawScope_base::_fromDynamicCast().
192 {
193         Arts::ObjectReference r;
194 
195         if(Arts::Dispatcher::the()->stringToObjectReference(r,objectref))
196                 return Amarok::RawScope_base::_fromReference(r,true);
197         return 0;
198 }
void Amarok::RawScope_stub::buffer (long newValue) [virtual]
Implements Amarok::RawScope_base (p.).
Definition at line 302 of file amarokarts.cc.
303 {
304         long methodID = _lookupMethodFast("method:0000000c5f7365745f6275666665720000000005766f6964000000000200000001000000056c6f6e6700000000096e657756616c7565000000000000000000");
305         long requestID;
306         Arts::Buffer *request, *result;
307         request = Arts::Dispatcher::the()->createRequest(requestID,_objectID,methodID);
308         request->writeLong(newValue);
309         request->patchLength();
310         _connection->qSendBuffer(request);
311 
312         result = Arts::Dispatcher::the()->waitForResult(requestID,_connection);
313         if(result) delete result;
314 }
long Amarok::RawScope_stub::buffer () [virtual]
Implements Amarok::RawScope_base (p.).
Definition at line 286 of file amarokarts.cc.
287 {
288         long methodID = _lookupMethodFast("method:0000000c5f6765745f62756666657200000000056c6f6e6700000000020000000000000000");
289         long requestID;
290         Arts::Buffer *request, *result;
291         request = Arts::Dispatcher::the()->createRequest(requestID,_objectID,methodID);
292         request->patchLength();
293         _connection->qSendBuffer(request);
294 
295         result = Arts::Dispatcher::the()->waitForResult(requestID,_connection);
296         if(!result) return 0; // error occurred
297         long returnCode = result->readLong();
298         delete result;
299         return returnCode;
300 }
std::vector< float > * Amarok::RawScope_stub::scope () [virtual]
Implements Amarok::RawScope_base (p.).
Definition at line 269 of file amarokarts.cc.
270 {
271         long methodID = _lookupMethodFast("method:0000000673636f706500000000072a666c6f617400000000020000000000000000");
272         long requestID;
273         Arts::Buffer *request, *result;
274         request = Arts::Dispatcher::the()->createRequest(requestID,_objectID,methodID);
275         request->patchLength();
276         _connection->qSendBuffer(request);
277 
278         result = Arts::Dispatcher::the()->waitForResult(requestID,_connection);
279         std::vector<float> *_returnCode = new std::vector<float>;
280         if(!result) return _returnCode; // error occurred
281         result->readFloatSeq(*_returnCode);
282         delete result;
283         return _returnCode;
284 }
Member Data Documentation
unsigned long Amarok::RawScope_base::_IID = Arts::MCOPUtils::makeIID(`Amarok::RawScope`) [static, inherited]
Definition at line 381 of file amarokarts.cc.
Referenced by Amarok::RawScope_base::_cast(), Amarok::RawScope_base::_create(), and Amarok::RawScope_base::_fromDynamicCast().
The documentation for this class was generated from the following files:
amarokarts.h
amarokarts.cc