EngineController Class Reference
#include <enginecontroller.h>
Detailed Description
This class captures amaroK specific behaviour for some common features. Accessing the engine directly is perfectly legal but on your own risk. TODO: Hide proxy stuff!
Definition at line 33 of file enginecontroller.h.
Public Slots
void previous ()
void next ()
void play (const MetaBundle &bundle)
void play (bool test, const MetaBundle &bundle)
void pause ()
void stop ()
void playPause ()
int increaseVolume (int ticks=100/25)
int decreaseVolume (int ticks=100/25)
int setVolume (int percent)
Signals
void orderNext ()
void orderPrevious ()
void orderCurrent ()
void TrackPosition (int)
Public Member Functions
virtual ~EngineController ()
void attach (EngineObserver *observer)
void detach (EngineObserver *observer)
Static Public Member Functions
EngineController * instance ()
EngineBase * engine ()
void setEngine (EngineBase *)
Protected Member Functions
void stateChangedNotify (EngineBase::EngineState)
void newMetaDataNotify (const MetaBundle &, bool)
void volumeChangedNotify (int)
void trackPositionChangedNotify (long)
Private Slots
void slotMainTimer ()
void newMetaData (const MetaBundle &)
Private Member Functions
EngineController ()
Private Attributes
EngineBase * m_pEngine
MetaBundle m_bundle
bool m_proxyError
QTimer * m_pMainTimer
long m_delayTime
Static Private Attributes
const int MAIN_TIMER = 150
Constructor & Destructor Documentation
EngineController::~EngineController () [virtual]
Definition at line 77 of file enginecontroller.cpp.
78 {
79 kdDebug() << k_funcinfo << endl;
80 }
EngineController::EngineController () [private]
Definition at line 61 of file enginecontroller.cpp.
References dummyEngine, m_pEngine, m_pMainTimer, MAIN_TIMER, EngineBase::setVolume(), and slotMainTimer().
66     : m_pEngine( &dummyEngine ) //FIXME better would be a static member or something
67     , m_proxyError( false )
68     , m_pMainTimer( new QTimer( this ) )
69     , m_delayTime( 0 )
70 {
71     m_pEngine->setVolume( AmarokConfig::masterVolume() );
72 
73     connect( m_pMainTimer, SIGNAL( timeout() ), this, SLOT( slotMainTimer() ) );
74     m_pMainTimer->start( MAIN_TIMER );
75 }
Member Function Documentation
void EngineSubject::attach (EngineObserver * observer) [inherited]
Definition at line 92 of file engineobserver.cpp.
References EngineSubject::Observers.
93 {
94     if( !observer || Observers.find( observer ) != -1 )
95         return;
96     Observers.append( observer );
97 }
int EngineController::decreaseVolume (int ticks = 100/25) [slot]
Definition at line 180 of file enginecontroller.cpp.
References m_pEngine, setVolume(), and EngineBase::volume().
181 {
182     return setVolume( m_pEngine->volume() - ticks );
183 }
void EngineSubject::detach (EngineObserver * observer) [inherited]
Definition at line 100 of file engineobserver.cpp.
References EngineSubject::Observers.
101 {
102     if( Observers.find( observer ) != -1 ) Observers.remove();
103 }
EngineBase* EngineController::engine () [inline, static]
Definition at line 43 of file enginecontroller.h.
References instance(), and m_pEngine.
Referenced by Analyzer::Base< W >::drawFrame(), and Myplayer::handleSlider().
43 { return instance()->m_pEngine; }
int EngineController::increaseVolume (int ticks = 100/25) [slot]
Definition at line 173 of file enginecontroller.cpp.
References m_pEngine, setVolume(), and EngineBase::volume().
174 {
175     return setVolume( m_pEngine->volume() + ticks );
176 }
EngineController * EngineController::instance () [static]
Definition at line 53 of file enginecontroller.cpp.
Referenced by engine(), Myplayer::handleNext(), Myplayer::handlePrevious(), Myplayer::Myplayer(), Myplayer::next(), Myplayer::pause(), Myplayer::play(), play(), Myplayer::previous(), setEngine(), Myplayer::setVolume(), and Myplayer::stop().
54 {
55     //will only be instantiated the first time this function is called
56     static EngineController Instance;
57 
58     return &Instance;
59 }
void EngineController::newMetaData (const MetaBundle &) [inline, private, slot]
Definition at line 211 of file enginecontroller.cpp.
212 {
213 /*    m_bundle = bundle;
214 
215 //    newMetaDataNotify( m_bundle, false  );*/
216 }
void EngineSubject::newMetaDataNotify (const MetaBundle &, bool) [protected, inherited]
Definition at line 56 of file engineobserver.cpp.
References EngineObserver::engineNewMetaData(), and EngineSubject::Observers.
Referenced by play().
57 {
58     QPtrListIterator<EngineObserver> it( Observers );
59     EngineObserver *observer;
60     while( ( observer = it.current() ) != 0 )
61     {
62         ++it;
63         observer->engineNewMetaData( bundle, trackChanged );
64     }
65 }
void EngineController::next () [slot]
Definition at line 90 of file enginecontroller.cpp.
References orderNext().
Referenced by Myplayer::next(), and slotMainTimer().
91 {
92     kdDebug() << "EngineController->next" << endl;
93     emit orderNext();
94 }
void EngineController::orderCurrent () [signal]
Definition at line 161 of file enginecontroller.moc.
162 {
163     activate_signal( staticMetaObject()->signalOffset() + 2 );
164 }
void EngineController::orderNext () [signal]
Definition at line 149 of file enginecontroller.moc.
Referenced by next().
150 {
151     activate_signal( staticMetaObject()->signalOffset() + 0 );
152 }
void EngineController::orderPrevious () [signal]
Definition at line 155 of file enginecontroller.moc.
Referenced by previous().
156 {
157     activate_signal( staticMetaObject()->signalOffset() + 1 );
158 }
void EngineController::pause () [slot]
Definition at line 150 of file enginecontroller.cpp.
References EngineBase::loaded(), m_pEngine, EngineBase::pause(), EngineBase::play(), EngineBase::state(), and EngineSubject::stateChangedNotify().
Referenced by Myplayer::pause(), and play().
151 {
152     if ( m_pEngine->loaded() )
153     {
154         if ( m_pEngine->state() == EngineBase::Paused )
155             m_pEngine->play();
156         else
157             m_pEngine->pause();
158         stateChangedNotify( m_pEngine->state() );
159     }
160 }
void EngineController::play (bool test, const MetaBundle & bundle) [slot]
Definition at line 136 of file enginecontroller.cpp.
References m_pEngine, EngineSubject::newMetaDataNotify(), EngineBase::play(), EngineSubject::stateChangedNotify(), and MetaBundle::url().
137 {
138         const KURL &trackurl = bundle.url();    
139         kdDebug() << "[enginecontroller]SoundSystem: " << bundle.url() << endl;
140         m_pEngine->play( trackurl );    
141 
142    //  kdDebug() << "[engine] It's Playing: " << bundle.track() << endl;
143 
144     stateChangedNotify( EngineBase::Playing );
145     newMetaDataNotify( bundle, true /* track change */ );
146       
147 }
void EngineController::play (const MetaBundle & bundle) [slot]
Definition at line 111 of file enginecontroller.cpp.
References instance(), m_pEngine, pause(), EngineBase::play(), EngineBase::state(), and EngineSubject::stateChangedNotify().
Referenced by Myplayer::handleNext(), Myplayer::handlePrevious(), and Myplayer::play().
112 {
113 qWarning("[EngineController::play]");
114     if ( m_pEngine->state() == EngineBase::Paused )
115     {
116         m_pEngine->play();
117         stateChangedNotify( EngineBase::Playing );
118 qWarning("Pause->play");        
119     }
120     else if( m_pEngine->state() == EngineBase::Playing )
121     {
122         EngineController::instance()->pause();  
123         
124 qWarning("play->pause");        
125     }
126     else 
127     {
128          EngineController::instance()->play(true,bundle);
129         
130 qWarning("other situation");    
131     }   
132 //        emit orderCurrent(); // keep currenttrack to avoid signal?
133 }
void EngineController::playPause () [slot]
Definition at line 98 of file enginecontroller.cpp.
99 {
100 /*    //this is used by the TrayIcon and PlayPauseAction
101 
102     if( m_pEngine->state() == EngineBase::Playing )
103     {
104         pause();
105     }
106     else play();*/
107 }
void EngineController::previous () [slot]
Definition at line 83 of file enginecontroller.cpp.
References orderPrevious().
Referenced by Myplayer::previous().
84 {
85     emit orderPrevious();
86 }
void EngineController::setEngine (EngineBase *) [static]
Definition at line 186 of file enginecontroller.cpp.
References instance(), and m_pEngine.
Referenced by Myplayer::Myplayer().
187 {
188     instance()->m_pEngine = engine;
189     kdDebug() << "[enginecontroller]engine: " << engine << endl;
190     //NOTE many engine properties are only set in applySettings
191 }
int EngineController::setVolume (int percent) [slot]
Definition at line 193 of file enginecontroller.cpp.
References m_pEngine, AmarokConfig::setMasterVolume(), EngineBase::setVolume(), EngineBase::volume(), and EngineSubject::volumeChangedNotify().
Referenced by decreaseVolume(), increaseVolume(), and Myplayer::setVolume().
194 {
195     if( percent < 0 ) percent = 0; //can't make uint as all signals use int and slot has to match
196     if( percent > 100 ) percent = 100;
197 
198     if( percent != m_pEngine->volume() )
199     {
200         AmarokConfig::setMasterVolume( percent );
201 
202         m_pEngine->setVolume( percent );
203 
204         volumeChangedNotify( percent );
205     }
206 
207     return m_pEngine->volume();
208 }
void EngineController::slotMainTimer () [inline, private, slot]
Definition at line 220 of file enginecontroller.cpp.
References AmarokConfig::crossfade(), AmarokConfig::crossfadeLength(), EngineBase::isStream(), MetaBundle::length(), m_bundle, m_delayTime, m_pEngine, MAIN_TIMER, next(), EngineBase::position(), EngineBase::state(), EngineBase::supportsXFade(), AmarokConfig::trackDelayLength(), TrackPosition(), and EngineSubject::trackPositionChangedNotify().
Referenced by EngineController().
221 {
222     if( m_pEngine->state() == EngineBase::Empty ) return;
223     const uint position = m_pEngine->position();
224     const uint length   = m_bundle.length() * 1000;
225 
226     trackPositionChangedNotify( position );
227 
228     // check if track has ended or is broken
229     if ( m_pEngine->state() == EngineBase::Idle )
230     {
231         kdDebug() << k_funcinfo << "Idle detected. Skipping track.\n";
232 
233         if ( AmarokConfig::trackDelayLength() > 0 ) //this can occur syncronously to XFade and not be fatal
234         {
235             //delay before start of next track, without freezing the app
236             m_delayTime += MAIN_TIMER;
237             if ( m_delayTime >= AmarokConfig::trackDelayLength() )
238             {
239                 m_delayTime = 0;
240                 next();
241             }
242         }
243         else
244             next();
245     }
246     // Crossfading
247     else if ( ( AmarokConfig::crossfade() ) &&
248               ( m_pEngine->supportsXFade() ) &&
249               ( !m_pEngine->isStream() ) &&
250               ( length ) &&
251               ( length - position < (uint)AmarokConfig::crossfadeLength() )  )
252     {
253         kdDebug() << k_funcinfo << "Crossfading to next track.\n";
254         next();
255     }
256     emit TrackPosition(position/1000);
257 }
void EngineSubject::stateChangedNotify (EngineBase::EngineState) [protected, inherited]
Definition at line 44 of file engineobserver.cpp.
References EngineObserver::engineStateChanged(), and EngineSubject::Observers.
Referenced by pause(), play(), and stop().
45 {
46     QPtrListIterator<EngineObserver> it( Observers );
47     EngineObserver *observer;
48     while( ( observer = it.current() ) != 0 )
49     {
50         ++it;
51         observer->engineStateChanged( state );
52     }
53 }
void EngineController::stop () [slot]
Definition at line 164 of file enginecontroller.cpp.
References m_pEngine, EngineBase::state(), EngineSubject::stateChangedNotify(), and EngineBase::stop().
Referenced by Myplayer::handleNext(), Myplayer::next(), Myplayer::play(), Myplayer::previous(), and Myplayer::stop().
165 {
166 /*    m_bundle = MetaBundle(); */
167     m_pEngine->stop();
168     stateChangedNotify( m_pEngine->state() );  
169 }
void EngineController::TrackPosition (int) [signal]
Definition at line 167 of file enginecontroller.moc.
Referenced by slotMainTimer().
168 {
169     activate_signal( staticMetaObject()->signalOffset() + 3, t0 );
170 }
void EngineSubject::trackPositionChangedNotify (long) [protected, inherited]
Definition at line 80 of file engineobserver.cpp.
References EngineObserver::engineTrackPositionChanged(), and EngineSubject::Observers.
Referenced by slotMainTimer().
81 {
82     QPtrListIterator<EngineObserver> it( Observers );
83     EngineObserver *observer;
84     while( ( observer = it.current() ) != 0 )
85     {
86         ++it;
87         observer->engineTrackPositionChanged( position );
88     }
89 }
void EngineSubject::volumeChangedNotify (int) [protected, inherited]
Definition at line 68 of file engineobserver.cpp.
References EngineObserver::engineVolumeChanged(), and EngineSubject::Observers.
Referenced by setVolume().
69 {
70     QPtrListIterator<EngineObserver> it( Observers );
71     EngineObserver *observer;
72     while( ( observer = it.current() ) != 0 )
73     {
74         ++it;
75         observer->engineVolumeChanged( percent );
76     }
77 }
Member Data Documentation
MetaBundle EngineController::m_bundle [private]
Definition at line 81 of file enginecontroller.h.
Referenced by slotMainTimer().
long EngineController::m_delayTime [private]
Definition at line 84 of file enginecontroller.h.
Referenced by slotMainTimer().
EngineBase* EngineController::m_pEngine [private]
Definition at line 80 of file enginecontroller.h.
Referenced by decreaseVolume(), engine(), EngineController(), increaseVolume(), pause(), play(), setEngine(), setVolume(), slotMainTimer(), and stop().
QTimer* EngineController::m_pMainTimer [private]
Definition at line 83 of file enginecontroller.h.
Referenced by EngineController().
bool EngineController::m_proxyError [private]
Definition at line 82 of file enginecontroller.h.
const int EngineController::MAIN_TIMER = 150 [static, private]
Definition at line 78 of file enginecontroller.h.
Referenced by EngineController(), and slotMainTimer().
The documentation for this class was generated from the following files:
enginecontroller.h
enginecontroller.moc
enginecontroller.cpp