FHT Class Reference
#include <fht.h>
Detailed Description
Implementation of the Hartley Transform after Bracewell's discrete algorithm. The algorithm is subject to US patent No. 4,646,256 (1987) but was put into public domain by the Board of Trustees of Stanford University in 1994 and is now freely available[1].
[1] Computer in Physics, Vol. 9, No. 4, Jul/Aug 1995 pp 373-379
Definition at line 32 of file fht.h.
Public Member Functions
FHT (int)
~FHT ()
int sizeExp () const
int size () const
float * copy (float *, float *)
float * clear (float *)
void scale (float *, float)
void ewma (float *d, float *s, float w)
void pattern (float *d, bool rect)
void logSpectrum (float *out, float *p)
void semiLogSpectrum (float *)
void spectrum (float *)
void power (float *)
void power2 (float *)
void transform8 (float *)
void transform (float *)
Private Member Functions
void makeCasTable ()
void _transform (float *, int, int)
Private Attributes
int m_exp2
int m_num
float * m_buf
float * m_tab
int * m_log
Constructor & Destructor Documentation
FHT::FHT (int)
Prepare transform for data sets with $2^n$ numbers, whereby $n$ should be at least 3. Values of more than 3 need a trigonometry table.
See also: makeCasTable()(p.)
Definition at line 26 of file fht.cpp.
References m_buf, m_exp2, m_num, m_tab, and makeCasTable().
26               :
27         m_buf(0),
28         m_tab(0),
29         m_log(0)
30 {
31         if (n < 3) {
32                 m_num = 0;
33                 m_exp2 = -1;
34                 return;
35         }
36         m_exp2 = n;
37         m_num = 1 << n;
38         if (n > 3) {
39                 m_buf = new float[m_num];
40                 m_tab = new float[m_num * 2];
41                 makeCasTable();
42         }
43 }
FHT::~FHT ()
Definition at line 46 of file fht.cpp.
References m_buf, m_log, and m_tab.
47 {
48         delete[] m_buf;
49         delete[] m_tab;
50         delete[] m_log;
51 }
Member Function Documentation
void FHT::_transform (float *, int, int) [private]
Recursive in-place Hartley transform. For internal use only!
Definition at line 221 of file fht.cpp.
References m_buf, m_num, m_tab, and transform8().
Referenced by power2(), and transform().
222 {
223         if (n == 8) {
224                 transform8(p + k);
225                 return;
226         }
227 
228         int i, j, ndiv2 = n / 2;
229         float a, *t1, *t2, *t3, *t4, *ptab, *pp;
230 
231         for (i = 0, t1 = m_buf, t2 = m_buf + ndiv2, pp = &p[k]; i < ndiv2; i++)
232                 *t1++ = *pp++, *t2++ = *pp++;
233 
234         memcpy(p + k, m_buf, sizeof(float) * n);
235 
236         _transform(p, ndiv2, k);
237         _transform(p, ndiv2, k + ndiv2);
238 
239         j = m_num / ndiv2 - 1;
240         t1 = m_buf;
241         t2 = t1 + ndiv2;
242         t3 = p + k + ndiv2;
243         ptab = m_tab;
244         pp = p + k;
245 
246         a = *ptab++ * *t3++;
247         a += *ptab * *pp;
248         ptab += j;
249 
250         *t1++ = *pp + a;
251         *t2++ = *pp++ - a;
252 
253         for (i = 1, t4 = p + k + n; i < ndiv2; i++, ptab += j) {
254                 a = *ptab++ * *t3++;
255                 a += *ptab * *--t4;
256 
257                 *t1++ = *pp + a;
258                 *t2++ = *pp++ - a;
259         }
260         memcpy(p + k, m_buf, sizeof(float) * n);
261 }
float * FHT::clear (float *)
Definition at line 76 of file fht.cpp.
References m_num.
77 {
78         return (float *)memset(d, 0, m_num * sizeof(float));
79 }
float * FHT::copy (float *, float *)
Definition at line 70 of file fht.cpp.
References m_num.
Referenced by Analyzer::Base< W >::transform().
71 {
72         return (float *)memcpy(d, s, m_num * sizeof(float));
73 }
void FHT::ewma (float * d, float * s, float w)
Exponentially Weighted Moving Average (EWMA) filter.
Parameters:
d is the filtered data.
s is fresh input.
w is the weighting factor.
Definition at line 89 of file fht.cpp.
References m_num.
90 {
91         for (int i = 0; i < (m_num / 2); i++, d++, s++)
92                 *d = *d * w + *s * (1 - w);
93 }
void FHT::logSpectrum (float * out, float * p)
Logarithmic audio spectrum. Maps semi-logarithmic spectrum to logarithmic frequency scale, interpolates missing values. A logarithmic index map is calculated at the first run only.
Parameters:
p is the input array.
out is the spectrum.
Definition at line 116 of file fht.cpp.
References m_log, m_num, and semiLogSpectrum().
Referenced by Analyzer::Base< W >::transform().
117 {
118         int n = m_num / 2, i, j, k, *r;
119         if (!m_log) {
120                 m_log = new int[n];
121                 float f = n / log10(n);
122                 for (i = 0, r = m_log; i < n; i++, r++) {
123                         j = int(rint(log10(i + 1.0) * f));
124                         *r = j >= n ? n - 1 : j;
125                 }
126         }
127         semiLogSpectrum(p);
128         *out++ = *p = *p / 100;
129         for (k = i = 1, r = m_log; i < n; i++) {
130                 j = *r++;
131                 if (i == j)
132                         *out++ = p[i];
133                 else {
134                         float base = p[k - 1];
135                         float step = (p[j] - base) / (j - (k - 1));
136                         for (float corr = 0; k <= j; k++, corr += step)
137                                 *out++ = base + corr;
138                 }
139         }
140 }
void FHT::makeCasTable () [private]
Create a table of CAS (cosine and sine) values. Has only to be done in the constructor and saves from calculating the same values over and over while transforming.
Definition at line 54 of file fht.cpp.
References m_num, and m_tab.
Referenced by FHT().
55 {
56         float d, *costab, *sintab;
57         int ul, ndiv2 = m_num / 2;
58 
59         for (costab = m_tab, sintab = m_tab + m_num / 2 + 1, ul = 0; ul < m_num; ul++) {
60                 d = M_PI * ul / ndiv2;
61                 *costab = *sintab = cos(d);
62 
63                 costab += 2, sintab += 2;
64                 if (sintab > m_tab + m_num * 2)
65                         sintab = m_tab + 1;
66         }
67 }
void FHT::pattern (float * d, bool rect)
Test routine to create wobbling sine or rectangle wave.
Parameters:
d destination vector.
rect rectangle if true, sine otherwise.
Definition at line 97 of file fht.cpp.
References m_num, and sind().
98 {
99         static float f = 1.0;
100         static float h = 0.1;
101         int i;
102         for (i = 0; i < 3 * m_num / 4; i++, p++) {
103                 float o = 360.0 * i / m_num;
104                 *p = sind(f * o);
105                 if (rect)
106                         *p = *p < 0 ? -1.0 : 1.0;
107         }
108         for (; i < m_num; i++)
109                 *p++ = 0.0;
110         if (f > m_num / 2.0 || f < .05)
111                 h = -h;
112         f += h;
113 }
void FHT::power (float *)
Calculates a mathematically correct FFT power spectrum. If further scaling is applied later, use power2 instead and factor the 0.5 in the final scaling factor.
See also: FHT::power2()(p.)
Definition at line 162 of file fht.cpp.
References m_num, and power2().
Referenced by Sonogram::transform().
163 {
164         power2(p);
165         for (int i = 0; i < (m_num / 2); i++)
166                 *p++ *= .5;
167 }
void FHT::power2 (float *)
Calculates an FFT power spectrum with doubled values as a result. The values need to be multiplied by 0.5 to be exact. Note that you only get $2^{n-1}$ power values for a data set of $2^n$ input values.
See also: FHT::power()(p.)
Definition at line 170 of file fht.cpp.
References _transform(), and m_num.
Referenced by power(), semiLogSpectrum(), and spectrum().
171 {
172         int i;
173         float *q;
174         _transform(p, m_num, 0);
175 
176         *p = (*p * *p), *p += *p, p++;
177 
178         for (i = 1, q = p + m_num - 2; i < (m_num / 2); i++, --q)
179                 *p++ = (*p * *p) + (*q * *q);
180 }
void FHT::scale (float *, float)
Definition at line 82 of file fht.cpp.
References m_num.
Referenced by Sonogram::transform(), and Analyzer::Base< W >::transform().
83 {
84         for (int i = 0; i < (m_num / 2); i++)
85                 *p++ *= d;
86 }
void FHT::semiLogSpectrum (float *)
Semi-logarithmic audio spectrum.
Definition at line 143 of file fht.cpp.
References m_num, and power2().
Referenced by logSpectrum().
144 {
145         float e;
146         power2(p);
147         for (int i = 0; i < (m_num / 2); i++, p++) {
148                 e = 10.0 * log10(sqrt(*p * .5));
149                 *p = e < 0 ? 0 : e;
150         }
151 }
int FHT::size () const [inline]
Definition at line 62 of file fht.h.
References m_num.
Referenced by Sonogram::demo(), and Analyzer::Base< W >::transform().
62 { return m_num; }
int FHT::sizeExp () const [inline]
Definition at line 61 of file fht.h.
References m_exp2.
61 { return m_exp2; }
void FHT::spectrum (float *)
Fourier spectrum.
Definition at line 154 of file fht.cpp.
References m_num, and power2().
155 {
156         power2(p);
157         for (int i = 0; i < (m_num / 2); i++, p++)
158                 *p = (float)sqrt(*p * .5);
159 }
void FHT::transform (float *)
Definition at line 183 of file fht.cpp.
References _transform(), m_num, and transform8().
184 {
185         if (m_num == 8)
186                 transform8(p);
187         else
188                 _transform(p, m_num, 0);
189 }
void FHT::transform8 (float *)
Discrete Hartley transform of data sets with 8 values.
Definition at line 192 of file fht.cpp.
Referenced by _transform(), and transform().
193 {
194         float a, b, c, d, e, f, g, h, b_f2, d_h2;
195         float a_c_eg, a_ce_g, ac_e_g, aceg, b_df_h, bdfh;
196 
197         a = *p++, b = *p++, c = *p++, d = *p++;
198         e = *p++, f = *p++, g = *p++, h = *p;
199         b_f2 = (b - f) * M_SQRT2;
200         d_h2 = (d - h) * M_SQRT2;
201 
202         a_c_eg = a - c - e + g;
203         a_ce_g = a - c + e - g;
204         ac_e_g = a + c - e - g;
205         aceg = a + c + e + g;
206 
207         b_df_h = b - d + f - h;
208         bdfh = b + d + f + h;
209 
210         *p = a_c_eg - d_h2;
211         *--p = a_ce_g - b_df_h;
212         *--p = ac_e_g - b_f2;
213         *--p = aceg - bdfh;
214         *--p = a_c_eg + d_h2;
215         *--p = a_ce_g + b_df_h;
216         *--p = ac_e_g + b_f2;
217         *--p = aceg + bdfh;
218 }
Member Data Documentation
float* FHT::m_buf [private]
Definition at line 36 of file fht.h.
Referenced by _transform(), FHT(), and ~FHT().
int FHT::m_exp2 [private]
Definition at line 34 of file fht.h.
Referenced by FHT(), and sizeExp().
int* FHT::m_log [private]
Definition at line 38 of file fht.h.
Referenced by logSpectrum(), and ~FHT().
int FHT::m_num [private]
Definition at line 35 of file fht.h.
Referenced by _transform(), clear(), copy(), ewma(), FHT(), logSpectrum(), makeCasTable(), pattern(), power(), power2(), scale(), semiLogSpectrum(), size(), spectrum(), and transform().
float* FHT::m_tab [private]
Definition at line 37 of file fht.h.
Referenced by _transform(), FHT(), makeCasTable(), and ~FHT().
The documentation for this class was generated from the following files:
fht.h
fht.cpp