Function_Control_Area Class Reference
#include <function_control_area.h>
Detailed Description
Author: sonicat
Definition at line 31 of file function_control_area.h.
Public Slots
void slotProcessChangeFunc ()
void slotChangeButton (int)
void slotImageDetial ()
void slotShowImageDetial ()
Signals
void signalChangeFunc (int)
void signalBackToManagement ()
Public Member Functions
Function_Control_Area (QWidget *parent=0, const char *name=0)
void xSetup ()
~Function_Control_Area ()
Public Attributes
SkinButton * fun_btn_internet
SkinButton * fun_btn_player
SkinButton * fun_btn_management
SkinButton * fun_btn_albumclock
SkinButton * fun_btn_setting
SkinButton * fun_btn_close
SkinButton * fun_btn_imagedetial
Private Attributes
QPixmap * btnGraphic [14]
QPixmap pixBackground
Constructor & Destructor Documentation
Function_Control_Area::Function_Control_Area (QWidget * parent = 0, const char * name = 0)
Definition at line 22 of file function_control_area.cpp.
References xSetup().
23  : QWidget(parent, name)
24 {
25         xSetup();
26 }
Function_Control_Area::~Function_Control_Area ()
Definition at line 29 of file function_control_area.cpp.
30 {
31 }
Member Function Documentation
void Function_Control_Area::signalBackToManagement () [signal]
Definition at line 104 of file function_control_area.moc.
Referenced by slotImageDetial().
105 {
106     activate_signal( staticMetaObject()->signalOffset() + 1 );
107 }
void Function_Control_Area::signalChangeFunc (int) [signal]
Definition at line 98 of file function_control_area.moc.
Referenced by slotImageDetial(), slotProcessChangeFunc(), slotShowImageDetial(), and xSetup().
99 {
100     activate_signal( staticMetaObject()->signalOffset() + 0, t0 );
101 }
void Function_Control_Area::slotChangeButton (int) [slot]
Definition at line 118 of file function_control_area.cpp.
References em_albumclock, em_close, em_imagedetial, em_internet, em_management, em_player, em_setting, fun_btn_albumclock, fun_btn_close, fun_btn_imagedetial, fun_btn_internet, fun_btn_management, fun_btn_player, and fun_btn_setting.
Referenced by slotImageDetial(), slotProcessChangeFunc(), slotShowImageDetial(), and xSetup().
119 {
120    if(v==em_internet)
121    {
122      fun_btn_internet->show();
123      fun_btn_player->hide();
124      fun_btn_management->hide();
125      fun_btn_albumclock->hide();
126      fun_btn_setting->hide();
127      fun_btn_close->hide();
128      fun_btn_imagedetial->hide();
129    }
130    else if(v==em_player)
131    {
132      fun_btn_internet->hide();
133      fun_btn_player->show();
134      fun_btn_management->hide();
135      fun_btn_albumclock->hide();
136      fun_btn_setting->hide();
137      fun_btn_close->hide();
138      fun_btn_imagedetial->hide();
139    }
140    else if(v==em_management)
141    {
142      fun_btn_internet->hide();
143      fun_btn_player->hide();
144      fun_btn_management->show();
145      fun_btn_albumclock->hide();
146      fun_btn_setting->hide();
147      fun_btn_close->hide();
148      fun_btn_imagedetial->hide();
149    }
150    else if(v==em_albumclock)
151    {
152      fun_btn_internet->hide();
153      fun_btn_player->hide();
154      fun_btn_management->hide();
155      fun_btn_albumclock->show();
156      fun_btn_setting->hide();
157      fun_btn_close->hide();
158      fun_btn_imagedetial->hide();
159    }
160    else if(v==em_setting)
161    {
162      fun_btn_internet->hide();
163      fun_btn_player->hide();
164      fun_btn_management->hide();
165      fun_btn_albumclock->hide();
166      fun_btn_setting->show();
167      fun_btn_close->hide();
168      fun_btn_imagedetial->hide();
169    }
170    else if(v==em_close)
171    {
172      fun_btn_internet->hide();
173      fun_btn_player->hide();
174      fun_btn_management->hide();
175      fun_btn_albumclock->hide();
176      fun_btn_setting->hide();
177      fun_btn_close->show();
178      fun_btn_imagedetial->hide();
179    }
180    else if(v==em_imagedetial)
181    {
182     fun_btn_internet->hide();
183      fun_btn_player->hide();
184      fun_btn_management->hide();
185      fun_btn_albumclock->hide();
186      fun_btn_setting->hide();
187      fun_btn_close->hide();
188      fun_btn_imagedetial->show();
189    }
190 }
void Function_Control_Area::slotImageDetial () [slot]
Definition at line 192 of file function_control_area.cpp.
References em_management, GlobalSetting, HDASSGlobalSetting::intHDASS_FUNCTION_STATE, signalBackToManagement(), signalChangeFunc(), and slotChangeButton().
Referenced by xSetup().
193 {
194       //Back to em_management state
195       GlobalSetting.intHDASS_FUNCTION_STATE=em_management;
196       slotChangeButton(GlobalSetting.intHDASS_FUNCTION_STATE);
197       emit signalChangeFunc(GlobalSetting.intHDASS_FUNCTION_STATE);
198       emit signalBackToManagement();
199 }
void Function_Control_Area::slotProcessChangeFunc () [slot]
Definition at line 108 of file function_control_area.cpp.
References GlobalSetting, HDASSGlobalSetting::intHDASS_FUNCTION_STATE, signalChangeFunc(), and slotChangeButton().
Referenced by xSetup().
109 {
110   //DAVID Process To Next Function
111   GlobalSetting.intHDASS_FUNCTION_STATE++;
112   GlobalSetting.intHDASS_FUNCTION_STATE%=6;
113   //qWarning("FunctionState::%d\n",GlobalSetting.intHDASS_FUNCTION_STATE);
114   slotChangeButton(GlobalSetting.intHDASS_FUNCTION_STATE);
115   emit signalChangeFunc(GlobalSetting.intHDASS_FUNCTION_STATE);
116 }
void Function_Control_Area::slotShowImageDetial () [slot]
Definition at line 201 of file function_control_area.cpp.
References em_imagedetial, GlobalSetting, HDASSGlobalSetting::intHDASS_FUNCTION_STATE, signalChangeFunc(), and slotChangeButton().
202 {
203       GlobalSetting.intHDASS_FUNCTION_STATE=em_imagedetial;
204       slotChangeButton(GlobalSetting.intHDASS_FUNCTION_STATE);
205       emit signalChangeFunc(GlobalSetting.intHDASS_FUNCTION_STATE);
206 }
void Function_Control_Area::xSetup ()
Definition at line 33 of file function_control_area.cpp.
References btnGraphic, fun_btn_albumclock, fun_btn_close, fun_btn_imagedetial, fun_btn_internet, fun_btn_management, fun_btn_player, fun_btn_setting, GlobalSetting, HDASSGlobalSetting::intHDASS_FUNCTION_STATE, pixBackground, SkinButton::setPixmaps(), signalChangeFunc(), slotChangeButton(), slotImageDetial(), and slotProcessChangeFunc().
Referenced by Function_Control_Area().
34 {
35    QBitmap mask=QBitmap("/root/kde_application/hdass08/skin/function_control_masking.png");
36    setMask(mask);
37    //DAVID Setup Background;
38    pixBackground.load("/root/kde_application/hdass08/skin/FunctionAreaBackground.png");
39    setBackgroundPixmap(pixBackground);
40    //InitButton Graphic
41    btnGraphic[0]=new QPixmap("/root/kde_application/hdass08/skin/skin-function-button-internet.png");
42    btnGraphic[1]=new QPixmap("/root/kde_application/hdass08/skin/skin-function-button-internet-active.png");
43    btnGraphic[2]=new QPixmap("/root/kde_application/hdass08/skin/skin-function-button-player.png");
44    btnGraphic[3]=new QPixmap("/root/kde_application/hdass08/skin/skin-function-button-player-active.png");
45    btnGraphic[4]=new QPixmap("/root/kde_application/hdass08/skin/skin-function-button-management.png");
46    btnGraphic[5]=new QPixmap("/root/kde_application/hdass08/skin/skin-function-button-management-active.png");
47    btnGraphic[6]=new QPixmap("/root/kde_application/hdass08/skin/skin-function-button-albumclock.png");
48    btnGraphic[7]=new QPixmap("/root/kde_application/hdass08/skin/skin-function-button-albumclock-active.png");
49    btnGraphic[8]=new QPixmap("/root/kde_application/hdass08/skin/skin-function-button-setting.png");
50    btnGraphic[9]=new QPixmap("/root/kde_application/hdass08/skin/skin-function-button-setting-active.png");
51    btnGraphic[10]=new QPixmap("/root/kde_application/hdass08/skin/skin-function-button-close.png");
52    btnGraphic[11]=new QPixmap("/root/kde_application/hdass08/skin/skin-function-button-close-active.png");
53    btnGraphic[12]=new QPixmap("/root/kde_application/hdass08/skin/skin-function-button-imagedetial.png");
54    btnGraphic[13]=new QPixmap("/root/kde_application/hdass08/skin/skin-function-button-imagedetial-active.png");
55    
56    //Init Skinbutton
57    fun_btn_internet             =new SkinButton(this);
58    fun_btn_player              =new SkinButton(this);
59    fun_btn_management     =new SkinButton(this);
60    fun_btn_albumclock       =new SkinButton(this);
61    fun_btn_setting             =new SkinButton(this);
62    fun_btn_close               =new SkinButton(this);
63    fun_btn_imagedetial      =new SkinButton(this);
64    
65    fun_btn_internet->setPixmaps(btnGraphic[0],btnGraphic[1]);
66    fun_btn_internet->setGeometry(0,0,135,135);
67    fun_btn_internet->show();
68    
69    fun_btn_player->setPixmaps(btnGraphic[2],btnGraphic[3]);
70    fun_btn_player->setGeometry(0,0,135,135);
71    fun_btn_player->hide();
72    
73    fun_btn_management->setPixmaps(btnGraphic[4],btnGraphic[5]);
74    fun_btn_management->setGeometry(0,0,135,135);
75    fun_btn_management->hide();
76    
77    fun_btn_albumclock->setPixmaps(btnGraphic[6],btnGraphic[7]);
78    fun_btn_albumclock->setGeometry(0,0,135,135);
79    fun_btn_albumclock->hide();
80    
81    fun_btn_setting->setPixmaps(btnGraphic[8],btnGraphic[9]);
82    fun_btn_setting->setGeometry(0,0,135,135);
83    fun_btn_setting->hide();
84    
85    fun_btn_close->setPixmaps(btnGraphic[10],btnGraphic[11]);
86    fun_btn_close->setGeometry(0,0,135,135);
87    fun_btn_close->hide();
88    
89    fun_btn_imagedetial->setPixmaps(btnGraphic[12],btnGraphic[13]);
90    fun_btn_imagedetial->setGeometry(0,0,135,135);
91    fun_btn_imagedetial->hide();
92    
93    
94    
95    connect(fun_btn_internet,SIGNAL(released()),this,SLOT(slotProcessChangeFunc()));
96     connect(fun_btn_player,SIGNAL(released()),this,SLOT(slotProcessChangeFunc()));
97      connect(fun_btn_management,SIGNAL(released()),this,SLOT(slotProcessChangeFunc()));
98       connect(fun_btn_albumclock,SIGNAL(released()),this,SLOT(slotProcessChangeFunc()));
99        connect(fun_btn_setting,SIGNAL(released()),this,SLOT(slotProcessChangeFunc()));
100         connect(fun_btn_close,SIGNAL(released()),this,SLOT(slotProcessChangeFunc()));
101         connect(fun_btn_imagedetial,SIGNAL(released()),this,SLOT(slotImageDetial()));
102       //DAVID Set the Function Control Area State
103       
104       slotChangeButton(GlobalSetting.intHDASS_FUNCTION_STATE);
105       emit signalChangeFunc(GlobalSetting.intHDASS_FUNCTION_STATE);
106 }
Member Data Documentation
QPixmap* Function_Control_Area::btnGraphic[14] [private]
Definition at line 49 of file function_control_area.h.
Referenced by xSetup().
SkinButton * Function_Control_Area::fun_btn_albumclock
Definition at line 39 of file function_control_area.h.
Referenced by slotChangeButton(), and xSetup().
SkinButton * Function_Control_Area::fun_btn_close
Definition at line 39 of file function_control_area.h.
Referenced by slotChangeButton(), and xSetup().
SkinButton * Function_Control_Area::fun_btn_imagedetial
Definition at line 39 of file function_control_area.h.
Referenced by slotChangeButton(), and xSetup().
SkinButton* Function_Control_Area::fun_btn_internet
Definition at line 39 of file function_control_area.h.
Referenced by slotChangeButton(), and xSetup().
SkinButton * Function_Control_Area::fun_btn_management
Definition at line 39 of file function_control_area.h.
Referenced by slotChangeButton(), and xSetup().
SkinButton * Function_Control_Area::fun_btn_player
Definition at line 39 of file function_control_area.h.
Referenced by slotChangeButton(), and xSetup().
SkinButton * Function_Control_Area::fun_btn_setting
Definition at line 39 of file function_control_area.h.
Referenced by slotChangeButton(), and xSetup().
QPixmap Function_Control_Area::pixBackground [private]
Definition at line 50 of file function_control_area.h.
Referenced by xSetup().
The documentation for this class was generated from the following files:
function_control_area.h
function_control_area.moc
function_control_area.cpp