InfoArea Class Reference
#include <infoarea.h>
Detailed Description
Author: sonicat
Definition at line 38 of file infoarea.h.
Public Slots
void slotReadListFromPlayList (KURL::List playlist)
void ReadList ()
void slotDeleteItems ()
void slotDoubleClicked (QListViewItem *item)
void slotHadleSongInfo (int, int, QString, QString, QString)
Signals
void signalReadList ()
void signalRemoveList (KURL::List removelist, HDASS_ACTION_TYPE action)
void signalPlayItem (QString FileName)
void singalPlayItem ()
Public Member Functions
InfoArea (QWidget *parent=0, const char *name=0)
void xSetup ()
~InfoArea ()
Public Attributes
SkinButton * IABtnVolumeUp
SkinButton * IABtnVolumeDown
SkinButton * IABtnPlayListDelete
QWidget * m_pAnalyzer
QListView * PlayList
KURL::List curr_list
Private Member Functions
void InitPlayList ()
void InitSongInfo ()
void ShowSongInfo (int m_length, int m_bitrate, QString m_title, QString m_artist, QString m_album)
Private Attributes
QPixmap pixBackground
QPixmap * BtnGraphic [6]
QLabel * Artist
QLabel * Album
QLabel * Length
QLabel * Year
QLabel * Title
QLabel * BitRate
Constructor & Destructor Documentation
InfoArea::InfoArea (QWidget * parent = 0, const char * name = 0)
Definition at line 26 of file infoarea.cpp.
References xSetup().
27  : QWidget(parent, name)
28 {
29   xSetup();
30 }
InfoArea::~InfoArea ()
Definition at line 33 of file infoarea.cpp.
34 {
35 }
Member Function Documentation
void InfoArea::InitPlayList () [private]
Definition at line 77 of file infoarea.cpp.
References InitSongInfo(), PlayList, ReadList(), and slotDoubleClicked().
Referenced by xSetup().
78 {
79   PlayList=new QListView(this);
80   PlayList->addColumn( "Items" );
81   PlayList->setColumnWidth(0,316);
82   PlayList->setRootIsDecorated( TRUE );
83   PlayList->setGeometry(35,60,316,420);
84   
85   QFont f( "Helvetica", 12, QFont::Bold );
86   PlayList->setFont( f );
87   
88   PlayList->show();
89   connect(PlayList,SIGNAL(doubleClicked ( QListViewItem * )),this,SLOT(slotDoubleClicked(QListViewItem* )));
90   ReadList();
91   InitSongInfo();
92   
93 }
void InfoArea::InitSongInfo () [private]
Definition at line 141 of file infoarea.cpp.
References Artist, BitRate, and Title.
Referenced by InitPlayList().
142 {
143    Artist=new QLabel(this);
144    Artist->setPaletteBackgroundColor(QColor(255,255,255));
145    Artist->hide();
146    
147    Album=new QLabel(this);
148    Album->setPaletteBackgroundColor(QColor(255,255,255));
149    Album->hide();
150    
151    BitRate=new QLabel(this);
152    BitRate->setPaletteBackgroundColor(QColor(255,255,255));
153    BitRate->hide();
154    
155    Title=new QLabel(this);
156    Title->setPaletteBackgroundColor(QColor(255,255,255));
157    Title->hide();
158    
159    
160    Artist->move(420,210);
161    Album->move(420,240);
162    BitRate->move(420,270);
163    Title->move(580,270);
164    
165    QFont f( "Helvetica", 14, QFont::Bold );
166    
167    Artist->setFont( f );
168    Album->setFont( f );
169    Title->setFont( f );
170    BitRate->setFont( f );
171    
172 } 
void InfoArea::ReadList () [slot]
Definition at line 112 of file infoarea.cpp.
References signalReadList().
Referenced by InitPlayList(), and HDASS08::xSetup().
113 {
114       emit signalReadList();
115 }
void InfoArea::ShowSongInfo (int m_length, int m_bitrate, QString m_title, QString m_artist, QString m_album) [private]
Definition at line 173 of file infoarea.cpp.
174 {
175 
176 }
void InfoArea::signalPlayItem (QString FileName) [signal]
Definition at line 141 of file infoarea.moc.
Referenced by slotDoubleClicked().
142 {
143     activate_signal( staticMetaObject()->signalOffset() + 2, t0 );
144 }
void InfoArea::signalReadList () [signal]
Definition at line 118 of file infoarea.moc.
Referenced by ReadList().
119 {
120     activate_signal( staticMetaObject()->signalOffset() + 0 );
121 }
void InfoArea::signalRemoveList (KURL::List removelist, HDASS_ACTION_TYPE action) [signal]
Definition at line 127 of file infoarea.moc.
Referenced by slotDeleteItems().
128 {
129     if ( signalsBlocked() )
130         return;
131     QConnectionList *clist = receivers( staticMetaObject()->signalOffset() + 1 );
132     if ( !clist )
133         return;
134     QUObject o[3];
135     static_QUType_ptr.set(o+1,&t0);
136     static_QUType_ptr.set(o+2,&t1);
137     activate_signal( clist, o );
138 }
void InfoArea::singalPlayItem () [signal]
Definition at line 147 of file infoarea.moc.
Referenced by slotDoubleClicked().
148 {
149     activate_signal( staticMetaObject()->signalOffset() + 3 );
150 }
void InfoArea::slotDeleteItems () [slot]
Definition at line 116 of file infoarea.cpp.
References curr_list, em_remove, PlayList, and signalRemoveList().
Referenced by xSetup().
117 {
118         KURL::List remove_list;
119         int i=0;
120         HDASSPlayListItem *CurChild=(HDASSPlayListItem*)PlayList->firstChild();
121         for(KURL::List::ConstIterator remove_it = curr_list.begin();remove_it != curr_list.end();remove_it++,i++)
122         {
123                 if(CurChild->isSelected ())
124                 
125                 {
126                         remove_list <<(*remove_it).url();
127                 }
128                 CurChild=(HDASSPlayListItem*)CurChild->nextSibling();
129         }
130         emit signalRemoveList(remove_list,em_remove);
131 }
void InfoArea::slotDoubleClicked (QListViewItem * item) [slot]
Definition at line 133 of file infoarea.cpp.
References signalPlayItem(), and singalPlayItem().
Referenced by InitPlayList().
134 {
135    HDASSPlayListItem *clickitem=(HDASSPlayListItem *)item;
136    qWarning("DoubleClikced");
137    emit signalPlayItem(clickitem->text(0));
138    emit singalPlayItem();
139  
140 }
void InfoArea::slotHadleSongInfo (int, int, QString, QString, QString) [slot]
Definition at line 177 of file infoarea.cpp.
References Artist, BitRate, and Title.
178 {
179    QString strArtist=QString("Artist :") +(m_artist.isEmpty()?QString(" No Info"):m_artist);
180    QString strTitle=(m_title.isEmpty()?QString(" No Info"):m_title);
181    QString strAlbum=QString("Album :") +(m_album.isEmpty()?QString(" No Info"):m_album);
182    
183    QFont f( "Helvetica", 14, QFont::Bold );
184    QFontMetrics fm(f);
185    
186    Artist->resize(fm.width(strArtist),fm.height());
187    Artist->setText(strArtist);
188    
189    Title->move(580-fm.width(strTitle)/2,Title->y());
190    Title->resize(fm.width(strTitle),fm.height());
191    Title->setText(strTitle);
192    
193    Album->resize(fm.width(strTitle),fm.height());
194    Album->setText(strAlbum);
195    
196    BitRate->setText(QString("BitRate : %1 ").arg(m_bitrate));
197     
198    //Artist->show();
199   // Album->show();
200    //BitRate->show();
201    Title->show();
202 
203    
204 }
void InfoArea::slotReadListFromPlayList (KURL::List playlist) [slot]
Definition at line 97 of file infoarea.cpp.
References curr_list, and PlayList.
98 { 
99    curr_list=playlist;
100    //Clear ValueList
101    PlayList->clear();
102    
103    
104    for( KURL::List::ConstIterator it = playlist.begin();it != playlist.end();it++)
105    {
106     //Add to value list
107     qWarning((*it).fileName());
108      new HDASSPlayListItem( PlayList,(*it).fileName());
109    }
110 }
void InfoArea::xSetup ()
Definition at line 37 of file infoarea.cpp.
References BtnGraphic, IABtnPlayListDelete, IABtnVolumeDown, IABtnVolumeUp, InitPlayList(), m_pAnalyzer, SkinButton::setPixmaps(), and slotDeleteItems().
Referenced by InfoArea().
38 {
39    //DAVID Setup Background;
40    pixBackground.load("/root/kde_application/hdass08/skin/InfoAreaBackground.png");
41    setBackgroundPixmap(pixBackground);
42    
43    //DAVID
44    m_pAnalyzer = new Sonogram( this );            
45    m_pAnalyzer->setGeometry( 417,144, 338,60 );
46    m_pAnalyzer->show();
47    
48    //DAVID Load BtnGraphic
49    BtnGraphic[0]=new QPixmap("/root/kde_application/hdass08/skin/InfoAreaBtn-VolumeUp.png");
50    BtnGraphic[1]=new QPixmap("/root/kde_application/hdass08/skin/InfoAreaBtn-VolumeUp-Active.png");
51    BtnGraphic[2]=new QPixmap("/root/kde_application/hdass08/skin/InfoAreaBtn-VolumeDown.png");
52    BtnGraphic[3]=new QPixmap("/root/kde_application/hdass08/skin/InfoAreaBtn-VolumeDown-Active.png");
53    BtnGraphic[4]=new QPixmap("/root/kde_application/hdass08/skin/InfoAreaBtn-PlayListDelete.png");
54    BtnGraphic[5]=new QPixmap("/root/kde_application/hdass08/skin/InfoAreaBtn-PlayListDelete-Active.png");
55    //DAVID Set Volume Buttons
56    IABtnVolumeUp=new SkinButton(this);
57    IABtnVolumeDown=new SkinButton(this);
58    IABtnPlayListDelete=new SkinButton(this);
59 
60    IABtnVolumeUp->setPixmaps(BtnGraphic[0],BtnGraphic[1]);
61    IABtnVolumeUp->setGeometry(418,38,60,60);
62    IABtnVolumeUp->show();
63    
64    IABtnVolumeDown->setPixmaps(BtnGraphic[2],BtnGraphic[3]);
65    IABtnVolumeDown->setGeometry(684,349,60,60);
66    IABtnVolumeDown->show();
67    
68    IABtnPlayListDelete->setPixmaps(BtnGraphic[4],BtnGraphic[5]);
69    IABtnPlayListDelete->setGeometry(346,477,42,42);
70    IABtnPlayListDelete->show();
71    connect(IABtnPlayListDelete,SIGNAL(clicked()),this,SLOT(slotDeleteItems()));
72    //DAVID Init PlayList Table
73    InitPlayList();
74    
75    
76 }
Member Data Documentation
QLabel * InfoArea::Album [private]
Definition at line 64 of file infoarea.h.
QLabel* InfoArea::Artist [private]
Definition at line 64 of file infoarea.h.
Referenced by InitSongInfo(), and slotHadleSongInfo().
QLabel * InfoArea::BitRate [private]
Definition at line 64 of file infoarea.h.
Referenced by InitSongInfo(), and slotHadleSongInfo().
QPixmap* InfoArea::BtnGraphic[6] [private]
Definition at line 63 of file infoarea.h.
Referenced by xSetup().
KURL::List InfoArea::curr_list
Definition at line 49 of file infoarea.h.
Referenced by slotDeleteItems(), and slotReadListFromPlayList().
SkinButton * InfoArea::IABtnPlayListDelete
Definition at line 45 of file infoarea.h.
Referenced by xSetup().
SkinButton * InfoArea::IABtnVolumeDown
Definition at line 45 of file infoarea.h.
Referenced by xSetup(), and HDASS08::xSetup().
SkinButton* InfoArea::IABtnVolumeUp
Definition at line 45 of file infoarea.h.
Referenced by xSetup(), and HDASS08::xSetup().
QLabel * InfoArea::Length [private]
Definition at line 64 of file infoarea.h.
QWidget* InfoArea::m_pAnalyzer
Definition at line 46 of file infoarea.h.
Referenced by xSetup().
QPixmap InfoArea::pixBackground [private]
Definition at line 62 of file infoarea.h.
QListView* InfoArea::PlayList
Definition at line 47 of file infoarea.h.
Referenced by InitPlayList(), slotDeleteItems(), and slotReadListFromPlayList().
QLabel * InfoArea::Title [private]
Definition at line 64 of file infoarea.h.
Referenced by InitSongInfo(), and slotHadleSongInfo().
QLabel * InfoArea::Year [private]
Definition at line 64 of file infoarea.h.
The documentation for this class was generated from the following files:
infoarea.h
infoarea.moc
infoarea.cpp