keyboard_key Class Reference
#include <keyboard_key.h>
Detailed Description
Author: root
Definition at line 29 of file keyboard_key.h.
Public Types
enum KEY_TYPE { KEY,
CHANGE,
ENTER,
BACKSPACE
 }
Public Slots
void slotSetCase (bool upper)
void slotClicked ()
void slotPressed ()
void slotReleased ()
void slotEnter ()
void slotChange ()
void slotBackSpace ()
void slotSetPixmap (QPixmap,QPixmap)
Signals
void signalSendChar (QString strChar)
void signalEnter ()
void signalChange ()
void signalBackSpace ()
Public Member Functions
keyboard_key (QWidget *parent=0, const char *name=0, QString strUpper=0, QString strLower=0, KEY_TYPE _type=KEY)
~keyboard_key ()
void xSetup (QString u, QString l)
Protected Member Functions
void drawButton (QPainter *p)
Private Attributes
QString strCurChar
QString strCharUp
QString strCharLower
bool upper
QPixmap pixBackground
QPixmap pixAcitve
QPixmap pixInactive
KEY_TYPE key_type
Member Enumeration Documentation
enum keyboard_key::KEY_TYPE
Enumeration values:
KEY
CHANGE
ENTER
BACKSPACE
Definition at line 34 of file keyboard_key.h.
35 {
36   KEY,
37   CHANGE,
38   ENTER,
39   BACKSPACE
40 };
Constructor & Destructor Documentation
keyboard_key::keyboard_key (QWidget * parent = 0, const char * name = 0, QString strUpper = 0, QString strLower = 0, KEY_TYPE _type = KEY)
Definition at line 23 of file keyboard_key.cpp.
References key_type, and xSetup().
24  : QPushButton(parent, name)
25 {
26    
27    key_type=_type;
28    xSetup(strUpper,strLower);
29 }
keyboard_key::~keyboard_key ()
Definition at line 32 of file keyboard_key.cpp.
33 {
34 }
Member Function Documentation
void keyboard_key::drawButton (QPainter * p) [protected]
Definition at line 91 of file keyboard_key.cpp.
References strCurChar.
92 {
93   p->drawPixmap(0,0,pixBackground);
94   p->drawText( rect(), AlignCenter, strCurChar );
95 }
void keyboard_key::signalBackSpace () [signal]
Definition at line 132 of file keyboard_key.moc.
Referenced by slotBackSpace().
133 {
134     activate_signal( staticMetaObject()->signalOffset() + 3 );
135 }
void keyboard_key::signalChange () [signal]
Definition at line 126 of file keyboard_key.moc.
Referenced by slotChange().
127 {
128     activate_signal( staticMetaObject()->signalOffset() + 2 );
129 }
void keyboard_key::signalEnter () [signal]
Definition at line 120 of file keyboard_key.moc.
Referenced by slotEnter().
121 {
122     activate_signal( staticMetaObject()->signalOffset() + 1 );
123 }
void keyboard_key::signalSendChar (QString strChar) [signal]
Definition at line 114 of file keyboard_key.moc.
Referenced by slotClicked().
115 {
116     activate_signal( staticMetaObject()->signalOffset() + 0, t0 );
117 }
void keyboard_key::slotBackSpace () [slot]
Definition at line 124 of file keyboard_key.cpp.
References signalBackSpace().
Referenced by xSetup().
125 {
126  emit signalBackSpace();
127 }
void keyboard_key::slotChange () [slot]
Definition at line 119 of file keyboard_key.cpp.
References signalChange().
Referenced by xSetup().
120 {
121   emit signalChange();
122 }
void keyboard_key::slotClicked () [slot]
Definition at line 86 of file keyboard_key.cpp.
References signalSendChar(), and strCurChar.
Referenced by xSetup().
87 {
88    emit signalSendChar(strCurChar);
89 }
void keyboard_key::slotEnter () [slot]
Definition at line 114 of file keyboard_key.cpp.
References signalEnter().
Referenced by xSetup().
115 {
116   emit signalEnter();
117 }
void keyboard_key::slotPressed () [slot]
Definition at line 96 of file keyboard_key.cpp.
References pixAcitve.
Referenced by xSetup().
97 {
98   pixBackground=pixAcitve;
99   repaint();
100 }
void keyboard_key::slotReleased () [slot]
Definition at line 101 of file keyboard_key.cpp.
References pixInactive.
Referenced by xSetup().
102 {
103  pixBackground=pixInactive;
104  repaint();
105 }
void keyboard_key::slotSetCase (bool upper) [slot]
Definition at line 77 of file keyboard_key.cpp.
References strCharLower, strCharUp, and strCurChar.
Referenced by xSetup().
78 {
79    if(upper)
80    strCurChar=strCharUp;
81    else
82    strCurChar=strCharLower;
83    repaint();
84 }
void keyboard_key::slotSetPixmap (QPixmap, QPixmap) [slot]
Definition at line 106 of file keyboard_key.cpp.
References pixAcitve, and pixInactive.
Referenced by keyboard::InitKey().
107 {
108    pixInactive=inactive;
109    pixAcitve=pix_active;
110    pixBackground=pixInactive;
111    resize(pixBackground.size());
112    repaint();
113 }
void keyboard_key::xSetup (QString u, QString l)
Definition at line 35 of file keyboard_key.cpp.
References BACKSPACE, CHANGE, ENTER, KEY, key_type, pixAcitve, pixInactive, slotBackSpace(), slotChange(), slotClicked(), slotEnter(), slotPressed(), slotReleased(), slotSetCase(), strCharLower, and strCharUp.
Referenced by keyboard_key().
36 { 
37   //DAVID  set up
38   pixInactive.load("/root/kde_application/hdass08/skin/keybtn.png");
39   pixAcitve.load("/root/kde_application/hdass08/skin/keybtn-active.png");
40   pixBackground=pixInactive;
41   //QBitmap mask=QBitmap("/root/kde_application/hdass08/skin/key_btn_mask.png");
42   //setMask(mask);
43   resize(pixBackground.size());
44   QFont serifFont( "Helvetica", 18, QFont::Bold );
45   setFont(serifFont); 
46   strCharUp=up;
47   strCharLower=lo;
48   //DAVID default is the lowercase
49   upper=true;
50   slotSetCase(upper);
51   //setText(strCharLower);
52   switch(key_type)
53   {
54    case KEY:
55    
56    connect(this,SIGNAL(clicked()),this,SLOT(slotClicked()));
57    break;
58    
59    case ENTER:
60    
61    connect(this,SIGNAL(clicked()),this,SLOT(slotEnter()));
62    break;
63    
64    case BACKSPACE:
65    connect(this,SIGNAL(clicked()),this,SLOT(slotBackSpace()));
66    break;  
67    
68    case CHANGE:
69    connect(this,SIGNAL(clicked()),this,SLOT(slotChange()));
70    break; 
71   }
72   
73   connect(this,SIGNAL(pressed()),this,SLOT(slotPressed()));
74   connect(this,SIGNAL(released()),this,SLOT(slotReleased()));
75 }
Member Data Documentation
KEY_TYPE keyboard_key::key_type [private]
Definition at line 66 of file keyboard_key.h.
Referenced by keyboard_key(), and xSetup().
QPixmap keyboard_key::pixAcitve [private]
Definition at line 65 of file keyboard_key.h.
Referenced by slotPressed(), slotSetPixmap(), and xSetup().
QPixmap keyboard_key::pixBackground [private]
Definition at line 65 of file keyboard_key.h.
QPixmap keyboard_key::pixInactive [private]
Definition at line 65 of file keyboard_key.h.
Referenced by slotReleased(), slotSetPixmap(), and xSetup().
QString keyboard_key::strCharLower [private]
Definition at line 63 of file keyboard_key.h.
Referenced by slotSetCase(), and xSetup().
QString keyboard_key::strCharUp [private]
Definition at line 63 of file keyboard_key.h.
Referenced by slotSetCase(), and xSetup().
QString keyboard_key::strCurChar [private]
Definition at line 63 of file keyboard_key.h.
Referenced by drawButton(), slotClicked(), and slotSetCase().
bool keyboard_key::upper [private]
Definition at line 64 of file keyboard_key.h.
The documentation for this class was generated from the following files:
keyboard_key.h
keyboard_key.moc
keyboard_key.cpp