Amarok::Synth_STEREO_XFADE_base Class Reference
#include <amarokarts.h>
Public Member Functions
Synth_STEREO_XFADE_base * _copy ()
virtual std::vector< std::string > _defaultPortsIn () const
virtual std::vector< std::string > _defaultPortsOut () const
void * _cast (unsigned long iid)
virtual float percentage ()=0
virtual void percentage (float newValue)=0
Static Public Member Functions
Synth_STEREO_XFADE_base * _create (const std::string &subClass=`Amarok::Synth_STEREO_XFADE`)
Synth_STEREO_XFADE_base * _fromString (const std::string &objectref)
Synth_STEREO_XFADE_base * _fromReference (Arts::ObjectReference ref, bool needcopy)
Synth_STEREO_XFADE_base * _fromDynamicCast (const Arts::Object &object)
Static Public Attributes
unsigned long _IID = Arts::MCOPUtils::makeIID(`Amarok::Synth_STEREO_XFADE`)
Member Function Documentation
void * Amarok::Synth_STEREO_XFADE_base::_cast (unsigned long iid)
Definition at line 71 of file amarokarts.cc.
References _IID.
Referenced by _fromDynamicCast(), and Amarok::Synth_STEREO_XFADE::_method_call().
72 {
73         if(iid == Amarok::Synth_STEREO_XFADE_base::_IID) return (Amarok::Synth_STEREO_XFADE_base *)this;
74         if(iid == Arts::SynthModule_base::_IID) return (Arts::SynthModule_base *)this;
75         if(iid == Arts::Object_base::_IID) return (Arts::Object_base *)this;
76         return 0;
77 }
Synth_STEREO_XFADE_base* Amarok::Synth_STEREO_XFADE_base::_copy () [inline]
Definition at line 24 of file amarokarts.h.
Referenced by _fromDynamicCast().
24                                                 {
25                 assert(_refCnt > 0);
26                 _refCnt++;
27                 return this;
28         }
Amarok::Synth_STEREO_XFADE_base * Amarok::Synth_STEREO_XFADE_base::_create (const std::string & subClass = `Amarok::Synth_STEREO_XFADE`) [static]
Definition at line 8 of file amarokarts.cc.
References _IID.
Referenced by Amarok::Synth_STEREO_XFADE::_Creator().
9 {
10         Arts::Object_skel *skel = Arts::ObjectManager::the()->create(subClass);
11         assert(skel);
12         Amarok::Synth_STEREO_XFADE_base *castedObject = (Amarok::Synth_STEREO_XFADE_base *)skel->_cast(Amarok::Synth_STEREO_XFADE_base::_IID);
13         assert(castedObject);
14         return castedObject;
15 }
std::vector< std::string > Amarok::Synth_STEREO_XFADE_base::_defaultPortsIn () const [virtual]
Definition at line 62 of file amarokarts.cc.
62                                                                           {
63         std::vector<std::string> ret;
64         return ret;
65 }
std::vector< std::string > Amarok::Synth_STEREO_XFADE_base::_defaultPortsOut () const [virtual]
Definition at line 66 of file amarokarts.cc.
66                                                                            {
67         std::vector<std::string> ret;
68         return ret;
69 }
Amarok::Synth_STEREO_XFADE_base * Amarok::Synth_STEREO_XFADE_base::_fromDynamicCast (const Arts::Object & object) [static]
Definition at line 26 of file amarokarts.cc.
References _cast(), _copy(), _fromString(), and _IID.
27 {
28         if(object.isNull()) return 0;
29 
30         Amarok::Synth_STEREO_XFADE_base *castedObject = (Amarok::Synth_STEREO_XFADE_base *)object._base()->_cast(Amarok::Synth_STEREO_XFADE_base::_IID);
31         if(castedObject) return castedObject->_copy();
32 
33         return _fromString(object._toString());
34 }
Amarok::Synth_STEREO_XFADE_base * Amarok::Synth_STEREO_XFADE_base::_fromReference (Arts::ObjectReference ref, bool needcopy) [static]
Definition at line 36 of file amarokarts.cc.
Referenced by _fromString().
37 {
38         Amarok::Synth_STEREO_XFADE_base *result;
39         result = (Amarok::Synth_STEREO_XFADE_base *)Arts::Dispatcher::the()->connectObjectLocal(r,"Amarok::Synth_STEREO_XFADE");
40         if(result)
41         {
42                 if(!needcopy)
43                         result->_cancelCopyRemote();
44         }
45         else
46         {
47                 Arts::Connection *conn = Arts::Dispatcher::the()->connectObjectRemote(r);
48                 if(conn)
49                 {
50                         result = new Amarok::Synth_STEREO_XFADE_stub(conn,r.objectID);
51                         if(needcopy) result->_copyRemote();
52                         result->_useRemote();
53                         if (!result->_isCompatibleWith("Amarok::Synth_STEREO_XFADE")) {
54                                 result->_release();
55                                 return 0;
56                         }
57                 }
58         }
59         return result;
60 }
Amarok::Synth_STEREO_XFADE_base * Amarok::Synth_STEREO_XFADE_base::_fromString (const std::string & objectref) [static]
Definition at line 17 of file amarokarts.cc.
References _fromReference().
Referenced by _fromDynamicCast().
18 {
19         Arts::ObjectReference r;
20 
21         if(Arts::Dispatcher::the()->stringToObjectReference(r,objectref))
22                 return Amarok::Synth_STEREO_XFADE_base::_fromReference(r,true);
23         return 0;
24 }
virtual void Amarok::Synth_STEREO_XFADE_base::percentage (float newValue) [pure virtual]
Implemented in Amarok::Synth_STEREO_XFADE_stub (p.).
virtual float Amarok::Synth_STEREO_XFADE_base::percentage () [pure virtual]
Implemented in Amarok::Synth_STEREO_XFADE_stub (p.).
Referenced by Amarok::Synth_STEREO_XFADE::percentage().
Member Data Documentation
unsigned long Amarok::Synth_STEREO_XFADE_base::_IID = Arts::MCOPUtils::makeIID(`Amarok::Synth_STEREO_XFADE`) [static]
Definition at line 180 of file amarokarts.cc.
Referenced by _cast(), _create(), and _fromDynamicCast().
The documentation for this class was generated from the following files:
amarokarts.h
amarokarts.cc