DownFile Class Reference
#include <DownFile.h>
Public Slots
void handleDone (bool)
Signals
void Finished (bool)
Public Member Functions
DownFile (const KURL &)
~DownFile ()
Public Attributes
QHttp * http
QFile * downloadfile
Constructor & Destructor Documentation
DownFile::DownFile (const KURL &)
Definition at line 25 of file DownFile.cpp.
References downloadfile, handleDone(), and http.
26 {  
27 kdDebug() << "DownFile -> url -> " << url << endl;
28 kdDebug() << "DownFile -> host -> " << url.host() << endl;      
29 kdDebug() << "DownFile -> FileName -> " << url.fileName() << endl;    
30     downloadfile = new QFile( url.fileName() );
31     downloadfile->open( IO_WriteOnly );
32     
33     http = new QHttp(this);
34     http->setHost(url.host());
35     http->get( url.path(),downloadfile); 
36     connect(http, SIGNAL(done(bool)), this, SLOT(handleDone(bool)));  
37     
38 //    KURL src("http://140.116.5.200/~f7490124/Browser/Macgyver.mp3");
39 //    KURL des("file:/home/karban/Macgyver.mp3");
40 //    KIO::FileCopyJob testfile(src,des,777,false,true,true,true);
41 //    testfile.slotStart();
42 //    KIO::TransferJob *job = KIO::get( src, false, true );
43 //    connect(job,SIGNAL(data(KIO::Job *,const QByteArray &)),this,SLOT(handleData(KIO::Job *, const QByteArray &)));
44 }
DownFile::~DownFile ()
Definition at line 46 of file DownFile.cpp.
47 {
48 
49 }
Member Function Documentation
void DownFile::Finished (bool) [signal]
Definition at line 90 of file DownFile.moc.
Referenced by handleDone().
91 {
92     activate_signal_bool( staticMetaObject()->signalOffset() + 0, t0 );
93 }
void DownFile::handleDone (bool) [slot]
Definition at line 51 of file DownFile.cpp.
References downloadfile, and Finished().
Referenced by DownFile().
52 {
53      downloadfile->close();
54 kdDebug() << "Download Finish !!!!!!!!!! "<< endl; 
55      emit Finished(error);        
56 }
Member Data Documentation
QFile* DownFile::downloadfile
Definition at line 40 of file DownFile.h.
Referenced by DownFile(), and handleDone().
QHttp* DownFile::http
Definition at line 39 of file DownFile.h.
Referenced by DownFile().
The documentation for this class was generated from the following files:
DownFile.h
DownFile.moc
DownFile.cpp