MetaBundle Class Reference
#include <metabundle.h>
Public Member Functions
MetaBundle ()
MetaBundle (const KURL &u)
MetaBundle (const QString &title, const QString &streamUrl, const int bitrate, const QString &genre, const QString &streamName, const KURL &)
MetaBundle (const KURL &url, TagLib::Tag *tag, TagLib::AudioProperties *ap=0)
MetaBundle & readTags (bool audioProperties=true)
int length () const
int bitrate () const
int sampleRate () const
bool exist ()
const KURL & url () const
const QString & title () const
const QString & artist () const
const QString & album () const
const QString & year () const
const QString & comment () const
const QString & genre () const
const QString & track () const
QString prettyTitle () const
QString prettyURL () const
QString prettyBitrate () const
QString prettyLength () const
QString prettySampleRate () const
Static Public Member Functions
QString prettyBitrate (int)
QString prettyLength (int)
QString prettyTime (int, bool showHours=true)
QString zeroPad (uint i)
QString prettyTitle (QString)
Static Public Attributes
const int Undetermined = -2
const int Irrelevant = -1
const int Unavailable = 0
Private Member Functions
void init (TagLib::AudioProperties *ap=0)
void init (const KFileMetaInfo &info)
Static Private Member Functions
QString prettyGeneric (const QString &, int)
Private Attributes
KURL m_url
QString m_title
QString m_artist
QString m_album
QString m_year
QString m_comment
QString m_genre
QString m_track
int m_bitrate
int m_length
int m_sampleRate
bool exists
Constructor & Destructor Documentation
MetaBundle::MetaBundle () [inline]
Definition at line 33 of file metabundle.h.
References init().
33 { init(); }
MetaBundle::MetaBundle (const KURL & u) [inline]
Definition at line 34 of file metabundle.h.
References m_url, and readTags().
34 : m_url( u ) { readTags(); }
MetaBundle::MetaBundle (const QString & title, const QString & streamUrl, const int bitrate, const QString & genre, const QString & streamName, const KURL &)
Definition at line 39 of file metabundle.cpp.
45   : m_url       ( url )
46   , m_title     ( streamUrl + QString( " -- " ) + title )
47   , m_genre     ( genre )
48   , m_bitrate   ( bitrate )
49   , m_length    ( Irrelevant )
50   , m_sampleRate( Unavailable )
51   ,exists(false)
52 {
53 kdDebug() << "Test point 1 " << endl;
54 }
MetaBundle::MetaBundle (const KURL & url, TagLib::Tag * tag, TagLib::AudioProperties * ap = 0)
Definition at line 96 of file metabundle.cpp.
References init().
97   : m_url( url )
98   , m_title(   TStringToQString( tag->title() ).stripWhiteSpace() )
99   , m_artist(  TStringToQString( tag->artist() ).stripWhiteSpace() )
100   , m_album(   TStringToQString( tag->album() ).stripWhiteSpace() )
101   , m_year(    tag->year() ? QString::number( tag->year() ) : QString::null )
102   , m_comment( TStringToQString( tag->comment() ).stripWhiteSpace() )
103   , m_genre(   TStringToQString( tag->genre() ).stripWhiteSpace() )
104   , m_track(   tag->track() ? QString::number( tag->track() ) : QString::null )
105   ,exists(false)
106 {
107 kdDebug() << "Test point 2 " << endl;
108     init( ap );
109 }
Member Function Documentation
const QString& MetaBundle::album () const [inline]
Definition at line 61 of file metabundle.h.
References m_album.
Referenced by Myplayer::handleMessage().
61 { return m_album; }
const QString& MetaBundle::artist () const [inline]
Definition at line 60 of file metabundle.h.
References m_artist.
Referenced by Myplayer::handleMessage().
60 { return m_artist; }
int MetaBundle::bitrate () const [inline]
Definition at line 55 of file metabundle.h.
References m_bitrate.
Referenced by Myplayer::handleMessage().
55 { return m_bitrate; }
const QString& MetaBundle::comment () const [inline]
Definition at line 63 of file metabundle.h.
References m_comment.
63 { return m_comment; }
bool MetaBundle::exist ()
Definition at line 256 of file metabundle.cpp.
References exists.
257 {
258         return exists;
259 }
const QString& MetaBundle::genre () const [inline]
Definition at line 64 of file metabundle.h.
References m_genre.
64 { return m_genre; }
void MetaBundle::init (const KFileMetaInfo & info) [private]
Definition at line 130 of file metabundle.cpp.
References exists, m_album, m_artist, m_bitrate, m_comment, m_genre, m_length, m_sampleRate, m_title, m_track, m_url, m_year, prettyTitle(), and Undetermined.
131 {
132     if( info.isValid() )
133     {
134         exists=true;
135         m_artist     = info.item( "Artist" ).string();
136         m_album      = info.item( "Album" ).string();
137         m_year       = info.item( "Year" ).string();
138         m_comment    = info.item( "Comment" ).string();
139         m_genre      = info.item( "Genre" ).string();
140         m_track      = info.item( "Track" ).string();
141         m_bitrate    = info.item( "Bitrate" ).value().toInt();
142         m_length     = info.item( "Length" ).value().toInt();
143         m_sampleRate = info.item( "Sample Rate" ).value().toInt();
144 
145         /*
146          * For title, check if it is valid. If not, use prettyTitle.
147          * See bug#83650.
148          */
149         KFileMetaInfoItem item = info.item( "Title" );
150         if( item.isValid() )
151             m_title = item.string();
152         else
153             m_title = prettyTitle( m_url.fileName() );
154     }
155     else m_bitrate = m_length = m_sampleRate = Undetermined;
156 }
void MetaBundle::init (TagLib::AudioProperties * ap = 0) [private]
Definition at line 112 of file metabundle.cpp.
References exists, m_bitrate, m_length, m_sampleRate, m_url, and Undetermined.
Referenced by MetaBundle(), and readTags().
113 {
114     if( !m_url.isLocalFile() )
115      {
116         exists=false;    
117         return;
118     }   
119     if( ap )
120     {
121         m_bitrate    = ap->bitrate();
122         m_length     = ap->length();
123         m_sampleRate = ap->sampleRate();
124     }
125     else m_bitrate = m_length = m_sampleRate = Undetermined;
126     exists=true;
127 }
int MetaBundle::length () const [inline]
Definition at line 54 of file metabundle.h.
References m_length.
Referenced by Myplayer::handleMessage(), and EngineController::slotMainTimer().
54 { return m_length > 0 ? m_length : 0; }
QString MetaBundle::prettyBitrate (int) [static]
Definition at line 244 of file metabundle.cpp.
References bitrateStore, and prettyGeneric().
245 {
246     return ( i % 32 == 0 && i < 257 ) ? bitrateStore[ i /32 ] : prettyGeneric( i18n( "Bitrate", "%1 kbps" ), i );
247 }
QString MetaBundle::prettyBitrate () const [inline]
Definition at line 69 of file metabundle.h.
References m_bitrate.
69 { return prettyBitrate( m_bitrate ); }
QString MetaBundle::prettyGeneric (const QString &, int) [static, private]
Definition at line 250 of file metabundle.cpp.
References Undetermined.
Referenced by prettyBitrate(), and prettySampleRate().
251 {
252     //TODO ensure this inlines
253 
254     return ( i > 0 ) ? s.arg( i ) : ( i == Undetermined ) ? "?" : QString::null;
255 }
QString MetaBundle::prettyLength (int) [static]
Definition at line 212 of file metabundle.cpp.
References Irrelevant, prettyTime(), and Unavailable.
213 {
214     QString s;
215 
216     if( seconds > 0 ) s = prettyTime( seconds, false );
217     else if( seconds == Unavailable ) s = '?';
218     else if( seconds == Irrelevant  ) s = '-';
219 
220     return s; //Undetermined = ""
221 }
QString MetaBundle::prettyLength () const [inline]
Definition at line 70 of file metabundle.h.
References m_length.
70 { return prettyLength( m_length ); }
QString MetaBundle::prettySampleRate () const [inline]
Definition at line 71 of file metabundle.h.
References m_sampleRate, and prettyGeneric().
71 { return prettyGeneric( i18n( "SampleRate", "%1 Hz" ), m_sampleRate ); }
QString MetaBundle::prettyTime (int, bool showHours = true) [static]
Definition at line 224 of file metabundle.cpp.
References zeroPad().
Referenced by prettyLength().
225 {
226     QString s = QChar( ':' );
227     s.append( zeroPad( seconds % 60 ) ); //seconds
228     seconds /= 60;
229 
230     if( showHours )
231     {
232         s.prepend( zeroPad( seconds % 60 ) ); //minutes
233         s.prepend( ':' );
234         seconds /= 60;
235     }
236 
237     //don't zeroPad the last one, as it can be greater than 2 digits
238     s.prepend( QString::number( seconds ) ); //hours or minutes depending on above if block
239 
240     return s;
241 }
QString MetaBundle::prettyTitle (QString) [static]
Definition at line 200 of file metabundle.cpp.
201 {
202     QString &s = filename; //just so the code is more readable
203 
204     //remove file extension, s/_/ /g and decode %2f-like sequences
205     s = s.left( s.findRev( '.' ) ).replace( '_', ' ' );
206     s = KURL::decode_string(s);
207 
208     return s;
209 }
QString MetaBundle::prettyTitle () const
Definition at line 187 of file metabundle.cpp.
References m_artist, m_title, and m_url.
Referenced by init().
188 {
189     //NOTE this gets regressed often, please be careful!
190     //NOTE whatever you do, handle the stream case, streams have no artist but have an excellent title
191 
192     QString s = m_artist;
193     if( !s.isEmpty() ) s += " - ";
194     s += m_title;
195     if( s.isEmpty() ) s = prettyTitle( m_url.fileName() );
196     return s;
197 }
QString MetaBundle::prettyURL () const [inline]
Definition at line 68 of file metabundle.h.
References m_url.
68 { return m_url.prettyURL(); }
MetaBundle & MetaBundle::readTags (bool audioProperties = true)
Definition at line 159 of file metabundle.cpp.
References init(), m_album, m_artist, m_comment, m_genre, m_title, m_track, m_url, and m_year.
Referenced by MetaBundle().
160 {
161     //TODO detect mimetype and use specfic reader like Scott recommends
162 
163    TagLib::FileRef f( m_url.path().local8Bit(), audioProperties, TagLib::AudioProperties::Fast );
164 
165    if ( !f.isNull() )
166    {
167         if( f.tag() )
168         {
169             TagLib::Tag *tag = f.tag();
170 
171             m_title   = TStringToQString( tag->title() ).stripWhiteSpace();
172             m_artist  = TStringToQString( tag->artist() ).stripWhiteSpace();
173             m_album   = TStringToQString( tag->album() ).stripWhiteSpace();
174             m_comment = TStringToQString( tag->comment() ).stripWhiteSpace();
175             m_genre   = TStringToQString( tag->genre() ).stripWhiteSpace();
176             m_year    = tag->year() ? QString::number( tag->year() ) : QString::null;
177             m_track   = tag->track() ? QString::number( tag->track() ) : QString::null;
178         }
179         init( f.audioProperties() );
180     }
181     else init( KFileMetaInfo( m_url, QString::null, KFileMetaInfo::Everything ) );
182 
183     return *this;
184 }
int MetaBundle::sampleRate () const [inline]
Definition at line 56 of file metabundle.h.
References m_sampleRate.
56 { return m_sampleRate; }
const QString& MetaBundle::title () const [inline]
Definition at line 59 of file metabundle.h.
References m_title.
Referenced by Myplayer::handleMessage().
59 { return m_title; }
const QString& MetaBundle::track () const [inline]
Definition at line 65 of file metabundle.h.
References m_track.
65 { return m_track; }
const KURL& MetaBundle::url () const [inline]
Definition at line 58 of file metabundle.h.
References m_url.
Referenced by EngineController::play().
58 { return m_url; }
const QString& MetaBundle::year () const [inline]
Definition at line 62 of file metabundle.h.
References m_year.
62 { return m_year; }
QString MetaBundle::zeroPad (uint i) [inline, static]
Definition at line 76 of file metabundle.h.
Referenced by prettyTime().
76 { return ( i < 10 ) ? QString( "0%1" ).arg( i ) : QString::number( i ); }
Member Data Documentation
bool MetaBundle::exists [private]
Definition at line 101 of file metabundle.h.
Referenced by exist(), and init().
const int MetaBundle::Irrelevant = -1 [static]
Definition at line 29 of file metabundle.h.
Referenced by prettyLength().
QString MetaBundle::m_album [private]
Definition at line 83 of file metabundle.h.
Referenced by album(), init(), and readTags().
QString MetaBundle::m_artist [private]
Definition at line 82 of file metabundle.h.
Referenced by artist(), init(), prettyTitle(), and readTags().
int MetaBundle::m_bitrate [private]
Definition at line 93 of file metabundle.h.
Referenced by bitrate(), init(), and prettyBitrate().
QString MetaBundle::m_comment [private]
Definition at line 85 of file metabundle.h.
Referenced by comment(), init(), and readTags().
QString MetaBundle::m_genre [private]
Definition at line 86 of file metabundle.h.
Referenced by genre(), init(), and readTags().
int MetaBundle::m_length [private]
Definition at line 94 of file metabundle.h.
Referenced by init(), length(), and prettyLength().
int MetaBundle::m_sampleRate [private]
Definition at line 95 of file metabundle.h.
Referenced by init(), prettySampleRate(), and sampleRate().
QString MetaBundle::m_title [private]
Definition at line 81 of file metabundle.h.
Referenced by init(), prettyTitle(), readTags(), and title().
QString MetaBundle::m_track [private]
Definition at line 87 of file metabundle.h.
Referenced by init(), readTags(), and track().
KURL MetaBundle::m_url [private]
Definition at line 80 of file metabundle.h.
Referenced by init(), MetaBundle(), prettyTitle(), prettyURL(), readTags(), and url().
QString MetaBundle::m_year [private]
Definition at line 84 of file metabundle.h.
Referenced by init(), readTags(), and year().
const int MetaBundle::Unavailable = 0 [static]
Definition at line 30 of file metabundle.h.
Referenced by prettyLength().
const int MetaBundle::Undetermined = -2 [static]
Definition at line 28 of file metabundle.h.
Referenced by init(), and prettyGeneric().
The documentation for this class was generated from the following files:
metabundle.h
metabundle.cpp