hdassAlbum Class Reference
#include <hdassalbum.h>
Detailed Description
Author: root
Definition at line 34 of file hdassalbum.h.
Public Slots
void AddImageToAlbum (KURL addimage)
void RemoveImageFromAlbum (KURL removeimage)
void ChangeMode (AlbumMode mode)
void slotNextImage ()
void slotPreviousImage ()
void slotPlayNStop ()
void slotModeChange (int)
void slotSetSwitchingTime (int time)
Public Member Functions
hdassAlbum (QWidget *parent=0, const char *name=0)
~hdassAlbum ()
void xSetup ()
void SlideShow ()
void DrawImage (QPixmap pix)
Public Attributes
KURL::List::ConstIterator it
KURL::List AlbumList
KURL::List FloderList
QPtrList< QPixmap > PixList
Private Types
enum AlbumMode { Album = 0,
Clock
 }
Private Member Functions
void ReadAlbumList (QString filename)
void SaveAlbumList ()
Private Attributes
int switchtime
QString AlbumListFileName
QFile * AlbumFile
QTimer * timer
Member Enumeration Documentation
enum hdassAlbum::AlbumMode [private]
Enumeration values:
Album
Clock
Definition at line 37 of file hdassalbum.h.
38 {
39   Album=0,
40   Clock     
41 };
Constructor & Destructor Documentation
hdassAlbum::hdassAlbum (QWidget * parent = 0, const char * name = 0)
Definition at line 26 of file hdassalbum.cpp.
References xSetup().
27  : QWidget(parent, name)
28 {
29    xSetup();
30 }
hdassAlbum::~hdassAlbum ()
Definition at line 33 of file hdassalbum.cpp.
34 {
35 
36 }
Member Function Documentation
void hdassAlbum::AddImageToAlbum (KURL addimage) [slot]
Definition at line 60 of file hdassalbum.cpp.
References AlbumList.
61 {
62    AlbumList<<addimage;
63 }
void hdassAlbum::ChangeMode (AlbumMode mode) [slot]
Definition at line 69 of file hdassalbum.cpp.
70 {
71 
72 }
void hdassAlbum::DrawImage (QPixmap pix)
Definition at line 154 of file hdassalbum.cpp.
Referenced by slotNextImage(), slotPreviousImage(), ImageDetial::slotShowFloder(), and xSetup().
155 {
156    
157    
158    int width ,height;
159    width=pix.width();
160    height=pix.height();
161    
162    QPixmap draw(QSize(800,540));
163    QPainter p(&draw);
164 
165    p.fillRect(0,0,800,540,Qt::black);
166    if(width<800&&height<540)
167    {
168        //DAVID draw image at center
169        p.drawPixmap((400-width/2),(270-height/2),pix);
170    }
171 
172    else
173    {
174         if(11*width>20*height)
175         {
176                 int newheight=(800*height/width);
177                 QImage rescale=pix.convertToImage().scale(800,newheight);
178                 p.drawImage(0,270-newheight/2,rescale);
179                 
180         } 
181         else
182         {
183                 int newwidth=(540*width/height);
184                 QImage rescale=pix.convertToImage().scale(newwidth,540);
185                 p.drawImage((400-newwidth/2),0,rescale);
186         }
187    }    
188    p.end();
189    setBackgroundPixmap(draw);
190 }
void hdassAlbum::ReadAlbumList (QString filename) [private]
Definition at line 77 of file hdassalbum.cpp.
References AlbumFile, AlbumList, and it.
Referenced by xSetup().
78 {
79         //DAVID open the file
80         AlbumFile=new QFile(filepath);
81         if(AlbumFile->open(IO_ReadOnly))
82         {
83                 //Read KURL from file to KURLList
84                 QTextStream stream( AlbumFile );
85                 while(!stream.atEnd())
86                 {
87                         KURL url(stream.readLine());
88                         //kdDebug()<<url.path();
89                         AlbumList<<url;
90                 }
91         }
92         else
93         {
94                 kdDebug()<<"hdassAlbum::ReadAlbumList ::: file not opened!!";
95         }
96         it=AlbumList.begin();
97 }
void hdassAlbum::RemoveImageFromAlbum (KURL removeimage) [slot]
Definition at line 65 of file hdassalbum.cpp.
References AlbumList.
66 {
67   AlbumList.remove(removeimage);
68 }
void hdassAlbum::SaveAlbumList () [private]
Definition at line 99 of file hdassalbum.cpp.
100 {
101 
102 }
void hdassAlbum::SlideShow ()
Definition at line 148 of file hdassalbum.cpp.
References switchtime, and timer.
149 {
150      qWarning("hdassAlbum::SlideShow()!!");
151      timer->start(switchtime*1000,FALSE);
152 }
void hdassAlbum::slotModeChange (int) [slot]
Definition at line 73 of file hdassalbum.cpp.
74 {
75 
76 }
void hdassAlbum::slotNextImage () [slot]
Definition at line 117 of file hdassalbum.cpp.
References AlbumList, DrawImage(), and it.
Referenced by xSetup().
118 {
119         //DAVID Read Image
120         it++;
121         if(it!=AlbumList.end())
122         {
123                 KURL url((*it).url());
124                 QPixmap pix;
125                 pix.load(url.path());
126                 DrawImage(pix);
127         }
128 }
void hdassAlbum::slotPlayNStop () [slot]
Definition at line 130 of file hdassalbum.cpp.
References switchtime, and timer.
131 {
132         if(timer->isActive ())
133         {
134                 timer->stop();
135         }
136         else
137         {
138                 timer->start(switchtime*1000,FALSE);
139         }
140 }
void hdassAlbum::slotPreviousImage () [slot]
Definition at line 104 of file hdassalbum.cpp.
References AlbumList, DrawImage(), and it.
105 {
106         //DAVID Read Image
107         it--;
108         if(it!=AlbumList.end())
109         {
110                 KURL url((*it).url());
111                 QPixmap pix;
112                 pix.load(url.path());
113                 DrawImage(pix);
114         }
115 }
void hdassAlbum::slotSetSwitchingTime (int time) [slot]
Definition at line 143 of file hdassalbum.cpp.
References switchtime.
144 {
145   switchtime=time;
146 }
void hdassAlbum::xSetup ()
Definition at line 38 of file hdassalbum.cpp.
References AlbumListFileName, DrawImage(), ReadAlbumList(), slotNextImage(), switchtime, and timer.
Referenced by hdassAlbum().
39 {
40   //DAVID Read album file list 
41   AlbumListFileName="AlbumList.txt";
42   ReadAlbumList(AlbumListFileName);
43   
44  
45 
46   //DAVID Set the switching time
47   switchtime=3;
48   //DAVID Set the timer
49   timer =new QTimer(this);
50   connect(timer,SIGNAL(timeout()),this,SLOT(slotNextImage()));
51   
52   //DAVID Draw a pix first
53   KURL url((*it).url());
54   QPixmap pix;
55   pix.load(url.path());
56   DrawImage(pix);
57   timer->stop();
58   
59 }
Member Data Documentation
QFile* hdassAlbum::AlbumFile [private]
Definition at line 65 of file hdassalbum.h.
Referenced by ReadAlbumList().
KURL::List hdassAlbum::AlbumList
Definition at line 50 of file hdassalbum.h.
Referenced by AddImageToAlbum(), ReadAlbumList(), RemoveImageFromAlbum(), slotNextImage(), and slotPreviousImage().
QString hdassAlbum::AlbumListFileName [private]
Definition at line 64 of file hdassalbum.h.
Referenced by xSetup().
KURL::List hdassAlbum::FloderList
Definition at line 50 of file hdassalbum.h.
KURL::List::ConstIterator hdassAlbum::it
Definition at line 49 of file hdassalbum.h.
Referenced by ReadAlbumList(), slotNextImage(), and slotPreviousImage().
QPtrList<QPixmap> hdassAlbum::PixList
Definition at line 51 of file hdassalbum.h.
int hdassAlbum::switchtime [private]
Definition at line 63 of file hdassalbum.h.
Referenced by SlideShow(), slotPlayNStop(), slotSetSwitchingTime(), and xSetup().
QTimer* hdassAlbum::timer [private]
Definition at line 66 of file hdassalbum.h.
Referenced by SlideShow(), slotPlayNStop(), and xSetup().
The documentation for this class was generated from the following files:
hdassalbum.h
hdassalbum.cpp