EngineObserver Class Reference
#include <engineobserver.h>
Detailed Description
if you want to observe the engine, inherit from this class and attach yourself to the engine with attach
Definition at line 29 of file engineobserver.h.
Public Member Functions
EngineObserver ()
virtual ~EngineObserver ()
virtual void engineStateChanged (EngineBase::EngineState)
virtual void engineNewMetaData (const MetaBundle &, bool)
virtual void engineVolumeChanged (int)
virtual void engineTrackPositionChanged (long)
Constructor & Destructor Documentation
EngineObserver::EngineObserver ()
Definition at line 23 of file engineobserver.cpp.
24 {
25     // autoadd to subject in constructor?
26 }
EngineObserver::~EngineObserver () [virtual]
Definition at line 29 of file engineobserver.cpp.
30 {
31 }
Member Function Documentation
virtual void EngineObserver::engineNewMetaData (const MetaBundle &, bool) [inline, virtual]
Definition at line 35 of file engineobserver.h.
Referenced by EngineSubject::newMetaDataNotify().
35 {}
virtual void EngineObserver::engineStateChanged (EngineBase::EngineState) [inline, virtual]
Definition at line 34 of file engineobserver.h.
Referenced by EngineSubject::stateChangedNotify().
34 {}
virtual void EngineObserver::engineTrackPositionChanged (long) [inline, virtual]
Definition at line 37 of file engineobserver.h.
Referenced by EngineSubject::trackPositionChangedNotify().
37 {}
virtual void EngineObserver::engineVolumeChanged (int) [inline, virtual]
Definition at line 36 of file engineobserver.h.
Referenced by EngineSubject::volumeChangedNotify().
36 {}
The documentation for this class was generated from the following files:
engineobserver.h
engineobserver.cpp