SubBarManagement Class Reference
#include <subbarmanagement.h>
Detailed Description
Author: sonicat
Definition at line 29 of file subbarmanagement.h.
Public Slots
void slotBtnMkFloder ()
void slotBtnPaste ()
void slotBtnCut ()
void slotBtnDelete ()
Signals
void signalManagementModeChange (int)
void signalMkdir ()
void singalPasteFUNC_MEDIAM ()
void signalCutFUNC_MEDIAM ()
void signalDeleteItem ()
Public Member Functions
SubBarManagement (QWidget *parent=0, const char *name=0)
~SubBarManagement ()
void xSetup ()
Public Attributes
SkinButton * SubBtnMM_Floder
SkinButton * SubBtnMM_Paste
SkinButton * SubBtnMM_Cut
SkinButton * SubBtnMM_Delete
SkinButton * SubBtnMM_MusicNImage
Private Types
enum MM_TYPE { em_mmimage,
em_mmmusic
 }
Private Slots
void slotChangeBtnImage ()
Private Attributes
QPixmap pixBackground
QPixmap * BtnGraphic [12]
MM_TYPE MMtype
Member Enumeration Documentation
enum SubBarManagement::MM_TYPE [private]
Enumeration values:
em_mmimage
em_mmmusic
Definition at line 32 of file subbarmanagement.h.
32 {em_mmimage,em_mmmusic};
Constructor & Destructor Documentation
SubBarManagement::SubBarManagement (QWidget * parent = 0, const char * name = 0)
Definition at line 22 of file subbarmanagement.cpp.
References xSetup().
23  : QWidget(parent, name)
24 {
25   xSetup();
26 }
SubBarManagement::~SubBarManagement ()
Definition at line 29 of file subbarmanagement.cpp.
30 {
31 }
Member Function Documentation
void SubBarManagement::signalCutFUNC_MEDIAM () [signal]
Definition at line 121 of file subbarmanagement.moc.
Referenced by slotBtnCut().
122 {
123     activate_signal( staticMetaObject()->signalOffset() + 3 );
124 }
void SubBarManagement::signalDeleteItem () [signal]
Definition at line 127 of file subbarmanagement.moc.
Referenced by slotBtnDelete().
128 {
129     activate_signal( staticMetaObject()->signalOffset() + 4 );
130 }
void SubBarManagement::signalManagementModeChange (int) [signal]
Definition at line 103 of file subbarmanagement.moc.
Referenced by slotChangeBtnImage().
104 {
105     activate_signal( staticMetaObject()->signalOffset() + 0, t0 );
106 }
void SubBarManagement::signalMkdir () [signal]
Definition at line 109 of file subbarmanagement.moc.
Referenced by slotBtnMkFloder().
110 {
111     activate_signal( staticMetaObject()->signalOffset() + 1 );
112 }
void SubBarManagement::singalPasteFUNC_MEDIAM () [signal]
Definition at line 115 of file subbarmanagement.moc.
Referenced by slotBtnPaste().
116 {
117     activate_signal( staticMetaObject()->signalOffset() + 2 );
118 }
void SubBarManagement::slotBtnCut () [slot]
Definition at line 115 of file subbarmanagement.cpp.
References signalCutFUNC_MEDIAM().
Referenced by xSetup().
116 {
117   emit signalCutFUNC_MEDIAM();
118 }
void SubBarManagement::slotBtnDelete () [slot]
Definition at line 120 of file subbarmanagement.cpp.
References signalDeleteItem().
Referenced by xSetup().
121 {
122   emit signalDeleteItem();
123 }
void SubBarManagement::slotBtnMkFloder () [slot]
Definition at line 105 of file subbarmanagement.cpp.
References signalMkdir().
Referenced by xSetup().
106 {
107   emit signalMkdir();
108 }
void SubBarManagement::slotBtnPaste () [slot]
Definition at line 110 of file subbarmanagement.cpp.
References singalPasteFUNC_MEDIAM().
Referenced by xSetup().
111 {
112   emit singalPasteFUNC_MEDIAM();
113 }
void SubBarManagement::slotChangeBtnImage () [private, slot]
Definition at line 89 of file subbarmanagement.cpp.
References em_mmimage, em_mmmusic, MMtype, SkinButton::setPixmaps(), signalManagementModeChange(), and SubBtnMM_MusicNImage.
Referenced by xSetup().
90 {
91    if(MMtype==em_mmmusic)
92    {
93       MMtype=em_mmimage;
94       SubBtnMM_MusicNImage->setPixmaps(BtnGraphic[10],BtnGraphic[11]);
95       emit signalManagementModeChange(0);
96    }
97    else
98    {
99      MMtype=em_mmmusic;
100      SubBtnMM_MusicNImage->setPixmaps(BtnGraphic[8],BtnGraphic[9]);
101      emit signalManagementModeChange(1);
102    }
103 }
void SubBarManagement::xSetup ()
Definition at line 33 of file subbarmanagement.cpp.
References em_mmmusic, MMtype, SkinButton::setPixmaps(), slotBtnCut(), slotBtnDelete(), slotBtnMkFloder(), slotBtnPaste(), slotChangeBtnImage(), SubBtnMM_Cut, SubBtnMM_Delete, SubBtnMM_Floder, SubBtnMM_MusicNImage, and SubBtnMM_Paste.
Referenced by SubBarManagement().
34 {
35    //DAVID Setup Background;
36    pixBackground.load("/root/kde_application/hdass08/skin/SubBarBackground.png");
37    setBackgroundPixmap(pixBackground);
38    
39    //DAVID init state
40    MMtype=em_mmmusic;
41    
42    //Btn Graphic
43    BtnGraphic[0]=new QPixmap("/root/kde_application/hdass08/skin/Bar-MM-Btn-Floder.png");
44    BtnGraphic[1]=new QPixmap("/root/kde_application/hdass08/skin/Bar-MM-Btn-Floder-Active.png");
45    BtnGraphic[2]=new QPixmap("/root/kde_application/hdass08/skin/Bar-MM-Btn-Paste.png");
46    BtnGraphic[3]=new QPixmap("/root/kde_application/hdass08/skin/Bar-MM-Btn-Paste-Active.png");
47    BtnGraphic[4]=new QPixmap("/root/kde_application/hdass08/skin/Bar-MM-Btn-Cut.png");
48    BtnGraphic[5]=new QPixmap("/root/kde_application/hdass08/skin/Bar-MM-Btn-Cut-Active.png");
49    BtnGraphic[6]=new QPixmap("/root/kde_application/hdass08/skin/Bar-MM-Btn-Delete.png");
50    BtnGraphic[7]=new QPixmap("/root/kde_application/hdass08/skin/Bar-MM-Btn-Delete-Active.png");
51    BtnGraphic[8]=new QPixmap("/root/kde_application/hdass08/skin/Bar-MM-Btn-Music.png");
52    BtnGraphic[9]=new QPixmap("/root/kde_application/hdass08/skin/Bar-MM-Btn-Music-Active.png");
53    BtnGraphic[10]=new QPixmap("/root/kde_application/hdass08/skin/Bar-MM-Btn-Image.png");
54    BtnGraphic[11]=new QPixmap("/root/kde_application/hdass08/skin/Bar-MM-Btn-Image-Active.png");
55    
56    SubBtnMM_Floder=new SkinButton(this);
57    SubBtnMM_Paste=new SkinButton(this);
58    SubBtnMM_Cut=new SkinButton(this);
59    SubBtnMM_Delete=new SkinButton(this);
60    SubBtnMM_MusicNImage=new SkinButton(this);
61    
62    SubBtnMM_Floder->setPixmaps(BtnGraphic[0],BtnGraphic[1]);
63    SubBtnMM_Floder->setGeometry(197,0,60,80);
64    SubBtnMM_Floder->show();
65    
66    SubBtnMM_Paste->setPixmaps(BtnGraphic[2],BtnGraphic[3]);
67    SubBtnMM_Paste->setGeometry(263,0,60,80);
68    SubBtnMM_Paste->show();
69    
70    SubBtnMM_Cut->setPixmaps(BtnGraphic[4],BtnGraphic[5]);
71    SubBtnMM_Cut->setGeometry(329,0,60,80);
72    SubBtnMM_Cut->show();
73    
74    SubBtnMM_Delete->setPixmaps(BtnGraphic[6],BtnGraphic[7]);
75    SubBtnMM_Delete->setGeometry(391,0,60,80);
76    SubBtnMM_Delete->show();
77    
78    SubBtnMM_MusicNImage->setPixmaps(BtnGraphic[8],BtnGraphic[9]);
79    SubBtnMM_MusicNImage->setGeometry(457,0,80,80);
80    SubBtnMM_MusicNImage->show();
81    
82    //DAVID Connect buttons
83    QObject::connect(SubBtnMM_MusicNImage,SIGNAL(pressed()),this,SLOT(slotChangeBtnImage()));
84    QObject::connect(SubBtnMM_Floder,SIGNAL(pressed()),this,SLOT(slotBtnMkFloder()));
85    QObject::connect(SubBtnMM_Paste,SIGNAL(pressed()),this,SLOT(slotBtnPaste()));
86    QObject::connect(SubBtnMM_Cut,SIGNAL(pressed()),this,SLOT(slotBtnCut()));
87    QObject::connect(SubBtnMM_Delete ,SIGNAL(pressed()),this,SLOT(slotBtnDelete()));
88 }
Member Data Documentation
QPixmap* SubBarManagement::BtnGraphic[12] [private]
Definition at line 54 of file subbarmanagement.h.
MM_TYPE SubBarManagement::MMtype [private]
Definition at line 55 of file subbarmanagement.h.
Referenced by slotChangeBtnImage(), and xSetup().
QPixmap SubBarManagement::pixBackground [private]
Definition at line 53 of file subbarmanagement.h.
SkinButton * SubBarManagement::SubBtnMM_Cut
Definition at line 38 of file subbarmanagement.h.
Referenced by xSetup().
SkinButton * SubBarManagement::SubBtnMM_Delete
Definition at line 38 of file subbarmanagement.h.
Referenced by xSetup().
SkinButton* SubBarManagement::SubBtnMM_Floder
Definition at line 38 of file subbarmanagement.h.
Referenced by xSetup().
SkinButton * SubBarManagement::SubBtnMM_MusicNImage
Definition at line 38 of file subbarmanagement.h.
Referenced by slotChangeBtnImage(), and xSetup().
SkinButton * SubBarManagement::SubBtnMM_Paste
Definition at line 38 of file subbarmanagement.h.
Referenced by xSetup().
The documentation for this class was generated from the following files:
subbarmanagement.h
subbarmanagement.moc
subbarmanagement.cpp