hdassplaylist Class Reference
#include <hdassplaylist.h>
Detailed Description
Author: sonicat
Definition at line 31 of file hdassplaylist.h.
Public Slots
void slotPLRequest ()
void slotReciveList (KURL::List list, HDASS_ACTION_TYPE act)
Signals
void signalPLSend (KURL::List)
Public Member Functions
hdassplaylist (QObject *parent=0, const char *name=0)
~hdassplaylist ()
void xSetup ()
void ReadListFile (QString FileName)
Public Attributes
QFile * List
KURL::List url_list
KURL::List url_list_cut_buffer
Private Member Functions
void RemoveList (KURL::List)
void CutList (KURL::List)
void PasteList ()
void SaveList ()
void AppendList (KURL::List)
Constructor & Destructor Documentation
hdassplaylist::hdassplaylist (QObject * parent = 0, const char * name = 0)
Definition at line 24 of file hdassplaylist.cpp.
References xSetup().
25  : QObject(parent, name)
26 {
27     xSetup();
28 }
hdassplaylist::~hdassplaylist ()
Definition at line 31 of file hdassplaylist.cpp.
References SaveList().
32 {
33      SaveList();
34 }
Member Function Documentation
void hdassplaylist::AppendList (KURL::List) [private]
Definition at line 152 of file hdassplaylist.cpp.
References signalPLSend(), and url_list.
Referenced by slotReciveList().
153 {
154     for(KURL::List::ConstIterator append_it = list.begin();append_it != list.end();append_it++)
155    {
156       url_list.append(*append_it);
157    }
158    emit signalPLSend(url_list);
159 }
void hdassplaylist::CutList (KURL::List) [private]
Definition at line 112 of file hdassplaylist.cpp.
References RemoveList(), and url_list_cut_buffer.
Referenced by slotReciveList().
113 {  
114   url_list_cut_buffer=cutlist;
115   RemoveList(cutlist);
116 }
void hdassplaylist::PasteList () [private]
Definition at line 117 of file hdassplaylist.cpp.
References signalPLSend(), url_list, and url_list_cut_buffer.
Referenced by slotReciveList().
118 {
119    for(KURL::List::ConstIterator paste_it = url_list_cut_buffer.begin();paste_it != url_list_cut_buffer.end();paste_it++)
120    {
121       url_list.append(*paste_it);
122    }
123    emit signalPLSend(url_list);
124 }
void hdassplaylist::ReadListFile (QString FileName)
Definition at line 42 of file hdassplaylist.cpp.
References List, and url_list.
Referenced by xSetup().
43 {
44    //Clear List
45    url_list.clear();
46    //ReadFile
47    kdDebug()<<FileName<<endl;
48    List =new QFile(FileName);
49    if ( List->open( IO_ReadOnly ) ) 
50    {
51         QTextStream stream( List );            
52         while ( !stream.atEnd() ) 
53         {
54                KURL url(stream.readLine()); // line of text excluding '\n'
55                QFile temp(url.path());
56                //check if the file exists
57                if(temp.exists())
58                {
59                        url_list << url;
60                }         
61              
62         }
63          kdError() << "Load Playlist "<< endl;
64         List->close();
65     }
66     else
67     {
68          kdError() << "PlayList:: "<<FileName<<"can't open!!"<< endl;
69         List->close();
70     }
71 }
void hdassplaylist::RemoveList (KURL::List) [private]
Definition at line 104 of file hdassplaylist.cpp.
References signalPLSend(), and url_list.
Referenced by CutList(), and slotReciveList().
105 {
106    for(KURL::List::ConstIterator remove_it = removelist.begin();remove_it != removelist.end();remove_it++)
107    {
108       url_list.remove(*remove_it);
109    }
110    emit signalPLSend(url_list);
111 }
void hdassplaylist::SaveList () [private]
Definition at line 125 of file hdassplaylist.cpp.
References GlobalSetting, List, HDASSGlobalSetting::ListFileName, and url_list.
Referenced by slotReciveList(), and ~hdassplaylist().
126 {
127   //DAVID New Save List File
128   List =new QFile(GlobalSetting.ListFileName);
129    if ( List->open( IO_WriteOnly ) ) 
130    {
131         QTextStream stream( List );
132         for( KURL::List::ConstIterator iterator = url_list.begin();iterator != url_list.end();iterator++)
133         {       
134             if(!(*iterator). isEmpty())
135             {
136                                 //DAVID Write to the file
137                 stream<<"file:"<<((*iterator).path())<<endl;
138             }   
139         }   
140         qWarning("SavePlayLists!!");
141         List->close();
142     }
143     else
144     {
145         
146         qWarning("PlayList can't be opened");
147         List->close();
148     }
149   
150 }
void hdassplaylist::signalPLSend (KURL::List) [signal]
Definition at line 96 of file hdassplaylist.moc.
Referenced by AppendList(), PasteList(), RemoveList(), and slotPLRequest().
97 {
98     if ( signalsBlocked() )
99         return;
100     QConnectionList *clist = receivers( staticMetaObject()->signalOffset() + 0 );
101     if ( !clist )
102         return;
103     QUObject o[2];
104     static_QUType_ptr.set(o+1,&t0);
105     activate_signal( clist, o );
106 }
void hdassplaylist::slotPLRequest () [slot]
Definition at line 72 of file hdassplaylist.cpp.
References signalPLSend(), and url_list.
73 {
74   //DAVID emit the playlist
75  
76   qWarning("hdassplaylist::slotPLRequest()");
77   emit signalPLSend(url_list);
78   
79 }
void hdassplaylist::slotReciveList (KURL::List list, HDASS_ACTION_TYPE act) [slot]
Definition at line 80 of file hdassplaylist.cpp.
References AppendList(), CutList(), em_cut, em_paste, em_remove, PasteList(), RemoveList(), and SaveList().
81 {
82   if(act==em_remove)
83   {
84    RemoveList(list);
85    SaveList();
86   }
87   else if(act==em_paste)
88   {
89     CutList(list);
90     SaveList();
91   }
92   else if(act==em_cut)
93   {
94     PasteList();
95     SaveList();
96   }
97   else 
98   {
99     AppendList(list);
100     SaveList();
101   }
102   
103 }
void hdassplaylist::xSetup ()
Definition at line 36 of file hdassplaylist.cpp.
References GlobalSetting, HDASSGlobalSetting::ListFileName, and ReadListFile().
Referenced by hdassplaylist().
37 {
38       //DAVID ReadListFile
39       ReadListFile(GlobalSetting.ListFileName);
40 }
Member Data Documentation
QFile* hdassplaylist::List
Definition at line 39 of file hdassplaylist.h.
Referenced by ReadListFile(), and SaveList().
KURL::List hdassplaylist::url_list
Definition at line 40 of file hdassplaylist.h.
Referenced by AppendList(), PasteList(), ReadListFile(), RemoveList(), SaveList(), and slotPLRequest().
KURL::List hdassplaylist::url_list_cut_buffer
Definition at line 40 of file hdassplaylist.h.
Referenced by CutList(), and PasteList().
The documentation for this class was generated from the following files:
hdassplaylist.h
hdassplaylist.moc
hdassplaylist.cpp