Amarok::RawScope Class Reference
#include <amarokarts.h>
Public Types
typedef RawScope_base _base_class
Public Member Functions
RawScope ()
RawScope (const Arts::SubClass &s)
RawScope (const Arts::Reference &r)
RawScope (const Arts::DynamicCast &c)
RawScope (const RawScope &target)
RawScope (Arts::Object::Pool &p)
RawScope & operator= (const RawScope &target)
operator Arts::StereoEffect () const
operator Arts::SynthModule () const
RawScope_base * _base ()
Arts::AutoSuspendState autoSuspend ()
void start ()
void stop ()
void streamInit ()
void streamStart ()
void streamEnd ()
long buffer ()
void buffer (long _newValue)
std::vector< float > * scope ()
Static Public Member Functions
RawScope null ()
RawScope _from_base (RawScope_base *b)
Protected Member Functions
RawScope (RawScope_base *b)
Private Member Functions
RawScope_base * _method_call ()
Static Private Member Functions
Arts::Object_base * _Creator ()
Private Attributes
RawScope_base * _cache
Member Typedef Documentation
typedef RawScope_base Amarok::RawScope::_base_class
Definition at line 205 of file amarokarts.h.
Constructor & Destructor Documentation
Amarok::RawScope::RawScope (RawScope_base * b) [inline, protected]
Definition at line 201 of file amarokarts.h.
201 : Arts::Object(b), _cache(0) {}
Amarok::RawScope::RawScope () [inline]
Definition at line 207 of file amarokarts.h.
Referenced by _from_base(), and null().
207 : Arts::Object(_Creator), _cache(0) {}
Amarok::RawScope::RawScope (const Arts::SubClass & s) [inline]
Definition at line 208 of file amarokarts.h.
208                                                :
209                 Arts::Object(RawScope_base::_create(s.string())), _cache(0) {}
        inline RawScope(const Arts::Reference &r) :
Amarok::RawScope::RawScope (const Arts::Reference & r) [inline]
Definition at line 210 of file amarokarts.h.
210                                                 :
211                 Arts::Object(r.isString()?(RawScope_base::_fromString(r.string())):(RawScope_base::_fromReference(r.reference(),true))), _cache(0) {}
        inline RawScope(const Arts::DynamicCast& c) : Arts::Object(RawScope_base::_fromDynamicCast(c.object())), _cache(0) {}
Amarok::RawScope::RawScope (const Arts::DynamicCast & c) [inline]
Definition at line 212 of file amarokarts.h.
212 : Arts::Object(RawScope_base::_fromDynamicCast(c.object())), _cache(0) {}
Amarok::RawScope::RawScope (const RawScope & target) [inline]
Definition at line 213 of file amarokarts.h.
213 : Arts::Object(target._pool), _cache(target._cache) {}
Amarok::RawScope::RawScope (Arts::Object::Pool & p) [inline]
Definition at line 214 of file amarokarts.h.
214 : Arts::Object(p), _cache(0) {}
Member Function Documentation
RawScope_base* Amarok::RawScope::_base () [inline]
Definition at line 227 of file amarokarts.h.
227 {return _cache?_cache:_method_call();}
Arts::Object_base * Amarok::RawScope::_Creator () [static, private]
Definition at line 377 of file amarokarts.cc.
References Amarok::RawScope_base::_create().
377                                           {
378         return Amarok::RawScope_base::_create();
379 }
RawScope Amarok::RawScope::_from_base (RawScope_base * b) [inline, static]
Definition at line 216 of file amarokarts.h.
References RawScope().
216 {return RawScope(b);}
RawScope_base* Amarok::RawScope::_method_call () [inline, private]
Definition at line 191 of file amarokarts.h.
References Amarok::RawScope_base::_cast().
Referenced by autoSuspend(), buffer(), scope(), start(), stop(), streamEnd(), streamInit(), and streamStart().
191                                              {
192                 _pool->checkcreate();
193                 if(_pool->base) {
194                         _cache=(RawScope_base *)_pool->base->_cast(RawScope_base::_IID);
195                         assert(_cache);
196                 }
197                 return _cache;
198         }
Arts::AutoSuspendState Amarok::RawScope::autoSuspend () [inline]
Definition at line 283 of file amarokarts.h.
References _method_call().
284 {
285         return _cache?static_cast<Arts::SynthModule_base*>(_cache)->autoSuspend():static_cast<Arts::SynthModule_base*>(_method_call())->autoSuspend();
286 }
void Amarok::RawScope::buffer (long _newValue) [inline]
Definition at line 318 of file amarokarts.h.
References _method_call(), and Amarok::RawScope_base::buffer().
319 {
320          _cache?static_cast<Amarok::RawScope_base*>(_cache)->buffer(_newValue):static_cast<Amarok::RawScope_base*>(_method_call())->buffer(_newValue);
321 }
long Amarok::RawScope::buffer () [inline]
Definition at line 313 of file amarokarts.h.
References _method_call(), and Amarok::RawScope_base::buffer().
Referenced by ArtsEngine::init().
314 {
315         return _cache?static_cast<Amarok::RawScope_base*>(_cache)->buffer():static_cast<Amarok::RawScope_base*>(_method_call())->buffer();
316 }
RawScope Amarok::RawScope::null () [inline, static]
Definition at line 215 of file amarokarts.h.
References RawScope().
Referenced by ArtsEngine::~ArtsEngine().
215 {return RawScope((RawScope_base*)0);}
Amarok::RawScope::operator Arts::StereoEffect () const [inline]
Definition at line 225 of file amarokarts.h.
References operator Arts::StereoEffect().
Referenced by operator Arts::StereoEffect().
225 { return Arts::StereoEffect(*_pool); }
Amarok::RawScope::operator Arts::SynthModule () const [inline]
Definition at line 226 of file amarokarts.h.
226 { return Arts::SynthModule(*_pool); }
RawScope& Amarok::RawScope::operator= (const RawScope & target) [inline]
Definition at line 217 of file amarokarts.h.
References _cache.
217                                                            {
218                 if (_pool == target._pool) return *this;
219                 _pool->Dec();
220                 _pool = target._pool;
221                 _cache = target._cache;
222                 _pool->Inc();
223                 return *this;
224         }
std::vector< float > * Amarok::RawScope::scope () [inline]
Definition at line 323 of file amarokarts.h.
References _method_call(), and Amarok::RawScope_base::scope().
Referenced by ArtsEngine::scope().
324 {
325         return _cache?static_cast<Amarok::RawScope_base*>(_cache)->scope():static_cast<Amarok::RawScope_base*>(_method_call())->scope();
326 }
void Amarok::RawScope::start () [inline]
Definition at line 288 of file amarokarts.h.
References _method_call().
Referenced by ArtsEngine::init().
289 {
290          _cache?static_cast<Arts::SynthModule_base*>(_cache)->start():static_cast<Arts::SynthModule_base*>(_method_call())->start();
291 }
void Amarok::RawScope::stop () [inline]
Definition at line 293 of file amarokarts.h.
References _method_call().
294 {
295          _cache?static_cast<Arts::SynthModule_base*>(_cache)->stop():static_cast<Arts::SynthModule_base*>(_method_call())->stop();
296 }
void Amarok::RawScope::streamEnd () [inline]
Definition at line 308 of file amarokarts.h.
References _method_call().
309 {
310          _cache?static_cast<Arts::SynthModule_base*>(_cache)->streamEnd():static_cast<Arts::SynthModule_base*>(_method_call())->streamEnd();
311 }
void Amarok::RawScope::streamInit () [inline]
Definition at line 298 of file amarokarts.h.
References _method_call().
299 {
300          _cache?static_cast<Arts::SynthModule_base*>(_cache)->streamInit():static_cast<Arts::SynthModule_base*>(_method_call())->streamInit();
301 }
void Amarok::RawScope::streamStart () [inline]
Definition at line 303 of file amarokarts.h.
References _method_call().
304 {
305          _cache?static_cast<Arts::SynthModule_base*>(_cache)->streamStart():static_cast<Arts::SynthModule_base*>(_method_call())->streamStart();
306 }
Member Data Documentation
RawScope_base* Amarok::RawScope::_cache [private]
Definition at line 190 of file amarokarts.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
amarokarts.h
amarokarts.cc