SubBarPlayer Class Reference
#include <subbarplayer.h>
Detailed Description
Author: sonicat
Definition at line 39 of file src/subbarplayer.h.
Public Slots
void handlePosition (int)
void handleVolume (int)
void handleSliderReleased ()
void handleSliderPressed ()
void handleNextPressed ()
void handleNextReleased ()
void handlePreviousPressed ()
void handlePreviousReleased ()
void handleForward ()
void handleBackward ()
void handleMessage (int m_length, int m_bitrate, QString m_title, QString m_artist, QString m_album)
void insertMedia (KURL::List list)
void removeMedia (KURL::List remove_list)
void initMedia (KURL::List list)
void ChangeBtnPlayPauseGraphic ()
void slotReceivePL (KURL::List list)
void slotReadList ()
void slotClickFromPlayList ()
void handlePosition (int)
void handleVolume (int)
void handleSliderReleased ()
void handleSliderPressed ()
void handleNextPressed ()
void handleNextReleased ()
void handlePreviousPressed ()
void handlePreviousReleased ()
void handleForward ()
void handleBackward ()
void handleMessage (int m_length, int m_bitrate, QString m_title, QString m_artist, QString m_album)
void insertMedia (KURL::List list)
void removeMedia (KURL::List remove_list)
void initMedia (KURL::List list)
void ChangeBtnPlayPauseGraphic ()
void slotReceivePL (KURL::List list)
void slotReadList ()
void slotClickFromPlayList ()
Signals
void signalRequestPL ()
void signalRequestPL ()
Public Member Functions
SubBarPlayer (QWidget *parent=0, const char *name=0)
~SubBarPlayer ()
void xSetup ()
SubBarPlayer (QWidget *parent=0, const char *name=0)
~SubBarPlayer ()
void xSetup ()
Public Attributes
QWidget * m_pAnalyzer
QSlider * playerPosition
QTimer * forwardTimer
QTimer * backwardTimer
Myplayer * m_player
KURL::List receive_list
SkinButton * SubBtnPlayer_PlayNPause
SkinButton * SubBtnPlayer_Backword
SkinButton * SubBtn_Forward
SkinButton * testBtn
QWidget * m_pAnalyzer
QSlider * playerPosition
QTimer * forwardTimer
QTimer * backwardTimer
Myplayer * m_player
SkinButton * SubBtnPlayer_PlayNPause
Private Types
enum PLAYSTATE { PAUSE,
GO
 }
enum PLAYSTATE { PAUSE,
GO
 }
Private Attributes
QPixmap pixBackground
QPixmap * BtnGraphic [8]
PLAYSTATE state
bool slider
QPixmap * BtnGraphic [8]
Member Enumeration Documentation
enum SubBarPlayer::PLAYSTATE [private]
Enumeration values:
PAUSE
GO
Definition at line 42 of file subbarplayer.h.
42 {PAUSE,GO};
enum SubBarPlayer::PLAYSTATE [private]
Enumeration values:
PAUSE
GO
Definition at line 42 of file src/subbarplayer.h.
42 {PAUSE,GO};
Constructor & Destructor Documentation
SubBarPlayer::SubBarPlayer (QWidget * parent = 0, const char * name = 0)
Definition at line 22 of file src/subbarplayer.cpp.
References m_player, slider, and xSetup().
23  : QWidget(parent, name)
24 {
25   //new Player here
26   m_player=new Myplayer;
27  
28   slider = true;
29   xSetup();
30 }
SubBarPlayer::~SubBarPlayer ()
Definition at line 33 of file src/subbarplayer.cpp.
References m_player.
34 {
35   delete m_player;
36 }
SubBarPlayer::SubBarPlayer (QWidget * parent = 0, const char * name = 0)
SubBarPlayer::~SubBarPlayer ()
Member Function Documentation
void SubBarPlayer::ChangeBtnPlayPauseGraphic () [slot]
void SubBarPlayer::ChangeBtnPlayPauseGraphic () [slot]
Definition at line 99 of file src/subbarplayer.cpp.
References GO, PAUSE, SkinButton::setPixmaps(), and SubBtnPlayer_PlayNPause.
Referenced by slotClickFromPlayList(), and xSetup().
100 {
101   if(state==SubBarPlayer::PAUSE)
102   {
103     state=SubBarPlayer::GO;
104     SubBtnPlayer_PlayNPause->setPixmaps(BtnGraphic[2],BtnGraphic[3]);
105   }
106   else
107   {
108     state=SubBarPlayer::PAUSE;
109     SubBtnPlayer_PlayNPause->setPixmaps(BtnGraphic[4],BtnGraphic[5]);
110   }
111 }
void SubBarPlayer::handleBackward () [slot]
void SubBarPlayer::handleBackward () [slot]
Definition at line 195 of file src/subbarplayer.cpp.
References playerPosition.
Referenced by xSetup().
196 {
197      kdDebug() << "[UI::handleBackward]" << endl;
198      int fast = playerPosition->value();
199      fast--;
200      playerPosition->setValue(fast);
201 }
void SubBarPlayer::handleForward () [slot]
void SubBarPlayer::handleForward () [slot]
Definition at line 171 of file src/subbarplayer.cpp.
References playerPosition.
Referenced by xSetup().
172 {
173      kdDebug() << "[UI::handleForward]" << endl;
174      int fast = playerPosition->value();
175      fast++;
176      playerPosition->setValue(fast);
177 //     Pos->setNum(fast);
178 }
void SubBarPlayer::handleMessage (int m_length, int m_bitrate, QString m_title, QString m_artist, QString m_album) [slot]
void SubBarPlayer::handleMessage (int m_length, int m_bitrate, QString m_title, QString m_artist, QString m_album) [slot]
Definition at line 203 of file src/subbarplayer.cpp.
References playerPosition.
Referenced by xSetup().
204 {
205         playerPosition->setMaxValue(m_length);
206 }
void SubBarPlayer::handleNextPressed () [slot]
void SubBarPlayer::handleNextPressed () [slot]
Definition at line 155 of file src/subbarplayer.cpp.
References forwardTimer, and slider.
156 {
157      kdDebug() << "Next Pressed"<< endl;
158      forwardTimer->start( 100 );
159      slider = false;
160      
161 }
void SubBarPlayer::handleNextReleased () [slot]
void SubBarPlayer::handleNextReleased () [slot]
Definition at line 163 of file src/subbarplayer.cpp.
References forwardTimer, Myplayer::handleSlider(), m_player, playerPosition, and slider.
164 {
165      kdDebug() << "Next Released" << endl;
166      forwardTimer->stop();
167      m_player->handleSlider(playerPosition->value());
168      slider = true;
169 }
void SubBarPlayer::handlePosition (int) [slot]
void SubBarPlayer::handlePosition (int) [slot]
Definition at line 134 of file src/subbarplayer.cpp.
References playerPosition, and slider.
Referenced by xSetup().
135 {
136 
137      if(slider)playerPosition->setValue(position);    
138 }
void SubBarPlayer::handlePreviousPressed () [slot]
void SubBarPlayer::handlePreviousPressed () [slot]
Definition at line 180 of file src/subbarplayer.cpp.
References backwardTimer, and slider.
181 {
182      kdDebug() << "Previous Pressed"<< endl;
183      backwardTimer->start( 100 );
184      slider = false;
185 }
void SubBarPlayer::handlePreviousReleased () [slot]
void SubBarPlayer::handlePreviousReleased () [slot]
Definition at line 187 of file src/subbarplayer.cpp.
References backwardTimer, Myplayer::handleSlider(), m_player, playerPosition, and slider.
188 {
189      kdDebug() << "Previous Released" << endl;
190      backwardTimer->stop();
191      m_player->handleSlider(playerPosition->value());
192      slider = true;
193 }
void SubBarPlayer::handleSliderPressed () [slot]
void SubBarPlayer::handleSliderPressed () [slot]
Definition at line 150 of file src/subbarplayer.cpp.
References slider.
Referenced by xSetup().
151 {
152      slider = false;
153 }
void SubBarPlayer::handleSliderReleased () [slot]
void SubBarPlayer::handleSliderReleased () [slot]
Definition at line 144 of file src/subbarplayer.cpp.
References Myplayer::handleSlider(), m_player, playerPosition, and slider.
Referenced by xSetup().
145 {
146      m_player->handleSlider(playerPosition->value());
147      slider = true;   
148 }
void SubBarPlayer::handleVolume (int) [slot]
void SubBarPlayer::handleVolume (int) [slot]
Definition at line 140 of file src/subbarplayer.cpp.
141 {
142 }
void SubBarPlayer::initMedia (KURL::List list) [slot]
void SubBarPlayer::initMedia (KURL::List list) [slot]
Definition at line 126 of file src/subbarplayer.cpp.
References Myplayer::handleRepeat(), Myplayer::initlist(), and m_player.
127 {
128         m_player->initlist(list);
129         m_player->handleRepeat(false);
130         kdDebug() << "[playercontrol]initMedia "<< endl; 
131 }
void SubBarPlayer::insertMedia (KURL::List list) [slot]
void SubBarPlayer::insertMedia (KURL::List list) [slot]
Definition at line 113 of file src/subbarplayer.cpp.
References Myplayer::add(), Myplayer::handleRepeat(), and m_player.
114 {
115      
116      m_player->add(list);
117      m_player->handleRepeat(true);
118      kdDebug() << "[playercontrol]insertMedia "<< endl; 
119      
120 }
void SubBarPlayer::removeMedia (KURL::List remove_list) [slot]
void SubBarPlayer::removeMedia (KURL::List remove_list) [slot]
Definition at line 122 of file src/subbarplayer.cpp.
References m_player, and Myplayer::removeMedia().
123 {
124      m_player->removeMedia(remove_list); 
125 }
void SubBarPlayer::signalRequestPL () [signal]
void SubBarPlayer::signalRequestPL () [signal]
Definition at line 143 of file subbarplayer.moc.
Referenced by slotReadList().
144 {
145     activate_signal( staticMetaObject()->signalOffset() + 0 );
146 }
void SubBarPlayer::slotClickFromPlayList () [slot]
void SubBarPlayer::slotClickFromPlayList () [slot]
Definition at line 218 of file src/subbarplayer.cpp.
References ChangeBtnPlayPauseGraphic(), and GO.
219 {
220   state=SubBarPlayer::GO;
221   ChangeBtnPlayPauseGraphic();
222 }
void SubBarPlayer::slotReadList () [slot]
void SubBarPlayer::slotReadList () [slot]
Definition at line 213 of file src/subbarplayer.cpp.
References signalRequestPL().
Referenced by xSetup().
214 {
215    emit signalRequestPL();
216   //insertMedia(receive_list);
217 }
void SubBarPlayer::slotReceivePL (KURL::List list) [slot]
void SubBarPlayer::slotReceivePL (KURL::List list) [slot]
Definition at line 208 of file src/subbarplayer.cpp.
References receive_list.
209 {
210   receive_list=list;
211 }
void SubBarPlayer::xSetup ()
void SubBarPlayer::xSetup ()
Definition at line 38 of file src/subbarplayer.cpp.
References backwardTimer, ChangeBtnPlayPauseGraphic(), forwardTimer, GO, handleBackward(), handleForward(), handleMessage(), handlePosition(), handleSliderPressed(), handleSliderReleased(), m_player, playerPosition, SkinButton::setPixmaps(), slotReadList(), SubBtn_Forward, SubBtnPlayer_Backword, and SubBtnPlayer_PlayNPause.
Referenced by SubBarPlayer().
39 {
40    //DAVID Setup Background;
41    pixBackground.load("/root/kde_application/hdass08/skin/SubBarBackground.png");
42    setBackgroundPixmap(pixBackground);
43    
44    //DAVID Load BtnGraphic
45    BtnGraphic[0]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Player-Btn-Previous.png");
46    BtnGraphic[1]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Player-Btn-Previous-Active.png");
47    BtnGraphic[2]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Player-Btn-Play.png");
48    BtnGraphic[3]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Player-Btn-Play-Active.png");
49    BtnGraphic[4]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Player-Btn-Pause.png");
50    BtnGraphic[5]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Player-Btn-Pause-Active.png");
51    BtnGraphic[6]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Player-Btn-Next.png");
52    BtnGraphic[7]=new QPixmap("/root/kde_application/hdass08/skin/Bar-Player-Btn-Next-Active.png");
53   
54    
55    SubBtnPlayer_PlayNPause =new SkinButton(this);
56    SubBtnPlayer_Backword     =new SkinButton(this);
57    SubBtn_Forward                =new SkinButton(this);
58    
59    SubBtnPlayer_Backword->setPixmaps(BtnGraphic[0],BtnGraphic[1]);
60    SubBtnPlayer_Backword->setGeometry(336,0,60,80);
61    SubBtnPlayer_Backword->show();
62    
63    SubBtnPlayer_PlayNPause->setPixmaps(BtnGraphic[2],BtnGraphic[3]);
64    SubBtnPlayer_PlayNPause->setGeometry(403,0,80,80);
65    SubBtnPlayer_PlayNPause->show();
66    
67    SubBtn_Forward->setPixmaps(BtnGraphic[6],BtnGraphic[7]);
68    SubBtn_Forward->setGeometry(484,0,60,80);
69    SubBtn_Forward->show();
70    
71    //DAVID Pos Slider
72    playerPosition = new QSlider(0,100,1,0,Qt::Horizontal,this);
73    playerPosition->setGeometry( QRect(10,39,300,15) );
74    //playerPosition->show();
75    
76    
77    QObject::connect(SubBtnPlayer_PlayNPause, SIGNAL(clicked()), m_player, SLOT(play()));
78    QObject::connect(SubBtnPlayer_PlayNPause,SIGNAL(clicked()),this,SLOT(ChangeBtnPlayPauseGraphic()));
79    QObject::connect(SubBtn_Forward, SIGNAL(clicked()), m_player, SLOT(next()));
80    QObject::connect(SubBtnPlayer_Backword, SIGNAL(clicked()), m_player, SLOT(previous()));
81 
82    state=SubBarPlayer::GO;
83    
84    connect(m_player, SIGNAL(positionMessage(int)), this, SLOT(handlePosition(int )));
85    connect(m_player,SIGNAL(trackMessage(int, int, QString, QString, QString )),this,SLOT(handleMessage(int, int, QString, QString, QString )));
86    connect(playerPosition, SIGNAL(sliderPressed()), this, SLOT(handleSliderPressed()));
87    connect(playerPosition, SIGNAL(sliderReleased()), this, SLOT(handleSliderReleased()));
88    
89     forwardTimer = new QTimer( this ); // create internal timer
90     connect( forwardTimer, SIGNAL(timeout()),this, SLOT(handleForward()) );
91 
92     
93     backwardTimer = new QTimer( this );
94     connect( backwardTimer, SIGNAL(timeout()), this, SLOT(handleBackward()) );
95     
96     slotReadList();
97 }
Member Data Documentation
QTimer* SubBarPlayer::backwardTimer
Definition at line 52 of file subbarplayer.h.
QTimer* SubBarPlayer::backwardTimer
Definition at line 52 of file src/subbarplayer.h.
Referenced by handlePreviousPressed(), handlePreviousReleased(), and xSetup().
QPixmap* SubBarPlayer::BtnGraphic[8] [private]
Definition at line 59 of file subbarplayer.h.
QPixmap* SubBarPlayer::BtnGraphic[8] [private]
Definition at line 59 of file src/subbarplayer.h.
QTimer* SubBarPlayer::forwardTimer
Definition at line 51 of file subbarplayer.h.
QTimer* SubBarPlayer::forwardTimer
Definition at line 51 of file src/subbarplayer.h.
Referenced by handleNextPressed(), handleNextReleased(), and xSetup().
QWidget* SubBarPlayer::m_pAnalyzer
Definition at line 49 of file subbarplayer.h.
QWidget* SubBarPlayer::m_pAnalyzer
Definition at line 49 of file src/subbarplayer.h.
Myplayer* SubBarPlayer::m_player
Definition at line 53 of file subbarplayer.h.
Myplayer* SubBarPlayer::m_player
Definition at line 53 of file src/subbarplayer.h.
Referenced by handleNextReleased(), handlePreviousReleased(), handleSliderReleased(), initMedia(), insertMedia(), removeMedia(), SubBarPlayer(), xSetup(), HDASS08::xSetup(), and ~SubBarPlayer().
QPixmap SubBarPlayer::pixBackground [private]
Definition at line 58 of file subbarplayer.h.
QSlider* SubBarPlayer::playerPosition
Definition at line 50 of file subbarplayer.h.
QSlider* SubBarPlayer::playerPosition
Definition at line 50 of file src/subbarplayer.h.
Referenced by handleBackward(), handleForward(), handleMessage(), handleNextReleased(), handlePosition(), handlePreviousReleased(), handleSliderReleased(), and xSetup().
KURL::List SubBarPlayer::receive_list
Definition at line 54 of file subbarplayer.h.
Referenced by slotReceivePL().
bool SubBarPlayer::slider [private]
Definition at line 61 of file subbarplayer.h.
Referenced by handleNextPressed(), handleNextReleased(), handlePosition(), handlePreviousPressed(), handlePreviousReleased(), handleSliderPressed(), handleSliderReleased(), and SubBarPlayer().
PLAYSTATE SubBarPlayer::state [private]
Definition at line 60 of file subbarplayer.h.
SkinButton * SubBarPlayer::SubBtn_Forward
Definition at line 55 of file subbarplayer.h.
Referenced by xSetup().
SkinButton * SubBarPlayer::SubBtnPlayer_Backword
Definition at line 55 of file subbarplayer.h.
Referenced by xSetup().
SkinButton* SubBarPlayer::SubBtnPlayer_PlayNPause
Definition at line 55 of file subbarplayer.h.
SkinButton* SubBarPlayer::SubBtnPlayer_PlayNPause
Definition at line 55 of file src/subbarplayer.h.
Referenced by ChangeBtnPlayPauseGraphic(), and xSetup().
SkinButton * SubBarPlayer::testBtn
Definition at line 55 of file subbarplayer.h.
The documentation for this class was generated from the following files:
src/subbarplayer.h
subbarplayer.h
subbarplayer.moc
src/subbarplayer.cpp
subbarplayer.cpp