HDASSPlayListItem Class Reference
#include <hdassplaylistitem.h>
Detailed Description
Author: sonicat
Definition at line 26 of file hdassplaylistitem.h.
Public Member Functions
HDASSPlayListItem (QListView *parent=0, const QString &text=0, Type tt=RadioButtonController)
~HDASSPlayListItem ()
void setup ()
HDASSPlayListItem (QListView *parent=0, const QString &text=0)
~HDASSPlayListItem ()
void setup ()
Constructor & Destructor Documentation
HDASSPlayListItem::HDASSPlayListItem (QListView * parent = 0, const QString & text = 0, Type tt = RadioButtonController)
Definition at line 22 of file hdassplaylistitem.cpp.
References setup().
22                                                                                         : QCheckListItem(parent,text,tt)
23 {
24   setup();
25 }
HDASSPlayListItem::~HDASSPlayListItem ()
Definition at line 27 of file hdassplaylistitem.cpp.
28 {
29 
30 }
HDASSPlayListItem::HDASSPlayListItem (QListView * parent = 0, const QString & text = 0)
Definition at line 22 of file src/hdassplaylistitem.cpp.
References setup().
22                                                                                : QListViewItem(parent,text)
23 {
24   setup();
25 }
HDASSPlayListItem::~HDASSPlayListItem ()
Member Function Documentation
void HDASSPlayListItem::setup ()
void HDASSPlayListItem::setup ()
Definition at line 32 of file hdassplaylistitem.cpp.
Referenced by HDASSPlayListItem().
33 {
34   QCheckListItem::setup();
35   setHeight(40);
36 }
The documentation for this class was generated from the following files:
hdassplaylistitem.h
src/hdassplaylistitem.h
hdassplaylistitem.cpp
src/hdassplaylistitem.cpp