hdassClock Class Reference
#include <hdassclock.h>
Public Slots
void setTime (const QTime &t)
Public Member Functions
hdassClock (QWidget *parent=0, const char *name=0)
void xSetup ()
~hdassClock ()
Protected Member Functions
void updateMask ()
void paintEvent (QPaintEvent *)
void drawClock (QPainter *)
Private Slots
void timeout ()
Private Attributes
QPoint clickPos
QTime time
QTimer * internalTimer
QPixmap pixBackground
Constructor & Destructor Documentation
hdassClock::hdassClock (QWidget * parent = 0, const char * name = 0)
Definition at line 24 of file hdassclock.cpp.
References xSetup().
25  : QWidget(parent, name)
26 {
27    xSetup();
28 }
hdassClock::~hdassClock ()
Definition at line 31 of file hdassclock.cpp.
32 {
33 
34 }
Member Function Documentation
void hdassClock::drawClock (QPainter *) [protected]
Definition at line 100 of file hdassclock.cpp.
References time.
Referenced by paintEvent(), and updateMask().
101 {
102     paint->setPen(Qt::white);
103     paint->save();
104     
105     paint->setWindow( -500,-500, 1000,1000 );
106 
107     QRect v = paint->viewport();
108     int d = QMIN( v.width(), v.height() );
109     paint->setViewport( v.left() + (v.width()-d)/2,v.top() + (v.height()-d)/2, d, d );
110     QPointArray pts;
111 
112     paint->save();
113     
114     paint->rotate( 30*(time.hour()%12-3) + time.minute()/2 ); 
115     QPixmap hr;
116     hr.load("/root/kde_application/hdass08/skin/hdassClockArrowHr.png"); 
117     paint->drawPixmap(0,(hr.height()/2)-100,hr);
118     paint->restore();
119 
120     paint->save();
121     paint->rotate( (time.minute()-15)*6 );
122     QPixmap min;
123     min.load("/root/kde_application/hdass08/skin/hdassClockArrowMin.png");
124     paint->drawPixmap(0,(min.height()/2)-90,min);
125     paint->restore();
126 }
void hdassClock::paintEvent (QPaintEvent *) [protected]
Definition at line 73 of file hdassclock.cpp.
References drawClock().
74 {
75     if ( autoMask() )
76         return;
77     QPainter paint( this );
78     paint.setBrush( colorGroup().foreground() );
79     drawClock( &paint );
80 }
void hdassClock::setTime (const QTime & t) [slot]
Definition at line 49 of file hdassclock.cpp.
References internalTimer, time, timeout(), and updateMask().
50 {
51   time = t;
52     disconnect( internalTimer, SIGNAL(timeout()), this, SLOT(timeout()) );
53     if (autoMask())
54         updateMask();
55     else
56         update();
57  
58 }
void hdassClock::timeout () [private, slot]
Definition at line 60 of file hdassclock.cpp.
References time, and updateMask().
Referenced by setTime(), and xSetup().
61 {
62     QTime old_time = time;
63     time = QTime::currentTime();
64     if ( old_time.minute() != time.minute() 
65         || old_time.hour() != time.hour() ) {   // minute or hour has changed
66         if (autoMask())
67             updateMask();
68         else
69             update();
70     }
71 }
void hdassClock::updateMask () [protected]
Definition at line 82 of file hdassclock.cpp.
References drawClock().
Referenced by setTime(), and timeout().
83 {
84    QBitmap bm( size() );
85     //bm.fill( color0 );                        //transparent
86 
87     QPainter paint;
88     paint.begin( &bm, this );
89     QBrush brush=QBrush(white);
90     brush.setStyle(SolidPattern); 
91     paint.setBrush( brush );            // use non-transparent color
92     paint.setPen(color1);
93 
94     drawClock( &paint );
95 
96     paint.end();
97     setMask( bm );
98 }
void hdassClock::xSetup ()
Definition at line 36 of file hdassclock.cpp.
References internalTimer, time, and timeout().
Referenced by hdassClock().
37 {
38     time = QTime::currentTime();                // get current time
39     internalTimer = new QTimer( this ); // create internal timer
40     connect( internalTimer, SIGNAL(timeout()), SLOT(timeout()) );
41     internalTimer->start( 5000 );               // emit signal every 5 seconds
42     
43     //DAVID Setbackgorund
44     pixBackground.load("/root/kde_application/hdass08/skin/ClockBackground.png");
45     setBackgroundPixmap(pixBackground);
46     
47 }
Member Data Documentation
QPoint hdassClock::clickPos [private]
Definition at line 53 of file hdassclock.h.
QTimer* hdassClock::internalTimer [private]
Definition at line 55 of file hdassclock.h.
Referenced by setTime(), and xSetup().
QPixmap hdassClock::pixBackground [private]
Definition at line 56 of file hdassclock.h.
QTime hdassClock::time [private]
Definition at line 54 of file hdassclock.h.
Referenced by drawClock(), setTime(), timeout(), and xSetup().
The documentation for this class was generated from the following files:
hdassclock.h
hdassclock.cpp