AmarokConfig Class Reference
#include <amarokconfig.h>
Public Member Functions
~AmarokConfig ()
Static Public Member Functions
AmarokConfig * self ()
void setVersion (const QString &v)
QString version ()
void setPlayerPos (const QPoint &v)
QPoint playerPos ()
void setPlaylistWindowPos (const QPoint &v)
QPoint playlistWindowPos ()
void setPlaylistWindowSize (const QSize &v)
QSize playlistWindowSize ()
void setSavePlaylist (bool v)
bool savePlaylist ()
void setFollowSymlinks (bool v)
bool followSymlinks ()
void setTimeDisplayRemaining (bool v)
bool timeDisplayRemaining ()
void setRepeatTrack (bool v)
bool repeatTrack ()
void setRepeatPlaylist (bool v)
bool repeatPlaylist ()
void setRandomMode (bool v)
bool randomMode ()
void setShowMetaInfo (bool v)
bool showMetaInfo ()
void setShowTrayIcon (bool v)
bool showTrayIcon ()
void setShowPlayerWindow (bool v)
bool showPlayerWindow ()
void setShowStatusBar (bool v)
bool showStatusBar ()
void setShowWelcomeTab (bool v)
bool showWelcomeTab ()
void setDirectoriesRecursively (bool v)
bool directoriesRecursively ()
void setTrackDelayLength (int v)
int trackDelayLength ()
void setHidePlaylistWindow (bool v)
bool hidePlaylistWindow ()
void setPlaylistWindowEnabled (bool v)
bool playlistWindowEnabled ()
void setUndoLevels (int v)
int undoLevels ()
void setCurrentAnalyzer (int v)
int currentAnalyzer ()
void setRememberEffects (bool v)
bool rememberEffects ()
void setPlaylistWindowSplitter (const QValueList< int > &v)
QValueList< int > playlistWindowSplitter ()
void setPlaylistFollowActive (bool v)
bool playlistFollowActive ()
void setShowSplashscreen (bool v)
bool showSplashscreen ()
void setMasterVolume (int v)
int masterVolume ()
void setHardwareMixer (bool v)
bool hardwareMixer ()
void setCrossfade (bool v)
bool crossfade ()
void setCrossfadeLength (int v)
int crossfadeLength ()
void setSoundSystem (const QString &v)
QString soundSystem ()
void setSoundOutput (const QString &v)
QString soundOutput ()
void setSoundDevice (const QString &v)
QString soundDevice ()
void setCustomSoundDevice (bool v)
bool customSoundDevice ()
void setTitleStreaming (bool v)
bool titleStreaming ()
void setOsdEnabled (bool v)
bool osdEnabled ()
void setOsdFont (const QFont &v)
QFont osdFont ()
void setOsdDrawShadow (bool v)
bool osdDrawShadow ()
void setOsdUseCustomColors (bool v)
bool osdUseCustomColors ()
void setOsdTextColor (const QColor &v)
QColor osdTextColor ()
void setOsdBackgroundColor (const QColor &v)
QColor osdBackgroundColor ()
void setOsdDuration (int v)
int osdDuration ()
void setOsdXOffset (int v)
int osdXOffset ()
void setOsdYOffset (int v)
int osdYOffset ()
void setOsdScreen (int v)
int osdScreen ()
void setOsdAlignment (int v)
int osdAlignment ()
void setUseCustomFonts (bool v)
bool useCustomFonts ()
void setPlaylistWindowFont (const QFont &v)
QFont playlistWindowFont ()
void setPlayerWidgetFont (const QFont &v)
QFont playerWidgetFont ()
void setPlayerWidgetScrollFont (const QFont &v)
QFont playerWidgetScrollFont ()
void setSchemeAmarok (bool v)
bool schemeAmarok ()
void setSchemeKDE (bool v)
bool schemeKDE ()
void setSchemeCustom (bool v)
bool schemeCustom ()
void setPlaylistWindowFgColor (const QColor &v)
QColor playlistWindowFgColor ()
void setPlaylistWindowBgColor (const QColor &v)
QColor playlistWindowBgColor ()
void setResumePlayback (bool v)
bool resumePlayback ()
void setResumeTrack (const QString &v)
QString resumeTrack ()
void setResumeTime (int v)
int resumeTime ()
void writeConfig ()
Protected Member Functions
AmarokConfig ()
Protected Attributes
QString mVersion
QPoint mPlayerPos
QPoint mPlaylistWindowPos
QSize mPlaylistWindowSize
bool mSavePlaylist
bool mFollowSymlinks
bool mTimeDisplayRemaining
bool mRepeatTrack
bool mRepeatPlaylist
bool mRandomMode
bool mShowMetaInfo
bool mShowTrayIcon
bool mShowPlayerWindow
bool mShowStatusBar
bool mShowWelcomeTab
bool mDirectoriesRecursively
int mTrackDelayLength
bool mHidePlaylistWindow
bool mPlaylistWindowEnabled
int mUndoLevels
int mCurrentAnalyzer
bool mRememberEffects
QValueList< int > mPlaylistWindowSplitter
bool mPlaylistFollowActive
bool mShowSplashscreen
int mMasterVolume
bool mHardwareMixer
bool mCrossfade
int mCrossfadeLength
QString mSoundSystem
QString mSoundOutput
QString mSoundDevice
bool mCustomSoundDevice
bool mTitleStreaming
bool mOsdEnabled
QFont mOsdFont
bool mOsdDrawShadow
bool mOsdUseCustomColors
QColor mOsdTextColor
QColor mOsdBackgroundColor
int mOsdDuration
int mOsdXOffset
int mOsdYOffset
int mOsdScreen
int mOsdAlignment
bool mUseCustomFonts
QFont mPlaylistWindowFont
QFont mPlayerWidgetFont
QFont mPlayerWidgetScrollFont
bool mSchemeAmarok
bool mSchemeKDE
bool mSchemeCustom
QColor mPlaylistWindowFgColor
QColor mPlaylistWindowBgColor
bool mResumePlayback
QString mResumeTrack
int mResumeTime
Static Protected Attributes
AmarokConfig * mSelf = 0
Constructor & Destructor Documentation
AmarokConfig::~AmarokConfig ()
Definition at line 249 of file amarokconfig.cpp.
References mSelf, and staticDeleter.
250 {
251   if ( mSelf == this )
252     staticDeleter.setObject( mSelf, 0, false );
253 }
AmarokConfig::AmarokConfig () [protected]
Definition at line 22 of file amarokconfig.cpp.
References mCrossfade, mCrossfadeLength, mCurrentAnalyzer, mCustomSoundDevice, mDirectoriesRecursively, mFollowSymlinks, mHardwareMixer, mHidePlaylistWindow, mMasterVolume, mOsdAlignment, mOsdBackgroundColor, mOsdDrawShadow, mOsdDuration, mOsdEnabled, mOsdFont, mOsdScreen, mOsdTextColor, mOsdUseCustomColors, mOsdXOffset, mOsdYOffset, mPlayerPos, mPlayerWidgetFont, mPlayerWidgetScrollFont, mPlaylistFollowActive, mPlaylistWindowBgColor, mPlaylistWindowEnabled, mPlaylistWindowFgColor, mPlaylistWindowFont, mPlaylistWindowPos, mPlaylistWindowSize, mPlaylistWindowSplitter, mRandomMode, mRememberEffects, mRepeatPlaylist, mRepeatTrack, mResumePlayback, mResumeTime, mResumeTrack, mSavePlaylist, mSchemeAmarok, mSchemeCustom, mSchemeKDE, mSelf, mShowMetaInfo, mShowPlayerWindow, mShowSplashscreen, mShowStatusBar, mShowTrayIcon, mShowWelcomeTab, mSoundDevice, mSoundOutput, mSoundSystem, mTimeDisplayRemaining, mTitleStreaming, mTrackDelayLength, mUndoLevels, mUseCustomFonts, and mVersion.
Referenced by self().
23   : KConfigSkeleton( "amarokrc" )
24 {
25   mSelf = this;
26   setCurrentGroup( "General Options" );
27 
28   KConfigSkeleton::ItemString  *itemVersion;
29   itemVersion = new KConfigSkeleton::ItemString( currentGroup(), "Version", mVersion );
30   addItem( itemVersion );
31   KConfigSkeleton::ItemPoint  *itemPlayerPos;
32   itemPlayerPos = new KConfigSkeleton::ItemPoint( currentGroup(), "Player Pos", mPlayerPos, QPoint(-1,-1) );
33   addItem( itemPlayerPos, "PlayerPos" );
34   KConfigSkeleton::ItemPoint  *itemPlaylistWindowPos;
35   itemPlaylistWindowPos = new KConfigSkeleton::ItemPoint( currentGroup(), "Playlist Window Pos", mPlaylistWindowPos, QPoint(-1,-1) );
36   addItem( itemPlaylistWindowPos, "PlaylistWindowPos" );
37   KConfigSkeleton::ItemSize  *itemPlaylistWindowSize;
38   itemPlaylistWindowSize = new KConfigSkeleton::ItemSize( currentGroup(), "Playlist Window Size", mPlaylistWindowSize, QSize(600,450) );
39   addItem( itemPlaylistWindowSize, "PlaylistWindowSize" );
40   KConfigSkeleton::ItemBool  *itemSavePlaylist;
41   itemSavePlaylist = new KConfigSkeleton::ItemBool( currentGroup(), "Save Playlist", mSavePlaylist, true );
42   addItem( itemSavePlaylist, "SavePlaylist" );
43   KConfigSkeleton::ItemBool  *itemFollowSymlinks;
44   itemFollowSymlinks = new KConfigSkeleton::ItemBool( currentGroup(), "Follow Symlinks", mFollowSymlinks, true );
45   addItem( itemFollowSymlinks, "FollowSymlinks" );
46   KConfigSkeleton::ItemBool  *itemTimeDisplayRemaining;
47   itemTimeDisplayRemaining = new KConfigSkeleton::ItemBool( currentGroup(), "Time Display Remaining", mTimeDisplayRemaining, false );
48   addItem( itemTimeDisplayRemaining, "TimeDisplayRemaining" );
49   KConfigSkeleton::ItemBool  *itemRepeatTrack;
50   itemRepeatTrack = new KConfigSkeleton::ItemBool( currentGroup(), "Repeat Track", mRepeatTrack, false );
51   addItem( itemRepeatTrack, "RepeatTrack" );
52   KConfigSkeleton::ItemBool  *itemRepeatPlaylist;
53   itemRepeatPlaylist = new KConfigSkeleton::ItemBool( currentGroup(), "Repeat Playlist", mRepeatPlaylist, false );
54   addItem( itemRepeatPlaylist, "RepeatPlaylist" );
55   KConfigSkeleton::ItemBool  *itemRandomMode;
56   itemRandomMode = new KConfigSkeleton::ItemBool( currentGroup(), "Random Mode", mRandomMode, false );
57   addItem( itemRandomMode, "RandomMode" );
58   KConfigSkeleton::ItemBool  *itemShowMetaInfo;
59   itemShowMetaInfo = new KConfigSkeleton::ItemBool( currentGroup(), "Show Meta Info", mShowMetaInfo, true );
60   addItem( itemShowMetaInfo, "ShowMetaInfo" );
61   KConfigSkeleton::ItemBool  *itemShowTrayIcon;
62   itemShowTrayIcon = new KConfigSkeleton::ItemBool( currentGroup(), "Show Tray Icon", mShowTrayIcon, true );
63   addItem( itemShowTrayIcon, "ShowTrayIcon" );
64   KConfigSkeleton::ItemBool  *itemShowPlayerWindow;
65   itemShowPlayerWindow = new KConfigSkeleton::ItemBool( currentGroup(), "Show Player Window", mShowPlayerWindow, true );
66   addItem( itemShowPlayerWindow, "ShowPlayerWindow" );
67   KConfigSkeleton::ItemBool  *itemShowStatusBar;
68   itemShowStatusBar = new KConfigSkeleton::ItemBool( currentGroup(), "Show Status Bar", mShowStatusBar, false );
69   addItem( itemShowStatusBar, "ShowStatusBar" );
70   KConfigSkeleton::ItemBool  *itemShowWelcomeTab;
71   itemShowWelcomeTab = new KConfigSkeleton::ItemBool( currentGroup(), "Show Welcome Tab", mShowWelcomeTab, true );
72   addItem( itemShowWelcomeTab, "ShowWelcomeTab" );
73   KConfigSkeleton::ItemBool  *itemDirectoriesRecursively;
74   itemDirectoriesRecursively = new KConfigSkeleton::ItemBool( currentGroup(), "Directories Recursively", mDirectoriesRecursively, true );
75   addItem( itemDirectoriesRecursively, "DirectoriesRecursively" );
76   KConfigSkeleton::ItemInt  *itemTrackDelayLength;
77   itemTrackDelayLength = new KConfigSkeleton::ItemInt( currentGroup(), "Track Delay Length", mTrackDelayLength, 0 );
78   addItem( itemTrackDelayLength, "TrackDelayLength" );
79   KConfigSkeleton::ItemBool  *itemHidePlaylistWindow;
80   itemHidePlaylistWindow = new KConfigSkeleton::ItemBool( currentGroup(), "Hide Playlist Window", mHidePlaylistWindow, true );
81   addItem( itemHidePlaylistWindow, "HidePlaylistWindow" );
82   KConfigSkeleton::ItemBool  *itemPlaylistWindowEnabled;
83   itemPlaylistWindowEnabled = new KConfigSkeleton::ItemBool( currentGroup(), "Playlist Window Enabled", mPlaylistWindowEnabled, true );
84   addItem( itemPlaylistWindowEnabled, "PlaylistWindowEnabled" );
85   KConfigSkeleton::ItemInt  *itemUndoLevels;
86   itemUndoLevels = new KConfigSkeleton::ItemInt( currentGroup(), "Undo Levels", mUndoLevels, 30 );
87   addItem( itemUndoLevels, "UndoLevels" );
88   KConfigSkeleton::ItemInt  *itemCurrentAnalyzer;
89   itemCurrentAnalyzer = new KConfigSkeleton::ItemInt( currentGroup(), "Current Analyzer", mCurrentAnalyzer, -1 );
90   addItem( itemCurrentAnalyzer, "CurrentAnalyzer" );
91   KConfigSkeleton::ItemBool  *itemRememberEffects;
92   itemRememberEffects = new KConfigSkeleton::ItemBool( currentGroup(), "Remember Effects", mRememberEffects, true );
93   addItem( itemRememberEffects, "RememberEffects" );
94   QValueList<int> defaultPlaylistWindowSplitter;
95   defaultPlaylistWindowSplitter.append( 70 );
96   defaultPlaylistWindowSplitter.append( 140 );
97 
98   KConfigSkeleton::ItemIntList  *itemPlaylistWindowSplitter;
99   itemPlaylistWindowSplitter = new KConfigSkeleton::ItemIntList( currentGroup(), "Playlist Window Splitter", mPlaylistWindowSplitter, defaultPlaylistWindowSplitter );
100   addItem( itemPlaylistWindowSplitter, "PlaylistWindowSplitter" );
101   KConfigSkeleton::ItemBool  *itemPlaylistFollowActive;
102   itemPlaylistFollowActive = new KConfigSkeleton::ItemBool( currentGroup(), "Playlist Follow Active", mPlaylistFollowActive, false );
103   addItem( itemPlaylistFollowActive, "PlaylistFollowActive" );
104   KConfigSkeleton::ItemBool  *itemShowSplashscreen;
105   itemShowSplashscreen = new KConfigSkeleton::ItemBool( currentGroup(), "Show Splashscreen", mShowSplashscreen, true );
106   addItem( itemShowSplashscreen, "ShowSplashscreen" );
107 
108   setCurrentGroup( "Playback" );
109 
110   KConfigSkeleton::ItemInt  *itemMasterVolume;
111   itemMasterVolume = new KConfigSkeleton::ItemInt( currentGroup(), "Master Volume", mMasterVolume, 50 );
112   itemMasterVolume->setMinValue(0);
113   itemMasterVolume->setMaxValue(100);
114   addItem( itemMasterVolume, "MasterVolume" );
115   KConfigSkeleton::ItemBool  *itemHardwareMixer;
116   itemHardwareMixer = new KConfigSkeleton::ItemBool( currentGroup(), "Hardware Mixer", mHardwareMixer, false );
117   addItem( itemHardwareMixer, "HardwareMixer" );
118   KConfigSkeleton::ItemBool  *itemCrossfade;
119   itemCrossfade = new KConfigSkeleton::ItemBool( currentGroup(), "Crossfade", mCrossfade, true );
120   addItem( itemCrossfade );
121   KConfigSkeleton::ItemInt  *itemCrossfadeLength;
122   itemCrossfadeLength = new KConfigSkeleton::ItemInt( currentGroup(), "Crossfade Length", mCrossfadeLength, 2200 );
123   addItem( itemCrossfadeLength, "CrossfadeLength" );
124   KConfigSkeleton::ItemString  *itemSoundSystem;
125   itemSoundSystem = new KConfigSkeleton::ItemString( currentGroup(), "Sound System", mSoundSystem, "aRts Engine" );
126   addItem( itemSoundSystem, "SoundSystem" );
127   KConfigSkeleton::ItemString  *itemSoundOutput;
128   itemSoundOutput = new KConfigSkeleton::ItemString( currentGroup(), "Sound Output", mSoundOutput, "Alsa" );
129   addItem( itemSoundOutput, "SoundOutput" );
130   KConfigSkeleton::ItemString  *itemSoundDevice;
131   itemSoundDevice = new KConfigSkeleton::ItemString( currentGroup(), "Sound Device", mSoundDevice );
132   addItem( itemSoundDevice, "SoundDevice" );
133   KConfigSkeleton::ItemBool  *itemCustomSoundDevice;
134   itemCustomSoundDevice = new KConfigSkeleton::ItemBool( currentGroup(), "Custom Sound Device", mCustomSoundDevice, false );
135   addItem( itemCustomSoundDevice, "CustomSoundDevice" );
136   KConfigSkeleton::ItemBool  *itemTitleStreaming;
137   itemTitleStreaming = new KConfigSkeleton::ItemBool( currentGroup(), "Title Streaming", mTitleStreaming, true );
138   addItem( itemTitleStreaming, "TitleStreaming" );
139 
140   setCurrentGroup( "OSD" );
141 
142   KConfigSkeleton::ItemBool  *itemOsdEnabled;
143   itemOsdEnabled = new KConfigSkeleton::ItemBool( currentGroup(), "Osd Enabled", mOsdEnabled, true );
144   addItem( itemOsdEnabled, "OsdEnabled" );
145   KConfigSkeleton::ItemFont  *itemOsdFont;
146   itemOsdFont = new KConfigSkeleton::ItemFont( currentGroup(), "Osd Font", mOsdFont, QFont("Arial",20) );
147   addItem( itemOsdFont, "OsdFont" );
148   KConfigSkeleton::ItemBool  *itemOsdDrawShadow;
149   itemOsdDrawShadow = new KConfigSkeleton::ItemBool( currentGroup(), "Osd Draw Shadow", mOsdDrawShadow, true );
150   addItem( itemOsdDrawShadow, "OsdDrawShadow" );
151   KConfigSkeleton::ItemBool  *itemOsdUseCustomColors;
152   itemOsdUseCustomColors = new KConfigSkeleton::ItemBool( currentGroup(), "Osd Use Custom Colors", mOsdUseCustomColors, false );
153   addItem( itemOsdUseCustomColors, "OsdUseCustomColors" );
154   KConfigSkeleton::ItemColor  *itemOsdTextColor;
155   itemOsdTextColor = new KConfigSkeleton::ItemColor( currentGroup(), "Osd Text Color", mOsdTextColor, QColor( "#ffff00" ) );
156   addItem( itemOsdTextColor, "OsdTextColor" );
157   KConfigSkeleton::ItemColor  *itemOsdBackgroundColor;
158   itemOsdBackgroundColor = new KConfigSkeleton::ItemColor( currentGroup(), "Osd Background Color", mOsdBackgroundColor, QColor( "#1500a0" ) );
159   addItem( itemOsdBackgroundColor, "OsdBackgroundColor" );
160   KConfigSkeleton::ItemInt  *itemOsdDuration;
161   itemOsdDuration = new KConfigSkeleton::ItemInt( currentGroup(), "Osd Duration", mOsdDuration, 5000 );
162   itemOsdDuration->setMinValue(500);
163   itemOsdDuration->setMaxValue(10000);
164   addItem( itemOsdDuration, "OsdDuration" );
165   KConfigSkeleton::ItemInt  *itemOsdXOffset;
166   itemOsdXOffset = new KConfigSkeleton::ItemInt( currentGroup(), "Osd X Offset", mOsdXOffset, 30 );
167   itemOsdXOffset->setMinValue(0);
168   itemOsdXOffset->setMaxValue(10000);
169   addItem( itemOsdXOffset, "OsdXOffset" );
170   KConfigSkeleton::ItemInt  *itemOsdYOffset;
171   itemOsdYOffset = new KConfigSkeleton::ItemInt( currentGroup(), "Osd Y Offset", mOsdYOffset, 30 );
172   itemOsdYOffset->setMinValue(0);
173   itemOsdYOffset->setMaxValue(10000);
174   addItem( itemOsdYOffset, "OsdYOffset" );
175   KConfigSkeleton::ItemInt  *itemOsdScreen;
176   itemOsdScreen = new KConfigSkeleton::ItemInt( currentGroup(), "Osd Screen", mOsdScreen, 0 );
177   addItem( itemOsdScreen, "OsdScreen" );
178   QValueList<KConfigSkeleton::ItemEnum::Choice> valuesOsdAlignment;
179   {
180     KConfigSkeleton::ItemEnum::Choice choice;
181     choice.name = "Left";
182     valuesOsdAlignment.append( choice );
183   }
184   {
185     KConfigSkeleton::ItemEnum::Choice choice;
186     choice.name = "Middle";
187     valuesOsdAlignment.append( choice );
188   }
189   {
190     KConfigSkeleton::ItemEnum::Choice choice;
191     choice.name = "Center";
192     valuesOsdAlignment.append( choice );
193   }
194   {
195     KConfigSkeleton::ItemEnum::Choice choice;
196     choice.name = "Right";
197     valuesOsdAlignment.append( choice );
198   }
199   KConfigSkeleton::ItemEnum  *itemOsdAlignment;
200   itemOsdAlignment = new KConfigSkeleton::ItemEnum( currentGroup(), "Osd Alignment", mOsdAlignment, valuesOsdAlignment, EnumOsdAlignment::Center );
201   addItem( itemOsdAlignment, "OsdAlignment" );
202 
203   setCurrentGroup( "Fonts" );
204 
205   KConfigSkeleton::ItemBool  *itemUseCustomFonts;
206   itemUseCustomFonts = new KConfigSkeleton::ItemBool( currentGroup(), "Use Custom Fonts", mUseCustomFonts, false );
207   addItem( itemUseCustomFonts, "UseCustomFonts" );
208   KConfigSkeleton::ItemFont  *itemPlaylistWindowFont;
209   itemPlaylistWindowFont = new KConfigSkeleton::ItemFont( currentGroup(), "Playlist Window Font", mPlaylistWindowFont, QFont("Helvetica",9) );
210   addItem( itemPlaylistWindowFont, "PlaylistWindowFont" );
211   KConfigSkeleton::ItemFont  *itemPlayerWidgetFont;
212   itemPlayerWidgetFont = new KConfigSkeleton::ItemFont( currentGroup(), "Player Widget Font", mPlayerWidgetFont, QFont("Helvetica",9) );
213   addItem( itemPlayerWidgetFont, "PlayerWidgetFont" );
214   KConfigSkeleton::ItemFont  *itemPlayerWidgetScrollFont;
215   itemPlayerWidgetScrollFont = new KConfigSkeleton::ItemFont( currentGroup(), "Player Widget Scroll Font", mPlayerWidgetScrollFont, QFont("Helvetica",9) );
216   addItem( itemPlayerWidgetScrollFont, "PlayerWidgetScrollFont" );
217 
218   setCurrentGroup( "Colors" );
219 
220   KConfigSkeleton::ItemBool  *itemSchemeAmarok;
221   itemSchemeAmarok = new KConfigSkeleton::ItemBool( currentGroup(), "Scheme Amarok", mSchemeAmarok, false );
222   addItem( itemSchemeAmarok, "SchemeAmarok" );
223   KConfigSkeleton::ItemBool  *itemSchemeKDE;
224   itemSchemeKDE = new KConfigSkeleton::ItemBool( currentGroup(), "Scheme KDE", mSchemeKDE, true );
225   addItem( itemSchemeKDE, "SchemeKDE" );
226   KConfigSkeleton::ItemBool  *itemSchemeCustom;
227   itemSchemeCustom = new KConfigSkeleton::ItemBool( currentGroup(), "Scheme Custom", mSchemeCustom, false );
228   addItem( itemSchemeCustom, "SchemeCustom" );
229   KConfigSkeleton::ItemColor  *itemPlaylistWindowFgColor;
230   itemPlaylistWindowFgColor = new KConfigSkeleton::ItemColor( currentGroup(), "Playlist Window Fg Color", mPlaylistWindowFgColor, QColor( "#80a0ff" ) );
231   addItem( itemPlaylistWindowFgColor, "PlaylistWindowFgColor" );
232   KConfigSkeleton::ItemColor  *itemPlaylistWindowBgColor;
233   itemPlaylistWindowBgColor = new KConfigSkeleton::ItemColor( currentGroup(), "Playlist Window Bg Color", mPlaylistWindowBgColor, QColor( "#000000" ) );
234   addItem( itemPlaylistWindowBgColor, "PlaylistWindowBgColor" );
235 
236   setCurrentGroup( "Session" );
237 
238   KConfigSkeleton::ItemBool  *itemResumePlayback;
239   itemResumePlayback = new KConfigSkeleton::ItemBool( currentGroup(), "Resume Playback", mResumePlayback, false );
240   addItem( itemResumePlayback, "ResumePlayback" );
241   KConfigSkeleton::ItemPath  *itemResumeTrack;
242   itemResumeTrack = new KConfigSkeleton::ItemPath( currentGroup(), "Resume Track", mResumeTrack );
243   addItem( itemResumeTrack, "ResumeTrack" );
244   KConfigSkeleton::ItemInt  *itemResumeTime;
245   itemResumeTime = new KConfigSkeleton::ItemInt( currentGroup(), "Resume Time", mResumeTime, -1 );
246   addItem( itemResumeTime, "ResumeTime" );
247 }
Member Function Documentation
bool AmarokConfig::crossfade () [inline, static]
Get Whether to crossfade between tracks
Definition at line 547 of file amarokconfig.h.
References mCrossfade, and self().
Referenced by EngineController::slotMainTimer().
548     {
549       return self()->mCrossfade;
550     }
int AmarokConfig::crossfadeLength () [inline, static]
Get Length of crossfade, in milliseconds
Definition at line 566 of file amarokconfig.h.
References mCrossfadeLength, and self().
Referenced by EngineController::slotMainTimer().
567     {
568       return self()->mCrossfadeLength;
569     }
int AmarokConfig::currentAnalyzer () [inline, static]
Get Index of current visual analyzer
Definition at line 414 of file amarokconfig.h.
References mCurrentAnalyzer, and self().
415     {
416       return self()->mCurrentAnalyzer;
417     }
bool AmarokConfig::customSoundDevice () [inline, static]
Get Don't use the autodetected audiosink sound device
Definition at line 642 of file amarokconfig.h.
References mCustomSoundDevice, and self().
643     {
644       return self()->mCustomSoundDevice;
645     }
bool AmarokConfig::directoriesRecursively () [inline, static]
Get Whether to add directories to playlist recursively
Definition at line 319 of file amarokconfig.h.
References mDirectoriesRecursively, and self().
320     {
321       return self()->mDirectoriesRecursively;
322     }
bool AmarokConfig::followSymlinks () [inline, static]
Get Whether to follow symlinks while adding items to playlist recursively
Definition at line 129 of file amarokconfig.h.
References mFollowSymlinks, and self().
130     {
131       return self()->mFollowSymlinks;
132     }
bool AmarokConfig::hardwareMixer () [inline, static]
Get Use soundcard hardware mixer for volume
Definition at line 528 of file amarokconfig.h.
References mHardwareMixer, and self().
529     {
530       return self()->mHardwareMixer;
531     }
bool AmarokConfig::hidePlaylistWindow () [inline, static]
Get Whether to hide playlist together with player window
Definition at line 357 of file amarokconfig.h.
References mHidePlaylistWindow, and self().
358     {
359       return self()->mHidePlaylistWindow;
360     }
int AmarokConfig::masterVolume () [inline, static]
Get Master volume
Definition at line 509 of file amarokconfig.h.
References mMasterVolume, and self().
510     {
511       return self()->mMasterVolume;
512     }
int AmarokConfig::osdAlignment () [inline, static]
Get Align OSD to
Definition at line 870 of file amarokconfig.h.
References mOsdAlignment, and self().
871     {
872       return self()->mOsdAlignment;
873     }
QColor AmarokConfig::osdBackgroundColor () [inline, static]
Get Background Color for On-Screen Display
Definition at line 775 of file amarokconfig.h.
References mOsdBackgroundColor, and self().
776     {
777       return self()->mOsdBackgroundColor;
778     }
bool AmarokConfig::osdDrawShadow () [inline, static]
Get Draw a shadow around the text.
Definition at line 718 of file amarokconfig.h.
References mOsdDrawShadow, and self().
719     {
720       return self()->mOsdDrawShadow;
721     }
int AmarokConfig::osdDuration () [inline, static]
Get How many milliseconds the text should be displayed
Definition at line 794 of file amarokconfig.h.
References mOsdDuration, and self().
795     {
796       return self()->mOsdDuration;
797     }
bool AmarokConfig::osdEnabled () [inline, static]
Get Use On-Screen Display
Definition at line 680 of file amarokconfig.h.
References mOsdEnabled, and self().
681     {
682       return self()->mOsdEnabled;
683     }
QFont AmarokConfig::osdFont () [inline, static]
Get Font for On-Screen Display
Definition at line 699 of file amarokconfig.h.
References mOsdFont, and self().
700     {
701       return self()->mOsdFont;
702     }
int AmarokConfig::osdScreen () [inline, static]
Get OSD screen
Definition at line 851 of file amarokconfig.h.
References mOsdScreen, and self().
852     {
853       return self()->mOsdScreen;
854     }
QColor AmarokConfig::osdTextColor () [inline, static]
Get Font Color for On-Screen Display
Definition at line 756 of file amarokconfig.h.
References mOsdTextColor, and self().
757     {
758       return self()->mOsdTextColor;
759     }
bool AmarokConfig::osdUseCustomColors () [inline, static]
Get Whether to use custom colors for the OSD
Definition at line 737 of file amarokconfig.h.
References mOsdUseCustomColors, and self().
738     {
739       return self()->mOsdUseCustomColors;
740     }
int AmarokConfig::osdXOffset () [inline, static]
Get X position offset
Definition at line 813 of file amarokconfig.h.
References mOsdXOffset, and self().
814     {
815       return self()->mOsdXOffset;
816     }
int AmarokConfig::osdYOffset () [inline, static]
Get Y position offset
Definition at line 832 of file amarokconfig.h.
References mOsdYOffset, and self().
833     {
834       return self()->mOsdYOffset;
835     }
QPoint AmarokConfig::playerPos () [inline, static]
Get Position of player window
Definition at line 53 of file amarokconfig.h.
References mPlayerPos, and self().
54     {
55       return self()->mPlayerPos;
56     }
QFont AmarokConfig::playerWidgetFont () [inline, static]
Get Font in player window
Definition at line 927 of file amarokconfig.h.
References mPlayerWidgetFont, and self().
928     {
929       return self()->mPlayerWidgetFont;
930     }
QFont AmarokConfig::playerWidgetScrollFont () [inline, static]
Get Font in player window title scroller
Definition at line 946 of file amarokconfig.h.
References mPlayerWidgetScrollFont, and self().
947     {
948       return self()->mPlayerWidgetScrollFont;
949     }
bool AmarokConfig::playlistFollowActive () [inline, static]
Get Whether the playlist should scroll with the active playlist item
Definition at line 471 of file amarokconfig.h.
References mPlaylistFollowActive, and self().
472     {
473       return self()->mPlaylistFollowActive;
474     }
QColor AmarokConfig::playlistWindowBgColor () [inline, static]
Get Playlist window background color
Definition at line 1041 of file amarokconfig.h.
References mPlaylistWindowBgColor, and self().
1042     {
1043       return self()->mPlaylistWindowBgColor;
1044     }
bool AmarokConfig::playlistWindowEnabled () [inline, static]
Get Whether the playlist window is visible
Definition at line 376 of file amarokconfig.h.
References mPlaylistWindowEnabled, and self().
377     {
378       return self()->mPlaylistWindowEnabled;
379     }
QColor AmarokConfig::playlistWindowFgColor () [inline, static]
Get Playlist window foreground color
Definition at line 1022 of file amarokconfig.h.
References mPlaylistWindowFgColor, and self().
1023     {
1024       return self()->mPlaylistWindowFgColor;
1025     }
QFont AmarokConfig::playlistWindowFont () [inline, static]
Get Font in playlist window
Definition at line 908 of file amarokconfig.h.
References mPlaylistWindowFont, and self().
909     {
910       return self()->mPlaylistWindowFont;
911     }
QPoint AmarokConfig::playlistWindowPos () [inline, static]
Get Position of playlist window
Definition at line 72 of file amarokconfig.h.
References mPlaylistWindowPos, and self().
73     {
74       return self()->mPlaylistWindowPos;
75     }
QSize AmarokConfig::playlistWindowSize () [inline, static]
Get Size of playlist window
Definition at line 91 of file amarokconfig.h.
References mPlaylistWindowSize, and self().
92     {
93       return self()->mPlaylistWindowSize;
94     }
QValueList<int> AmarokConfig::playlistWindowSplitter () [inline, static]
Get Playlist window splitter positions
Definition at line 452 of file amarokconfig.h.
References mPlaylistWindowSplitter, and self().
453     {
454       return self()->mPlaylistWindowSplitter;
455     }
bool AmarokConfig::randomMode () [inline, static]
Get Whether to play tracks in random order
Definition at line 205 of file amarokconfig.h.
References mRandomMode, and self().
206     {
207       return self()->mRandomMode;
208     }
bool AmarokConfig::rememberEffects () [inline, static]
Get Persistent audio effects
Definition at line 433 of file amarokconfig.h.
References mRememberEffects, and self().
434     {
435       return self()->mRememberEffects;
436     }
bool AmarokConfig::repeatPlaylist () [inline, static]
Get Whether to play whole playlist repeatedly
Definition at line 186 of file amarokconfig.h.
References mRepeatPlaylist, and self().
187     {
188       return self()->mRepeatPlaylist;
189     }
bool AmarokConfig::repeatTrack () [inline, static]
Get Whether to play track repeatedly
Definition at line 167 of file amarokconfig.h.
References mRepeatTrack, and self().
168     {
169       return self()->mRepeatTrack;
170     }
bool AmarokConfig::resumePlayback () [inline, static]
Get Resume playback of last played track on startup
Definition at line 1060 of file amarokconfig.h.
References mResumePlayback, and self().
1061     {
1062       return self()->mResumePlayback;
1063     }
int AmarokConfig::resumeTime () [inline, static]
Get Time to resume at, in seconds
Definition at line 1098 of file amarokconfig.h.
References mResumeTime, and self().
1099     {
1100       return self()->mResumeTime;
1101     }
QString AmarokConfig::resumeTrack () [inline, static]
Get Track URL to resume upon startup
Definition at line 1079 of file amarokconfig.h.
References mResumeTrack, and self().
1080     {
1081       return self()->mResumeTrack;
1082     }
bool AmarokConfig::savePlaylist () [inline, static]
Get Whether to save playlist on quit
Definition at line 110 of file amarokconfig.h.
References mSavePlaylist, and self().
111     {
112       return self()->mSavePlaylist;
113     }
bool AmarokConfig::schemeAmarok () [inline, static]
Get Whether to use amaroK standard colors in the playlist window
Definition at line 965 of file amarokconfig.h.
References mSchemeAmarok, and self().
966     {
967       return self()->mSchemeAmarok;
968     }
bool AmarokConfig::schemeCustom () [inline, static]
Get Whether to use user-defined colors in the playlist window
Definition at line 1003 of file amarokconfig.h.
References mSchemeCustom, and self().
1004     {
1005       return self()->mSchemeCustom;
1006     }
bool AmarokConfig::schemeKDE () [inline, static]
Get Whether to use global KDE(p.) colors in the playlist window
Definition at line 984 of file amarokconfig.h.
References mSchemeKDE, and self().
985     {
986       return self()->mSchemeKDE;
987     }
AmarokConfig * AmarokConfig::self () [static]
Definition at line 12 of file amarokconfig.cpp.
References AmarokConfig(), mSelf, and staticDeleter.
Referenced by crossfade(), crossfadeLength(), currentAnalyzer(), customSoundDevice(), directoriesRecursively(), followSymlinks(), hardwareMixer(), hidePlaylistWindow(), masterVolume(), osdAlignment(), osdBackgroundColor(), osdDrawShadow(), osdDuration(), osdEnabled(), osdFont(), osdScreen(), osdTextColor(), osdUseCustomColors(), osdXOffset(), osdYOffset(), playerPos(), playerWidgetFont(), playerWidgetScrollFont(), playlistFollowActive(), playlistWindowBgColor(), playlistWindowEnabled(), playlistWindowFgColor(), playlistWindowFont(), playlistWindowPos(), playlistWindowSize(), playlistWindowSplitter(), randomMode(), rememberEffects(), repeatPlaylist(), repeatTrack(), resumePlayback(), resumeTime(), resumeTrack(), savePlaylist(), schemeAmarok(), schemeCustom(), schemeKDE(), setCrossfade(), setCrossfadeLength(), setCurrentAnalyzer(), setCustomSoundDevice(), setDirectoriesRecursively(), setFollowSymlinks(), setHardwareMixer(), setHidePlaylistWindow(), setMasterVolume(), setOsdAlignment(), setOsdBackgroundColor(), setOsdDrawShadow(), setOsdDuration(), setOsdEnabled(), setOsdFont(), setOsdScreen(), setOsdTextColor(), setOsdUseCustomColors(), setOsdXOffset(), setOsdYOffset(), setPlayerPos(), setPlayerWidgetFont(), setPlayerWidgetScrollFont(), setPlaylistFollowActive(), setPlaylistWindowBgColor(), setPlaylistWindowEnabled(), setPlaylistWindowFgColor(), setPlaylistWindowFont(), setPlaylistWindowPos(), setPlaylistWindowSize(), setPlaylistWindowSplitter(), setRandomMode(), setRememberEffects(), setRepeatPlaylist(), setRepeatTrack(), setResumePlayback(), setResumeTime(), setResumeTrack(), setSavePlaylist(), setSchemeAmarok(), setSchemeCustom(), setSchemeKDE(), setShowMetaInfo(), setShowPlayerWindow(), setShowSplashscreen(), setShowStatusBar(), setShowTrayIcon(), setShowWelcomeTab(), setSoundDevice(), setSoundOutput(), setSoundSystem(), setTimeDisplayRemaining(), setTitleStreaming(), setTrackDelayLength(), setUndoLevels(), setUseCustomFonts(), setVersion(), showMetaInfo(), showPlayerWindow(), showSplashscreen(), showStatusBar(), showTrayIcon(), showWelcomeTab(), soundDevice(), soundOutput(), soundSystem(), timeDisplayRemaining(), titleStreaming(), trackDelayLength(), undoLevels(), useCustomFonts(), version(), and writeConfig().
13 {
14   if ( !mSelf ) {
15     staticDeleter.setObject( mSelf, new AmarokConfig() );
16     mSelf->readConfig();
17   }
18 
19   return mSelf;
20 }
void AmarokConfig::setCrossfade (bool v) [inline, static]
Set Whether to crossfade between tracks
Definition at line 537 of file amarokconfig.h.
References mCrossfade, and self().
538     {
539       if (!self()->isImmutable( "Crossfade" ))
540         self()->mCrossfade = v;
541     }
void AmarokConfig::setCrossfadeLength (int v) [inline, static]
Set Length of crossfade, in milliseconds
Definition at line 556 of file amarokconfig.h.
References mCrossfadeLength, and self().
557     {
558       if (!self()->isImmutable( "CrossfadeLength" ))
559         self()->mCrossfadeLength = v;
560     }
void AmarokConfig::setCurrentAnalyzer (int v) [inline, static]
Set Index of current visual analyzer
Definition at line 404 of file amarokconfig.h.
References mCurrentAnalyzer, and self().
405     {
406       if (!self()->isImmutable( "CurrentAnalyzer" ))
407         self()->mCurrentAnalyzer = v;
408     }
void AmarokConfig::setCustomSoundDevice (bool v) [inline, static]
Set Don't use the autodetected audiosink sound device
Definition at line 632 of file amarokconfig.h.
References mCustomSoundDevice, and self().
633     {
634       if (!self()->isImmutable( "CustomSoundDevice" ))
635         self()->mCustomSoundDevice = v;
636     }
void AmarokConfig::setDirectoriesRecursively (bool v) [inline, static]
Set Whether to add directories to playlist recursively
Definition at line 309 of file amarokconfig.h.
References mDirectoriesRecursively, and self().
310     {
311       if (!self()->isImmutable( "DirectoriesRecursively" ))
312         self()->mDirectoriesRecursively = v;
313     }
void AmarokConfig::setFollowSymlinks (bool v) [inline, static]
Set Whether to follow symlinks while adding items to playlist recursively
Definition at line 119 of file amarokconfig.h.
References mFollowSymlinks, and self().
120     {
121       if (!self()->isImmutable( "FollowSymlinks" ))
122         self()->mFollowSymlinks = v;
123     }
void AmarokConfig::setHardwareMixer (bool v) [inline, static]
Set Use soundcard hardware mixer for volume
Definition at line 518 of file amarokconfig.h.
References mHardwareMixer, and self().
519     {
520       if (!self()->isImmutable( "HardwareMixer" ))
521         self()->mHardwareMixer = v;
522     }
void AmarokConfig::setHidePlaylistWindow (bool v) [inline, static]
Set Whether to hide playlist together with player window
Definition at line 347 of file amarokconfig.h.
References mHidePlaylistWindow, and self().
348     {
349       if (!self()->isImmutable( "HidePlaylistWindow" ))
350         self()->mHidePlaylistWindow = v;
351     }
void AmarokConfig::setMasterVolume (int v) [inline, static]
Set Master volume
Definition at line 499 of file amarokconfig.h.
References mMasterVolume, and self().
Referenced by EngineController::setVolume().
500     {
501       if (!self()->isImmutable( "MasterVolume" ))
502         self()->mMasterVolume = v;
503     }
void AmarokConfig::setOsdAlignment (int v) [inline, static]
Set Align OSD to
Definition at line 860 of file amarokconfig.h.
References mOsdAlignment, and self().
861     {
862       if (!self()->isImmutable( "OsdAlignment" ))
863         self()->mOsdAlignment = v;
864     }
void AmarokConfig::setOsdBackgroundColor (const QColor & v) [inline, static]
Set Background Color for On-Screen Display
Definition at line 765 of file amarokconfig.h.
References mOsdBackgroundColor, and self().
766     {
767       if (!self()->isImmutable( "OsdBackgroundColor" ))
768         self()->mOsdBackgroundColor = v;
769     }
void AmarokConfig::setOsdDrawShadow (bool v) [inline, static]
Set Draw a shadow around the text.
Definition at line 708 of file amarokconfig.h.
References mOsdDrawShadow, and self().
709     {
710       if (!self()->isImmutable( "OsdDrawShadow" ))
711         self()->mOsdDrawShadow = v;
712     }
void AmarokConfig::setOsdDuration (int v) [inline, static]
Set How many milliseconds the text should be displayed
Definition at line 784 of file amarokconfig.h.
References mOsdDuration, and self().
785     {
786       if (!self()->isImmutable( "OsdDuration" ))
787         self()->mOsdDuration = v;
788     }
void AmarokConfig::setOsdEnabled (bool v) [inline, static]
Set Use On-Screen Display
Definition at line 670 of file amarokconfig.h.
References mOsdEnabled, and self().
671     {
672       if (!self()->isImmutable( "OsdEnabled" ))
673         self()->mOsdEnabled = v;
674     }
void AmarokConfig::setOsdFont (const QFont & v) [inline, static]
Set Font for On-Screen Display
Definition at line 689 of file amarokconfig.h.
References mOsdFont, and self().
690     {
691       if (!self()->isImmutable( "OsdFont" ))
692         self()->mOsdFont = v;
693     }
void AmarokConfig::setOsdScreen (int v) [inline, static]
Set OSD screen
Definition at line 841 of file amarokconfig.h.
References mOsdScreen, and self().
842     {
843       if (!self()->isImmutable( "OsdScreen" ))
844         self()->mOsdScreen = v;
845     }
void AmarokConfig::setOsdTextColor (const QColor & v) [inline, static]
Set Font Color for On-Screen Display
Definition at line 746 of file amarokconfig.h.
References mOsdTextColor, and self().
747     {
748       if (!self()->isImmutable( "OsdTextColor" ))
749         self()->mOsdTextColor = v;
750     }
void AmarokConfig::setOsdUseCustomColors (bool v) [inline, static]
Set Whether to use custom colors for the OSD
Definition at line 727 of file amarokconfig.h.
References mOsdUseCustomColors, and self().
728     {
729       if (!self()->isImmutable( "OsdUseCustomColors" ))
730         self()->mOsdUseCustomColors = v;
731     }
void AmarokConfig::setOsdXOffset (int v) [inline, static]
Set X position offset
Definition at line 803 of file amarokconfig.h.
References mOsdXOffset, and self().
804     {
805       if (!self()->isImmutable( "OsdXOffset" ))
806         self()->mOsdXOffset = v;
807     }
void AmarokConfig::setOsdYOffset (int v) [inline, static]
Set Y position offset
Definition at line 822 of file amarokconfig.h.
References mOsdYOffset, and self().
823     {
824       if (!self()->isImmutable( "OsdYOffset" ))
825         self()->mOsdYOffset = v;
826     }
void AmarokConfig::setPlayerPos (const QPoint & v) [inline, static]
Set Position of player window
Definition at line 43 of file amarokconfig.h.
References mPlayerPos, and self().
44     {
45       if (!self()->isImmutable( "PlayerPos" ))
46         self()->mPlayerPos = v;
47     }
void AmarokConfig::setPlayerWidgetFont (const QFont & v) [inline, static]
Set Font in player window
Definition at line 917 of file amarokconfig.h.
References mPlayerWidgetFont, and self().
918     {
919       if (!self()->isImmutable( "PlayerWidgetFont" ))
920         self()->mPlayerWidgetFont = v;
921     }
void AmarokConfig::setPlayerWidgetScrollFont (const QFont & v) [inline, static]
Set Font in player window title scroller
Definition at line 936 of file amarokconfig.h.
References mPlayerWidgetScrollFont, and self().
937     {
938       if (!self()->isImmutable( "PlayerWidgetScrollFont" ))
939         self()->mPlayerWidgetScrollFont = v;
940     }
void AmarokConfig::setPlaylistFollowActive (bool v) [inline, static]
Set Whether the playlist should scroll with the active playlist item
Definition at line 461 of file amarokconfig.h.
References mPlaylistFollowActive, and self().
462     {
463       if (!self()->isImmutable( "PlaylistFollowActive" ))
464         self()->mPlaylistFollowActive = v;
465     }
void AmarokConfig::setPlaylistWindowBgColor (const QColor & v) [inline, static]
Set Playlist window background color
Definition at line 1031 of file amarokconfig.h.
References mPlaylistWindowBgColor, and self().
1032     {
1033       if (!self()->isImmutable( "PlaylistWindowBgColor" ))
1034         self()->mPlaylistWindowBgColor = v;
1035     }
void AmarokConfig::setPlaylistWindowEnabled (bool v) [inline, static]
Set Whether the playlist window is visible
Definition at line 366 of file amarokconfig.h.
References mPlaylistWindowEnabled, and self().
367     {
368       if (!self()->isImmutable( "PlaylistWindowEnabled" ))
369         self()->mPlaylistWindowEnabled = v;
370     }
void AmarokConfig::setPlaylistWindowFgColor (const QColor & v) [inline, static]
Set Playlist window foreground color
Definition at line 1012 of file amarokconfig.h.
References mPlaylistWindowFgColor, and self().
1013     {
1014       if (!self()->isImmutable( "PlaylistWindowFgColor" ))
1015         self()->mPlaylistWindowFgColor = v;
1016     }
void AmarokConfig::setPlaylistWindowFont (const QFont & v) [inline, static]
Set Font in playlist window
Definition at line 898 of file amarokconfig.h.
References mPlaylistWindowFont, and self().
899     {
900       if (!self()->isImmutable( "PlaylistWindowFont" ))
901         self()->mPlaylistWindowFont = v;
902     }
void AmarokConfig::setPlaylistWindowPos (const QPoint & v) [inline, static]
Set Position of playlist window
Definition at line 62 of file amarokconfig.h.
References mPlaylistWindowPos, and self().
63     {
64       if (!self()->isImmutable( "PlaylistWindowPos" ))
65         self()->mPlaylistWindowPos = v;
66     }
void AmarokConfig::setPlaylistWindowSize (const QSize & v) [inline, static]
Set Size of playlist window
Definition at line 81 of file amarokconfig.h.
References mPlaylistWindowSize, and self().
82     {
83       if (!self()->isImmutable( "PlaylistWindowSize" ))
84         self()->mPlaylistWindowSize = v;
85     }
void AmarokConfig::setPlaylistWindowSplitter (const QValueList< int > & v) [inline, static]
Set Playlist window splitter positions
Definition at line 442 of file amarokconfig.h.
References mPlaylistWindowSplitter, and self().
443     {
444       if (!self()->isImmutable( "PlaylistWindowSplitter" ))
445         self()->mPlaylistWindowSplitter = v;
446     }
void AmarokConfig::setRandomMode (bool v) [inline, static]
Set Whether to play tracks in random order
Definition at line 195 of file amarokconfig.h.
References mRandomMode, and self().
196     {
197       if (!self()->isImmutable( "RandomMode" ))
198         self()->mRandomMode = v;
199     }
void AmarokConfig::setRememberEffects (bool v) [inline, static]
Set Persistent audio effects
Definition at line 423 of file amarokconfig.h.
References mRememberEffects, and self().
424     {
425       if (!self()->isImmutable( "RememberEffects" ))
426         self()->mRememberEffects = v;
427     }
void AmarokConfig::setRepeatPlaylist (bool v) [inline, static]
Set Whether to play whole playlist repeatedly
Definition at line 176 of file amarokconfig.h.
References mRepeatPlaylist, and self().
177     {
178       if (!self()->isImmutable( "RepeatPlaylist" ))
179         self()->mRepeatPlaylist = v;
180     }
void AmarokConfig::setRepeatTrack (bool v) [inline, static]
Set Whether to play track repeatedly
Definition at line 157 of file amarokconfig.h.
References mRepeatTrack, and self().
158     {
159       if (!self()->isImmutable( "RepeatTrack" ))
160         self()->mRepeatTrack = v;
161     }
void AmarokConfig::setResumePlayback (bool v) [inline, static]
Set Resume playback of last played track on startup
Definition at line 1050 of file amarokconfig.h.
References mResumePlayback, and self().
1051     {
1052       if (!self()->isImmutable( "ResumePlayback" ))
1053         self()->mResumePlayback = v;
1054     }
void AmarokConfig::setResumeTime (int v) [inline, static]
Set Time to resume at, in seconds
Definition at line 1088 of file amarokconfig.h.
References mResumeTime, and self().
1089     {
1090       if (!self()->isImmutable( "ResumeTime" ))
1091         self()->mResumeTime = v;
1092     }
void AmarokConfig::setResumeTrack (const QString & v) [inline, static]
Set Track URL to resume upon startup
Definition at line 1069 of file amarokconfig.h.
References mResumeTrack, and self().
1070     {
1071       if (!self()->isImmutable( "ResumeTrack" ))
1072         self()->mResumeTrack = v;
1073     }
void AmarokConfig::setSavePlaylist (bool v) [inline, static]
Set Whether to save playlist on quit
Definition at line 100 of file amarokconfig.h.
References mSavePlaylist, and self().
101     {
102       if (!self()->isImmutable( "SavePlaylist" ))
103         self()->mSavePlaylist = v;
104     }
void AmarokConfig::setSchemeAmarok (bool v) [inline, static]
Set Whether to use amaroK standard colors in the playlist window
Definition at line 955 of file amarokconfig.h.
References mSchemeAmarok, and self().
956     {
957       if (!self()->isImmutable( "SchemeAmarok" ))
958         self()->mSchemeAmarok = v;
959     }
void AmarokConfig::setSchemeCustom (bool v) [inline, static]
Set Whether to use user-defined colors in the playlist window
Definition at line 993 of file amarokconfig.h.
References mSchemeCustom, and self().
994     {
995       if (!self()->isImmutable( "SchemeCustom" ))
996         self()->mSchemeCustom = v;
997     }
void AmarokConfig::setSchemeKDE (bool v) [inline, static]
Set Whether to use global KDE(p.) colors in the playlist window
Definition at line 974 of file amarokconfig.h.
References mSchemeKDE, and self().
975     {
976       if (!self()->isImmutable( "SchemeKDE" ))
977         self()->mSchemeKDE = v;
978     }
void AmarokConfig::setShowMetaInfo (bool v) [inline, static]
Set Whether to show track metadata
Definition at line 214 of file amarokconfig.h.
References mShowMetaInfo, and self().
215     {
216       if (!self()->isImmutable( "ShowMetaInfo" ))
217         self()->mShowMetaInfo = v;
218     }
void AmarokConfig::setShowPlayerWindow (bool v) [inline, static]
Set Whether to show player window
Definition at line 252 of file amarokconfig.h.
References mShowPlayerWindow, and self().
253     {
254       if (!self()->isImmutable( "ShowPlayerWindow" ))
255         self()->mShowPlayerWindow = v;
256     }
void AmarokConfig::setShowSplashscreen (bool v) [inline, static]
Set Whether a splash-screen should be displayed on startup
Definition at line 480 of file amarokconfig.h.
References mShowSplashscreen, and self().
481     {
482       if (!self()->isImmutable( "ShowSplashscreen" ))
483         self()->mShowSplashscreen = v;
484     }
void AmarokConfig::setShowStatusBar (bool v) [inline, static]
Set Whether to show the Playlist Statusbar
Definition at line 271 of file amarokconfig.h.
References mShowStatusBar, and self().
272     {
273       if (!self()->isImmutable( "ShowStatusBar" ))
274         self()->mShowStatusBar = v;
275     }
void AmarokConfig::setShowTrayIcon (bool v) [inline, static]
Set Whether to show icon in system tray
Definition at line 233 of file amarokconfig.h.
References mShowTrayIcon, and self().
234     {
235       if (!self()->isImmutable( "ShowTrayIcon" ))
236         self()->mShowTrayIcon = v;
237     }
void AmarokConfig::setShowWelcomeTab (bool v) [inline, static]
Set Toggle the Welcome-page in the browser bar
Definition at line 290 of file amarokconfig.h.
References mShowWelcomeTab, and self().
291     {
292       if (!self()->isImmutable( "ShowWelcomeTab" ))
293         self()->mShowWelcomeTab = v;
294     }
void AmarokConfig::setSoundDevice (const QString & v) [inline, static]
Set Sound output device to use
Definition at line 613 of file amarokconfig.h.
References mSoundDevice, and self().
614     {
615       if (!self()->isImmutable( "SoundDevice" ))
616         self()->mSoundDevice = v;
617     }
void AmarokConfig::setSoundOutput (const QString & v) [inline, static]
Set Sound output method to use
Definition at line 594 of file amarokconfig.h.
References mSoundOutput, and self().
595     {
596       if (!self()->isImmutable( "SoundOutput" ))
597         self()->mSoundOutput = v;
598     }
void AmarokConfig::setSoundSystem (const QString & v) [inline, static]
Set Sound system to use
Definition at line 575 of file amarokconfig.h.
References mSoundSystem, and self().
576     {
577       if (!self()->isImmutable( "SoundSystem" ))
578         self()->mSoundSystem = v;
579     }
void AmarokConfig::setTimeDisplayRemaining (bool v) [inline, static]
Set Whether to display remaining track time
Definition at line 138 of file amarokconfig.h.
References mTimeDisplayRemaining, and self().
139     {
140       if (!self()->isImmutable( "TimeDisplayRemaining" ))
141         self()->mTimeDisplayRemaining = v;
142     }
void AmarokConfig::setTitleStreaming (bool v) [inline, static]
Set Read titles of shoutcast streams
Definition at line 651 of file amarokconfig.h.
References mTitleStreaming, and self().
652     {
653       if (!self()->isImmutable( "TitleStreaming" ))
654         self()->mTitleStreaming = v;
655     }
void AmarokConfig::setTrackDelayLength (int v) [inline, static]
Set Delay between tracks, in milliseconds
Definition at line 328 of file amarokconfig.h.
References mTrackDelayLength, and self().
329     {
330       if (!self()->isImmutable( "TrackDelayLength" ))
331         self()->mTrackDelayLength = v;
332     }
void AmarokConfig::setUndoLevels (int v) [inline, static]
Set Number of undo levels in playlist
Definition at line 385 of file amarokconfig.h.
References mUndoLevels, and self().
386     {
387       if (!self()->isImmutable( "UndoLevels" ))
388         self()->mUndoLevels = v;
389     }
void AmarokConfig::setUseCustomFonts (bool v) [inline, static]
Set Whether to use user-defined fonts
Definition at line 879 of file amarokconfig.h.
References mUseCustomFonts, and self().
880     {
881       if (!self()->isImmutable( "UseCustomFonts" ))
882         self()->mUseCustomFonts = v;
883     }
void AmarokConfig::setVersion (const QString & v) [inline, static]
Set Amarok(p.) Version
Definition at line 24 of file amarokconfig.h.
References mVersion, and self().
25     {
26       if (!self()->isImmutable( "Version" ))
27         self()->mVersion = v;
28     }
bool AmarokConfig::showMetaInfo () [inline, static]
Get Whether to show track metadata
Definition at line 224 of file amarokconfig.h.
References mShowMetaInfo, and self().
225     {
226       return self()->mShowMetaInfo;
227     }
bool AmarokConfig::showPlayerWindow () [inline, static]
Get Whether to show player window
Definition at line 262 of file amarokconfig.h.
References mShowPlayerWindow, and self().
263     {
264       return self()->mShowPlayerWindow;
265     }
bool AmarokConfig::showSplashscreen () [inline, static]
Get Whether a splash-screen should be displayed on startup
Definition at line 490 of file amarokconfig.h.
References mShowSplashscreen, and self().
491     {
492       return self()->mShowSplashscreen;
493     }
bool AmarokConfig::showStatusBar () [inline, static]
Get Whether to show the Playlist Statusbar
Definition at line 281 of file amarokconfig.h.
References mShowStatusBar, and self().
282     {
283       return self()->mShowStatusBar;
284     }
bool AmarokConfig::showTrayIcon () [inline, static]
Get Whether to show icon in system tray
Definition at line 243 of file amarokconfig.h.
References mShowTrayIcon, and self().
244     {
245       return self()->mShowTrayIcon;
246     }
bool AmarokConfig::showWelcomeTab () [inline, static]
Get Toggle the Welcome-page in the browser bar
Definition at line 300 of file amarokconfig.h.
References mShowWelcomeTab, and self().
301     {
302       return self()->mShowWelcomeTab;
303     }
QString AmarokConfig::soundDevice () [inline, static]
Get Sound output device to use
Definition at line 623 of file amarokconfig.h.
References mSoundDevice, and self().
624     {
625       return self()->mSoundDevice;
626     }
QString AmarokConfig::soundOutput () [inline, static]
Get Sound output method to use
Definition at line 604 of file amarokconfig.h.
References mSoundOutput, and self().
605     {
606       return self()->mSoundOutput;
607     }
QString AmarokConfig::soundSystem () [inline, static]
Get Sound system to use
Definition at line 585 of file amarokconfig.h.
References mSoundSystem, and self().
586     {
587       return self()->mSoundSystem;
588     }
bool AmarokConfig::timeDisplayRemaining () [inline, static]
Get Whether to display remaining track time
Definition at line 148 of file amarokconfig.h.
References mTimeDisplayRemaining, and self().
149     {
150       return self()->mTimeDisplayRemaining;
151     }
bool AmarokConfig::titleStreaming () [inline, static]
Get Read titles of shoutcast streams
Definition at line 661 of file amarokconfig.h.
References mTitleStreaming, and self().
662     {
663       return self()->mTitleStreaming;
664     }
int AmarokConfig::trackDelayLength () [inline, static]
Get Delay between tracks, in milliseconds
Definition at line 338 of file amarokconfig.h.
References mTrackDelayLength, and self().
Referenced by EngineController::slotMainTimer().
339     {
340       return self()->mTrackDelayLength;
341     }
int AmarokConfig::undoLevels () [inline, static]
Get Number of undo levels in playlist
Definition at line 395 of file amarokconfig.h.
References mUndoLevels, and self().
396     {
397       return self()->mUndoLevels;
398     }
bool AmarokConfig::useCustomFonts () [inline, static]
Get Whether to use user-defined fonts
Definition at line 889 of file amarokconfig.h.
References mUseCustomFonts, and self().
890     {
891       return self()->mUseCustomFonts;
892     }
QString AmarokConfig::version () [inline, static]
Get Amarok(p.) Version
Definition at line 34 of file amarokconfig.h.
References mVersion, and self().
35     {
36       return self()->mVersion;
37     }
void AmarokConfig::writeConfig () [inline, static]
Definition at line 1104 of file amarokconfig.h.
References self().
1105     {
1106       static_cast<KConfigSkeleton*>(self())->writeConfig();
1107     }
Member Data Documentation
bool AmarokConfig::mCrossfade [protected]
Definition at line 1143 of file amarokconfig.h.
Referenced by AmarokConfig(), crossfade(), and setCrossfade().
int AmarokConfig::mCrossfadeLength [protected]
Definition at line 1144 of file amarokconfig.h.
Referenced by AmarokConfig(), crossfadeLength(), and setCrossfadeLength().
int AmarokConfig::mCurrentAnalyzer [protected]
Definition at line 1134 of file amarokconfig.h.
Referenced by AmarokConfig(), currentAnalyzer(), and setCurrentAnalyzer().
bool AmarokConfig::mCustomSoundDevice [protected]
Definition at line 1148 of file amarokconfig.h.
Referenced by AmarokConfig(), customSoundDevice(), and setCustomSoundDevice().
bool AmarokConfig::mDirectoriesRecursively [protected]
Definition at line 1129 of file amarokconfig.h.
Referenced by AmarokConfig(), directoriesRecursively(), and setDirectoriesRecursively().
bool AmarokConfig::mFollowSymlinks [protected]
Definition at line 1119 of file amarokconfig.h.
Referenced by AmarokConfig(), followSymlinks(), and setFollowSymlinks().
bool AmarokConfig::mHardwareMixer [protected]
Definition at line 1142 of file amarokconfig.h.
Referenced by AmarokConfig(), hardwareMixer(), and setHardwareMixer().
bool AmarokConfig::mHidePlaylistWindow [protected]
Definition at line 1131 of file amarokconfig.h.
Referenced by AmarokConfig(), hidePlaylistWindow(), and setHidePlaylistWindow().
int AmarokConfig::mMasterVolume [protected]
Definition at line 1141 of file amarokconfig.h.
Referenced by AmarokConfig(), masterVolume(), and setMasterVolume().
int AmarokConfig::mOsdAlignment [protected]
Definition at line 1162 of file amarokconfig.h.
Referenced by AmarokConfig(), osdAlignment(), and setOsdAlignment().
QColor AmarokConfig::mOsdBackgroundColor [protected]
Definition at line 1157 of file amarokconfig.h.
Referenced by AmarokConfig(), osdBackgroundColor(), and setOsdBackgroundColor().
bool AmarokConfig::mOsdDrawShadow [protected]
Definition at line 1154 of file amarokconfig.h.
Referenced by AmarokConfig(), osdDrawShadow(), and setOsdDrawShadow().
int AmarokConfig::mOsdDuration [protected]
Definition at line 1158 of file amarokconfig.h.
Referenced by AmarokConfig(), osdDuration(), and setOsdDuration().
bool AmarokConfig::mOsdEnabled [protected]
Definition at line 1152 of file amarokconfig.h.
Referenced by AmarokConfig(), osdEnabled(), and setOsdEnabled().
QFont AmarokConfig::mOsdFont [protected]
Definition at line 1153 of file amarokconfig.h.
Referenced by AmarokConfig(), osdFont(), and setOsdFont().
int AmarokConfig::mOsdScreen [protected]
Definition at line 1161 of file amarokconfig.h.
Referenced by AmarokConfig(), osdScreen(), and setOsdScreen().
QColor AmarokConfig::mOsdTextColor [protected]
Definition at line 1156 of file amarokconfig.h.
Referenced by AmarokConfig(), osdTextColor(), and setOsdTextColor().
bool AmarokConfig::mOsdUseCustomColors [protected]
Definition at line 1155 of file amarokconfig.h.
Referenced by AmarokConfig(), osdUseCustomColors(), and setOsdUseCustomColors().
int AmarokConfig::mOsdXOffset [protected]
Definition at line 1159 of file amarokconfig.h.
Referenced by AmarokConfig(), osdXOffset(), and setOsdXOffset().
int AmarokConfig::mOsdYOffset [protected]
Definition at line 1160 of file amarokconfig.h.
Referenced by AmarokConfig(), osdYOffset(), and setOsdYOffset().
QPoint AmarokConfig::mPlayerPos [protected]
Definition at line 1115 of file amarokconfig.h.
Referenced by AmarokConfig(), playerPos(), and setPlayerPos().
QFont AmarokConfig::mPlayerWidgetFont [protected]
Definition at line 1167 of file amarokconfig.h.
Referenced by AmarokConfig(), playerWidgetFont(), and setPlayerWidgetFont().
QFont AmarokConfig::mPlayerWidgetScrollFont [protected]
Definition at line 1168 of file amarokconfig.h.
Referenced by AmarokConfig(), playerWidgetScrollFont(), and setPlayerWidgetScrollFont().
bool AmarokConfig::mPlaylistFollowActive [protected]
Definition at line 1137 of file amarokconfig.h.
Referenced by AmarokConfig(), playlistFollowActive(), and setPlaylistFollowActive().
QColor AmarokConfig::mPlaylistWindowBgColor [protected]
Definition at line 1175 of file amarokconfig.h.
Referenced by AmarokConfig(), playlistWindowBgColor(), and setPlaylistWindowBgColor().
bool AmarokConfig::mPlaylistWindowEnabled [protected]
Definition at line 1132 of file amarokconfig.h.
Referenced by AmarokConfig(), playlistWindowEnabled(), and setPlaylistWindowEnabled().
QColor AmarokConfig::mPlaylistWindowFgColor [protected]
Definition at line 1174 of file amarokconfig.h.
Referenced by AmarokConfig(), playlistWindowFgColor(), and setPlaylistWindowFgColor().
QFont AmarokConfig::mPlaylistWindowFont [protected]
Definition at line 1166 of file amarokconfig.h.
Referenced by AmarokConfig(), playlistWindowFont(), and setPlaylistWindowFont().
QPoint AmarokConfig::mPlaylistWindowPos [protected]
Definition at line 1116 of file amarokconfig.h.
Referenced by AmarokConfig(), playlistWindowPos(), and setPlaylistWindowPos().
QSize AmarokConfig::mPlaylistWindowSize [protected]
Definition at line 1117 of file amarokconfig.h.
Referenced by AmarokConfig(), playlistWindowSize(), and setPlaylistWindowSize().
QValueList<int> AmarokConfig::mPlaylistWindowSplitter [protected]
Definition at line 1136 of file amarokconfig.h.
Referenced by AmarokConfig(), playlistWindowSplitter(), and setPlaylistWindowSplitter().
bool AmarokConfig::mRandomMode [protected]
Definition at line 1123 of file amarokconfig.h.
Referenced by AmarokConfig(), randomMode(), and setRandomMode().
bool AmarokConfig::mRememberEffects [protected]
Definition at line 1135 of file amarokconfig.h.
Referenced by AmarokConfig(), rememberEffects(), and setRememberEffects().
bool AmarokConfig::mRepeatPlaylist [protected]
Definition at line 1122 of file amarokconfig.h.
Referenced by AmarokConfig(), repeatPlaylist(), and setRepeatPlaylist().
bool AmarokConfig::mRepeatTrack [protected]
Definition at line 1121 of file amarokconfig.h.
Referenced by AmarokConfig(), repeatTrack(), and setRepeatTrack().
bool AmarokConfig::mResumePlayback [protected]
Definition at line 1178 of file amarokconfig.h.
Referenced by AmarokConfig(), resumePlayback(), and setResumePlayback().
int AmarokConfig::mResumeTime [protected]
Definition at line 1180 of file amarokconfig.h.
Referenced by AmarokConfig(), resumeTime(), and setResumeTime().
QString AmarokConfig::mResumeTrack [protected]
Definition at line 1179 of file amarokconfig.h.
Referenced by AmarokConfig(), resumeTrack(), and setResumeTrack().
bool AmarokConfig::mSavePlaylist [protected]
Definition at line 1118 of file amarokconfig.h.
Referenced by AmarokConfig(), savePlaylist(), and setSavePlaylist().
bool AmarokConfig::mSchemeAmarok [protected]
Definition at line 1171 of file amarokconfig.h.
Referenced by AmarokConfig(), schemeAmarok(), and setSchemeAmarok().
bool AmarokConfig::mSchemeCustom [protected]
Definition at line 1173 of file amarokconfig.h.
Referenced by AmarokConfig(), schemeCustom(), and setSchemeCustom().
bool AmarokConfig::mSchemeKDE [protected]
Definition at line 1172 of file amarokconfig.h.
Referenced by AmarokConfig(), schemeKDE(), and setSchemeKDE().
AmarokConfig * AmarokConfig::mSelf = 0 [static, protected]
Definition at line 9 of file amarokconfig.cpp.
Referenced by AmarokConfig(), self(), and ~AmarokConfig().
bool AmarokConfig::mShowMetaInfo [protected]
Definition at line 1124 of file amarokconfig.h.
Referenced by AmarokConfig(), setShowMetaInfo(), and showMetaInfo().
bool AmarokConfig::mShowPlayerWindow [protected]
Definition at line 1126 of file amarokconfig.h.
Referenced by AmarokConfig(), setShowPlayerWindow(), and showPlayerWindow().
bool AmarokConfig::mShowSplashscreen [protected]
Definition at line 1138 of file amarokconfig.h.
Referenced by AmarokConfig(), setShowSplashscreen(), and showSplashscreen().
bool AmarokConfig::mShowStatusBar [protected]
Definition at line 1127 of file amarokconfig.h.
Referenced by AmarokConfig(), setShowStatusBar(), and showStatusBar().
bool AmarokConfig::mShowTrayIcon [protected]
Definition at line 1125 of file amarokconfig.h.
Referenced by AmarokConfig(), setShowTrayIcon(), and showTrayIcon().
bool AmarokConfig::mShowWelcomeTab [protected]
Definition at line 1128 of file amarokconfig.h.
Referenced by AmarokConfig(), setShowWelcomeTab(), and showWelcomeTab().
QString AmarokConfig::mSoundDevice [protected]
Definition at line 1147 of file amarokconfig.h.
Referenced by AmarokConfig(), setSoundDevice(), and soundDevice().
QString AmarokConfig::mSoundOutput [protected]
Definition at line 1146 of file amarokconfig.h.
Referenced by AmarokConfig(), setSoundOutput(), and soundOutput().
QString AmarokConfig::mSoundSystem [protected]
Definition at line 1145 of file amarokconfig.h.
Referenced by AmarokConfig(), setSoundSystem(), and soundSystem().
bool AmarokConfig::mTimeDisplayRemaining [protected]
Definition at line 1120 of file amarokconfig.h.
Referenced by AmarokConfig(), setTimeDisplayRemaining(), and timeDisplayRemaining().
bool AmarokConfig::mTitleStreaming [protected]
Definition at line 1149 of file amarokconfig.h.
Referenced by AmarokConfig(), setTitleStreaming(), and titleStreaming().
int AmarokConfig::mTrackDelayLength [protected]
Definition at line 1130 of file amarokconfig.h.
Referenced by AmarokConfig(), setTrackDelayLength(), and trackDelayLength().
int AmarokConfig::mUndoLevels [protected]
Definition at line 1133 of file amarokconfig.h.
Referenced by AmarokConfig(), setUndoLevels(), and undoLevels().
bool AmarokConfig::mUseCustomFonts [protected]
Definition at line 1165 of file amarokconfig.h.
Referenced by AmarokConfig(), setUseCustomFonts(), and useCustomFonts().
QString AmarokConfig::mVersion [protected]
Definition at line 1114 of file amarokconfig.h.
Referenced by AmarokConfig(), setVersion(), and version().
The documentation for this class was generated from the following files:
amarokconfig.h
amarokconfig.cpp