qfileiconview.cpp File Reference
#include `qfileiconview.h`
#include <qpainter.h>
#include <qstringlist.h>
#include <qpixmap.h>
#include <qmime.h>
#include <qstrlist.h>
#include <qdragobject.h>
#include <qmessagebox.h>
#include <qevent.h>
#include <qpopupmenu.h>
#include <qcursor.h>
#include <qapplication.h>
#include <qwmatrix.h>
#include <math.h>
#include <stdlib.h>
#include <kdebug.h>
Functions
void cleanup ()
QPixmap * addBorder (QPixmap *pix, bool hasAlpha)
bool isRoot (const QString &s)
Variables
QPixmap * iconFileLarge = 0
QPixmap * ArrayImage [100]
Function Documentation
QPixmap* addBorder (QPixmap * pix, bool hasAlpha)
Definition at line 183 of file qfileiconview.cpp.
Referenced by QtFileIconViewItem::QtFileIconViewItem().
184 {
185         //DAVID Read Background
186         QPixmap pbgxpm=QPixmap("/root/kde_application/hdass08/skin/bgxpm.png");
187         //DAVID Read Boarder Image
188         QImage ptop=QImage("/root/kde_application/hdass08/skin/border.png");
189         
190         //DAVID New a QPixmap res with size pix->size()
191         QPixmap res(pix->size());
192         
193         //Draw it on painter
194         QPainter p(&res);
195                 if(hasAlpha) 
196                         p.drawTiledPixmap (0, 0, pix->width(), pix->height(),pbgxpm);
197                 //DAVID draw broder to painter          
198                 p.drawImage(0, 0, ptop.scale(pix->width(), pix->height()));
199                 p.drawImage((int)floor((float)pix->width()/ptop.width()*14),
200                         (int)floor((float)pix->height()/ptop.height()*13),
201                         pix->convertToImage().smoothScale(
202                                 (int)ceil(pix->width()*0.79738562092),
203                                 (int)ceil(pix->height()*0.76691729323)));
204         p.end();
205         QImage a=res.convertToImage().scale(70,70);
206         QPixmap *temp=new QPixmap(a);
207         return temp;
208 }
void cleanup () [static]
Definition at line 30 of file qfileiconview.cpp.
References iconFileLarge.
Referenced by QtFileIconView::QtFileIconView().
31 {
32     
33     delete iconFileLarge;
34     iconFileLarge = 0;
35     
36 }
bool isRoot (const QString & s) [static]
Definition at line 354 of file qfileiconview.cpp.
Referenced by QtFileIconView::readDir().
355 {
356 #if defined(Q_OS_UNIX)
357     if ( s == "/" )
358         return TRUE;
359 #elif defined(Q_OS_WIN32)
360     QString p = s;
361     if ( p.length() == 3 &&
362          p.right( 2 ) == ":/" )
363         return TRUE;
364     if ( p[ 0 ] == '/' && p[ 1 ] == '/' ) {
365         int slashes = p.contains( '/' );
366         if ( slashes <= 3 )
367             return TRUE;
368         if ( slashes == 4 && p[ (int)p.length() - 1 ] == '/' )
369             return TRUE;
370     }
371 #endif
372 
373     return FALSE;
374 }
Variable Documentation
QPixmap* ArrayImage[100]
Definition at line 29 of file qfileiconview.cpp.
Referenced by QtFileIconViewItem::pixmap(), and QtFileIconViewItem::QtFileIconViewItem().
QPixmap* iconFileLarge = 0 [static]
Definition at line 28 of file qfileiconview.cpp.
Referenced by cleanup(), QtFileIconViewItem::pixmap(), and QtFileIconView::QtFileIconView().